### ISSUE TITLE
You can't smelt iron ore to get metal sheets in a forge.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31290] opened 2021-11-15 15:51 UTC
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Wanted to get metal sheets as space hobo to expand my shack, but couldn't smelt all the iron ore I had in the forge to get those metal sheets.

# Steps to Reproduce
1- Make a forge (or just go space hobo)
2- Get iron ore from the roid
3- Fuel the forge with whatever
4- Put the iron ores inside the forge
5- Lit it
6- Wait for the forge to run out of fuel
7- Get the iron ores back from it

# What you Expected
Metal sheets instead of the iron ore I just put in there.

# What Actually Happened
It gave me the iron ores, I wanted metal sheets.

**Comment by jwhitak** [comment] 2021-11-15 15:56
Duplicate of #30226, #31110, and #31165

**Closed as completed** 2021-11-17 21:55 UTC
