### ISSUE TITLE
sliding windoor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9917] opened 2016-05-05 19:39 UTC
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 1474b4a97d5ebc03b0afd7eeb233462abe8dce48 
> 
> General description of the issue

some sliding doors no longer open when pushed against as a mommi e.g the hydro windoors to mainhall way

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ComicIronic** [comment] 2016-05-05 20:14
Dupe of #9908

**Closed as completed by ComicIronic** 2016-05-05 20:14 UTC
