### ISSUE TITLE
Removing Anomaly Batteries during Timed Emission Breaks Cooldown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14763] opened 2017-04-29 06:46 UTC
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
For the Anomaly Power Utilizer you can completely break them if you remove the battery while its on cooldown from a timed emission.

I'm not entirely sure if thats the cause, but it does make the utilizer completely unusable

**Comment by Cyadox** [comment] 2021-11-28 04:40
After some manual testing, I can honestly say I have no idea how to reproduce this.

Steps taken:
1. Spawned random artifact with some ability (heating surrounding area in this case)
2. Put in anomaly scanner pod, turned on isolation field, isolated particles into battery
3. Put battery in power utilizer and then did:

- Start normally, then remove battery. Reinserted, which put into Cooldown mode, then removed and reinserted again immediately
- As above, but waited out Cooldown duration as well before reinserting.
- Start in Timed mode, remove battery immediately and reinserted immediately, then waited out Cooldown
- Start in Timed mode, wait entire duration (5 in this case), then waited out Cooldown
- Start in Timed mode, wait entire duration, remove and reinsert battery, then wait out Cooldown
- As above, but remove and reinsert battery during Cooldown

Every time the effects worked as intended, the battery drained as normal, the timer was adjustable as normal... either this was fixed incidentally ages ago or it was a UI glitch/error.

**Closed as completed** 2021-11-28 05:49 UTC
Labels: Bug / Fix, Easy Fix
