### ISSUE TITLE
Remove rad effects on viruses

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6492] opened 2015-11-09 05:10 UTC
This kills the virologist.  The job is the least loved and people regularly call for virologists to be lynched/banned for releasing strictly beneficial viruses because at the first sign of radiation, some braindead guy will mutate his virus and kill everyone with it.  The job is at an all time low.

Remove.

**Comment by clusterfack** [comment] 2015-11-09 05:19
Find the code then, comment it out, make a PR

**Comment by Probe1** [comment] 2015-11-09 05:24
Could you put a discussion tag on please?

**Comment by PJB3005** [comment] 2015-11-09 06:32
Agreed, it should be removed.

**Comment by Hoshi-chan** [comment] 2015-11-09 12:36
Yes, yes, yes. I would like to see virologists as a regular part of the staff again.

**Comment by ihadtoregisterforthis** [comment] 2015-11-09 12:40
Notice that not only Pun-Pun and braindeads are exposed to radiation, as many people stay outside maint to get the free powers.

**Comment by Angelite191** [comment] 2015-11-09 18:45
100% support.

**Comment by Rei1226** [comment] 2015-11-09 18:57
Agreed. Give this shitty job some purpose other then "roll for antag, if you dont get it, go jump into space".

**Comment by Skullyton** [comment] 2015-11-09 19:04
Rather than remove it entirely, how about lower the probability of it mutating from guaranteed to "Some poor sod got unlucky".

**Comment by PJB3005** [comment] 2015-11-09 19:05
@Skullyton any chance is too much of a chance.

**Comment by Faptastic** [comment] 2015-11-09 19:47
:+1: Then it just needs the third infection vector back to not make it contagious so you can give botany monkeys that glow in the dark, produce doctors delight, eggs and tricord without fear of it spreading. The dream is almost reality!

**Comment by FudgePucker** [comment] 2015-11-11 15:39
>Virology

:-1:
I think the radiation causing the comon cold to turn into super aids is a fun feature, it makes viral outbreak random events more unpredicable because a harmless virus that no one bothers to treat can turn into a station depopulator.

Just make it so that people who are braindead or monkeys can't get mutated.

**Comment by clusterfack** [comment] 2015-11-11 16:09
Random outbreak events are a separate thing and they still exist and they are still extremely deadly. Almost none of the randomly generated viruses are harmless in any way.

**Comment by Probe1** [comment] 2015-11-11 16:26
Something to think about 

Viro is almost never done anymore.  No one wants beneficial viruses.  They always turn into non beneficial ones.  Always.  So when a random viral outbreak shows up it's IMMEDIATELY treated because any slight message will send someone blitzing to medbay.

If they also have a beneficial virus they might not realize that they've picked up a harmful one too.  Until it's too late and it's spread.

**Comment by Arthurdentist** [comment] 2015-11-26 01:46
I support this wholeheartedly

**Comment by clusterfack** [comment] 2015-11-26 05:02
Well pretty much solved by the merged PR listed here

**Comment by Zth--** [comment] 2015-11-26 05:15
Was that PR tested? This is from today http://puu.sh/lz5DW/cc47d748b3.png
I was playing that round and I can confirm it

**Comment by clusterfack** [comment] 2015-11-26 06:11
*Trusting the thread*

That's a mistake

**Comment by ihadtoregisterforthis** [comment] 2015-11-26 13:27
You say it was a self-fulfilling prophecy? Or a Thanksgiving miracle?

![correctional object xv 2015-11-25 224238](https://cloud.githubusercontent.com/assets/13305885/11423683/44cfa686-9425-11e5-8059-a1c2e4e8b133.png)

**Comment by Probe1** [comment] 2015-11-26 18:36
Glorious.  I can see myself getting turbofucked.   

Anyway what this is needs is testing, and testing is simple.

Fire up a local serb, make a virus manually or with debug (try under Secrets / Custom virus), and run the test dummies through the ringer of rad storms, singlo/SME exposure, mutagen injections, and exposure to a radio transmitter for good measure.

If no one does it then I will tomorrow afternoon when I get home.

**Comment by PJB3005** [comment] 2015-11-26 19:11
Reopening until this is confirmed as the thread being dumb.

**Comment by 9600bauds** [comment] 2016-01-03 00:40
I can confirm that the thread was being dumb. I was not able to mutate a virus with any amount of radiation from my testing.
![2016-01-02_21-39-46](https://cloud.githubusercontent.com/assets/6526157/12076773/6b5ac380-b199-11e5-83e3-8fe60aa7c52f.png)

**Comment by clusterfack** [comment] 2016-01-03 04:00
YOU LISTENED TO THE THREAD, YOU FUCKING FOOL!

**Closed by clusterfack** 2016-01-03 04:00 UTC
Labels: Discussion, Needs Moar Testing
