### ISSUE TITLE
Legacy Cult: Summoning soul stones does not work and expends a charge

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20009] opened 2018-10-06 23:05 UTC
#### Description of issue
On the tin, if you're a starting cultist and use that option on your starting paper you just waste a precious charge from it and fails to spawn one. Seems to be a new bug since datums.

#### Server revision

98ca78c6a1f8cc9f87798d1c6fd9e4ab2bbcd493 
3fb5a0e5a47e3d0e13a9fdeee420c851212d002c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment] 2018-10-07 00:07
>when you correct a bug and accidentally introduce a new one

:100:

**Comment by ShiftyRail** [comment] 2018-10-07 00:49
![image](https://user-images.githubusercontent.com/31417754/46577019-6a5f3000-c9ca-11e8-924d-d2e12b993a83.png)
Unable to reproduce, am on latest version. When did this happen ? Maybe I can find a runtime.

**Comment by Gringonius** [comment] 2018-10-07 03:35
Friday night, I ahelped a few seconds later at [20:05:05].

**Comment by ShiftyRail** [comment] 2018-10-07 11:11
I think the gist of the problem was there was too much runes being drawn, and talismans effectively work as portable runes when used.
This is a slight mechanical changes from before, where they'd just call the procedure of the rune without actually spawning one

**Comment by ShiftyRail** [comment] 2018-10-16 16:29
@Exxion This was closed. I forgot to automagically close it.

**Closed as completed** 2018-10-16 17:00 UTC
Labels: Bug / Fix
