### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Firebombs made from rags don't work.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4039] opened 2015-04-22 00:00 UTC
> Revision (Should be above if you're viewing this from ingame!)
> fa8de85
> 
> General description of the issue
> Firebombs don't set things on fire.
> I don't know what else to say.
> 
> What you expected to happen
> Fire
> 
> What actually happened
> No fire
> 
> Steps to reproduce if possible
> Fill beer bottle with lighter fluid.
> Put a rag in it.
> Light it on fire.
> Toss at someones face.
> Be filled with sadness and regret.

**Comment by SarahJohnson489** [comment] 2015-04-26 10:28
Seconding this. It was implemented as just a hotspot generator pretty much.

**Comment by FudgePucker** [comment] 2015-11-11 18:25
I will retest this later this afternoon or tonight. Have rags even been worked on sense I made this issue?

**Comment by gbasood** [comment] 2016-01-18 19:34
Still an issue

**Comment by BarneyGumball** [comment] 2016-10-21 14:55
Not sure if I misunderstood the issue, but I filled a beer bottle with welder fluid, stuffed a rag in it, lit it on fire and threw it.  It spread the fuel around and lit it on fire.  Seems to be fixed.

**Comment by BarneyGumball** [comment] 2016-10-26 04:41
Correcting myself here:  It works when thrown normally but hitting mobs throws a runtime.

```
[14:39:46] Runtime in footprints_and_rag.dm,47: Cannot read null.total_volume
  proc name: afterattack (/obj/item/weapon/reagent_containers/glass/rag/afterattack)
  usr: Giovanni Burkett (barneygumball) (/mob/living/carbon/human)
  usr.loc: The floor (133, 143, 1) (/turf/simulated/floor)
```

**Comment by 9600bauds** [comment] 2016-12-14 14:42
Tested locally, molotovs do correctly work, they are just fuckin' arse

They need to be full of welding fuel to work and even they all they do is ignite the fuel off the floor.
Also, only a few hardcoded types of bottle can be molotovs, even though you need to empty them and give them welding fuel to work.

Will fix the harmless runtime

**Comment by 9600bauds** [comment] 2016-12-14 14:45
Since everything seems to be working as intended (even though the "intended" part is awful), closing this, open another issue if you want molotovs to be less arse

**Closed by 9600bauds** 2016-12-14 14:45 UTC
Labels: Bug / Fix
