### ISSUE TITLE
Cryopod is a default "yes" midround mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29777] opened 2021-06-12 20:10 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5aa9f1a3ea2e93249851f4e8a8e2e377d6b2ff7b

# Description
you have to opt out each time and there's no setting to set it to "never no yes always", so it's always just yes

please add a setting for it in midround modes

**Comment by DeityLink** [comment] 2021-06-13 01:22
duplicate of #29573

**Closed as completed by DeityLink** 2021-06-13 01:22 UTC
