### ISSUE TITLE
hobo huts walk through windows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32204] opened 2022-03-12 15:26 UTC
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
640def376fa86972a10781008b1229fbd59a5072

# Description
can walk through the front windoor and window of the hobo hut despite it being there
# Steps to Reproduce
cheat physics and walk through glass
# What you Expected
door to open
# What Actually Happened
how are doors real just walk through em

**Comment by Cartlord** [comment] 2022-03-12 16:10
I can confirm this, you can walk straight through one of the windoors on a hobo hut - it won't open, you just go straight through, and since it's closed it can still block atmos.

**Comment by Kurfursten** [comment] 2022-03-12 17:09
Was the hobo hut in its default orientation or rotated? If rotated I think this is definitely a quirk of directional windows

**Comment by Eneocho** [comment] 2022-03-12 20:49
Windoors, not windows. And I've had this happen to me as well on rotated hobo huts (the windoors are facing east).

**Comment by Kurfursten** [comment] 2022-03-13 02:31
I am guessing this is true of both windoors and windows, but you aren't noticing it because the windows are stacked covering multiple directions

**Closed as completed** 2022-04-01 21:47 UTC
