### ISSUE TITLE
Synergy: research shuttle dock not wired

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28077] opened 2020-10-23 08:22 UTC
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
c15c93d390a631d9eb220e25744bc19b02842836

# Description
hi can youplease fix the wiring already this is like my 2nd or third bug report about it pls and thx
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment] 2020-10-25 03:35
Duplicate of something

**Closed as completed by DamianX** 2020-10-25 03:35 UTC
