### ISSUE TITLE
Smoke animation seems to stick around forever

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#37029] opened 2024-09-02 04:35 UTC
#### Description of issue
Sometimes the smoke effect on items seems to persist even though temperature is normal
![dreamseeker_s7tJwyMrEV](https://github.com/user-attachments/assets/56e8e091-ce25-42ae-be5c-9e5c8daddce3)
![image](https://github.com/user-attachments/assets/7165a2f8-386b-4fa7-858c-b49d3dab7ae1)

#### Difference between expected and actual behavior 
endless smoking
it to stop eventually at normal temperatures

#### Steps to reproduce
Get something hot enough to stop smoking but not hot enough to burn maybe? Not sure.

**Comment by west3436** [comment] 2024-09-02 14:50
Duplicate of #37005.

**Closed as not planned by west3436** 2024-09-02 14:51 UTC
