### ISSUE TITLE
AI Turrets Not Working Regardless Of Firing Mode

### ISSUE THREAD

**Issue by TurboGay** [d3athrow/vgstation13#31219] opened 2021-11-05 20:29 UTC
#### Description of issue
Expect turrets to fire, but instead they do nothing regardless if on lethals or stun mode

#### Difference between expected and actual behavior
expect turret to do turret things
heehoo they do nothing

#### Steps to reproduce
walk into ai upload and see if they fire or not, I've had core turrets do the same 

#### Length of time in which bug has been known to occur
It's been happening for at least a week or two, but from what I've seen other people say it's been happening before that

#### Server revision
550525ddac31c9d324ef8a0011ac33f5cb17074b

**Comment by west3436** [comment] 2021-11-05 20:41
duplicate of #31208

**Closed as completed** 2021-11-11 16:30 UTC
