### ISSUE TITLE
goonchat autoscroll

### ISSUE THREAD

**Issue by Boxe** [d3athrow/vgstation13#9113] opened 2016-03-28 21:07 UTC
whenever someone does HTML fucker or whatever the hell, autoscroll will suddenly stop because fuck you

fix it

**Comment by gbasood** [comment] 2016-03-28 21:07
steps to reproduce

**Comment by Exxion** [comment] 2016-03-28 21:08
It happens when the text is too tall.
Fixed by clicking the "X NEW MESSAGES" button

**Comment by Boxe** [comment] 2016-03-28 21:10
seems to happen whenever something pops a new line like when it uses `<br>`

pop `<font face="Comic sans MS" size="3">test test<br><br><br>test</font>` into ooc to try it

**Comment by Exxion** [comment] 2016-03-28 21:20
Ah, so it happens whenever a message is more than one line tall, whether due to `<br>`s or really big text.

**Comment by Intigracy** [comment] 2016-03-28 21:34
Is HTML working in OOC?

**Comment by gbasood** [comment] 2016-03-28 21:37
User-inserted HTML no that got fixed

**Comment by NigglyWiggly** [comment] 2016-03-28 22:58
It happens anytime a fucking adminlog takes up just barely 2 lines.
I don't really know any good way to describe this.
If there's a notification of a player joining with a low player age, that log will typically have like 5 characters on the next line.
That fucks up the scrolling.
Any other admin logs with a similar length fuck it up, anything beyond that doesn't seem to do it though.

Also the autoscrolling will stop when you scroll up, but if you leave it there for too long it will just start scrolling again anyway.

**Comment by gbasood** [comment] 2016-03-30 05:10
@NigglyWiggly That last one is, I'm assuming, because the log has a max length and you hit it
The rest sounds like issues with line height and the window not properly handling autoscrolling for that

**Comment by NigglyWiggly** [comment] 2016-04-01 20:52
See that's what I thought, the max length thing.
But I'll scroll up when there's 5 messages and it'll start autoscrolling again, but I'll come back to my computer to see an odd length message messed up the scrolling and I have 1000+ messages, so i dunno

**Comment by Boxe** [comment] 2016-04-03 22:30
fix when

**Comment by Boxe** [comment] 2016-04-07 01:06
fix when

**Comment by Konater** [comment] 2016-04-10 10:33
If you scroll up it's expected that the autoscrolling stops so that you can read previous messages, it does this up to the point of hitting the max log length. When it hits max log length you're fighting to scroll up and read previous messages as more people talk. When you clear all messages it works again.

**Comment by NigglyWiggly** [comment] 2016-04-10 14:11
That doesn't always seem to happen though
I've had it start scrolling again at 50 new messages but I've come back from getting a drink or something to find that a slightly-longer-than-usual message will have stopped the scrolling and I'll have literally over 1000 messages. Like when I said that earlier i want to be clear that I was not exagerrating, I think the number was 1148 or so, and it wasn't scrolling on its own

**Comment by ihadtoregisterforthis** [comment] 2016-04-10 15:43
Scrolling to the newest line in chat doesn't count (or not always at least) as "reading messages", you can go down all the way and the chat will autoscroll while adding to the unread messages number.

**Comment by NigglyWiggly** [comment] 2016-06-01 21:10
Reminder that this is STILL FUCKED.

**Comment by Boxe** [comment] 2016-06-01 21:10
:eggplant:

**Comment by clusterfack** [comment] 2016-06-13 15:36
I encountered a bug that is far different from what you described but has the same effect to pjb and asked him to fix it here: https://github.com/d3athrow/vgstation13/pull/10538.

I don't really have any idea what YOU guys are talking about but maybe this will help.

**Comment by clusterfack** [comment] 2016-09-06 07:51
If this is still happening reopen and give some real good and specific details about it.

**Closed by clusterfack** 2016-09-06 07:51 UTC
Labels: Bug / Fix, Goonchat

**Comment by Exxion** [comment] 2016-09-06 13:24
It does still happen if something's font size is too big, I believe, but that is only an issue with badmin fuckery

**Comment by NigglyWiggly** [comment] 2016-09-07 21:18
It is still happening almost every time I get an ahelp that goes over 1 line.

**Comment by Exxion** [comment] 2016-09-07 21:27
Works On My Machine:tm:

**Comment by Boxe** [comment] 2016-09-07 21:38
:eggplant:

**Comment by gbasood** [comment] 2016-09-08 16:23
@NigglyWiggly do your ahelps not go to your special tab?

**Comment by Exxion** [comment] 2016-09-08 16:27
That wouldn't matter for the problem he's describing, unless they ONLY go to the special tab

But anyway I don't have this problem even in Goonchat

**Comment by NigglyWiggly** [comment] 2016-09-08 19:42
I don't use special tab, no.
This occasionally happens with logs and prayers as well
