### ISSUE TITLE
(WEB REPORT BY: 1pirateguy REMOTE: 198.245.63.50:7777) weird thing when stacking dosh

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3858] opened 2015-04-10 07:02 UTC
>Revision (Should be above if you're viewing this from ingame!)
5610615fb3920d22cefabbbe28720197b1b67792 

>General description of the issue
this happens when I stack dosh http://puu.sh/h8k6V.png

>What you expected to happen
not to see weird code in the action

>What actually happened
dosh stacked but this happend

>Steps to reproduce if possible
double click to stack dosh

**Comment by ComicIronic** [comment] 2015-04-10 13:22
Duplicate of #3794.

**Closed by ComicIronic** 2015-04-10 13:22 UTC
