### ISSUE TITLE
This is a test dont even look at this

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#9466] opened 2016-04-15 22:05 UTC
Pls dont ban this is a test

**Comment by Probe1** [comment] 2016-04-15 22:07
HA HA HA LOOK AT THIS GUY HE CAN'T CLOSE IT.

**Comment by Exxion** [comment] 2016-04-15 22:09
A test of what?

**Comment by 9600bauds** [comment] 2016-04-15 22:12
![loyalty](https://cloud.githubusercontent.com/assets/6526157/14576276/fb97b75a-033d-11e6-9cc3-bd4a5a5b0ef0.jpg)

**Comment by Brolaire** [comment] 2016-04-15 23:10
[Needs Flashlight Eyes]

**Comment by Killette2** [comment] 2016-04-16 17:06
![autism](https://cloud.githubusercontent.com/assets/5169310/14582481/14179bd8-03d4-11e6-9480-a72f01d35ebb.png)

**Comment by Probe1** [comment] 2016-04-16 17:15
@Killette2 I can't even tell if that's from another game or all the [FEATURE REQUESTS] you've posted here compiled into an image.

**Comment by Killette2** [comment] 2016-04-16 17:22
Get rekt probe, I now have only 2 pages of feature request, some which have been attempted to been brought back from the dead by me but are still ignored, and they're all reasonable to an extent.

**Comment by Shadowmech88** [comment] 2016-04-16 17:27
> eating flakes of dead skin
> a reasonable feature request

**Comment by Killette2** [comment] 2016-04-16 17:29
That was an experiment. Take an otherwise reasonable request that wouldn't cause any major problems (like cancer) in game, and add 1(one) weird thing to it, then the whole idea would go out the window.

**Comment by Shadowmech88** [comment] 2016-04-16 17:36
> otherwise reasonable
> ignoring an itch would cause you to develop puss-filled boils that you have to go to Medbay to get drained

**Comment by Killette2** [comment] 2016-04-16 17:40
It had sound gamey logic, and it was to mimic how ignoring damage to eye welding results in your heads about to split open. Also it was intended to be equally as progressive, so it'd take about 40 minutes for an itch to go that far, you could cure the itch yourself just by simply scratching it (medicineless self cure), gives medbay more variety, and the only way to get itch is to take space drugs or get the itching virus from virology, both which deservedly give you that fuckin itch.

**Comment by 9600bauds** [comment] 2016-04-16 19:20
Before this gets nuked I want to know what was being tested @MusgardTiger

**Comment by Probe1** [comment] 2016-04-16 19:28
He probably wanted to test us on whether we had sweet fuckin sprite art and I do not intend to fail.

![1456028656253](https://cloud.githubusercontent.com/assets/8550416/14583177/cb79ce0a-03e7-11e6-8f9d-90bd5ac147ba.gif)

**Comment by Killette2** [comment] 2016-04-17 02:30
Maybe he wants to test if a bar singulo is a good idea

![barsingulo](https://cloud.githubusercontent.com/assets/5169310/14584742/daef7e30-0422-11e6-92e5-910ad8d72b31.png)

**Comment by Probe1** [comment] 2016-04-17 02:51
It was not.

**Comment by Killette2** [comment] 2016-04-17 18:40
It actually was before the shift turned 3 hours, and admins spawned shit in it. That said, I have thought of further and better safety precautions since the construction of this last one.

**Comment by 9600bauds** [comment] 2016-05-26 15:45
We'll never know what this was a test of

**Closed as completed by 9600bauds** 2016-05-26 15:45 UTC
Labels: Honk, Logging / Administration, 100%  tested

**Comment by PJB3005** [comment] 2016-05-26 15:49
Whatever it was we tested it well.

**Comment by Killette2** [comment] 2016-05-26 16:01
low test
