### ISSUE TITLE
Can't emote when silenced

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16091] opened 2017-09-25 23:32 UTC
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
fdf7afd1e49b6a3cca41d0c4c89391c7308eb03d

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by N3X15** [comment] 2017-09-26 00:31
Duplicate of #16092

**Closed as completed** 2017-09-26 00:31 UTC
