### ISSUE TITLE
[Goofchem] various

### ISSUE THREAD

**Issue by gayniggersex666** [d3athrow/vgstation13#3026] opened 2015-02-15 10:08 UTC
Nerf cyanide, it takes like a minute and a half for 5u to kill someone, bp+clf3 smoke/foam doesnt set off an explosion either, needs a reagent that heats up other reagents while in the beaker like real goon chem.

**Comment by ComicIronic** [comment] 2015-02-15 10:21
Cyanide is a duplicate of #3025.

**Comment by Iamgoofball** [comment] 2015-02-27 03:02
@ComicIronic @d3athrow this is fixed on the latest test server build, it can be closed

**Closed** 2015-02-27 16:31 UTC
Labels: Bug, Feature Request, Goof Chem
