### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777) New Med HUD Problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5990] opened 2015-10-06 02:04 UTC
It occasionally will not show the damage bar for some reason.
example picture: http://puu.sh/kA4ad/2e14b4d376.png

**Comment by Shadowmech88** [comment] 2015-10-06 02:15
Not a bug, #5931 made it so that the health bar does not show up for people who are at 100% health.

**Comment by clusterfack** [comment] 2015-10-06 14:57
Mmmm someone make a changelog entry about this feature and I'll close the issue

**Closed** 2015-10-11 04:45 UTC
Labels: Need Changelog
