### ISSUE TITLE
Flamethrowers are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28277] opened 2020-11-30 02:08 UTC
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
1a849f32ca9dbb9ed92d7512cf6c7d8624332aa6

# Description
Flamethrowers went from being deadly to not working at all. Shooting flames at something will shoot a stream that stops short of the target. This includes the firebreath spell, potentially wasting a slot in a bundle.
# Steps to Reproduce
shoot flames. Be disappointed
# What you Expected
roastie toastie
# What Actually Happened
cuck coders fucking everything up, as usual

**Comment by SonixApache** [comment] 2020-11-30 12:22
afaik coders haven't touched flamercode in a while, this just sorta started happening
the plume projectile hits a mob and just flat stops for reasons unknown

**Comment by drawsstuff** [comment] 2020-11-30 16:08
I noticed this while playing a wizard with fire breath. It made the spell ultimately worthless.

**Comment by Blithering** [comment] 2020-12-03 17:05
Noticed it in the flame traps on the asteroid station satellite.

**Comment by Exxion** [comment] 2020-12-03 20:04
Duplicate of #28153 but this one has more discussion so whatever
Also, does anyone know roughly when this started?

**Closed as completed** 2020-12-04 12:33 UTC
