### ISSUE TITLE
Cooking Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10062] opened 2016-05-15 07:37 UTC
(WEB REPORT BY: charmstruck REMOTE: 172.93.109.202:7777)

> Revision 8f20ff31d56feb5e4cf157a43b9b124eda3e4d50 
> 
> General description of the issue
> Whenever a pizza or sandwich is processed using the fryer or grill, it ejects the toppings that were on it. Or produces a duplicate? Since the product appears to be correct other than the ejected topping. Haven't ground up the food to check the contents, so it may be lacking the nutrients/whatnot
> 
> What you expected to happen
> Food
> 
> What actually happened
> Food + Topping
> 
> Steps to reproduce if possible
> Make a sandwich, fry it

**Comment by Kurfursten** [comment] 2016-05-15 09:04
Goonkitchen was a mistake

**Comment by Exxion** [comment] 2016-05-15 10:03
It's probably actually due to a fix for a bug with Goofkitchen rather than being an original part of Goofkitchen
Because it used to never ever eject anything ever, including random shit you threw into pizzas, meaning you could eat anything small

**Comment by Killette2** [comment] 2016-05-15 13:24
I believe I've seen this same bug being reported before. Anyone have a link to the old report?

**Comment by Manfreedo** [comment] 2016-08-15 09:17
Little adition. If you grind the food the duped topping disapears as well. (great magic trick)
Do it with a watermelon and put the nuke disk in it then grind the original food. I'm wondering if the disk will respawn.

**Comment by Eneocho** [comment] 2024-02-09 18:13
Tested, couldn't reproduce anymore. Must've been fixed in one of the many kitchen reworks.

**Closed as completed by Eneocho** 2024-02-09 18:13 UTC
Labels: Bug / Fix, Needs Moar Testing
