### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Research station airlock doesn't bolt when cycled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5775] opened 2015-09-21 03:49 UTC
3d42a60efc3fdb4c46feb8f9282f22da12b413ee

Research station airlock doesn't bolt when cycled

WHY DOESN'T IT CYCLE

**Comment by clusterfack** [comment] 2015-09-21 21:35
which map tho

**Comment by gbasood** [comment] 2016-01-17 23:54
I think Box still has this issue. The pressure never hits the target pressure to finish cycling so it never does.

Occurs primarily after cycling to exterior to exit the research station the first time and then trying to cycle to re-enter

Just keep doing this until it happens, and it will, to reproduce

**Comment by 9600bauds** [comment] 2016-12-14 22:14
closing by virtue of "web report over a year old with missing info and never heard from again" + couldn't reproduce on Box

**Closed by 9600bauds** 2016-12-14 22:14 UTC
Labels: Bug / Fix, Needs Pics / Needs Moar Info
