### ISSUE TITLE
I (Plasmaman) can still use the telesci console as a ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10255] opened 2016-05-28 10:58 UTC
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9a4a34a0b6db2b2230a4d05cbf2926cb323a6c09 
> 
> General description of the issue
> PLASMAMAN GHOST CAN OPEN AND USE THE TELESCI CONSOLE
> 
> What you expected to happen
> FOR IT NOT TO HAPPEN
> 
> What actually happened
> ITS HAPPENING
> 
> Steps to reproduce if possible
> be me (or a plasmaman)
> open the console
> teleport someone into hellfire

**Comment by 9600bauds** [comment] 2016-05-28 18:34
Does the plasmaman thing have any relevance or can I close this for #8393

**Comment by TheFriggenSawbones** [comment] 2016-05-28 19:01
it does, no other race can do it.

**Comment by Kammerjunk** [comment] 2016-05-28 19:48
Have you gotten other plasmamen and other non-plasmamen to try it? I remember the ghost who did it in #8393 was human, and the comment you left there said you were a posibrain.
Either way, all ghosts are /mob/dead/observer so I dunno why them being plasmamen should matter, but I guess what do I know

**Comment by 9600bauds** [comment] 2016-05-28 20:01
cannot reproduce even as plasmaman

**Comment by clusterfack** [comment] 2016-05-28 21:43
Literally nothing about your past body except your appearance is saved when becoming an observer.

**Comment by TheFriggenSawbones** [comment] 2016-05-28 22:57
OK SO PLASMAMEN CANT DO IT

IM THE ONLY MAN WHO CAN

why? this is some deep shit

**Comment by PJB3005** [comment] 2016-05-28 23:13
You're the chosen one.

**Comment by Kammerjunk** [comment] 2016-05-28 23:16
You were meant to bring balance to the code, not destroy it.

**Comment by TheFriggenSawbones** [comment] 2016-05-28 23:24
it's nano ui
if you turn it off in Preferences it lets you FUCK with TELESCI
@PJB3005

**Comment by TheFriggenSawbones** [comment] 2016-05-28 23:48
`/obj/machinery/computer/telescience/attack_hand(mob/user as mob)
	if(user.client && user.client.prefs.usenanoui)//Check if the player is using nanoUI or not.
		ui_interact(user)
		return
	else
		interact(user)`

i pray this is the piece of code that fucked it so i can look smart

**Comment by PJB3005** [comment] 2016-05-28 23:52
Nope that's the code to handle opening the UI.

I have no idea how having nano off (its the only UI that supports it) could cause this because it should be using the exact same topic calls.

**Comment by PJB3005** [comment] 2016-05-28 23:55
Welp

So the telescience computer is shit code and doesn't correctly sanitize the topic calls, luckily nano actually does some checks before the topic call. The browser interface doesn't though...

**Comment by clusterfack** [comment] 2016-05-31 19:12
Pic nic

**Comment by clusterfack** [comment] 2016-05-31 19:12
It seems like someone should fix this!

**Comment by Megamaw** [comment] 2016-06-01 23:20
And you guys said skeletons were overpowered. Pssshaw.

**Closed as completed** 2016-06-02 21:44 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Exploitable, Sanity / Ghosthands
