### ISSUE TITLE
Ever since roll datums sprites repeatedly fail to load client side

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19820] opened 2018-09-27 02:08 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
f7ecef48b833d3fcdd9476a79d067effcaa682ec

# Description
Ever since patch I've had random crashes or freezes where I then am invisible afterwards.  I havent found a fix yet and its annoying and probably not universal
# Steps to Reproduce

Crash, reload
# What you Expected

To reload
# What Actually Happened

Invisibru

**Comment by SGuivenne** [comment] 2018-09-27 02:42
Crashes are being reported by multiple people in the northwestern quadrant of the bridge hallway.

**Comment by Substance455** [comment] 2018-09-27 02:51
Revert these changes, please. The sprites don't look that good and they're crashing everyone.

**Comment by ShiftyRail** [comment] 2018-09-27 09:47
This isn't necessarily a role_datums thing at all

I've had it happen the day after datums were merged, but when the .rsc was fully downloaded it's seamless
Basically there was a change not that long ago that made you download resources while on the lobby instead of before joining. The problem is that it puts a very heavy load on the client while it's downloading those things, probably causing you to crash/close it in frustration (in which case you have to do it again)

@Substance455 absolutely epic

**Comment by nervere** [comment] 2023-11-13 18:09
No longer an issue (wasn't ever really one though...)

**Closed as completed by nervere** 2023-11-13 18:09 UTC
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️
