### ISSUE TITLE
Blood Vendor not vending

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20056] opened 2018-10-09 17:42 UTC
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
# Revision
5ec54480ac85135eb6f46e8cd7f7ef001354f2f3

# Description
The blood vendor in box at least does not let you take blood bags out of it
# Steps to Reproduce
try to vend anything from the blood vendor
# What you Expected
to get blood vended
# What Actually Happened
it won't vend blood bags

**Comment by Irradiation** [comment] 2018-10-09 17:58
Were all blood types borked or was it only a specific blood type?

**Comment by Irradiation** [comment] 2018-10-09 18:03
Well, I tested it. Something broke the bloodbank vend hardcore.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment] 2018-10-16 03:18
Dupe of #20196 which has more info

**Closed as completed** 2018-10-16 03:46 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️
