### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Vision bugged by mutations

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5122] opened 2015-06-25 15:38 UTC
>Revision (Should be above if you're viewing this from ingame!)

615d402edc2f2fac55992f903250517c85edea6a 
>General description of the issue
Gained enhanced vision range mutation from radiation while incapacitated hud sits in black bock at normal resolution while world is visible in enhanced range.

>What you expected to happen
Gain enhanced vision range but have my screen still stay black as if i was incapacitated

>What actually happened
Vision expanded past my incapacitated vision and appears as visible despite me being incapcitated, also unable to wake up or see player spirte.

>Steps to reproduce if possible
Gain the mutation while downed?

**Comment by Shadowmech88** [comment] 2015-06-25 17:28
If I remember correctly, the position of HUD elements is hardcoded, so moving them all to be in coordination with the farsight mutation would be a feat.

**Comment by ComicIronic** [comment] 2015-06-26 00:14
Known issue, duplicate of #3500

**Closed by ComicIronic** 2015-06-26 00:14 UTC
