### ISSUE TITLE
New Grilles in medbay Invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7895] opened 2016-01-27 15:54 UTC
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Unsure if this applies anywhere but medbay, but making grilles in medbay made them invisible.

**Comment by 9600bauds** [comment] 2016-01-27 16:08
??????

**Comment by Exxion** [comment] 2016-01-27 16:20
I'd bet money that this is actually just that BYOND bug where sprites get fucked up clientside in long rounds

**Comment by ghost** [comment] 2016-01-27 20:04
[Can't reproduce]

**Comment by Exxion** [comment] 2016-01-27 20:11
In other words yeah it's just that unfixable BYOND bug that shits up sprites
Once my ghost turned into bats when I faced south

**Comment by DamianX** [comment] 2017-05-17 15:40
close this

**Comment by Intigracy** [comment] 2017-05-17 19:56
this is that old issue where getting grilles from pool gave them the incorrect icon

**Closed as completed** 2017-05-17 19:55 UTC
Labels: Needs Moar Testing, T-Thanks BYOND

**Comment by Exxion** [comment] 2017-05-17 23:53
It's not the icon, but close enough

Unless there are multiple grille pooling issues
