### ISSUE TITLE
Balaclava covers winter hood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25756] opened 2020-01-27 01:48 UTC
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
4d2a5ba161d36be983ea882a7ed73822a72206b7

# Description
When wearing balaclava on the face slot and using the built in hood on the winter coat, the balaclava appears on the outside.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Zth--** [comment] 2020-01-27 12:52
Duplicate of #23908

**Closed as completed by Zth--** 2020-01-27 12:52 UTC
