### ISSUE TITLE
Shades cannot see anything, lighting isn't applied

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30172] opened 2021-08-10 22:34 UTC
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
69c3b4fc721503af4791ac16870a39adf02e34bb

# Description
Shades have opaque light overlays blocking vision
# Steps to Reproduce
Become a shade as cultist
# What you Expected
Clear vision or lighting
# What Actually Happened
Default sprites

**Comment by DeityLink** [comment] 2021-08-10 22:51
Duplicate of #30166

I'm on it.

**Closed as completed by DeityLink** 2021-08-10 22:51 UTC
