### ISSUE TITLE
Oversized font causes barsign to fall off the wall and break

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29716] opened 2021-06-06 16:57 UTC
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
bbba352827f0d8a6ffdc9b112ac5a3431fab7038

# Description
I am pretty sure this is what caused it since the sign replacement that was given to me functioned perfectly fine afterward and the font size was the only setting I had changed.
# Steps to Reproduce
Go to the customizing menu for the barsign and set the font size above the default 16 or whatever, I had tried fontsize 20 since I had no reference for font sizes at first.  Apply the settings and the sign falls off the wall.
# What you Expected
I expected big text.
# What Actually Happened
I accidentally broke it.

**Comment by Securitymain** [comment] 2023-11-01 08:28
Unable to reproduce, perhaps fixed by https://github.com/vgstation-coders/vgstation13/pull/13542 ?
@Kurfursten pls close

**Closed as completed** 2023-11-01 08:43 UTC
Labels: Bug / Fix
