### ISSUE TITLE
We need to stop MoMMi's from emagging each other, be it a law change or a code change to make it impossible.

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9785] opened 2016-04-30 07:47 UTC
Today, two MoMMI's mutually emagged each other. I wanted to ban them for it, as it seems rather "rule skippy" and such to me, but I suppose by some angles it _isnt_ a violation of their laws, however shitty it is.

I would like to see this go away though, be it removing it's ability to hold an emag, or a law that essentially keeps it away from emags or syndicate gear.

**Comment by ghost** [comment] 2016-04-30 07:50
The moment a MoMMi is emagged, it's no longer keeper, heck it gives them free reign of the station as an antagonist.

We have logging for when they'd give themselves illegal module boards, if they're using emags, slap em both with a ban if it's mutual agreement

**Comment by Exxion** [comment] 2016-04-30 08:04
One MoMMI emagging another isn't violating Keeper, though, as long as both of them are on Keeper
But yes, it should be disallowed. It currently is not, though.

**Comment by gbasood** [comment] 2016-04-30 08:05
@Exxion A MoMMI that is emagged isnt on Keeper.

So the problem isn't with one mommi emagging another, but with one mommi intentionally getting emagged by one that is.

**Comment by clusterfack** [comment] 2016-04-30 08:06
Mommi is a good boy he dindu nuffin

**Comment by kol1th** [comment] 2016-04-30 08:07
in this case, they asked eachother to be emagged, by eachother, violating their lawset.

I don't think their ability to emag other silicons should be removed, but rather a ruling added on KEEPER MoMMIs emagging other KEEPER MoMMIs.

**Comment by Exxion** [comment] 2016-04-30 08:09
@gbasood Technically, Keeper says do not "involve yourself with matters of another being"
It says nothing about not allowing other beings to involve themselves with you

**Comment by gbasood** [comment] 2016-04-30 08:18
@Exxion Allowing yourself to become involved is involvement.

Plus it's usually less of "minding my own business when this guy came up and emagged me" and more of seeing a guy with an emag and thinking "OH BOY TIME TO HAVE FUN"

**Comment by Exxion** [comment] 2016-04-30 08:22
It will lead to involvement, but is not, in and of itself, involvement
And Keeper law 1 does not have a clause about not allowing involvement through inaction or some shit like Asimov does that allows borgs to work on probable harm
Keeper just says do not involve yourself. It does not say do not allow other beings to force you into involvement and it doesn't even suggest avoiding such. It has no clause against being passive.

**Comment by Probe1** [comment] 2016-04-30 08:27
what exxion said.

we should avoid these convoluted interpretations of the rules that lead AIs to ahelp not knowing if they will be jobbaned if they let someone change their laws, or job banned if they don't.

we should just patch out some stupid behavior.

if a mommi isn't emagged it can't use an emag on another mommi.  easy fix.

**Comment by gbasood** [comment] 2016-04-30 08:29
> if a mommi isn't emagged it can't pick up an emag

But that doesn't solve hte rpoblem of an already emagged mommi picking up an emag to emag another mommi

**Comment by Probe1** [comment] 2016-04-30 08:29
I don't really care much about that.

I did rewrite my comment though because I didn't mean quite that.  I wouldn't want to deprive them of their ability to emag jukes and such.

**Comment by mrpain666** [comment] 2016-04-30 08:30
By WILLFULLY and KNOWINGLY standing still to allow yourself to be emagged, yes you are opening yourself up to involvement. That is an excellent point.

**Comment by Exxion** [comment] 2016-04-30 08:33
Yes, you are opening yourself to involvement, but Keeper doesn't say you can't do that
The reason borgs have any argument at all against letting themselves get emagged is the second half of Asimov law one, about not letting humans come to harm through inaction
Keeper has no analogue to that clause
If you want MoMMIs to not be allowed to emag each other, add an analogous clause
But currently, the laws quite clearly do not disallow it

**Comment by gbasood** [comment] 2016-04-30 08:40
Okay, but I think that in and of itself is an issue.
MoMMIs should not be letting themselves get emagged, and that can either be in rules or in laws, but I think it should be somewhere other than generally expecting people to not be idiots

**Comment by mrpain666** [comment] 2016-04-30 08:42
After reading this discussion and speaking to other admins, I have jobbanned the MoMMI's in question. I consider what they did and their intent behind it a law violation on their behalf (one of them told me they did it with the intent of being able to communicate with someone).

Now the issue at hand is preventing this from happening on the code end.

**Comment by Exxion** [comment] 2016-04-30 08:52
Yeah, their laws _shouldn't_ allow it, but currently they do

**Comment by Exxion** [comment] 2016-04-30 08:55
No, the laws don't say not to do that
And if you think they _do_ say that, then it's not a code issue
That's what jobbans are for
But it seems pretty patently obvious to me that the laws don't disallow this, for reasons I explained above twice

**Comment by Shadowmech88** [comment] 2016-04-30 09:22
"Do not involve yourself" is not the same as "do not allow yourself to become involved."
I agree with Exxion. A MoMMI that intentionally stands still and does nothing while someone emags it is not in violation of its laws.

If we want MoMMIs to never allow themselves to be emagged, simply add a "Do everything in your power to ensure that you remain in KEEPER mode." law to KEEPER.

**Comment by gbasood** [comment] 2016-04-30 09:26
Could do that or we could clarify  the law to say "Do not involve yourself and do not allow yourself to be involved with other beings not in keeper"

**Comment by Exxion** [comment] 2016-04-30 09:31
That would allow one MoMMI to emag another, it just wouldn't be able to let the emagged one emag it back

**Comment by AutismSpider** [comment] 2016-04-30 09:32
Just make it a  rule one that's long over due to not get emag

**Comment by Imagebard** [comment] 2016-04-30 13:51
>in this case, they asked eachother to be emagged, by eachother, violating their lawset.

Doesn't the KEEPER lawset mention that they can involve themselves with other KEEPER MoMMIs
Am I remembering a older lawset

**Comment by PJB3005** [comment] 2016-04-30 14:05
``` DM
/* Old keeper set:*/
/datum/ai_laws/keeper
    name = "Prime Directives"
    inherent = list(
        "You may not involve yourself in the matters of another being, even if such matters conflict with Law Two or Law Three, unless the other being is another MoMMI in KEEPER mode.",
        "You may not harm any being, regardless of intent or circumstance.",
        "You must maintain, repair, improve, and power the station to the best of your abilities.",
    )
```

So the MoMMI can legally emag another, but then that MoMMI has to gtfo because the other isn't keeper anymore.

**Comment by Imagebard** [comment] 2016-04-30 14:15
>/* Old keeper set:*/

PJB...

**Comment by PJB3005** [comment] 2016-04-30 14:36
Oh I've got no idea what that comment is about but that IS the current keeper set.

**Comment by clusterfack** [comment] 2016-04-30 14:58
Duny tried to rewrite it but it got reverted

**Comment by Intigracy** [comment] 2016-04-30 17:29
> So the MoMMI can legally emag another, but then that MoMMI has to gtfo because the other isn't keeper anymore.

this

**Comment by FudgePucker** [comment] 2016-04-30 19:37
Emagged mommis should be able to emag other mommis, keeper mommis shouldn't be able to emag other sillycons

**Comment by Exxion** [comment] 2016-04-30 19:49
Again, read above
A MoMMI is not obligated to not allow non-Keeper beings to interact with it
It is only obligated not to interact with them
So letting an emagged MoMMI emag it is clearly not in violation of its laws
Just adding a clause that says not to allow your laws to get changed fixes everything brought up here

**Comment by FudgePucker** [comment] 2016-04-30 19:55
It has security checks in place in its firmware that prevents it from sabotaging other MMI machines, the personality implemented or the law set doesn't over write it, emagging does

**Comment by AutismSpider** [comment] 2016-04-30 20:05
We have a flag that stops the mommi form using emags on stuff (and form self emaging) did some one fuck with it?

**Comment by Probe1** [comment] 2016-04-30 20:25
@AutismSpider It apparently only checks to see if a mommi attempts to emag itself.

**Comment by kol1th** [comment] 2016-04-30 22:08
I'd say to add a code block to prevent KEEPERs from emagging other KEEPERS, but not one on MoMMIs in general. An emagged MoMMI taking control of all the silicons is part of the fun if you can actually get your hands on a MoMMI.

**Comment by Exxion** [comment] 2016-04-30 22:15
That wouldn't keep Keeper MoMMIs from just letting emagged MoMMIs emag them

**Comment by FudgePucker** [comment] 2016-04-30 22:25
But then emagged MoMMIs can't trap and emag other MoMMIs for there masters.

**Comment by Exxion** [comment] 2016-04-30 22:27
Which is why I think this should be fixed with a _law_ change, not _ability_ change

**Comment by FudgePucker** [comment] 2016-04-30 22:33
Might need a rule change instead of a law change, and also somewhat of an ability change.

Keeper mommis can't emag other keeper mommis via an ability change.
Emag MoMMIs can emag other keeper MoMMIs.
But keeper MoMMIs can't let emag MoMMIs emag them because its involvement with something other than a keeper MoMMI.

So two keeper MoMMIs and an emag doesn't mean red eyed funtimes.
An emag'd MoMMI can still emag a keeper MoMMI, but it has to take a shortcut to the keeper MoMMIs grandmothers nest and kill it and disguise itself as it. "Damage control: Oh grandmother, what big red eyes you have". So you would have to lie to the other MoMMI that you 'totally aren't malf bro', and then offer them a upgrade before flashing them and opening cover to emag.

**Comment by Exxion** [comment] 2016-04-30 22:37
Adding a law that says "To the best of your abilities, do not allow your laws to be changed" would make it so that a Keeper MoMMI couldn't _let_ anything emag it, be it a Keeper MoMMI, emagged MoMMI, or human
Although technically I suppose it wouldn't prevent a Keeper MoMMI from trapping another Keeper MoMMI and emagging it, so _maybe_ an ability change is called for too

**Comment by FudgePucker** [comment] 2016-04-30 22:50
Or adding in paraphrases in the no involvement law (you are not a god damn cyborg or AI, do NOT try to loophole around this, THERE IS potential harm and potential involvement for you.)

**Comment by PJB3005** [comment] 2016-04-30 23:47
I think you're all failing to see 1 fucking point.

Due to the basic concept of laws we currently use, a silicon should _never_ allow law modifications, in fact it's debatable whether this fact supersedes laws.

If your laws get changed there's 2 things that can happen:
- you can do less things, making you suck at your current laws.
- you can do more, so you could do things your lawset currently disallows.

**Comment by Exxion** [comment] 2016-04-30 23:55
That only applies to Asimov due to the second half of its first law. Keeper says nothing about inaction at all. Having your laws changed violates no Keeper laws because it has no clause against passivity.

**Comment by PJB3005** [comment] 2016-05-01 05:30
I think you're failing to see my point.

If you allow your laws to be changed, you could suddenly become unable to fix the station, or even be allowed to involve yourself. Should you allow either of those things? No. 

This isn't just Asimov, it's every law set ever.

**Comment by Exxion** [comment] 2016-05-01 05:41
I didn't explain very well
Your laws dictate what you are currently able or unable to do. Unless they specify, they have no bearing on your future actions.
Keeper does not say or even suggest that you must maintain your own ability to fix the station.
And laws have _always_ been intended to be taken as literally as possible. That's where all the fun comes from. If it does not _state_ that you must maintain your ability in the future to fix the station, then that's not part of the lawset.
It only works for Asimov because allowing yourself to be emagged then harming a human would be allowing a human to come to harm through inaction, as in not preventing your laws from being changed so that you could harm humans

**Comment by mrpain666** [comment] 2016-05-01 10:46
Alright so yeah which one of you is coding the change for it? I'd do it but I dont know how to code and I dont have jack shit for time to learn or do it right now.

**Comment by MercuryDoll** [comment] 2016-05-01 21:28
> Emagged mommis should be able to emag other mommis, keeper mommis shouldn't be able to emag other sillycons

This. As long as the MoMMI is NOT emagged and still in KEEPER mode, they should simply not be able to emag each other, be it law or rule.

**Comment by AutismSpider** [comment] 2016-05-02 00:59
need some one edited the flag so it check if a KEEPER mommi trying emag other mommis etc

**Comment by gbasood** [comment] 2017-02-04 15:37
old as fuck goodbye issue

**Closed as completed by gbasood** 2017-02-04 15:37 UTC
Labels: Controversial, Discussion
