### ISSUE TITLE
Hot Chili no longer increases body temperature

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#3128] opened 2015-02-20 18:07 UTC
To test this: Eat Hot Chili, watch as nothing happens.

I suspect its an issue with the reagent capscisin or however it is correctly spelt. Might very well be something else however.

**Comment by CptWad** [comment] 2015-02-20 23:55
I ate one earlier and I got hot.
Potency is important to heat factors. Try eating many peppers in a short period for the super hotness

**Comment by Probe1** [comment] 2015-02-21 06:31
I just checked in round by eating ten.  While it did give me an increased body temperature, it did not give me burns as I expected it to.

Needs more testin.

**Comment by Kurfursten** [comment] 2015-04-22 10:38
Not a bug. Hot Chili does indeed contain 3u of Capsaicin and capsaicin increases your body temperature.

**Comment by clusterfack** [comment] 2015-04-25 09:10
Chili hasn't been changed in forever, it has 3u capsaicin
Capsaicin hasn't been changed in forever either

The thing is, your body temp will correct itself with the environment if you aren't wearing a hardsuit. Wear a hardsuit and eat the chili and you'll find the effect is much more pronounced.

**Closed by clusterfack** 2015-04-25 09:10 UTC
Labels: Bug, Feature Loss
