### ISSUE TITLE
infect_mob_random_greater event creates 2 viruses

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12179] opened 2016-10-12 21:50 UTC
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 02a01197183ab1b5eb1b5655d68eb7944e7f6d63 
> 
> General description of the issue
> While it's to be expected with an event name causing a fair bit of chaos. Spawning 2 viruses that have the potential to have gibbingtons, kingston, arachnogenesis, etc. seems more of an oversight
> 
> What you expected to happen
> Okay boys, rev up the radium and watch your monkeys, we got a virus to cure
> 
> What actually happened
> THE MONKEYS ARE EITHER DEAD OR BEING EATEN BY SPIDERS SO WE CAN'T USE THEIR BLOOD thanks to #11779, I'LL CURE IT WITH MY OWN BODY and then they fell to instant toxin-death as both cures procced at the same time

http://i.imgur.com/Z4mjktK.png

> Steps to reproduce if possible
> Wait for a greater random virus event to occur, or try and force one yourself

**Comment by SonixApache** [comment] 2016-10-12 21:51
related: #12141

**Comment by Allspice** [comment] 2016-10-12 22:00
I thought that was a feature

**Comment by despotate** [comment] 2016-12-23 21:54
Tested and couldn't reproduce. Every time I manually forced the event it only made one virus. Nothing in the code suggests it'd duplicate them either.

**Comment by Probe1** [comment] 2016-12-23 22:54
I'll get back to you on that I think it's because you were local testing and you were the only ckey.

**Comment by despotate** [comment] 2016-12-23 23:49
Yeah, I was local testing with just myself as the ckey. Still scratching my head on how having more of them would result in duplicating viruses.

**Comment by DeityLink** [comment] 2019-08-02 13:02
Fixed by nuviro. Both Viral infections and outbreak events now infect all victims with the same disease.

**Closed as completed** 2019-08-02 15:02 UTC
Labels: Balance, Discussion
