### ISSUE TITLE
MegaSeed Servitor bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6551] opened 2015-11-11 17:10 UTC
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
# Bug 1: Second generation and above seeds (Ones that have been extracted from the seed extractor) lose their icon once put into the megaseed servitor and retrieved.
# Bug 1.5: Possibly related to bug 1, some seeds that come out as question marks, when planted, yield no plant at all.
# Bug 2: Upon putting in an extracted seed into the Servitor, all other seeds lose their name besides the ones that are listed as 'out of stock'

**Comment by Probe1** [comment] 2015-11-11 17:18
partially but not completely a duplicate of 
https://github.com/d3athrow/vgstation13/issues/6538

**Comment by ghost** [comment] 2016-01-03 21:17
Check if it still happens with Botany3

**Comment by 9600bauds** [comment] 2016-01-04 21:51
Still happens, haven't looked into it yet, I don't like this vending machine storage business

**Comment by 9600bauds** [comment] 2016-01-26 20:37
Related to #7684

**Comment by gbasood** [comment] 2016-01-30 00:37
Botanist put some potato seeds into the vendor and apparently it added to the total count of tomato seeds.

But when he ejected them, the packet was empty.

![](http://i.imgur.com/gAfQs51.png)
???

**Comment by 9600bauds** [comment] 2016-01-30 01:06
Deity needs to look into this

**Comment by 9600bauds** [comment] 2016-05-08 22:37
I'm just gonna link all the related issues here @DeityLink

**Comment by Exxion** [comment] 2016-05-08 23:15
Easy solution: Just remove the ability to put seeds back in the MegaSeed Servitor
Normally I don't advocate for removing features in order to fix bugs, but this is a special case because there are two other machines _right there in hydroponics_ that do a better job of storing seeds than the Servitor ever will

**Comment by 9600bauds** [comment] 2016-05-08 23:27
A lot of people don't know the Seed Extractor works too
How to make it more intuitive?

**Closed** 2016-10-30 12:00 UTC
Labels: Bug / Fix
