### ISSUE TITLE
Botany3: Nettles, deathnettles, novaflowers can't be grinded

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7511] opened 2016-01-03 18:42 UTC
Putting them into grinder and grinding them results in 0 chems.
Novaflowers have to be put in using a plantbag.

**Comment by 9600bauds** [comment] 2016-01-03 20:48
That's weird, I specifically didn't touch those. I'll look into it

**Comment by Kurfursten** [comment] 2016-01-03 21:27
@deitylink

**Comment by DeityLink** [comment] 2016-01-05 23:28
Eh, I didn't touch nettles nor deathnettles. It COULD be because those three are inedible grown, and as such not part of an allowed type path.

**Comment by 9600bauds** [comment] 2016-01-10 01:13
Cannot reproduce nettle or deathnettle issue
![space_station_13_2016-01-09_22-13-11](https://cloud.githubusercontent.com/assets/6526157/12219339/3d7b5760-b71e-11e5-867b-836b8b3b7dff.png)

**Comment by 9600bauds** [comment] 2016-01-26 01:38
Should be fixed in #7739

**Closed as completed** 2016-03-29 21:42 UTC
Labels: Bug / Fix, Feature Loss
