### ISSUE TITLE
Lights don't follow when you crawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16931] opened 2017-12-29 21:56 UTC
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
e7ddf7f785a85dace4a59a8269406caa4b983cef

# Description
Lights will not follow you while you crawl around in maint.

# Steps to Reproduce
Turn on light
Rest
click adjacent tiles
# What you Expected
Light stays centered on me
# What Actually Happened
Light stays where i was and only rarely updates

**Comment by ShiftyRail** [comment] 2017-12-29 22:09
Duplicate of #16877

**Comment by MadmanMartian** [comment] 2017-12-29 22:17
Duplicate.

**Closed as completed by MadmanMartian** 2017-12-29 22:17 UTC
