### ISSUE TITLE
Cyborg - Supply - Sheet Snatcher 9000 view bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30416] opened 2021-08-29 22:27 UTC
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
89ed3dc43bdd1097ee79cac3de5822c6729d39fe

# Description
alt clicked the SS9000 to see what sheets i had in the container, then got zoomed out
# Steps to Reproduce
Above
# What you Expected
yes
# What Actually Happened
that

**Comment by DeityLink** [comment] 2021-08-29 22:42
Duplicate of #27141

**Closed as completed by DeityLink** 2021-08-29 22:42 UTC
Labels: Bug / Fix
