### ISSUE TITLE
Breaking tape nullspaces you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28686] opened 2021-01-27 01:17 UTC
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
53320cf0775751099cdc5ac0fa4ecd3b781e1760

# Description
Breaking tape seems to have a chance to nullspace you
# Steps to Reproduce
break tape. Maybe move at the same time?
# What you Expected
Tape break
# What Actually Happened
Step between worlds

**Comment by Kurfursten** [comment] 2021-01-27 03:04
I couldn't reproduce this or even find relevant runtimes. Also a bunch of other people were breaking tape. I don't think it was the tape.

**Comment by Blithering** [comment] 2021-01-27 05:00
Did some testing in the thunderdome. Couldn't replicate it but one thing I noticed was the "you can't break the tape unless you use force" message did not pop up when I was cutting tape and got nullspaced, the baton was able to cut in help intent just fine.

**Comment by Kurfursten** [comment] 2021-01-27 05:03
Unrelated, that message only shows if you don't use a weapon

**Comment by Blithering** [comment] 2021-01-27 05:07
The message did pop up using the baton in the thunderdome though.

**Comment by beesil** [comment] 2021-01-27 05:54
related #20767

i've witnessed this before with a mommi, seems very rare. do you remember what intent you were on?

**Comment by Kurfursten** [comment] 2021-01-27 06:07
Possible cause: theoretically if you bump tape as it is being destroyed and you are allowed to access it, you would be sent to nullspace since it would be in nullspace (this is the feature that allows you to walk into tape if you are permitted access)

The odds of this bump timing are probably extremely low and then it might require some ref magic. I tried to reproduce >30 times at centcomm with no luck, but this is the only likely cause.

**Comment by Blithering** [comment] 2021-01-27 16:21
That sounds about right, since there as a lot of tape thrown around, I was moving to the next bit as I poked the one currently in reach.

**Comment by Exxion** [comment] 2021-01-27 17:46
There is an ancient bug somewhere that if you bump a slime the same frame it bumps you, you get nullspaced

**Comment by DeityLink** [comment] 2021-08-18 12:04
In the meantime it'll be easy to add a sanity check before the forceMove

**Closed as completed** 2021-08-19 20:04 UTC
Labels: T-Thanks BYOND
