### ISSUE TITLE
Couches and chairs overlay on top of railings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34853] opened 2023-08-02 21:01 UTC
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173

# Description
Couches and chairs appear over railing sprites at certain angles, particularly facing downwards, 6 o clock, south, however you wanna label it.
# Steps to Reproduce
Build railing for decoration, build couch or chair on same tile
# What you Expected
Railing takes priority and covers furniture like it does for machines 
# What Actually Happened
Ugly looking situation where a chair or couch is phasing through a railing

**Comment by Hinaichigo** [comment] 2023-08-03 02:47
Duplicate of #34782.

**Closed as completed** 2024-03-31 14:17 UTC
