### ISSUE TITLE
Extremely delayed welderbomb gibbing

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#17915] opened 2018-03-23 13:44 UTC
#### Description of issue
I was standing in maintenance when a wizard set off roughly ten welderbombs in the corridor outside. As it is the normal response to hearing an explosion, I opened the door to gawk at the mess and was sucked into the corridor by ZAS. I was preparing to fumble to turn my internals on when I was pulled over one of the space tiles caused by the explosion and instantly gibbed. At that point it had been a good ten seconds since the explosion and no further damage to the structure was occurring. While I am aware larger explosions sometimes lag with updating their damage, this is the first instance I have seen of it happening with welder bombs, and so late. 

#### Difference between expected and actual behavior
Expected the space tile to have finished exploding, when in fact it was still checking to gib anyone who enters

#### Steps to reproduce 
set off a few welder tanks, get sucked into the space they used to occupy afterwards maybe?

#### Specific information for locating

[20:12:44]GAME: Explosion with size (1, 2, 4) in area Starboard Primary Hallway 
[20:12:45]EMOTE: Thrush Ruckus/DT Scurvy (@303,228,1): <B>Thrush Ruckus</B> screams in agony!
[20:12:45]EMOTE: Dio Brando/ChugMonkey (@300,226,1): <B>Dio Brando</B> screams in agony!
[20:12:45]EMOTE: Dio Brando/ChugMonkey (@300,226,1): <B>Dio Brando</B> lets out a sharp cry and drops what they were holding in their left hand!
[20:12:45]EMOTE: Dio Brando/ChugMonkey (@300,226,1): <B>Dio Brando</B> seizes up and falls limp, his eyes dead and lifeless...
[20:12:47]EMOTE: Thrush Ruckus/DT Scurvy (@303,230,1): <B>Thrush Ruckus</B> seizes up and falls limp, his eyes dead and lifeless...
[20:12:48]ACCESS: Logout: *no key*/(Dio Brando) (Starboard Primary Hallway - 301,228,1)
[20:12:48]ACCESS: Login: ChugMonkey/(Dio Brando) from [NOPE] || BYOND v511
[20:12:48]SAY: Rollo/MrTawm (@209,228,1) As Galactic Common : Jesus fuck
[20:12:49]SAY: Unknown (as Albert Bernd)/Mxr41 (@304,255,1) As Galactic Common :  um
[20:12:50]SAY: Phil Ochs/AngstAlmighty (@293,221,1) As Galactic Common : Yup
[20:12:51]SAY: Thrush Ruckus/DT Scurvy/(Thrush Ruckus) (@300,225,1) Deadsay: stammers, "Who"
[20:12:53]EMOTE: Phil Ochs/AngstAlmighty (@289,221,1): <B>Phil Ochs</B> gasps!
[20:12:54]ACCESS: Logout: *no key*/(Shush) (Starboard Primary Hallway - 301,227,1)
[20:12:54]ACCESS: Login: Blithering/(Shush) from [NOPE] || BYOND v511

From the logs, 10 second gap between explosion's first fatalities, and my untimely transition from mime to wallpaper
#### Length of time in which bug has been known to occur

one explosion's worth of time

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by chesse20** [comment] 2018-03-23 18:53
i've seen explosions that don't end for like a full minute. It's a feature not a bug, so you can see the explosion coming and then run away

**Comment by Blithering** [comment] 2018-03-23 19:38
Again, this was a welderbomb explosion, and it was long over.

**Comment by Kurfursten** [comment] 2018-03-24 04:04
Since this is performance related, I think this may be unsolvable unless a way is found to make explosions resolve more quickly, which is naturally difficult since they involve a lot of objects simultaneously changing. We really should log welder explosions though, that would help solve the mystery if, for example, a welder was "pending" explosion and had disappeared but hadn't handled its detonation yet.

**Comment by Exxion** [comment] 2018-05-31 21:38
I don't think it *is* performance related if the tile you were gibbed on was already space. That means it had already *been* exploded.
That said, I have no alternative theories.

**Comment by Eneocho** [comment] 2024-02-10 22:24
Was unable to replicate. Closing it since we had the explosion performance rework that probably fixed it.

**Closed as not planned by Eneocho** 2024-02-10 22:24 UTC
Labels: Bug / Fix
