### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Solar Generator Control

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3709] opened 2015-04-02 23:58 UTC
So basically i noticed that the solar generator control doesn't automatic change the array orientation when there is no generated power,is that a feature or a bug?

**Comment by ComicIronic** [comment] 2015-04-03 00:18
Duplicate of #3398.
Web reports coming with a Github lookup when?

**Closed by ComicIronic** 2015-04-03 00:18 UTC
