### ISSUE TITLE
More library stuff!

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3428] opened 2015-03-16 03:10 UTC
The page system works and all, but it's pretty unwieldy. There's over 40 pages and it's a lot of junk to sift through when you can't just ctrl+f and find the book you want. When you lose power, the icons for the library computers switch to the apiary/single use spellbook. And it might have something to do with losing power and getting it back, but I can't seem to print manuals out at all
![ss 2015-03-15 at 08 24 04](https://cloud.githubusercontent.com/assets/9064611/6659225/f049f4aa-cb56-11e4-895c-1ba8eb200d39.jpg)

**Comment by ComicIronic** [comment] 2015-03-16 16:38
The second part is a duplicate of #3415.

**Comment by d3athrow** [comment] 2015-03-17 04:46
I can add searching to the main library comp I guess.

**Comment by NigglyWiggly** [comment] 2015-03-17 05:34
That would be great! I understand the need for the page thing, but as it is right now it's just sort of hard to get anything done in a reasonable amount of time

**Comment by sonime** [comment] 2015-03-18 04:00
I agree. Also search by SS13BN is broken again, the visitor computer doesn't seem to do category search. A "Jump To Page" option in the library computer would help also.

**Comment by GreatValue** [comment] 2015-03-27 21:45
Hey! I'm super interested in inputting a whole lot of new books in the system, but it seems the html isn't functioning. Also, printing manuals would be great! Just so you don't feel like this would be an update that would go unnoticed. 

Thanks! :dancers:

**Comment by Probe1** [comment] 2015-05-24 03:59
@NigglyWiggly how much of this got merged and how much is left?

**Comment by NigglyWiggly** [comment] 2015-05-25 19:51
I believe it all works fine now, the search works and all that.
Only thing I can think of beyond the formatting thing @GreatValue mentioned is that the Library computer can't be wrenched and moved around, but everything else can

**Comment by Kurfursten** [comment] 2015-10-15 21:36
@clusterfack Close this, as it's mostly done
@NigglyWiggly If it still interests you, make a new feature request to de-snowflake the library computer into a normal computer (e.g.: with a circuit and everything)

**Closed** 2015-10-16 00:50 UTC
Labels: Feature Request
