### ISSUE TITLE
Bell in backpack problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16323] opened 2017-10-24 16:48 UTC
(WEB REPORT BY: szuflox REMOTE: 172.93.109.202:7777)
# Revision
c82dce1e6c0c87b10c0b24893ccec568de34d4b6

# Description
When you put ringing bell in backpack you can't remove it, but you can wrench it and use it while it's still in your backpack.

# Steps to Reproduce
Unwrech the bell, put in backpack, wrench while in backpack, ring.
# What you Expected
Being able to remove it from backpack and not wrench it.
# What Actually Happened

**Comment by Exxion** [comment] 2017-10-24 16:52
Duplicate of #15606
And probably others but I don't want to go looking right now

**Closed as completed by Exxion** 2017-10-24 16:52 UTC
