### ISSUE TITLE
poppy seeds from the seed extractor don't go into the microwave

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20445] opened 2018-10-26 18:51 UTC
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)
# Revision
70c7e527e111d6b17f94bcde9c3ae8dafddc6108

# Description
The poppy prezels require poppy seeds to bake, but only the seeds from the vendor fit the microwave seeds from the extractor don't work
# Steps to Reproduce
try to put poppy seeds from the extractor into the microwave
# What you Expected
Prezels
# What Actually Happened
You have no idea what you can cook with this the packet of poppy seeds.

**Comment by Exxion** [comment] 2018-10-26 18:59
Taking bets on typecheck

**Comment by ShiftyRail** [comment] 2019-06-19 19:20
Dupe of #12582

**Closed as completed by ShiftyRail** 2019-06-19 19:20 UTC
Labels: Bug / Fix
