### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) (Map Issue: Taxi) No CAC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5239] opened 2015-07-04 15:26 UTC
>Revision
257b09d58690c116ac0d4071d151d7e5211a8c5b

Taxistation lacks a Central Atmospherics Computer OR an Atmospherics Automations Computer

At least one would be very nice

**Comment by ComicIronic** [comment] 2015-07-04 16:08
Duplicate of #4689

**Closed by ComicIronic** 2015-07-04 16:08 UTC
