### ISSUE TITLE
Wheelstation derelict MoMMI spawner is not giving the right lawset

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#35401] opened 2023-11-18 21:58 UTC
It's missing the law that forces it to stay on the station.
![laws](https://github.com/vgstation-coders/vgstation13/assets/41342767/f1259dfa-af7f-4931-805a-d79104b647d1)

**Comment by brndd** [comment] 2023-11-18 22:00
How does this even happen? The derelict on Wheel is literally copypasted from Boxstation, and as far as I can tell the spawner is exactly the same on both.

**Comment by nervere** [comment] 2023-11-18 22:23
This isn't a Wheel issue, it's an issue with derelict MoMMI's. They *have* the law, it just doesn't show when you first spawn in.
If you use `Show-Laws`, you will see it. Gonna close this as a duplicate of #29522

**Closed as not planned by nervere** 2023-11-18 22:23 UTC
