### ISSUE TITLE
Jukebox becomes unwrench/screwable after cutting the radiation wire

### ISSUE THREAD

**Issue by SirSkeleto** [d3athrow/vgstation13#22120] opened 2019-03-21 05:34 UTC
#### Description of issue

If you cut the radiation wire on the juke (as you should, if you intend to hack it without accidentally killing everyone), tools can no longer be used on the jukebox

#### Difference between expected and actual behavior

expected this not to happen, because why would it

#### Steps to reproduce

screwdriver and wrench a juke, see that it works, cut every wire but the rad wire, see it still works, cut the rad wire, see it stops working, does not start working when mended

#### Length of time in which bug has been known to occur

As long as I can remember

#### Server revision

current, just tested on test serb

[bug]

**Comment by Kurfursten** [comment] 2019-03-21 05:36
This is a dupe of #22099

**Closed as completed by Kurfursten** 2019-03-21 05:36 UTC
Labels: Bug / Fix
