### ISSUE TITLE
Paper Envelope Deleting items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19116] opened 2018-08-05 05:55 UTC
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
a9a159b5182cfbcbc6cede6afa1766a858dc8032

# Description
if you make an envelope and put something into it and then right click the envelope and fold it into another envelope the item inside is gone forever, the envelope can also be folded into a paper plane or whatever.

**Comment by Pathid** [comment] 2018-08-05 05:56
Duplicate of #18933

**Closed as completed** 2018-08-05 07:36 UTC
