### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Nitrogen tanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4303] opened 2015-05-05 16:38 UTC
a847b58facc9deaa3810b43dc6e1c9e6e9f59cde 

All nitrogen tanks (or tanks ive seen) have 0 nitrogen in said tanks. Even ones spawned by admins have 0

**Comment by PJB3005** [comment] 2015-05-05 16:42
Dupe of #4290,
Which was fixed by #4293

**Comment by ComicIronic** [comment] 2015-05-05 16:51
Is this definitely fixed?

**Comment by clusterfack** [comment] 2015-05-05 17:15
Apparently not?

**Comment by CptWad** [comment] 2015-05-05 19:05
Dunno related to #4300

**Closed** 2015-05-05 20:58 UTC
