### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Comms are fucked, yo.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3635] opened 2015-03-29 20:46 UTC
>Revision (Should be above if you're viewing this from ingame!)
f936c9a44a7fef1bd99ecf85011fe6604b937f9a 

>General description of the issue
No more department channels

>What you expected to happen
Talk via department channel

>What actually happened
Common channel, also all headsets lack their respective channel option

>Steps to reproduce if possible
Log in right now

**Comment by ComicIronic** [comment] 2015-03-29 21:13
Duplicate of #3632

**Closed by ComicIronic** 2015-03-29 21:13 UTC
