### ISSUE TITLE
(WEB REPORT BY: thataxxguy REMOTE: 198.245.63.50:7777) Paramedic station and starting headsets do not have medical channel.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3641] opened 2015-03-30 04:56 UTC
None of the headsets in the paramedics station or the one starting with have access to the medical channel on them despite being medical headsets.

All ones tested have this issue.

**Comment by CptWad** [comment] 2015-03-30 06:27
Duplicate of #3632

**Comment by ComicIronic** [comment] 2015-03-30 08:27
Say what you will about web reporting, but I wish people actually went on Github to report issues.

**Closed by ComicIronic** 2015-03-30 08:27 UTC
