### ISSUE TITLE
bugged fish egg scoop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17143] opened 2018-01-20 08:05 UTC
(WEB REPORT BY: davidsamathy REMOTE: 172.93.109.202:7777)
# Revision
61ac09958eace14213af691458932432085fbeb0

# Description
multiple fish of the same type produce eggs. the fish egg scoop removes them however does not create egg item for fish production
# Steps to Reproduce
build aquarium. place two fish of the same type inside. care for food and cleanliness until description of fish tank states fish tank has eggs. use egg scoop on fish tank
# What you Expected
egg clutches such as what are in the cargo crates to be produced upon use of the egg scoop
# What Actually Happened
the egg scoop removes eggs from description but no egg item(s) are created

**Comment by ShiftyRail** [comment] 2018-01-20 15:04
Duplicate of #17130

**Closed as completed** 2018-01-21 11:06 UTC
Labels: Bug / Fix
