### ISSUE TITLE
EMPs remove borgs from the Robots network listing for ever.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11002] opened 2016-07-13 19:50 UTC
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision f01cfbadfc946f6440c379dffcf7bf1f2b296901
> 
> General description of the issue
> Borg gets EMP'd, it is removed from AI Robots network list and never is listed there again.
> 
> What you expected to happen
> Borgles to return to that network eventually
> 
> What actually happened
> nope
> 
> Steps to reproduce if possible
> EMP a borg, as AI check Robots network.

**Comment by Intigracy** [comment] 2016-07-13 19:52
Was one of their components damaged and not fixed?

**Comment by Allspice** [comment] 2016-07-13 20:06
They were still hunting birds so I doubt their cams were fucked.

**Comment by Ephx1** [comment] 2016-07-14 14:15
Yeah this one was weird. I got EMP'd three times by a vox (those grenades are piss-poor by the way) and only ever got my armor dented, which was then fixed by a simple welding. Attempting a camera disable and enable did nothing to fix the problem it seems.

**Comment by jknpj** [comment] 2017-12-28 14:24
Not a bug. It just pulsed the camera wire, i mean come on people, you know how borg wires work, right?

**Closed as completed by jknpj** 2017-12-28 14:24 UTC
Labels: Needs Moar Testing
