### ISSUE TITLE
GETTING SHOT BY YOUR OWN FUCKING LASGUN

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27770] opened 2020-09-09 14:48 UTC
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
f8d973f2a3fe882f9533d57d6a629cab0f7c6411

# Description
I GOT HIT BY LASERS FROM MY OWN LASGUN

# Steps to Reproduce
SHOOT A WELDERTANK, WATCH THE LASERS GET THROWN LIKE SHRAPNEL INTO YOU

# What you Expected
EXPLOSIONS NOT FUCKING REFLECT LIGHT

# What Actually Happened
You fire the laser rifle!
Tayachiya has been hit by the beam.
You feel something rip in your chest!
You stagger under the impact!
Tayachiya has been hit by the beam.

**Comment by tayachiya** [comment] 2020-09-09 14:50
I absolutely, 100% blame this
https://github.com/vgstation-coders/vgstation13/pull/27406

**Comment by Armadingus** [comment] 2020-09-09 15:05
![Untitled](https://user-images.githubusercontent.com/55976761/92616493-940fe880-f2be-11ea-888c-60cded2295bc.png)
It's very bad, you're not even safe shooting past a window.

**Comment by Exxion** [comment] 2020-09-09 15:21
Duplicate of #27667

**Closed as completed by Exxion** 2020-09-09 15:21 UTC
