### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Eat Superpower

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5098] opened 2015-06-22 16:53 UTC
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Can't eat anything

>What you expected to happen
Eat something

>What actually happened
Couldn't eat anything at all

>Steps to reproduce if possible
Probably a coding problem

**Comment by Shadowmech88** [comment] 2015-06-22 17:21
Duplicate of #4903.

**Closed** 2015-06-22 17:52 UTC
