### ISSUE TITLE
Disassembling coffins turns the wood to metal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21155] opened 2018-12-28 21:47 UTC
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
3ec6d4389835ec03acc98b6a14dc0168b7722560

# Description

what it says on the tin

# Steps to Reproduce

Make coffin for 5 wood
Open coffin
Apply welder
????
Profit

# What you Expected

wood

# What Actually Happened

metal

**Comment by MadmanMartian** [comment] 2018-12-28 21:56
Dupe of #12571

Going to update this one with the ACTUAL steps to reproduce

**Closed as completed** 2018-12-29 19:09 UTC
