### ISSUE TITLE
Cult path going endless

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31465] opened 2021-11-28 20:57 UTC
(WEB REPORT BY: gazmenark REMOTE: 206.221.180.138:7777)
# Revision
bd2827898e618f83950aefb1df25db67603346bf

# Description

Sunday 28.11.2021 21:45 MEZ
Was going on an cult path to a known location. But the path did not get me there but continued endlessy through all z-levels

# Steps to Reproduce
Take cult path "Join" in Xenobio

# What you Expected
Getting to the path exit rune

# What Actually Happened
Getting a travel through space without end

**Comment by DeityLink** [comment] 2021-11-29 08:51
Sounds like a duplicate of #22828 which I somehow forgot about until now. Regardless both issues probably require the same kinda fix.

**Closed as completed** 2023-07-03 23:57 UTC
Labels: Bug / Fix
