### ISSUE TITLE
Cortical borer chem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6392] opened 2015-10-31 01:05 UTC
(WEB REPORT BY: dafuza REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Cortical borer chems don't metabolize

>What you expected to happen
chems to dissapate in the body over time

>What actually happened
the effects wore off, but the body scanner in medbay still registered chems in the body, and the health was decreased in medHUD, the cortical borer spells to check levels in the blood worked like I expected, and they showed no chems when subsequent doses were given.

>Steps to reproduce if possible
infest player, produce chems, wait for the taste blood spell to register nothing in the blood, and put the player in a body scanner

**Comment by Rei1226** [comment] 2015-11-10 00:48
Couldn't reproduce. Put 15u of Bicaridine in the host, waited until taste blood showed nothing, then put the body in a body scanner and it showed up as Bicaridine: 0. Nothing out of the ordinary.

**Comment by clusterfack** [comment] 2015-11-11 12:04
Per policy, closing web report with unable to reproduce. Also nexis probably fixed this at some point if it even happened as hes made various changes to it recently.

**Closed by clusterfack** 2015-11-11 12:04 UTC
Labels: Bug, Feature Loss, Unable To Reproduce
