### ISSUE TITLE
Cult Icon Bugged

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6268] opened 2015-10-22 20:44 UTC
I, for some reason, could not see my own cult icon once I was culted. I could see SOME other cultists' icons, but on other cultists I could not see them. Relogging did not fix the problem.
![culticon](https://cloud.githubusercontent.com/assets/3991927/10677688/84083542-78d3-11e5-9f30-9cba4b95c557.PNG)
Pic of me (with note proving my cult status) and no cult icon next to cultists with cult icons.

![culticon2](https://cloud.githubusercontent.com/assets/3991927/10677705/95c27c52-78d3-11e5-8207-b725ad96ac85.PNG)
Pic of me as an artificier with no cult icon, another artificier with no cult icon, and a third artificier that does have a cult icon for some reason.

**Comment by clusterfack** [comment] 2015-10-23 00:00
Likely caused by the runtime in cult icons that deity is fixing in #6255. Ideally that will also solve this issue at the same time.

**Comment by clusterfack** [comment] 2015-10-25 02:17
Going to close this due to the likely fix, reopen if you experience this again.

**Closed by clusterfack** 2015-10-25 02:17 UTC
