### ISSUE TITLE
wizards spawning with no jansports

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28083] opened 2020-10-24 21:26 UTC
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
9259913a8a94517e83b48b828aa2c24eac3ca9c2

# Description

wizards often spawn with no backpack

# Steps to Reproduce
1. spawn as a wizard

# What you Expected
backsack

# What Actually Happened
a lack of sack on my back

**Comment by DeityLink** [comment] 2021-08-24 15:46
Duplicate of #27766

**Closed as completed by DeityLink** 2021-08-24 15:46 UTC
Labels: Bug / Fix
