### ISSUE TITLE
Inspecting mimewall lags beyond.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#15280] opened 2017-06-23 07:27 UTC
#### Description of issue
Mimewall lags beyond for a few seconds if you inspect it, I asked in looc to confirmed it wasn't just a personal issue and have had this happen to me before. If it's any help the actual icon of the inspected mimewall looks weird in chat.

#### Server revision

Revision: 6b69d726d3f1b8ddf26ac2879d0bf8f7bf169f6f 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment] 2017-06-23 07:30
Essentially a duplicate of #10053, but that one doesn't mention the mimewall in the title, so it's fine

Also I figured that recent `bicon()` change would have fixed this. But apparently not.

**Comment by ZVee** [comment] 2017-06-27 18:40
Hello, if you still got a problem with freezing, i think this is what you're looking for - https://github.com/TauCetiStation/TauCetiClassic/blob/master/goon/code/datums/browserOutput.dm#L194 - and sorry, i was too lazy to fix it for our server properly, but the problem with client freeze is related to non existent icon_states in dmi file usually. Maybe someone else will come up with an idea, how to deal with this properly.

**Closed as completed** 2018-10-18 05:16 UTC
Labels: Bug / Fix
