### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16045] opened 2017-09-21 21:35 UTC
(WEB REPORT BY: lordofslips REMOTE: 172.93.109.202:7777)
# Revision
496b1608073cbe4561a9368914cd6088ab23101a

# Description
https://gyazo.com/7bdabe40a40a78bfb3883c2292e7d60c

# Steps to Reproduce
Two times.

# What you Expected
Too run smoothly like usally.

# What Actually Happened
Just got alot of bugs and errors.

**Comment by Shadowmech88** [comment] 2017-09-21 21:40
>Steps to Reproduce
>Two times.

What?

**Comment by Zth--** [comment] 2017-09-21 22:47
Duplicate of #15988

**Closed as completed** 2017-09-21 22:54 UTC
Labels: Bug / Fix, Needs Pics / Needs Moar Info
