### ISSUE TITLE
Occupation Preferences issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8235] opened 2016-02-12 11:54 UTC
when you have a job set to "high", if you right-click any **_other**_ job the job on "high" goes to "medium".
example:
you have scientist to "medium" and roboticist to "high";
right-click scientist;
scientist goes to "low" and roboticist goes to "medium".

**Comment by mrpain666** [comment] 2016-02-12 12:06
Are you trying to set multiple jobs to high? You can only have one job on high.

**Comment by PJB3005** [comment] 2016-02-12 12:19
Thanks @D3athrow

**Comment by uazuaz** [comment] 2016-02-12 13:59
@mrpain666 
nope, this happens when i lower another job from medium to low or from low to never.
am i the only one?

**Comment by Shadowmech88** [comment] 2019-10-31 01:55
This still exists.

**Comment by d3athrow** [comment] 2019-10-31 06:13
@PJB3005 
why am i assigned to this
i never touched job code that would cause this
fuck you pay me

**Comment by PJB3005** [comment] 2019-10-31 10:34
Hey man I'm sure I had a reason at the time but I'll be damned if I'll know that almost 4 years later.

**Comment by Zth--** [comment] 2019-10-31 11:16
I remember about this one. Right click wasn't working at all and pomf fixed it. This bug then emerged

**Comment by Shadowmech88** [comment] 2019-10-31 14:52
Where are job preferences within the code?

**Comment by PJB3005** [comment] 2019-11-01 01:53
It's all in `code/modules/client/preferences.dm`. I did some digging and `SetJob` is the proc that gets invoked when you  press one of the buttons in the occupations menu. `inc` appears to be zero when you decrease a job priority and 1 when you increase it.

**Comment by Shadowmech88** [comment] 2019-11-01 19:22
I can't wrap my head far enough around the bitwise operations and whatnot in the job procs to understand what the problem is. However, I did find out that when you left-click a job, `SetJobDepartment()` is called once, but when you right-click a job, `SetJobDepartment()` is called three times. Maybe that's related.

**Closed as completed** 2021-07-23 21:52 UTC
Labels: Bug / Fix
