### ISSUE TITLE
Fish net black hole

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33068] opened 2022-08-17 22:27 UTC
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
15e8ff2efd5f3e8c73ace1e8f70414c7f6f7852a

# Description
Fish nets are a black hole
# Steps to Reproduce
Use a fish net on an aquarium with fish inside
# What you Expected
To get fish
# What Actually Happened
Boko No fish

**Comment by adacovsk** [comment] 2022-08-17 22:37
Can't reproduce bug

**Comment by nervere** [comment] 2022-08-19 04:19
If anyone has more info on this, that'd be appreciated.

**Comment by adacovsk** [comment] 2022-08-19 06:29
yeah the dude said that he was retarded and he's going to try again

**Comment by adacovsk** [comment] 2022-11-28 20:02
@nervere you can close this now

**Closed as completed** 2023-06-10 17:00 UTC
