### ISSUE TITLE
WE NEED FUCKING WINTER CLOAKS FOR WIZARDS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24333] opened 2019-10-01 23:08 UTC
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
0d0e6f7f6e2c87612744451239c9cb785a9c1149

# Description
Got fucked over as stealthwiz because I needed to switch to the winter coat but I couldn't fucking put the staff on for it. This fucked me since time was of the essence and I was caught after being disarmed by snow while trying to get the wizard cloaks back on. This NEEDS a fix, either by allowing staffs to be stored on winter coats or giving wizards a unique cold-proof robe for Snow Taxi. It ruined the gimmick I was going to do.

**Comment by dsfartgeg** [comment] 2019-10-06 07:13
Duplicate of #24238

**Comment by Probe1** [comment] 2019-10-07 04:13
An issue once more, but this time with feeling

**Closed as completed by Probe1** 2019-10-07 04:13 UTC
