### ISSUE TITLE
You can enter the roid courtroom without any courtroom access if you enter via maintenance.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19179] opened 2018-08-07 21:25 UTC
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
5e4172d0f2bc43e30b54388a61e34609202ae441

# Description
You can enter the roid courtroom without any courtroom access if you enter via maintenance.

# Steps to Reproduce
>play on roid
>go in maints
>go into courtroom

# What you Expected
beep beep

# What Actually Happened
You can enter the court.

**Comment by SGuivenne** [comment] 2018-08-07 21:32
Duplicate of #19176

**Closed as completed** 2018-08-07 22:52 UTC
