### ISSUE TITLE
New CMC still resets scroll list when it updates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22778] opened 2019-05-05 05:36 UTC
(WEB REPORT BY: tellossee REMOTE: 206.221.180.138:7777)
# Revision
645fe1a653e7412dcd75129f12a8890491c2207f

see issue name. the last PR merged said it fixed this issue but it is still happening.

**Comment by PaulRitter** [comment] 2019-05-05 09:22
known, probably read #22687 and thought it was a pr

**Comment by PaulRitter** [comment] 2019-05-05 20:58
you can close this, the issue is known

**Comment by Exxion** [comment] 2019-05-05 21:26
Duplicate of #22687

**Closed as completed by Exxion** 2019-05-05 21:26 UTC

**Comment by Exxion** [comment] 2019-05-05 21:27
By the way I love how you have to say exactly that phrase with nothing else added to mark it as a duplicate, and for this trouble you get exactly nothing other than the thing there that says it was marked as a duplicate
As far as I can tell there isn't even a place to track duplicates
