### ISSUE TITLE
Welding Fuel doesn't light anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6427] opened 2015-11-04 02:27 UTC
(WEB REPORT BY: vladorf REMOTE: 158.69.55.2:7777)
Welding Fuel doesn't light anymore

When welding fuel is splashed on the ground, then a lit lighter is thrown at it, it doesn't catch fire anymore.

It used to / is supposed to catch fire, and the fire spreads to every tile with welding fuel spilt on it.

nothing.

Fill beaker with welding fuel, splash on ground, light lighter, throw lighter at tile with fuel splashed on it.

**Comment by N3X15** [comment] 2015-11-04 02:34
Duplicate of #6116.

**Closed by N3X15** 2015-11-04 02:34 UTC
