### ISSUE TITLE
Player Controlled Mouse view has Y axis locked when picked up by another player

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#30382] opened 2021-08-27 22:51 UTC
This possibly applies to other mobs that can be controlled by players but I can't test it because _SOMEONE_ decided I shouldn't have admin powers anymore just because I haven't touched the game in a few years or so.

As it says in the title, a player controlled mouse's vision is restricted to the same location on the Y axis it was at when they were picked up by another player, the X axis moves appropriately.

**Comment by DeityLink** [comment] 2021-08-27 23:00
Duplicate of #29757

As all the perspective bugs of Byond 514. Go back on stable (513).

**Closed as completed by DeityLink** 2021-08-27 23:00 UTC
Labels: T-Thanks BYOND
