### ISSUE TITLE
Jetpack Graphical Bug

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4056] opened 2015-04-22 16:11 UTC
Not sure what to make of this.
![silhouette](https://cloud.githubusercontent.com/assets/3991927/7279273/4b124c9c-e8e0-11e4-82f4-23db68873874.PNG)

**Comment by ComicIronic** [comment] 2015-04-22 16:13
DUPLICATE OF #4035.

This is shameful, you logged into Github to do this. It would have taken 5 seconds to search the word "jetpack" in the issue tracker.

**Closed by ComicIronic** 2015-04-22 16:13 UTC
