### ISSUE TITLE
Crew monitoring computer is showing metaclub map on Boxstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6617] opened 2015-11-15 20:30 UTC
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
2148960ff95e0433e0312997bc750d3da263a152 

>General description of the issue
The CMC is showing Metaclub's map while playing on Boxstation

>What you expected to happen
The CMC showing Boxstation

>What actually happened
http://puu.sh/lmM3B/5bec902894.jpg

**Comment by Ephx1** [comment] 2015-11-16 01:32
#5945 
It always happens if you played a different map and check the crew monitor afterwards.

**Comment by PJB3005** [comment] 2015-11-16 01:33
Er, does closing and reopening the UI fix this?

**Comment by Ephx1** [comment] 2015-11-16 01:48
I don't believe it does, unless it requires multiple opening and closings. I haven't tried relogging though.

**Comment by mrpain666** [comment] 2015-11-16 08:56
Relogging always fixes this, to my knowledge.

**Comment by clusterfack** [comment] 2015-11-16 14:57
Maybe it has to do with the asset cache and keeping dreamseeker open between rounds then

**Comment by PJB3005** [comment] 2015-11-16 15:54
@clusterfack keeping DS open between rounds shouldn't matter, since the file should get overriden by the cache next round.

And uh, the minimaps aren't implemented in the asset cache...

**Comment by clusterfack** [comment] 2015-11-16 16:11
Why wouldn't they be, they're used in the HTML interfaces aren't they

**Comment by PJB3005** [comment] 2015-11-16 17:42
Yes, but that doesn't mean I ever implemented the maps correctly.

**Comment by clusterfack** [comment] 2015-11-22 07:57
Actually a dupe of #5945

**Closed by clusterfack** 2015-11-22 07:57 UTC
Labels: Bug
