### ISSUE TITLE
Being high as fuck will still make you say shit while dead, into deadchat

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7069] opened 2015-12-16 02:24 UTC
Common to see ghosts spouting "beep... bop" against their will if someone poisoned them with Spiritbreaker

**Comment by Imagebard** [comment] 2015-12-16 03:27
>Spiritbreaker

Shhh
Not a Bug

**Comment by Intigracy** [comment] 2015-12-16 03:48
It's honestly pretty amusing when it happens.

**Comment by ghost** [comment] 2015-12-16 11:21
Getting so stoned your ghost is high is a feature, isn't it?

**Comment by ghost** [comment] 2015-12-17 12:43
"So, Patrick, how'd you die?"
"dude weed lmao"

**Comment by Intigracy** [comment] 2016-03-14 14:58
Too funny to fix.

**Comment by Intigracy** [comment] 2016-03-20 04:50
Do we have to fix this one, or can we close it?

**Comment by Imagebard** [comment] 2016-03-20 11:39
Yeah, this should have been closed some time ago.

**Comment by Imagebard** [comment] 2016-05-17 23:55
Spiritbreaker breaks spirits
Why is this issue still open

**Comment by Probe1** [comment] 2016-12-20 22:29
Don't do drugs you filthy hippie.

**Closed as completed by Probe1** 2016-12-20 22:29 UTC
Labels: Honk, IT'S A FEAAAATUUUUREEEEEEEEE
