### ISSUE TITLE
ai radio config is broken on deff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10587] opened 2016-06-16 20:33 UTC
(WEB REPORT BY: icytruth REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Defficiency AI radio is... defficient
> 
> General description of the issue
> Changes made to the radio config on Deff do nothing, you can't listen to medical, supply, etc.
> 
> What you expected to happen
> To be able to listen to all channels.
> 
> What actually happened
> I could only listen to sec and common.
> 
> Steps to reproduce if possible
> play deff as AI

**Comment by JustSumBody** [comment] 2016-06-16 22:13
I don't know about Deff in particular, but I know the AI radio setting has a habit of resetting when you reopen it.
If you enable medical/supply/whatever the channels are available after closing it, but reopening the menu resets them all to default
EDIT: Just tried it on Deff, the radios all seem to work with that same issue

**Comment by Probe1** [comment] 2016-11-30 12:18
Cannot reproduce after testing locally.

**Closed as completed** 2016-11-30 14:35 UTC
Labels: Mapping (Deff :wastebasket:)
