### ISSUE TITLE
Gumshoe Not Showing Blood in Color

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29062] opened 2021-03-22 00:18 UTC
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
02ff588d59b3c560c685d9ca75e882d32a72d8cb

# Description
it's in the name.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment] 2021-03-23 02:15
known for a while, nobody has taken the time to fix it, since overlays are a pain.

**Comment by robintime** [comment] 2021-04-10 16:32
duplicate of #28603

**Closed as completed by robintime** 2021-04-10 16:32 UTC
