### ISSUE TITLE
EMPed borgs have channels of their radio disabled with no way to re-enable it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13615] opened 2017-01-24 11:44 UTC
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
16e34f8e9f8fd4d9bb9fe9b4d00fc0b6bcb60e38 

>General description of the issue
As a borg, when hit with an emp, there's a chance that your internal radio may shut down like most headsets would. Only issue is that you can't turn the channels back on, meaning you're stuck with a radio that can't recieve.

>What you expected to happen
Be borg, get EMPed, lose radio speaker functionality, regain radio speaker functionality 

>What actually happened
Be borg, get EMPed, lose functionality forever.

>Steps to reproduce if possible
Be borg, get EMPed a bit, see if you can recieve radio messages

**Comment by ihadtoregisterforthis** [comment] 2017-01-24 14:46
Could have been a broken component

**Comment by SonixApache** [comment] 2017-01-24 14:58
Scanned radio component; 0 damage.
Radio was still outputting, just not inputting; people could hear my broadcasts, but I could not hear theirs or my own.
Replaced with a different radio component which enabled common, but didn't work for security (probably due to lack of encryption keys).
Had to fully reconstruct the borg shell for it to work again.

**Comment by uazuaz** [comment] 2017-01-24 15:13
if i remember right, there is a way to disassemble encryption keys from borgs radio; maybe just using a screwdriver on a borg with open panel without removing the power cell, i'm not sure.
what does it happen if you remove the encryption key then re-add it? what if you replace it?

also, there is a way for borgs to enable/disable each single channel as you do with earpieces?
maybe the emp just disables that.

**Comment by Sprok0** [comment] 2017-01-24 15:30
Could you not press the radio button and turn the channels back on? I can't reproduce this

**Comment by SonixApache** [comment] 2017-01-24 16:51
@uazuaz 
pretty sure that's exactly what happened, but there's no way to turn them back on,

@Sprok0 
Borgs have a radio button?

**Comment by Sprok0** [comment] 2017-01-24 16:55
![radio](https://cloud.githubusercontent.com/assets/19806447/22257406/fb34f5c0-e22b-11e6-908b-c639b68184ea.png)

**Comment by SonixApache** [comment] 2017-01-24 18:56
what the fuck

**Comment by SonixApache** [comment] 2017-01-24 19:00
okay, confirmed, i'm actually literally fucking retarded, feel free to close this

**Comment by uazuaz** [comment] 2017-01-24 19:01
you can close it.

**Comment by SonixApache** [comment] 2017-01-24 19:03
I can't, webreport.

**Comment by uazuaz** [comment] 2017-01-24 19:04
oh right.

**Comment by 9600bauds** [comment] 2017-01-24 19:07
can someone close [13615] for me so i can stop looking like an ass

**Closed as completed by 9600bauds** 2017-01-24 19:07 UTC

**Comment by Exxion** [comment] 2017-01-24 20:22
God damn stop using MoMMI-style references
