### ISSUE TITLE
You can use rest as a cyborg

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#10999] opened 2016-07-13 09:51 UTC
#### Description of issue

If you rest as a cyborg, you can move for a bit until you suddenly can't move and get locked out of your modules until you "sleep"
#### Difference between expected and actual behavior

Would probably want to either reword the rest text for borgs or make resting again get rid of it so it's consistent, hitting "sleep" to wake up isn't exactly intuitive. 
#### Steps to reproduce

Become a borg. Accidentally hit your rest bind. Get confused on why you're locked down. 
#### Specific information for locating

/mob/living/silicon/robot or something probably
#### Length of time in which bug has been known to occur

Unknown, happened to me in a round just now.
#### Server revision

f01cfbadfc946f6440c379dffcf7bf1f2b296901
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment] 2017-05-19 16:07
Tested, Sleep has nothing to do with it. It merely takes a few seconds after you hit rest to "get up".
NOT A BUG
CLOSE IT

**Comment by Intigracy** [comment] 2017-05-19 21:50
OP edited to show the real problem here

**Comment by Shadowmech88** [comment] 2018-10-13 01:41
I don't see the issue with borgs being able to rest. Altering your sprite to look like you're locked down/dead has usefulness to borgs just like being able to alter your sprite to look like you're stunned/dead has usefulness to humans.

**Closed as completed by Shadowmech88** 2018-10-13 01:41 UTC
Labels: Bug / Fix
