### ISSUE TITLE
Removing Electropack bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17316] opened 2018-02-03 13:12 UTC
(WEB REPORT BY: subs455 REMOTE: 172.93.109.202:7777)
# Revision
0c7b0934605f07fc0c7de56d7102ebd0d39afeda

# Description
If a Electropack is in your back slot, and you push E while having a backpack in your active hand, the two switch. That shouldnt happen, right?

# Steps to Reproduce
Have electropack in backslot

Have backpack in your hand

Push E
# What you Expected
I expected the "You need help taking this off!" message.
# What Actually Happened
My electropack came off.

**Comment by Pathid** [comment] 2018-02-03 14:59
Duplicate of #15326

**Closed as completed** 2018-02-03 19:10 UTC
