### ISSUE TITLE
[Bug] Lockbox says tracked_access instead of who opened it

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3963] opened 2015-04-17 20:47 UTC
I wanted to know who opened the lockbox.  I didn't get what I wanted.

![ss 2015-04-17 at 01 41 35](https://cloud.githubusercontent.com/assets/8550416/7210613/5f8b8944-e521-11e4-8245-4db8d72d9e42.png)

**Comment by DrCelt** [comment] 2015-04-20 19:30
The problem is

"	user << "<span class='info'>tracked_access</span>""
instead of "	user << "<span class='info'>[tracked_access]</span>"" 

Which I've fixed in the next revision of my PR on the economy but y'know it's with a bunch of other stuff so might be better to have you guys fix it

**Closed** 2015-04-30 21:18 UTC
