### ISSUE TITLE
Light not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22473] opened 2019-04-16 07:09 UTC
(WEB REPORT BY: arxix REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
Light in the suit helmet doesn't work same with PDA and flashlight
# Steps to Reproduce
dunno
# What you Expected
Some frickin light
# What Actually Happened
Was walking down the maint when suddenly my helmet light stopped to give off light same with pda tried to turn on and off both and no no EMP.

**Comment by RaccoonBro** [comment] 2019-04-16 20:44
this and #22472 seem like a round specific thing

**Comment by Exxion** [comment] 2019-04-16 21:58
Duplicate of #22472

**Closed as completed by Exxion** 2019-04-16 21:58 UTC
