### ISSUE TITLE
Nothing Can Go in the Candy Maker

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3883] opened 2015-04-12 18:42 UTC
I was getting the "It's already candy" message for everything I tried putting in, even a potato, which I am almost certain isn't candy.

**Comment by ComicIronic** [comment] 2015-04-12 19:24
duplicate of #2790.
You would have found this by searching candy in the issues list.

**Closed by ComicIronic** 2015-04-12 19:24 UTC
