### ISSUE TITLE
Cult HUD for Shades

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14845] opened 2017-05-16 04:18 UTC
(WEB REPORT BY: starnightx REMOTE: 172.93.109.202:7777)
It only shows wizard HUD or whatever that tiny icon is (for the person who slaved you) and the rest of the cult is not shown up for the shade

**Comment by Gunosaguki** [comment] 2017-05-16 18:51
apparently this is intentional(?) as they're not constructs yet. I dont see why they shouldnt though

**Comment by Allspice** [comment] 2017-05-17 00:39
It's not that they're not constructs, the issue is they are not cultists. Constructs produced by cultists are cultists, constructs produced by noncultists are not cultists, but shades produced by either are not cultists.

**Comment by DeityLink** [comment] 2018-01-23 14:29
yeah that's intended. think of being turned into a construct as becoming a proper baptised cultist.

**Comment by DeityLink** [comment] 2019-02-04 10:22
Shades can now actually be cultists, so this is now Fixed. @MadmanMartian

**Closed as completed** 2019-02-04 14:14 UTC
Labels: Oversight
