### ISSUE TITLE
Unable to access asset cache browser something-or-other

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6387] opened 2015-10-30 18:55 UTC
(WEB REPORT BY: sageoflight REMOTE: 158.69.55.2:7777)
Unable to access asset cache browser, if you are using a custom skin file, please allow DS to download the updated version, if you are not, then make a bug report. This is not a critical issue but can cause issues with resource downloading, as it is impossible to know when extra resources arrived to you.

I have no idea what this means help how do I computer.

**Comment by PJB3005** [comment] 2015-10-30 19:40
Dupe of #6382

**Closed by PJB3005** 2015-10-30 19:40 UTC
