### ISSUE TITLE
Vox in roboticist jumpsuit has no tail on sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23178] opened 2019-06-06 06:16 UTC
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
404bcadfbc1ff374de2253cf8e5e0a6728e9bf06

# Description
like in title. Voxes wearing roboticist jumpsuit have no tails.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment] 2019-06-06 09:00
No, the problem is the skin (quill?) color
The "newer" colors don't have them

**Comment by Zth--** [comment] 2019-12-09 02:15
Duplicate of #13714

**Closed as completed by Zth--** 2019-12-09 02:15 UTC
