### ISSUE TITLE
Tinfoil hat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8065] opened 2016-02-03 23:37 UTC
(WEB REPORT BY: kylefiredemon REMOTE: 158.69.55.2:7777)

> Revision c56c01874aeb015c2b2a2420bf93ff8cb1dd67a
> 
> Tinfoil hat doesn't show hair at all.
> 
> To have hair whenever I have the hair on or not.
> 
> Hat will not show hair and then when removed will have hair reappear
> 1. Get tinfoil hat. 2. Wear tinfoil hat.

**Comment by ghost** [comment] 2016-02-03 23:44
Fixed by #7929

**Comment by ihadtoregisterforthis** [comment] 2016-02-04 00:37
From 0 to 3, how much is this intended by design?

**Closed as completed** 2016-02-04 00:40 UTC
