### ISSUE TITLE
don't cross the streams

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#5619] opened 2015-08-01 13:15 UTC
![http://i.imgur.com/YmWeRdS.png](http://i.imgur.com/YmWeRdS.png)
@N3x15
https://www.youtube.com/watch?v=jyaLZHiJJnE

**Comment by FudgePucker** [comment] 2015-08-01 19:25
Fucking lasers, how do they work?

**Comment by 9600bauds** [comment] 2015-12-16 08:33
Is this still an issue?

**Comment by PJB3005** [comment] 2015-12-16 12:20
I know that due to a feature request on the BYOND forums I made, BYOND doesn't kill the server anymore if there's been 3 infinite loops.

Also N3X15 hardcapped beams, so I doubt it.

**Comment by gbasood** [comment] 2016-01-16 20:35
I can't seem to duplicate this myself. Closing until someone else manages to reproduce.

**Closed by gbasood** 2016-01-16 20:35 UTC
Labels: Bug, Exploitable, Needs Moar Testing
