### ISSUE TITLE
CMC monitor maps broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8192] opened 2016-02-10 04:57 UTC
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
http://puu.sh/n2pa4/655543fe83.jpg map shows up like this, not sure why, only does this on z level 1 and z level 6.

**Comment by 9600bauds** [comment] 2016-02-10 04:58
Dupe of #8157

**Comment by PJB3005** [comment] 2016-02-10 04:58
Dupe

**Comment by 9600bauds** [comment] 2016-02-10 04:58
2slow

**Comment by PJB3005** [comment] 2016-02-10 04:59
Wow we hit close at the exact same time.

**Closed as completed** 2016-02-10 04:58 UTC
