### ISSUE TITLE
Newscasters broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20327] opened 2018-10-20 05:00 UTC
(WEB REPORT BY: slashbolt REMOTE: 172.93.109.202:7777)
# Revision
8fa4ddfd642d428f2e8ac2e1cbdd2042a6af2737

# Description
Flavortext only shows the first character. This issue is also present on newscaster feed channels occasionally.

# Steps to Reproduce
Try to submit a story to a feed channel or examine a an epic static OC.

# What you Expected
To read flavortext and submit stories to newsfeeds
# What Actually Happened
I got the first character of the flavortext and newsfeed channels

**Comment by DamianX** [comment] 2018-10-20 05:04
Duplicate of #20273 but it also mentions newscasters so

**Closed as completed** 2018-10-21 18:38 UTC
Labels: Bug / Fix
