### ISSUE TITLE
BUG: Unable to find role (antag role)

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#17117] opened 2018-01-17 09:50 UTC
![ss 2018-01-17 at 04 49 08](https://user-images.githubusercontent.com/8556111/35036281-dc459a40-fb41-11e7-97b1-0fb823a6eb66.png)

This seems like it might be bad.

Happens when saving character setup, at round start, if that matters.

**Comment by DamianX** [comment] 2018-01-17 09:51
Duplicate of #16456

**Closed as completed by DamianX** 2018-01-17 09:51 UTC
