### ISSUE TITLE
Coffin Transmution

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16784] opened 2017-12-15 04:03 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description

Coffins, when dissassembled (via welding??) are rendered into metal... despite coffins being made of wood.
# Steps to Reproduce

Construct or locate a wooden coffin, open it, weld it apart.
# What you Expected

To either set it on fire or get wood back
# What Actually Happened

Magically transmuted 5 wood planks into 2 Iron sheets (I suspect whoever coded coffins got lazy)

**Comment by Sooose** [comment] 2017-12-16 11:19
Probably because coffins are just children of closets.

**Comment by Pathid** [comment] 2017-12-16 16:12
Duplicate of https://github.com/vgstation-coders/vgstation13/issues/12571

**Closed as completed** 2017-12-17 15:16 UTC
Labels: Bug / Fix
