### ISSUE TITLE
Fucking wheel chairs are unstoppable war machines that needs to be reworked post haste

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#5901] opened 2015-09-30 08:17 UTC
"I'm going to stand out against Wheel chair nonsense. You can't poly acid the chair, in smoke, spray, or grenade, you can't flashbang anyone on the chair, it blocks taser shots and bullets, I don't know too much about it and lasers, it can boost using fucking fire extinguishers, and an unlimited amount of people can sit on it. AN UNLIMITED AMOUNT OF UNSTUNNABLE, NEAR UNHARMABLE SHITBEANS TOWERING ON A FUCKING WHEELCHAIR SHOOTING 10 ROUNDS OF FIREARMS A SECOND! I've personally had to deal with a memechair tower and let me tell you, it's funny for the first 5 minutes, then they realize the power that they have and it quickly becomes a shit fest. Do you know what it takes to properly subdue a memechair with minimal damage? I'll show you.

![image](https://cloud.githubusercontent.com/assets/5303834/10187975/05db434a-672a-11e5-9658-b47a0904d0a0.png)

This was an admin spawned Seraph with a fucking rocket launcher."

Please fix this shit before more griff fueled incidents result in more people getting banned.

**Comment by clusterfack** [comment] 2015-09-30 09:08
I told you guys fun things were bad

**Comment by Probe1** [comment] 2015-09-30 09:35
i'm absolutely positive that it wasn't always.  I used to use flashbangs when unlimited people could get on it to clear them off, since if you stunned one another would just take the wheel.

Used to work.

**Comment by Unfit** [comment] 2015-09-30 09:43
Unless something broke, the 10 guys 1 wheelchair thing has been fixed. The round you're talking about had an an infinite wheelchair spawned in by admins

**Comment by Shadowmech88** [comment] 2015-09-30 14:11
If normal wheelchairs really do block taser shots and bullets and flashbangs, that should be fixed anyway since it would mean that cripples would then be the strongest players in the game, with our combat system.

**Comment by PJB3005** [comment] 2015-09-30 14:34
@Shadowmech88 it's the same issue as not being able to hit people on a wall, for example, I think the janicart has a hack to fix this though.

**Comment by PJB3005** [comment] 2015-10-27 20:57
Considering admins actually spawned an infinite one in themselves, I'll tag this as not a bug, comment if it happens without adminbus though

**Closed** 2015-10-27 20:57 UTC
Labels: Not A Bug
