### ISSUE TITLE
silicon atmos analyzers do not work when trying to analyze the air around you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9186] opened 2016-03-31 23:39 UTC
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 9b9aa46c2593bf6be288397cb1f34f61c7e64f68 
> 
> General description of the issue

Mommi and silicon air analyzers would not work when tested at escape. confirmed by me and the mommi who called it in

> What you expected to happen

To get a readout of the air around me

> What actually happened

nothing

> Steps to reproduce if possible

be mommi
analyze air

**Comment by Shadowmech88** [comment] 2016-04-01 07:45
Duplicate of #9115.

**Comment by Probe1** [comment] 2016-04-01 09:30
no ones atmos analyzers are working.  

They work when used on pipes and rad collectors

They do not work when used normally to take an air reading.

**Comment by Shadowmech88** [comment] 2016-04-01 09:33
Is to do with goon chat?

**Comment by ihadtoregisterforthis** [comment] 2016-04-01 10:32
Ghost ones work at least

**Closed as completed** 2016-04-01 17:42 UTC
Labels: Bug / Fix, Feature Loss
