### ISSUE TITLE
THE SAMMI MEGATHREAD

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#9823] opened 2016-05-01 20:46 UTC
Hey since Sammi's are in the game lets place our complaints/ideas here this is a good and legal use of github.

**Comment by gbasood** [comment] 2016-05-01 20:49
@TheFriggenSawbones I'd rather actual bugs be documented in single bug reports but this is fine as a discussion issue I guess

**Comment by TheFriggenSawbones** [comment] 2016-05-01 20:50
Yeah thats what I was aiming for I hope it works out

They can't give hugs (fucked up) or throw things. This makes assembling kinda annoying unless you have tables all around you. Maybe give them the ability to place things one tile away if that's possible.
Since they're based off Mommis (I guess?) They also don't have a Wave emote which is totally fucked.

Maybe have upgrades for sammis? Like wheels so they can move super slowly or a dexterity upgrade so they can use hookshots?

**Comment by gbasood** [comment] 2016-05-01 20:52
@TheFriggenSawbones The throwing thing is SORT OF addressed in #9820

**Comment by Hoshi-chan** [comment] 2016-05-01 20:53
You can't hug with only one arm, Sawbones...

**Comment by gbasood** [comment] 2016-05-01 20:54
@hoshi-chan elbow hugs, sidehugs, litearlly just full body hugs without the second arm

**Comment by TheFriggenSawbones** [comment] 2016-05-01 20:55
yeah you fucking can try it hug someone with one arm its possible

**Comment by Hoshi-chan** [comment] 2016-05-01 20:59
Okay, correction: you can't hug if you're just a robot arm on a stick.

**Comment by ihadtoregisterforthis** [comment] 2016-05-01 21:00
SAMMI milestone when?

**Comment by gbasood** [comment] 2016-05-01 21:01
@Hoshi-chan fight me irl
@ihadtoregisterforthis nah

**Comment by Hoshi-chan** [comment] 2016-05-01 21:02
@gbasood MEET ME SOMEWHERE

**Comment by MercuryDoll** [comment] 2016-05-01 21:16
What they need is the ability to place items adjacent to them as mentioned.
Remove binary.
Rewrite the laws completely and make it similar to KEEPER. Eg. "Follow your tasks", "Do not concern yourself in the matter of other beings unless it directly relates to your given task." This is important to counter metagaming and easy snitching.

Possible suggestions: Make them able to work while un-anchored. When anchored, they'll draw power from the APC and recharge their batteries. Nerf their tools like Mat-Synth and RPD, perhaps they need to be loaded up with each tool individually before they can use it.

**Comment by Kurfursten** [comment] 2016-05-01 21:26
I came back from the dead just to say that I don't think anything, even Celt Hypothermia, has ever caused such a riot.

Except maybe that one time Pomf accidentally the map files and telecoms was ported to the middle of medbay and rooms were randomly filled with plasma.

**Comment by icantthinkofanameritenow** [comment] 2016-05-02 01:39
My main "concern" is that the job is in itself nothing more than a thing to keep bored ghosts busy, and there are better ways of doing that than ordering them to man an autolathe or some inane shit like that. Giving them laws is a bad move too- they can't follow orders if they can just "drop out" if they don't like said orders now, so you either have to take out the ability for them to drop out or ban them from the job for breaking their laws.

**Comment by Shadowmech88** [comment] 2016-05-02 01:46
> there are better ways of doing that than ordering them to man an autolathe or some inane shit like that

What if the bored ghosts _want_ to man an autolathe or some inane shit like that?

**Comment by icantthinkofanameritenow** [comment] 2016-05-02 01:54
@Shadowmech88

First, I would question their sanity. After that I'd advise them to become a diona or golem without greentiding/golemtiding for a change.

**Comment by Shadowmech88** [comment] 2016-05-02 01:59
As I stated on the PR, SAMMIs are particularly useful for ghosts that want to kill 5-10 minutes while they wait for their bodies to be found/cloned. Inhabiting a diona or a golem would not be an optimal solution for them.

**Comment by icantthinkofanameritenow** [comment] 2016-05-02 02:23
@Shadowmech88
And as I stated, I feel like it would be better for the game not to include an "easy out" so to speak. It takes away some of the sting of death, IMO.

**Comment by gbasood** [comment] 2016-05-02 02:52
Here's the problem SAMMIs:
- They're designed to do a job that players don't want to do, filled by players.
- They have one hand and can't make a lot of stuff because of it.
- **Their law 3 can be overriden by a harm law in law 2, which is a law anyone can set via simple interaction**
- Simple hop in/hop out at any time mobs do not work well for us, because it nulls the reference to the ghost's body, so it's only useful for players don't want to return their bodies.
- You can make a SAMMI and have it use its mat fab to make a massive net profit in mats.

**Comment by Shadowmech88** [comment] 2016-05-02 03:05
> Simple hop in/hop out at any time mobs do not work well for us, because it nulls the reference to the ghost's body, so it's only useful for players don't want to return their bodies.

Is there no way to code around this specifically for SAMMIs?

**Comment by gbasood** [comment] 2016-05-02 03:12
@Shadowmech88 Theorhetically yes but the cons seem to outweigh the pros of actually re-merging SaMMIs

**Comment by Shadowmech88** [comment] 2016-05-02 03:20
Out of the problems you listed, the first one is subjective, the second one isn't a problem since nothing requires two hands to construct, and the last three can easily be fixed via code.
What other cons are there?

**Comment by icantthinkofanameritenow** [comment] 2016-05-02 03:37
> nothing requires two hands to construct

It does make the construction process exponentially slower, which kind of defeats the purpose of the thing. 

I already pointed out how the act of dropping out is in itself a law violation, so you either have to make significant changes to the laws allowing it or just not give them laws like a posibrain.

**Comment by gbasood** [comment] 2016-05-02 16:42
Since I haven't heard from @cloroxygen since after the initial merge/shortly before the revert, I'm gonna call SaMMIs abandoned
They were too shit for this world
Feel free to keep discussing if you want

**Comment by MercuryDoll** [comment] 2016-05-02 16:42
>    They're designed to do a job that players don't want to do, filled by players.

Subjective, sometimes doing menial tasks is better than sitting idly doing nothing. The "play something else while you wait then" argument is kinda dumb. Sure i could play HuniePop while waiting to be cloned but i didn't open dreamseeker to play something other than 2d spessmen.

>    They have one hand and can't make a lot of stuff because of it.

No task other than dualwielding melee weapons requires two hands. Doing construction one-handed isn't significantly slower than two handed, especially since SAMMIs come with the complete toolset in a quickbar already.

>    Their law 3 can be overriden by a harm law in law 2, which is a law anyone can set via simple interaction

Anyone with a basic understanding of AI laws should recognize the lawset as completely unfitting and needs to be rewritten from scratch. Being able to overwrite the laws like that is mostlikely unintentional, just like the thousands of other bugs.

>    Simple hop in/hop out at any time mobs do not work well for us, because it nulls the reference to the ghost's body, so it's only useful for players don't want to return their bodies.

Coding issue, pretty sure this can be fixed.

>    You can make a SAMMI and have it use its mat fab to make a massive net profit in mats.

Again, a balance issue that's mostlikely getting removed before it's ever re-merged.

> And as I stated, I feel like it would be better for the game not to include an "easy out" so to speak. It takes away some of the sting of death, IMO. 

It's not an "easy out", it's just something to occupy yourself with while getting back into the game proper. An "easy out" would be a MoMMI fabricator right on the station instead of the Derelict, which was dismissed long ago. And the "sting of death" thing sounds kinda dumb because in a game of spess death comes easy and unpredictably more often than not. So much that people expect to die at every corner, and when it comes it's just another one of countless deaths. There's no "sting", it's just "well i'm dead again,back to the waiting game."

**Closed as completed** 2016-05-02 16:41 UTC
Labels: Discussion

**Comment by ghost** [comment] 2016-05-02 21:46
@gbasood 
Not abandoned - It's just the start of the work week.

> Simple hop in/hop out at any time mobs do not work well for us, because it nulls the reference to the ghost's body, so it's only useful for players don't want to return their bodies.

Not true at all.
SAMMIs keep reference to the original body, using the reenter corpse verb takes you to your original body.

> Their law 3 can be overriden by a harm law in law 2, which is a law anyone can set via simple interaction

I put the law input behind the silicon ID lock but it got reverted too quickly to make a PR, it'll be included in the next version.

> You can make a SAMMI and have it use its mat fab to make a massive net profit in mats.

That was already discussed; it was determined by the majority this was a non-issue.

_Anyways_, look forward to some updated SAMMI in the future.

**Comment by icantthinkofanameritenow** [comment] 2016-05-02 22:33
Only give it the MoMMI synth, so it can't dupe rare metals. That'll silence that issue entirely. 

As for laws, I doubt it even needs any beyond "do what you're told, and don't be a griffing shitter". Applying silicon laws of any sort to it would be more harmful than beneficial if you ask me.

**Comment by gbasood** [comment] 2016-05-02 22:50
@cloroxygen Except that I jumped in someone else's body after ghosting out of a SaMMI sure

**Comment by ghost** [comment] 2016-05-03 00:24
@gbasood 
Weird.
`src.mind.current = src.mind.original`
is all we are doing there.

Seemed to work locally with the scenarios I tested.
Can you post an issue with steps to reproduce it if you haven't already?

@icantthinkofanameritenow 

> "do what you're told, and don't be a griffing shitter".

That is what I was trying to go for but with a more IC friendly spin on it.
I'll have some time to consider better wording/arrangement for the laws.

**Comment by gbasood** [comment] 2016-05-03 15:49
@cloroxygen Don't have exact steps at the the moment and it's hard to reproduce on a non-live server so here's some possible steps:
- Have two players, one who dies after roundstart and one who is an observer
- Have the one who died get put into an MMI (or possibly posibrain as was the case here)
- Build a SAMMI using the MMI/posi
- Now that our dead player is in the SAMMI, have the observer click the sammi that player is already in in order to jump into it (which is entirely possible, somehow)
- Both of them will occupy the SAMMI now. Both of them can talk through the sammi.
- Have the observer player ghost.
- Have another player attempt to clone the dead player. Observer player should receive bwoinks about getting cloned.

It's entirely possible that you didn't override something from MoMMIs/posibrains/MMIs that caused this.
You might be better off making a separate silicon mob that doesn't inherit from borg, AI or MoMMIs.

**Comment by ghost** [comment] 2016-05-03 17:45
@gbasood 
Tanks Bruv

That issue may exist elsewhere but a check preventing two minds from taking it over may prevent this issue from arising.

I'll get it buttoned down here soon.

**Comment by ComicIronic** [comment] 2016-05-03 18:01
Free mats for no cost is not a non-issue. It was a major problem for MoMMIs when they first got the matfab, and that was for silicons with a non interaction law and no ability to be ordered by humans.
