### ISSUE TITLE
ion rifle sprite bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28316] opened 2020-12-05 01:52 UTC
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
9c11db3ad5517d57df1c857ab5486f04c18f7e12

it has an extra frame when its out of charge, it flickers black-blue

**Comment by SonixApache** [comment] 2020-12-05 02:30
@drawsstuff

**Comment by drawsstuff** [comment] 2020-12-05 04:15
i dont know how to pr the fix i made it literally the day it was merged

**Comment by DamianX** [comment] 2020-12-05 22:39
Duplicate of #27370

**Closed as completed by DamianX** 2020-12-05 22:39 UTC
