### ISSUE TITLE
Sounds are wonky since no-sound-in-space was added

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2447] opened 2015-01-05 21:06 UTC
The feature is cool, but...

Bag/backpack/box rustling sound doesn't play UNLESS you are standing on an airlock tile.
Clown shoes made no sound in the escape shuttle. How horrifying!
Glass airlocks make a windoor sound. Is this intended?

**Comment by ComicIronic** [comment] 2015-01-05 21:33
Glass airlocks were addressed in an earlier issue and the sound change was caused by the airlock sound system changes.

Could you explain the first one? Do you mean that unless you're inside an airlock, the sounds don't play at all, even in the station?
And for the second, were any other sounds not playing in the shuttle?

**Comment by vgrainicorn** [comment] 2015-01-05 21:42
That's right, bag rustling sounds just don't play ever unless you sit in the same tile as an airlock. 1. Spawn as assistant 2. Open your bag, no sound 3. Open an airlock and walk inside (I tested with glass airlocks) 4. Open bag, sound plays

For the second I think other sounds were playing, that is, there was an atmosphere in the shuttle at the time. I couldn't test it more and I didn't want to bother an admin to do it.

**Comment by ComicIronic** [comment] 2015-01-05 22:11
I've determined the issue with the rustle, I think.
The shuttle is a more interesting issue. See if you can reproduce it with the clown shoes or any other sounds.

**Comment by BestName** [comment] 2015-01-06 10:15
Sounds just seem to disappear sometimes as well, like the game just goes completely mute for a few seconds.

**Comment by ComicIronic** [comment] 2015-01-31 20:40
If nobody manages to reproduce these issues, I'll close this.

**Closed** 2015-02-22 21:51 UTC
Labels: Needs Moar Testing
