### ISSUE TITLE
Viruses trying to create way too goddamn often.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13230] opened 2017-01-03 01:06 UTC
@despotate 
http://game.ss13.moe/logs/2017/01-January/02-Monday.log
Scroll down half way to find _a metric shitton of virus creation attempts_
https://a.pomf.cat/akfzsk.webm

At the very least this is far too many logs to be reasonable.  But the meat and potatoes is we're trying to create way too many fucking viruses at once.

**Comment by despotate** [comment] 2017-01-03 01:08
Yep.

The actual problem here is that there's _too few_ logs. All we have for that round is the logs from when they're trying to infect someone, so we don't know why infinite amounts of them were created in the first place because literally no other functions in virus2 are logged. There's actually a lot of logs in other functions but all of them are commented out for some reason.

So I'm currently working on adding more debug logs as I'm not confident on the cause of this infinite loop of virus creation, so that we can know why this happened next time. For now, just remember to hit "cure all viruses" if the serb crashes the same way again.

I might even pick up on the cause of all this while adding logging.

**Comment by Probe1** [comment] 2017-01-03 01:14
>it crashed the serb
WAIT WHAT

**Comment by despotate** [comment] 2017-01-03 01:15
[15:54:42]DEBUG: Attempting virus 2867
[15:54:42]DEBUG: Attempting virus 9590
[15:54:42]DEBUG: Attempting virus 2615
[15:54:42]DEBUG: Attempting virus 3399
[15:54:42]DEBUG: Attempting virus 8090
[15:54:42]DEBUG: Attempting virus 2191
[15:54:42]DEBUG: Attempting virus 3327
[15:54:42]DEBUG: Attempting virus 7760
[15:54:43]OOC: Cindy Kate/Praecordia (@222,281,1): welcome to our feature presentation

Two more things are also surprising about the logs:
- There was literally no mention of `virus` in the logs that round before the wall of infection attempts
- The lag happened _before_ the first attempts at infection which were logged, meaning it probably started when a shit ton of viruses were created

**Comment by despotate** [comment] 2017-01-03 02:50
Might as well close this now. Tested on test serb, ~~died to gibbington's~~, no crash.

**Closed as completed** 2017-01-03 19:27 UTC
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, Oversight, Logging / Administration
