### ISSUE TITLE
double bladed toy swords have no inhand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30731] opened 2021-09-13 00:46 UTC
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
a8b0b98965c75ef83e623666d7513b7fa5c58ef0

**Comment by DeityLink** [comment] 2021-09-13 03:02
Duplicate of #30712

**Closed as completed by DeityLink** 2021-09-13 03:02 UTC
Labels: Bug / Fix
