### ISSUE TITLE
lamprey still isnt votable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28032] opened 2020-10-16 06:49 UTC
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
2cfb9d7c57369825e0e48cdd2dd56f751b51f02a

-69000 score, lamprey still not votable
fuck you barry

**Comment by d3athrow** [comment] 2020-10-16 06:54
based

**Comment by SonixApache** [comment] 2020-10-16 09:06
working as intended

**Comment by robintime** [comment] 2021-04-10 07:38
#28033 is a more descriptive duplicate of this issue

**Closed as completed by robintime** 2021-04-10 07:38 UTC
