### ISSUE TITLE
ZAS is extremely inconsistent when breaking double-border-windows, frequently seems to not work

### ISSUE THREAD

**Issue by help-maint** [d3athrow/vgstation13#29180] opened 2021-04-08 16:30 UTC
Tested by breaking these 2 double-border windows, above and below the Arrivals shuttle. I broke these windows by using a laser gun.
![dreamseeker_08_04_2021_13_12_12_07](https://user-images.githubusercontent.com/81891904/114061672-12406780-986d-11eb-97c9-1e275c365e69.png)
![dreamseeker_08_04_2021_13_11_11_20](https://user-images.githubusercontent.com/81891904/114061675-13719480-986d-11eb-992b-b71bc43d86c3.png)

I would always get 1 of 2 results:
A- A breach is correctly generated and the room quickly vents,
![dreamseeker_08_04_2021_13_32_32_58](https://user-images.githubusercontent.com/81891904/114063420-f76ef280-986e-11eb-9335-89b5549924c0.png)
B- Breach is seemingly not generated, or rather, only an extremely slow breach.
![dreamseeker_08_04_2021_13_12_12_03](https://user-images.githubusercontent.com/81891904/114061937-5469a900-986d-11eb-9d19-08ec7b30ab1e.png)

Whether you get A or B when breaking a window seems to have bizarre conditions to it.
If you break the outside window first, wait 5 seconds, and then break the inside one, you seem to consistently get B, where the room depressurizes 100x slower than it's supposed to. Breaking the inside window first, then the outside one, or breaking both in quick succession, seems to usually result in A.
However, if the room was already partially depressurized, i.e. 70KPA, then breaking a double-border-window will seemingly always result in a slow breach no matter what method you use. This was the case both when having a 70KPA room because I broke a window somewhere else and the firelocks took a couple seconds to go down, and when I toggled emergency syphon for a few moments, so it's probably not firelock related.

**Comment by Exxion** [comment] 2021-04-08 17:42
#19258

**Comment by d3athrow** [comment] 2021-04-08 17:47
solution, get rid of zas for monstermos. it's tile based but way faster than fea or linda is because it uses dll calls to process things.

**Comment by Exxion** [comment] 2021-04-08 17:56
This particular problem can be (mostly) solved more simply than that
Also does Monstermos work on new versions of BYOND? It relies on extools, right? I know it's a custom version of extools but the basic extools is no longer supported.

**Comment by west3436** [comment] 2024-02-08 15:23
Duplicate of #19258

**Closed as not planned by west3436** 2024-02-08 15:23 UTC
Labels: Bug / Fix, System
