### ISSUE TITLE
Can't emag exofabs (to gain access)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11967] opened 2016-09-21 11:48 UTC
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 777a7453ab5486dfce43b02b3f9b3dd25b881973
> 
> General description of the issue
> Nothing happens when you emag an exofab.
> 
> What you expected to happen
> Emag exofab, get access
> 
> What actually happened
> slap emag onto exofab, no effect, UNAUTHORISED ACCESS DETECTED

**Comment by ComicIronic** [comment] 2016-09-21 16:28
Huh, weird.

**Comment by Manfreedo** [comment] 2016-09-21 20:06
Duplicate of https://github.com/d3athrow/vgstation13/issues/9054

**Closed as completed** 2016-09-24 02:27 UTC
Labels: Bug / Fix, Feature Loss
