### ISSUE TITLE
Discharging a gun into someone point blank while standing on them hits you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19535] opened 2018-09-01 04:02 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
4a8bd3e7ae934b0fab2c1454c643ae426a9f8b0d

# Description
Discharging a gun on harm intent at someone (which shoots INTO them) hits whoever is standing on top of them if they are down. 
# Steps to Reproduce

stun someone, stand on top of them, try harm intent hitting them
# What you Expected

Stun them
# What Actually Happened

Stunned self!?

**Comment by Blithering** [comment] 2018-09-01 20:14
https://github.com/vgstation-coders/vgstation13/issues/13486 Been an issue for a while now

**Comment by Exxion** [comment] 2018-09-14 02:33
Since GitHub now recognizes this phrase, I'll explicitly say "duplicate of #13486"
I guess that means this will autoclose when that one's closed? I don't know

**Comment by Exxion** [comment] 2018-09-14 02:36
Duplicate of #13486

**Comment by Exxion** [comment] 2018-09-14 02:36
THERE we go
Apparently the comment has to contain only that phrase, and it doesn't work if you *edit* it to do so
Thanks, GitHub

**Closed as completed** 2018-10-26 12:33 UTC
