### ISSUE TITLE
You put the Bag of Holding into the Bag of Holding

### ISSUE THREAD

**Issue by Theophrastus1** [d3athrow/vgstation13#36675] opened 2024-06-13 00:57 UTC
#### Description of issue
What it says on the tin, don't think hotkey usage makes a scrungulo with bags of holding

#### Difference between expected and actual behavior
no scungulo was loosed

#### Steps to reproduce
put bag of holding into bag of holding with the hotkey instead of clicking
![its fucked](https://github.com/vgstation-coders/vgstation13/assets/8057687/e540a15c-0d49-4f53-9adb-c9b10cfa6990)
![its fucked 2](https://github.com/vgstation-coders/vgstation13/assets/8057687/e9c9e87e-f0de-4a25-a01c-1636294c1e48)

**Comment by west3436** [comment] 2024-06-13 01:06
Duplicate of #36674

**Closed as completed by west3436** 2024-06-13 01:06 UTC
