### ISSUE TITLE
Taking pressure damage in cryo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12039] opened 2016-09-28 09:49 UTC
(WEB REPORT BY: kolith REMOTE: 172.93.109.202:7777)

> Revision 0e07cd0217834583181458ec75010de45fe43077 
> 
> General description of the issue
> you take a shit ton of brute damage from pressure in cryo.
> 
> What you expected to happen
> not take damage in cryo
> 
> What actually happened
> took damage from cryo
> 
> Steps to reproduce if possible
> get in cryo, die

**Comment by kol1th** [comment] 2016-09-28 09:50
@PJB3005 did you do this

**Comment by SonixApache** [comment] 2016-09-28 12:32
Dupe of #11914, related to someone changing shit so you're actually affected by the atmosphere inside the tube rather than just medbay. Mostly appears on Deff.

**Closed as completed** 2016-09-28 14:47 UTC
