### ISSUE TITLE
diona in hand sprite broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26710] opened 2020-06-05 21:18 UTC
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
205665e66b6ff972474ad817f0b50c47089a8120

# Description
i picked up a diona it's sprite went invisible now i can't take it out of my bag
# Steps to Reproduce
pick up diona nymph
be unable to interact with it's item
# What you Expected
to not stuff my friend in a bag forever
# What Actually Happened
i can't pull him out of my bag and there's an invisible slot in the middle of my bag organization so i know it's there as an item.

**Comment by DeityLink** [comment] 2021-08-30 15:25
Is that still a thing?

**Comment by DeityLink** [comment] 2021-08-31 14:14
Duplicate of #26693

**Closed as completed by DeityLink** 2021-08-31 14:14 UTC
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, Needs Moar Testing
