### ISSUE TITLE
Inhands were overriden again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11311] opened 2016-08-06 02:30 UTC
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1686bb32ec200739880084d750cc464b91ba6359 

@Justsumbody broke inhand.dmi's with the tg instrument pr and they need to be repaired

**Comment by Exxion** [comment] 2016-08-07 06:14
I can't reproduce with blood-stained items
I can reproduce with an esword, though
Eswords appear to no longer ever have an inhand

**Comment by ComicIronic** [comment] 2016-08-07 09:37
Love bug reporters giving you a proper report and not just their assumptions about what happened.

**Comment by clusterfack** [comment] 2016-08-07 09:58
Fixed with facts

**Comment by JustSumBody** [comment] 2016-08-07 10:03
Whoops
I double checked in the IRC when I was doing this since it was my first time touching .dmi's, but apparently there was something about "Byond tools" I never knew about.

**Comment by Exxion** [comment] 2016-08-09 06:54
Fixed by #11353

**Closed as completed by Exxion** 2016-08-09 06:54 UTC
Labels: Sprites, Exploitable
