### ISSUE TITLE
Mooshroom Feedback

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18001] opened 2018-04-03 05:16 UTC
@MadmanMartian 
Missing a growth stage sprite
Seems to produce 2 walking mushrooms a piece resulting in huge swarms of empty purples
They grow up insanely fast and seemingly even involuntarily?

**Comment by vampirebat74** [comment] 2018-04-03 05:18
They seem to mature when exposed to darkness, but the problem is that they do so even if a player isn't controlling them. This results in a ton of braindead monkeyman mushrooms that you can't really do anything with but gib. Tbh they should just keel over and die like dionae

**Comment by AI-Is-Rogue** [comment] 2018-04-03 05:25
They're unable to use default emotes and the telepathy is very inconvenient since they can't talk, which means they are unable to use telepathy on each other.

**Comment by ihadtoregisterforthis** [comment] 2018-04-03 06:09
The cooldown on the inverted vision seems unneeded
The telepathy thing makes it not possible to speak to many people at once
The nutrition and speed based on light is very unpredictable and not obvious from the start

@AI-Is-Rogue You can examine someone to use telepathy

**Comment by spoonylove** [comment] 2018-04-03 07:52
the sideways sprites seem wonky, and for vision I was expecting night vision like through the NVGs not what it is currently.

**Comment by MadmanMartian** [comment] 2018-04-03 13:52
well whoops. The segmented sprites has all the limbs in the center, so you look like a giant blob of fun in the center.

**Comment by vampirebat74** [comment] 2018-04-03 16:09
I think the dark thing could really just be fixed with a bit of dialogue when you spawn. Maybe something like "You are a moshrum. You become powerful in the dark, but exposure to light causes you pain."

**Comment by MadmanMartian** [comment] 2018-04-03 18:38
good idea

**Comment by Kurfursten** [comment] 2018-04-03 19:27
I've noticed that most people don't seem to understand you need to examine someone to get them on your project mind list. This isn't a big deal for greys since they can just talk, but I think it warrants a warning for mushrooms.

**Closed as completed** 2018-04-03 19:53 UTC
