### ISSUE TITLE
Vox Atmos Suit doesn't protect from plasma leaks.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7988] opened 2016-01-31 05:17 UTC
(WEB REPORT BY: lexuskit REMOTE: 158.69.55.2:7777)
Revision: 08ca26d11f1552790c713fad9e5d29104c13a0da 

General description of the issue:
The suit that atmos tech vox come with simply do not protect them from plasma hazards as an atmos suit should.

What you expected to happen:
To walk into a plasma leak hazard and not die.

What actually happened:
Walked into a plasma leak hazard and the plasma contaminated literally everything.

Steps to reproduce if possible:
Start as atmos tech vox, wear your starting pressure suit, walk into plasma, watch as plasma kills you through an atmos suit.

**Comment by ghost** [comment] 2016-01-31 11:07
Duplicate of #7793 and fixed by #7929

**Closed as completed** 2016-01-31 11:36 UTC
