### ISSUE TITLE
If you're listening to streamed music while the round ends, the streamed music only stops when it actually ends, instead of when the server stops.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5675] opened 2015-09-15 21:20 UTC

**Comment by N3X15** [comment] 2015-09-15 22:26
Known issue, still working out how I'd fix this.  The issue is that the music is done via a client-side embedded player that only changes the music when the server tells it to.

**Comment by Probe1** [comment] 2015-09-16 04:03
@N3X15 if you happen to write a :stopmusic: proc, could you add it as an admin verb as well?  There are times I've wanted to stop music for some adminbus related sound to play.

**Comment by N3X15** [comment] 2015-09-25 07:03
Working on a fix for this, but it's hokey since you have to send the message to the client before the server gets the reboot message.

**Comment by N3X15** [comment] 2015-09-25 20:40
Okay, I put a 1-second sleep on it to try and avoid the race condition, and it still kills the server before the stop media command gets to the client.

Closing as can't fix.

**Closed by N3X15** 2015-09-25 20:40 UTC
Labels: Bug, Oversight
