### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Virus symptoms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3891] opened 2015-04-13 16:50 UTC
>Revision (Should be above if you're viewing this from ingame!)
5b5b9b8e55c942c3797a09b8282b0bd99ccec614 

>General description of the issue
Custom virus exhibiting different symptoms than spliced in

>What you expected to happen
Virus exhibits symptoms according to virus databas/the ones I spliced in

>What actually happened
Virus somehow retained the old pre-slpicing symptoms as well as exhibiting the new one (pierrots throat)

>Steps to reproduce if possible
Can't access the test server.
I took a virus dish that had 800 airborne spread, things like radians and world shaking, then replaced them with waiting, blading, clown and biobulin.

**Comment by Kurfursten** [comment] 2015-10-15 21:52
@clusterfack This appears to be WAD / Cannot Reproduce. Close it.

**Closed** 2015-10-16 00:52 UTC
