### ISSUE TITLE
Becoming the grinch: nullspace no-control edition

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21257] opened 2019-01-08 10:12 UTC
#### Description of issue
was a autotraitored posibrain
got put in a borg shell
died
ghosted
got polled for grinch, poll immediately closed when i applied
didn't actually get pulled as grinch
found an AI grinch feeling up walls
grinch got robusted
tried to re-enter corpse, ended up in dead grinch
went back to where I died to look at my old body but it was gone
kurfursten did a lookup and found my borg body in nullspace
[bugfix]

#### Server revision
69b5c5b6808562168fbd1494efcc5bd70865f458

**Comment by Kurfursten** [comment] 2019-01-08 11:08
no, the posibrain was in nullspace

and midround grinches having no mind is a dupe of #21142

**Closed as completed** 2022-12-20 19:45 UTC
Labels: Bug / Fix
