### ISSUE TITLE
Sleeper console not part of flatpack

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6626] opened 2015-11-17 00:03 UTC
(WEB REPORT BY: realestestate REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Flatpack fabricator creates a sleeper. console of the sleeper spawns adjacent to the flatpack fabricator, but not inside the flatpack

>What you expected to happen
the console be inside the flatpack, and spawns next to sleeper when opened

>What actually happened
console spawns immediately next to the fabricator, and not part of the flatpack

>Steps to reproduce if possible
use the flatpack fabricator to make a sleeper

**Comment by PJB3005** [comment] 2015-11-17 01:57
Dupe of #5311

**Closed by PJB3005** 2015-11-17 01:57 UTC
