### ISSUE TITLE
storage_slots above 14 doesn't work for boxes

### ISSUE THREAD

**Issue by brndd** [d3athrow/vgstation13#24972] opened 2019-11-11 12:31 UTC
Boxes, and presumably other containers, with `storage_slots` set to more than 14 cannot contain more than 14 items. If they're forcibly filled with more than 14 items (eg. the shotgun ammo boxes in the armory have 16 shells in them, with `storage_slots = 16`) it'll work, but if you take one item out you can't put it back in.

**Comment by utilitas-** [comment] 2019-11-11 12:53
Are you sure it's because of storage_slots and not because of max_wclass and max_combined_w_class? Looking at storage/box/buckshotshells, it has correctly set the storage_slots to 16 but the max_combined_w_class isn't overriden and stays at the default 14. Buckshot casing is RECYK_METAL which is 1 (I think).

**Comment by Kurfursten** [comment] 2019-11-11 15:27
w_type is actually the recycle material type, used by the recycling sorter

you're thinking of w_class, but your idea was essentially right - the box has a max_combined_w_class of 14 and each shell has a w_class of 1

**Comment by utilitas-** [comment] 2019-11-11 15:48
Maybe someone should just add premapped boxes to initialize and make them all set their storage_slots and max_combined_w_class according to their contents to >=14.

**Comment by Kurfursten** [comment] 2019-11-11 15:52
I wonder if it's important that the boxes contain 16 shells in the first place?

14 is a nicer breakpoint because we have 7 to a row, and burneddi is making that change to make printing additional buckshot much easier now. Just my thoughts.

**Comment by brndd** [comment] 2019-11-11 16:42
I didn't make the boxes or touch anything on them besides their name, this was just something I noticed while implementing the ammolathe PR.

**Comment by Kurfursten** [comment] 2019-11-11 16:47
I'm not implying you were in the wrong or something, just saying 14 shells might be enough considering it's about to get plenty easier to print more and 14 is a very nice round number for our storage purposes

**Comment by DeityLink** [comment] 2021-09-05 13:26
Seems related to #25485

**Comment by DeityLink** [comment] 2021-09-15 20:35
Well now that I've read the comments it seems to be working as intended. If someone else wants to tweak the balance go for it.

**Comment by DeityLink** [comment] 2021-09-15 20:36
Closing this because the title and OP are misleading of the actual "issues". Feel free to open other tickets if you want those to be discussed again.

**Closed as completed by DeityLink** 2021-09-15 20:35 UTC
Labels: Oversight
