### ISSUE TITLE
AIs doesn't actually have the radio frequencies in their notes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24305] opened 2019-09-29 17:33 UTC
(WEB REPORT BY: agentofzog REMOTE: 206.221.180.138:7777)
# Revision
5980f011aa6f657f30e24d85b1e7c2c7c18ea8dd

# Description
The AI's notes are empty, instead of having a list of all the radio frequencies

**Comment by ConkerDev** [comment] 2021-05-03 16:14
AIs notes arent empty anymore 
![imagen](https://user-images.githubusercontent.com/6278535/116902445-6ad00e00-ac3b-11eb-901e-80d8cd17c31e.png)

**Comment by DeityLink** [comment] 2021-09-06 04:49
Duplicate of #24501

**Closed as completed by DeityLink** 2021-09-06 04:49 UTC
