### ISSUE TITLE
Diona nymph freeze on ventcrawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8767] opened 2016-03-11 23:00 UTC
(WEB REPORT BY: termedclepe2 REMOTE: 158.69.55.2:7777)
Even when crawling into a 20C pipe filled with air, they freeze nearly instantly

**Comment by 9600bauds** [comment] 2016-03-11 23:19
According to Celt this is a feature because more air pressure = more heat transfer so you freeze to 20c ;)
It's stupid though.

**Comment by AutismSpider** [comment] 2016-03-12 00:12
more or less makes lings monkey mode useless they go into the vent and freeze to death

**Comment by PJB3005** [comment] 2016-03-12 00:31
@9600bauds but that's not how temperature works...

@DrCelt you dork.

**Comment by Brolaire** [comment] 2016-03-12 02:56
i also dont like that in some pipes theres so much pressure in some pipes you get stuck inside of them to the point you cannot crawl forward or backwards and start to slowly die in a pipe.

**Comment by PJB3005** [comment] 2016-03-12 11:47
Yes I've had a diona be paralyzed for some reason inside a pipe, they then died.

**Comment by Intigracy** [comment] 2016-03-12 22:41
Celt hates fun.

**Comment by Kitfox88** [comment] 2016-03-13 01:41
fuck diona larva die you little shits

**Comment by FudgePucker** [comment] 2016-03-13 23:41
Remember kids, if you fuck up and make a bug, twist it into a feature
100% tested

**Comment by Intigracy** [comment] 2016-03-13 23:53
@DrCelt

**Comment by Zth--** [comment] 2016-03-14 05:19
This is stupid and should be removed. Removing dionas the ability to vent crawl is a huge nerf

**Comment by 9600bauds** [comment] 2016-03-14 05:19
This shits over everything that can ventcrawl btw, not just dionas

**Comment by 9600bauds** [comment] 2016-03-14 05:19
@DrCelt

**Comment by Zth--** [comment] 2016-03-14 05:21
Then this is only worse. And this wasn't mentioned in any PR, was it?

**Comment by Intigracy** [comment] 2016-03-14 05:32
@DrCelt

**Comment by AutismSpider** [comment] 2016-03-14 06:42
Makes the ling monkey mode useless they go into the vent and freeze to death the atmos tech gimp suit stops them form freezing

**Comment by FudgePucker** [comment] 2016-03-14 13:07
100% tested

**Comment by Intigracy** [comment] 2016-03-14 13:45
@DrCelt

**Comment by Intigracy** [comment] 2016-03-14 22:33
@DrCelt

**Comment by Boxe** [comment] 2016-03-14 22:34
celt i swear

**Comment by NigglyWiggly** [comment] 2016-03-14 22:34
@DrCelt

**Comment by ihadtoregisterforthis** [comment] 2016-03-14 23:01
Your cries don't work, you need something like

## No wonder the Titanic sank, it was made in Belfast

**Comment by clusterfack** [comment] 2016-03-14 23:06
Celt left to escape the potato famine so he can't save us now.

**Comment by Intigracy** [comment] 2016-03-14 23:09
He was on yesterday shittalking my code.

**Comment by clusterfack** [comment] 2016-03-14 23:14
The heck @drcelt spending all day reading others code while making none of your own, are you trying to be a collaborator or something?

**Comment by ghost** [comment] 2016-03-14 23:18
feck off all of you

**Comment by NigglyWiggly** [comment] 2016-03-14 23:23
Maybe fix your shit first nerd

**Comment by Intigracy** [comment] 2016-03-14 23:54
What she said.

**Comment by Boxe** [comment] 2016-03-14 23:55
>she

**Comment by AutismSpider** [comment] 2016-03-15 00:02
celt you need fuck off or get back to work on your code and that snow map we have ALL this shit due to that map  has seen zero work so far

**Comment by Intigracy** [comment] 2016-03-15 00:30
I'll be sure to mention you every day until this is fixed.

@DrCelt

**Comment by Intigracy** [comment] 2016-03-15 14:11
day 2

@DrCelt

**Comment by PJB3005** [comment] 2016-03-15 16:05
Revert hypothermia when?

<sup><sup>that'll get Celt on his feet</sup></sup>

**Comment by Intigracy** [comment] 2016-03-16 17:03
day 3

@DrCelt

**Comment by Intigracy** [comment] 2016-03-19 03:02
day 4 because I forgot

@DrCelt

**Comment by Intigracy** [comment] 2016-03-19 03:02
day 5

@DrCelt

**Comment by 9600bauds** [comment] 2016-03-19 03:50
![](http://i.imgur.com/TBEWwzn.jpg)

**Comment by NigglyWiggly** [comment] 2016-03-19 16:05
@DrCelt 

# FIX IT FIX IT FIX IT FIX IT FIX IT FIX IT FIX IT

**Comment by Intigracy** [comment] 2016-03-19 16:05
day 6

@DrCelt

**Comment by Boxe** [comment] 2016-03-20 04:24
i think it's day 7 or something now so i'm gonna hijack this giddyup

 @DrCelt

**Comment by 9600bauds** [comment] 2016-03-20 05:31
Let's instead post one paragraph from http://www.theonion.com/article/freshly-scented-soap-to-cleanse-irish-586 every day

**Comment by Boxe** [comment] 2016-03-20 05:35
ok

DUBLIN, IRELAND—After centuries of suffering, the people of the world will finally have some much-needed relief from the offending filth of the ubiquitous Irish. The remedy: a new, freshly scented deodorant soap designed specifically with malodorous Irish riff-raff in mind.

**Comment by Intigracy** [comment] 2016-03-20 11:35
day 7

@DrCelt stop worshipping your potato altar and fix your shit

**Comment by NigglyWiggly** [comment] 2016-03-22 03:18
@DrCelt Fucking come on

**Comment by Intigracy** [comment] 2016-03-22 04:05
day 8

@DrCelt

**Comment by Intigracy** [comment] 2016-03-22 14:08
day 9

@DrCelt

**Comment by gbasood** [comment] 2016-03-22 18:05
Celt hasn't done shit since the 6th
He's either busy or exists only to tell other people their code is bad without looking at it now

**Comment by 9600bauds** [comment] 2016-03-22 22:10
How about a "yes it's intentional because of X" or "oh that's actually caused by Y and I didn't realize"

**Comment by Intigracy** [comment] 2016-03-24 03:52
day 10

@DrCelt

**Comment by Intigracy** [comment] 2016-03-24 17:09
day 11

@DrCelt

**Comment by gbasood** [comment] 2016-03-24 17:55
Fuck celt's opinion, it's stupid that pressure should fuck with temperature.
Fixit

**Comment by FudgePucker** [comment] 2016-03-24 17:59
Maybe if the pipes were at a higher pressure, like much higher. But if the pipes were just a couple of kpa above the normal room pressure then it is fucking stupid.
Some one do a test, if a pipe at room temp 20 c at 101kpa causes the nymph freeze then celt is fucking stupid and just came up with a stupid excuse to cover his shitcode.
"100% tested"

**Comment by Boxe** [comment] 2016-03-24 18:01
juan hundred

**Comment by gbasood** [comment] 2016-03-24 18:03
Honestly I don't think that they should affect temperature at all, ESPECIALLY when it comes to ventcrawling

So many ways to die inside a vent as it is

**Comment by Intigracy** [comment] 2016-03-25 16:52
day 12

@DrCelt

**Comment by gbasood** [comment] 2016-03-25 17:59
@Intigracy seriously Celt won't fix this
He doesn't go in IRC anymore, he only shows up to complain about people's PRs now

**Comment by 9600bauds** [comment] 2016-03-25 21:21
Coderbus: Not even once

**Comment by Intigracy** [comment] 2016-03-26 17:36
day 13

@DrCelt

**Comment by gbasood** [comment] 2016-03-28 18:50
right that's it

**Comment by 9600bauds** [comment] 2016-03-28 20:31
day 15

@DrCelt

**Comment by Intigracy** [comment] 2016-03-28 21:27
lmao

I gave up on pinging celt

**Comment by gbasood** [comment] 2016-03-28 21:42
Safe to assume he's going to show up and introduce a new feature no one wanted and then make a special meme machine like the Mancrowave and then leave for some unmentioned reason

Closing in favor of #9104

**Closed as completed** 2016-03-28 21:42 UTC
Labels: Bug / Fix, Balance, Feature Loss, IT'S A FEAAAATUUUUREEEEEEEEE
