### ISSUE TITLE
(WEB REPORT BY: jewishneocon REMOTE: 198.245.63.50:7777) custom on hoP computer wont work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4065] opened 2015-04-23 01:59 UTC
>Revision (Should be above if you're viewing this from ingame!)

ddf1f0a0ba426b4fde625ac2ea39db7c78406e11 
>General description of the issue
clicking
clicking custom on the id computer dont work
>What you expected to happen
let me put a custom job name

>What actually happened

redirects me back

**Comment by wwjnc** [comment] 2015-04-23 04:25
Duplicate of #3958

**Closed** 2015-04-23 09:19 UTC
