### ISSUE TITLE
Multi arm slots are buggy

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#24405] opened 2019-10-08 08:00 UTC
1. get any new arms via virus
2. try to click on arm 4 in your UI
3. it selects arm 5
4. apply this for any of your arms above 2
5. regret getting additional arms at all as you mash your cycle hotkey to function

**Comment by DamianX** [comment] 2019-10-08 09:15
Duplicate of #20622

**Closed as completed by DamianX** 2019-10-08 09:15 UTC
