### ISSUE TITLE
monkey ling rejuv broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12244] opened 2016-10-17 06:13 UTC
(WEB REPORT BY: strawberrytan REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)Revision: 8455e57862aebead00ae1c4ec09a06c7eb2c3a65
> 
> General description of the issue
> changeling who dies and rejuvenates in monkey form cannot change back
> 
> What you expected to happen
> a changeling monkey to be able to change form as changelings can
> 
> What actually happened
> after death, changeling monkey loses ability to become a non-simple mob and that sucks
> 
> Steps to reproduce if possible
> be a changeling
> be a monkey
> die

**Comment by Exxion** [comment] 2016-10-17 06:15
Alright this is much more helpful. But still a dupe of #11937

**Closed as completed by Exxion** 2016-10-17 06:15 UTC
