### ISSUE TITLE
Snackbar Machine does not create snack bar

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7318] opened 2015-12-27 05:41 UTC
(WEB REPORT BY: sylvos REMOTE: 158.69.55.2:7777)

> Revision f3a9da06e13a60c8ab64754477ea75ff35693730 
> 
> General description of the issue

Snackbar machine does not make snack bar when pressed

> What you expected to happen

A snack bar was created when I loaded reagents into the machine and pressed the button

> What actually happened

Nothing

> Steps to reproduce if possible

Try to make a snack bar. I used Nutriment. Button does not work.

**Comment by unid15** [comment] 2015-12-27 13:13
Did you have a beaker inside? The snackbar machine doesn't make snackbars unless there's a beaker inserted

Edit: NVM it was an issuue with chemmasters

**Comment by PJB3005** [comment] 2015-12-27 20:37
Didn't dylan touch the snackbar machine sort of semi-recently...?

**Comment by unid15** [comment] 2015-12-27 20:56
It's caused by chemmaster returning 1 at the end of its Topic()

**Comment by 9600bauds** [comment] 2015-12-28 00:11
nanoUI too much to handle

**Comment by 9600bauds** [comment] 2015-12-28 07:49
Was fixed by #7326
It turns out that not everything that looks like nano is nano

**Comment by PJB3005** [comment] 2015-12-28 13:26
@9600bauds if the chemmaster looks like Nano...

**Comment by 9600bauds** [comment] 2015-12-29 00:01
If it's not blue on white it's nano, scientifically proven

**Comment by 9600bauds** [comment] 2015-12-30 08:58
Close this

**Comment by clusterfack** [comment] 2015-12-30 08:58
ALLAHU SNACKBAR

**Closed as completed by clusterfack** 2015-12-30 08:58 UTC
Labels: Bug / Fix, Feature Loss
