### ISSUE TITLE
Waystation CMO office wall console offset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37064] opened 2024-09-07 02:51 UTC
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
c1e3abf3579ffcd4c4aac4003248af794f528f6c

# Byond Version
515.1643

# Description

The CMO wall console is placed between the intercomm and the card swipey thing, but to use it you have to be adjacent to the tile to the left of it instead for some reason. The phone cable also comes out of this tile.

**Comment by hacker-on-steroids** [comment] 2024-09-08 19:14
duplicate of #35574

**Closed as not planned** 2024-09-09 15:13 UTC
