### ISSUE TITLE
Mommi vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30619] opened 2021-09-07 22:59 UTC
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
2c23acabefcd08e24ccb3056741c5e37b0000177

# Description
You don't get meson vision
# Steps to Reproduce
Click vision button
# What you Expected
Mesons
# What Actually Happened
complete darkness

**Comment by DeityLink** [comment] 2021-09-07 23:24
Duplicate of #30597

**Closed as completed by DeityLink** 2021-09-07 23:24 UTC
Labels: Bug / Fix
