### ISSUE TITLE
Borgs are stunned and deafened by flashbangs

### ISSUE THREAD

**Issue by gayniggersex666** [d3athrow/vgstation13#2625] opened 2015-01-25 02:50 UTC

**Comment by Konater** [comment] 2015-01-25 02:54
The AI is also affected by them

**Comment by ComicIronic** [comment] 2015-01-25 14:43
Considering borgs are affected by flashes, I wouldn't mark this down as an issue.

The AI thing, maybe.

**Comment by Aurx** [comment] 2015-01-25 23:59
As long as they recover, I don't see what's wrong.  The flash stuns the borg, the bang deafens it.

**Comment by Kurfursten** [comment] 2015-10-15 21:23
@clusterfack Not a bug, close this

**Closed** 2015-10-16 00:49 UTC
