### ISSUE TITLE
Crew Monitoring Map bug [Defficency]

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6140] opened 2015-10-14 23:24 UTC
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Minimap on Crew Monitoring Computers is Box's map.

**Comment by Ephx1** [comment] 2015-10-14 23:39
This applies to any map switching, see #5945.

**Comment by clusterfack** [comment] 2015-10-15 00:05
How is that even possible, it generates its own minimap at roundstart

**Comment by Ephx1** [comment] 2015-10-16 20:50
Here, got a picture for it. Previous round was Meta, then it was box. It seems this also applies to the Bhangometer.
![fug](https://cloud.githubusercontent.com/assets/6224074/10553032/f0523110-7425-11e5-96b1-4da6302ec169.png)

**Comment by clusterfack** [comment] 2015-11-22 09:40
Still a dupe of #5945, ephx1 is right

**Closed by clusterfack** 2015-11-22 09:40 UTC
Labels: Bug, Feature Loss
