### ISSUE TITLE
Crew Monitoring Computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22789] opened 2019-05-05 15:50 UTC
(WEB REPORT BY: zer13 REMOTE: 206.221.180.138:7777)
# Revision
645fe1a653e7412dcd75129f12a8890491c2207f

# Description

Crew Monitoring computer text screen scrolls up automatically when scrolled down

# Steps to Reproduce

Go to the crew monitoring computer text screen and try scrolling down. Possibly requires refresh to be on.

# What you Expected

That the screen would not scroll down by itself.

# What Actually Happened

It scrolled down by itself.

**Comment by PaulRitter** [comment] 2019-05-05 20:58
you can close this, the issue is known

**Comment by Exxion** [comment] 2019-05-05 21:29
Duplicate of #22687

**Closed as completed by Exxion** 2019-05-05 21:29 UTC
