### ISSUE TITLE
Hide sprite command no longer works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6298] opened 2015-10-24 13:51 UTC
(WEB REPORT BY: cumoverme REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
0a65da02d0238543c2bdf9752a8fbece8cf12df3

>General description of the issue
The ghost verb "hide sprite" no longer works.

>What you expected to happen
To my sprite as ghost to be hidden.

>What actually happened
It comes back after two seconds hidden.

>Steps to reproduce if possible
Kill yourself, press Hide Sprite at ghost tab.

**Comment by clusterfack** [comment] 2015-10-25 02:15
This is probably caused by halloween shit so I'm closing this for now

**Closed by clusterfack** 2015-10-25 02:15 UTC
