### ISSUE TITLE
Coders need to be hugged mercilessly for fucking up cryo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6664] opened 2015-11-19 23:02 UTC
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Eats up 50% of cryomix while also causing massive amounts of burn damage thanks to coders fucking everything up again, thanks coders.

**Comment by 9600bauds** [comment] 2015-11-20 02:30
???

**Comment by PJB3005** [comment] 2015-11-20 02:36
inb4 asshole put acid in cryo tube

**Comment by 9600bauds** [comment] 2015-11-20 03:05
Unable to reproduce the "Eats up 50% of cryomix" part
Test dummy in non-harmful cryomix was only taking extremely small amounts of burn damage
Please don't delete the bug-reporting template (what happened, what did you expect to happen, how to reproduce) and add relevant fucking information to your web reports

**Comment by clusterfack** [comment] 2015-11-20 06:49
Players need to be **hugged mercilessly** for making questionable bug reports

**Comment by Probe1** [comment] 2015-11-20 22:02
Cryo was not messed with and had a very standard, run of the mill mix that would cause no trabble for players.  

Players put in cryo received increasing burns.

**Comment by 9600bauds** [comment] 2015-11-20 22:05
To elaborate: My own testing showed a very, very slow increase in burn damage while the patient was inside the cryotube, whether it be on or off. Probably caused by the player being in an extremely cold environment.
Even the weakest cryomix would cure the burn damage as soon as it happened, however the patient would get slowly roasted if the tube was left off or without a mix.

I'm not sure if this has always been the case or if this is intended (it does make a little bit of sense)

**Comment by Zth--** [comment] 2015-11-21 16:06
Burns with cold code was touched a month ago or so. Pretty sure it's related to this

**Comment by FudgePucker** [comment] 2015-11-21 18:13
Having cyro freeze people to death if not properly set up makes sense.

You are tossing them into a super cold environment, with out it being turned on or having the right chemical mix inserted it should cause severe tissue damage. If I walk into a super cold freezer nude, I am not going to be perfectly fine.

Cyro is already idiot proof enough, having some downside is alright.

**Comment by xevonix** [comment] 2015-11-23 02:56
cryo had a mixture of 30 cryo, 30 clonex, 10 alk, 5 rye, 5 dex+, 5 kelo, 5 derma, 5 antitoxin, 5 tricord at the time of the incident.
the cryo tube had also been properly cooled fully in the three or four other times this has happened since i filed this.
there is absolutely no reason for medbay to become even more shitty, considering its a place where people who can easily fuck over everything by not knowing what theyre doing wrong.

**Comment by 9600bauds** [comment] 2015-11-23 03:01
Literally any information about this helps since we haven't been able to reproduce it.
Does it happen consistently? Does it stop happening after a while? Does it happen to one patient, or to everyone? Does it happen with one tube or with both?
Do you have an idea of how much burn damage is applied? Does the cryomix suddenly vanish, or does it just chug it every second?
Have the burns and the cryomix drain happened independently, or do they both happen together?

**Comment by xevonix** [comment] 2015-11-23 03:13
it seems to happen randomly in a singular tube to one person, then the next person can use it just fine. I dont know what causes it, I dont know how to fix it. It fucking sucks it down at like double the speed I think.

**Comment by ghost** [comment] 2016-02-02 10:38
Well, half of this was addressed in #7786 (The cryo being consumed in extreme amounts), but what is causing that burn damage?

**Comment by ghost** [comment] 2016-02-03 12:26
WE JUST DON'T KNOW.

**Closed** 2016-02-03 21:46 UTC
Labels: Bug / Fix, Feature Loss, Needs Moar Testing, ⚠️ OH GOD IT'S LOOSE ⚠️
