### ISSUE TITLE
Socket Wrench fits in toolbelt

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11721] opened 2016-09-02 01:53 UTC
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)

> Revision caaba4b9028ea523f9f42f8a7b331ef64e73644a 
> 
> General description of the issue
> Socket Wrench can now be placed in toolbelt.
> 
> What you expected to happen
> too big too fit
> 
> What actually happened
> OP bullshit
> 
> Steps to reproduce if possible

**Comment by Intigracy** [comment] 2016-09-02 03:54
It doesn't fit in anything else though, not even backpacks.

**Comment by Killette2** [comment] 2016-09-02 08:16
It's special ability being able to always unwrench pipes is bullshit? Maybe if you walk around with magboots causing ZAS

**Comment by jknpj** [comment] 2016-09-02 12:18
@Intigracy 
Can't you use it in the hardsuit tank slot? I'm pretty sure you can.

@Killette2 
I never made ZAS with it and usually only get around 2~5 kpa of whatever is in the pipes to the air

I'm amazed this isn't a feature, because i remember being able to store them in my toolbelt since i started playing as engineer.

**Comment by Intigracy** [comment] 2016-09-02 12:21
It is, he just doesn't like the feature.

**Comment by Kurfursten** [comment] 2016-09-02 12:29
This one took some digging to find. They couldn't always fit in every tool-belt, but @Intigracy a _very_ sneaky change in #9354 by removing max_w_class from tool-belt.

Previously one major difference between a chief belt and a normal belt was that the chief belt could hold larger versions of items as well (foam/full extinguisher instead of mini, enlarged welder instead of normal welder, socket wrench instead of normal wrench). This balance PR got merged in one day without review and no balance tag. No changelog either.

**Comment by Intigracy** [comment] 2016-09-02 12:45
I actually didn't intend to change this.

**Comment by Intigracy** [comment] 2016-09-02 12:50
That PR was intended as a bugfix so if you want it to hold a specific item
without allowing a larger w_class you should be able to.

I wasn't aware until now that it uses typesof for the list.

Thanks for the vote of confidence though pal.

**Comment by Exxion** [comment] 2016-09-02 13:38
I'm like 80% sure I told you it did at one point
If you stick a = at the beginning of the string, it doesn't

**Comment by Kurfursten** [comment] 2016-09-02 14:35
Sorry for doubting you then.

**Comment by Intigracy** [comment] 2016-09-02 17:46
I have a pretty simple fix to this that I'll do when I get home later.

Canholdignoringwclass or whatever the var name is should be referenced when
canonlyhold is, rather than canonlyhold ignoring w_class.

**Comment by Killette2** [comment] 2016-09-02 17:51
So what happens next? We keep this a CE belt only feature, leave it alone, or gut it entirely.

**Comment by jknpj** [comment] 2016-09-02 17:54
CE only seems fine for me. It can already hold the RPD/RCD/Blueprints and other larger items so i see no issue with allowing it to hold more tools. TOOLBELT OF HOLDING WHEN?

**Comment by Intigracy** [comment] 2016-09-02 18:05
And extinguishers?

**Comment by Kurfursten** [comment] 2016-09-02 19:12
Yeah, I'd say return it back to the "old" way of only CE belt can hold the larger items.

Having a really powerful belt is part of what's supposed to get people to actually sign up as CE.

**Comment by Killette2** [comment] 2016-09-02 21:48
People sign up for head roles when they feel like powergaming? Color me surprised!

**Comment by Kurfursten** [comment] 2016-09-02 21:51
In the grim darkness of 2016, incentives are called "powergaming".

**Comment by Killette2** [comment] 2016-09-02 22:11
Well they sure don't sign up for roleplay or responsibility, but there's always that sweet unique gear

**Comment by jknpj** [comment] 2016-09-03 12:11
> People sign up for head roles when they feel like powergaming? Color me surprised!

In this case, autisming, because CEs are pretty much human-shaped mommis.

**Closed as completed** 2016-09-04 17:30 UTC
Labels: Balance, IT'S A FEAAAATUUUUREEEEEEEEE
