### ISSUE TITLE
Space Weeb issues

### ISSUE THREAD

**Issue by SirSkeleto** [d3athrow/vgstation13#21903] opened 2019-02-28 21:54 UTC
#### Description of issue

Spawning in as a chaplain (probably also as a clown or a mime or any role where spawning in has some special thing) still triggers when you pick a weeb, spawning you in as a religious leader with a bible and incense.

Dakimakuras hardly work. They can teleport you 1 tile away into a wall. Not exactly the most useful escape. I'm not certain about this but it also felt like sometimes it just didn't work on being shot.

Most of the weeb powers are extremely clunky and difficult to use. Upon examining the nentendie glove I saw that alt-click did something, and after draining 4 fully charged APCs I had an option ZAP and COOK. Unsure of what either of these did or are supposed to do. Having all 4 powers (upon examination of the code) visible but greyed out and with tooltips of some sort indicating use and required charge might be useful in indicating what you can actually do (especially 'cause there's no wiki page). Also the current method of teleporting behind someone (alt click to TOGGLE) is terrible, and it's very hard to tell whether or not it will work, or what it even does aside from moving you into range. I think use in hand would be better because it's not a used function and it would at least allow for quick use what with hotkeys existing.

#### Difference between expected and actual behavior

i expected space weeb to be not terrible

#### Steps to reproduce

pick space weeb
[qol]

**Comment by Kurfursten** [comment] 2019-02-28 22:00
tl;dnr he didn't read the wiki page, thinks there isn't one, partial duplicate of #21894

Not all of this is bad feedback though, maybe some tooltips can happen when real space ninja comes out

The latejoin thing is part of #21752 and both can be fixed by just making it set MODE

**Closed as completed** 2019-03-05 18:56 UTC
Labels: ❤️ Quality of Life ❤️
