### ISSUE TITLE
Changeling sting DNA/ SE injector

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8196] opened 2016-02-10 10:36 UTC
(WEB REPORT BY: kolith REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

ef413e1efd90d40ca5389a4f21c91aa0ea0d2142 

> General description of the issue
> Chaplain was absolutely messed up disability wise from prayers and stuff, changeling stung people with his SE. Injecting myself with a clean SE I had saved previously of myself.
> 
> What you expected to happen
> I expected the clean SE to rid me of the disabilities from the changeling DNA.
> 
> What actually happened
> It did not remove the disabilities.
> 
> Steps to reproduce if possible
> Have a human with extreme disabilities, and have a changeling take that person's DNA, and use the sting to transfer it to other people.

**Comment by DamianX** [comment] 2017-05-17 16:54
Tested:
Used extract DNA to succ a human with tons of disabilities
Used transformation sting on second human
Used clean SE on second human
second human lost all disabilities

COULD NOT REPRODUCE
CLOSE IT

**Closed as completed** 2017-05-17 19:09 UTC
Labels: Bug / Fix, Exploitable
