### ISSUE TITLE
Defficiency derelict has tiles that look like they're plating but can still be crowbar'd to actual plating

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#13327] opened 2017-01-09 02:11 UTC
`/turf/simulated/floor/plating/airless` + crowbar = `/turf/simulated/floor/airless`
deff probably isnt hte only derelict with this
but it means you cant use floor tiles on these tiles without crowbaring them first even though they look like plating

**Comment by Probe1** [comment] 2017-01-09 03:23
I want to find whoever started this meme and wipe them from the face of the Earth.

**Comment by BobdaBiscuit** [comment] 2017-01-09 10:10
I can confirm that all the derelicts have this issue.

**Comment by Probe1** [comment] 2017-01-12 20:47
Can't reproduce.  Please provide a picture of what tiles are being discussed.

**Comment by uazuaz** [comment] 2017-01-12 23:01
on deff, i found these inside the "derelict singularity engine" zone; they looks just like plating, but if you use a crowbar on them they pop out a tile;

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/21911801/acb5076c-d922-11e6-9c7f-99fe5730a5c3.png)

if you put the tile back on the plating, it will be invisible again;
if i try to examine the floor when the invisible tile is on it, the game freezes for few seconds on my pc; if there is no tile, there is no freeze; it only freezes when examining these "special" floors with a tile on them.
examining the floor shows these icons: without the tile on top, with the tile on bottom; they are never called "plating" like the other plating near them.

![floor](https://cloud.githubusercontent.com/assets/6170726/21911805/b3fdd328-d922-11e6-8d43-0a6c7797a565.png)

**Comment by Exxion** [comment] 2017-01-12 23:24
Ah yes
The freeze on icon bug
Happens because, for some reason or another, it's converting THE ENTIRE GODDAMN ICON FILE to base64 rather than just the one `icon_state`
Happens with fuel on the floor, too, and used to happen with pAIs
I guess it probably happens due to the object having a `null` `icon_state`? Not sure

Also WHY the FUCK are those floors like that?

**Comment by Probe1** [comment] 2017-01-13 00:19
Thank you @uazuaz

**Comment by uazuaz** [comment] 2017-01-13 01:13
no problem, by the way it's the same on meta, i can assume also on box.

![meta](https://cloud.githubusercontent.com/assets/6170726/21914746/8de908b6-d935-11e6-9b05-7274b049fc9c.png)

**Comment by Probe1** [comment] 2017-01-13 02:53
Fwiw as soon as you got me the picture I found all the rest of the sneaky little bastards. I just needed to know exactly which tile to start with.  If I was as smart as sood I'd have just searched for the path./

**Comment by gbasood** [comment] 2017-01-13 21:24
wait why wasn't that the place you STARTED looking

**Closed as completed** 2017-07-21 19:28 UTC
Labels: Bug / Fix, Mapping (Box :baby:), Mapping (Meta :no_mobile_phones:), Mapping (Deff :wastebasket:)
