### ISSUE TITLE
CREDITS DON'T APPEAR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31743] opened 2021-12-29 23:55 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
253a8cf19216f520479ef5331382c396a08a4edd

# Description
NO CREDITS IT JUST ENDS

**Comment by robintime** [comment] 2021-12-30 00:01
you already made this issue at #31725 which is already itself arguably a more descriptive duplicate of #31701. creating multiple reports of the same bug won't make it get fixed any faster, and instead just creates clutter on the github.

**Closed as completed by robintime** 2021-12-30 00:01 UTC
