### ISSUE TITLE
No supermatter shard on Metastation derelict

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11256] opened 2016-08-03 19:14 UTC
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c246201cd4fa9c35fa42145a33488f45b49e72e6 
> 
> General description of the issue
> There's no supermatter shard on the metastation derelict
> 
> What you expected to happen
> Mommi autism zone
> 
> What actually happened
> No supermatter
> 
> Steps to reproduce if possible
> Look for a shard on metastation derelict

**Comment by Kurfursten** [comment] 2016-08-03 19:40
Duplicate of #3420

This should be safe to close

**Closed as completed** 2016-08-03 20:25 UTC
