### ISSUE TITLE
Crew monitoring computer showing deff while on box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7590] opened 2016-01-06 20:23 UTC
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Last round was deff. Now on box the crew monitoring computer shows a map of deff (switching z levels doesn't fix it). Apparently the other paramedic is not affected
> 
> What you expected to happen
> To see the right map
> 
> What actually happened
> I saw a map of deff
> 
> Steps to reproduce if possible
> Not sure

**Comment by Kurfursten** [comment] 2016-01-06 20:45
Partial dupe of #5945

**Closed as completed** 2016-01-06 21:13 UTC
