### ISSUE TITLE
Person has no arms or hands but the sprites still show up when facing sideways

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22467] opened 2019-04-15 23:25 UTC
(WEB REPORT BY: kitfox88 REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
Title
# Steps to Reproduce
Be disarmed, turn sideways
# What you Expected
No arms or hands
# What Actually Happened
MY IMMERSIONS

**Comment by Exxion** [comment] 2019-04-15 23:39
Duplicate of #22223

**Closed as completed by Exxion** 2019-04-15 23:39 UTC
