### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) RCME Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3960] opened 2015-04-17 15:09 UTC
>Revision 
a1d008abaa220a4d351d0db18259d99708dd7766 

>General description of the issue
The RCME immediately kicks out Super Capacitors and Super Matter Bins when they are inserted. However, it still counts them as stocked, meaning that you could for instance repeatedly insert one Super Matter Bin and then replace 3 matter bins with only 1.

As a matter of preference, the RMCE should also display what's inside when examined, or be able to be opened to check inside like a pill collector or gadget bag.

**Comment by Probe1** [comment] 2015-04-17 16:10
duplicate of https://github.com/d3athrow/vgstation13/issues/3955

**Comment by ComicIronic** [comment] 2015-04-17 18:09
Doesn't look like a duplicate. Separate bug.

**Comment by Probe1** [comment] 2015-04-17 20:47
you're correct, I don't know how i misread it that badly but I did.

**Comment by dylanstrategie** [comment] 2015-04-18 18:48
I'll need to check the transfer procs to see just what the fuck is going on in here

**Comment by clusterfack** [comment] 2015-04-19 01:54
I don't even understand the issue report's statement well enough to comment unfortunately. By kick out does he mean its taken out of the list of components or contents set to the ground, or what.

**Comment by Kurfursten** [comment] 2015-04-20 06:57
@clusterfack Read more carefully, the object is placed on the ground BUT remains inside the list of components. Therefore you can repeatedly place a single Matter Bin into the RCME getting it counted several times. Then, at the cost of 0 Matter Bins, you can replace a machine's 3 Matter Bins. Keep the original to show off as a trophy.

**Closed** 2015-04-28 02:39 UTC
Labels: Bug, Needs Moar Testing
