### ISSUE TITLE
wooden tables wont get full refund on deconstruction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17522] opened 2018-02-19 20:34 UTC
(WEB REPORT BY: dacendeth REMOTE: 172.93.109.202:7777)
# Revision
e84eac5dd305b99e6d61f42091f1e7711d587efb

# Description
wooden tables cost 2 wood to make, but when wrenched return 1 wood

**Comment by DamianX** [comment] 2018-02-19 20:37
duplicate of #7840

**Closed as completed by DamianX** 2018-02-19 20:37 UTC
