### ISSUE TITLE
Examine sprites are broken again

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11892] opened 2016-09-15 00:43 UTC
They once again display a tiny naked vox rather than the person you're examining, regardless of whether or not the person in question is a vox.

![ss 2016-09-14 at 08 43 28](https://cloud.githubusercontent.com/assets/8556111/18534692/e94d9434-7abb-11e6-9838-235a3146862c.png)

**Comment by clusterfack** [comment] 2016-09-15 00:44
Oh don't worry, they were never fixed.

**Comment by Exxion** [comment] 2016-09-15 00:45
They're not broken again. They were never fixed since Goonchat.
Also this is a dupe of multiple other issues, one of which is yours

**Comment by Exxion** [comment] 2016-09-15 00:45
Damn it Cluster

**Closed as completed by Exxion** 2016-09-15 00:45 UTC

**Comment by Hoshi-chan** [comment] 2016-09-15 01:10
@Exxion Oh, sorry, they seemed to be working earlier this week. I only noticed them doing this again today, after all this 64x64 nonsense and the code completely breaking earlier.
