### ISSUE TITLE
The protolathe's micro lasers do nothing and can't be upgraded.

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22715] opened 2019-05-01 07:01 UTC
Today I was playing MoMMI, I was upgrading the machines in the nest when I saw that the RPED was only upgrading the manipulators and the matter bins, after that I deconstructed the protolathe and reassembled back but when the manipulators-bins where in place it said it didn't require anything else.

This happened in the box station MoMMI nest.

**Comment by boy2mantwicethefam** [comment] 2019-05-01 10:38
I'll look into it, pretty sure the problem is that they're spawned with new components and I didn't find the bit that determines component parts, because I did search for it and I thought only tampering with component_parts on New() would do something

**Comment by Exxion** [comment] 2019-05-02 20:20
Fixed by #22721

**Closed as completed by Exxion** 2019-05-02 20:20 UTC
