### ISSUE TITLE
box tcomm sat is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8703] opened 2016-03-07 23:26 UTC
(WEB REPORT BY: termedclepe2 REMOTE: 158.69.55.2:7777)
someone decided it be a good idea to make it ghost inaccesible for fuck all reason, but most importantly removed void suits and teleporter from it

I'm guessing it was a copy paste job by your local idiot mapper

**Comment by aceedex** [comment] 2016-03-07 23:29
Void suits and the teleporter are in, but it takes killing about 10 or so russians

**Comment by Imagebard** [comment] 2016-03-07 23:32
>for fuck all reason

Note: It really is fuck all because you can just zoom your vision to see what's inside of it but

**Comment by Ephx1** [comment] 2016-03-07 23:51
It was probably to prevent people from seeing the hazards and preparing beforehand, but like Imagebard said, you can just scrollwheel it up.
Or just click the big "BOXSTATION" button and look that way, really this feature is pointless, especially if you want to see people actually go through it.

**Comment by Probe1** [comment] 2016-03-08 00:07
Its intended.

**Comment by Imagebard** [comment] 2016-03-08 01:24
>Its intended

Yeah but should it be kept?

**Comment by Probe1** [comment] 2016-03-08 02:28
yes, people have an expectation of getting the goonecode to mean we answer GIMME SHIT prayers for once.  

the goonecode being a joke to get before meant we rarely answered Box prayers and it lead to confusion.

it's easy to circumvent the ghost barrier by checking the map but it might stop some players that appreciate a good surprise and don't spoil themselves and min/max by checking the code.

after the first week people stopped teleporting there and being surprised it was a one way trip till they cleared it.

clepes just a bit late to the party here.

**Comment by coldcola** [comment] 2016-03-08 03:04
I'm fairly new but I remember a little while ago all of the things were way easier to get, definitely more fun to do a trip over there with the new setup imo, especially the dismantling and rebuilding of the teleporter hub

**Comment by Imagebard** [comment] 2016-03-08 15:37
@Probe1 
So basically powergamers that scroll up to see what's inside the goonecode sat get a easier time getting the actual thing, and people that play legitimately will have harder time getting it?
I'm voting "remove the barrier" again. This is still counter-intuitive and prevents people form actually seeing the action going in the satellite when someone decides to actually try to beat it, which is the only thing ghosts/observers have going for them.

**Comment by Probe1** [comment] 2016-03-08 17:38
You could also just haunt a guy thats past the barrier.

It's not infallible.  It's just a casual way of keeping people who don't want to be spoiled from it.

**Comment by Probe1** [comment] 2016-04-03 10:40
anyway not a bug

**Comment by Probe1** [comment] 2016-11-29 16:14
still not a bug.

**Comment by Imagebard** [comment] 2016-12-03 19:18
Still retarded

**Comment by Exxion** [comment] 2016-12-03 22:19
Sorry I just woke up and clicked the wrong tag like an idiot

**Comment by DamianX** [comment] 2017-05-17 17:13
not a bug
CLOSE IT

**Closed as completed** 2017-05-17 19:09 UTC
Labels: Mapping (Box :baby:), Discussion
