### ISSUE TITLE
Runtime during initialization 1/4

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#14019] opened 2017-02-15 05:33 UTC
`[21:28:56] Runtime in uplinks.dm, line 25: Cannot read null.uplink_welcome
proc name: initialize (/obj/item/device/uplink/initialize)
src: Hidden Uplink. (/obj/item/device/uplink/hidden)
src.loc: the uplink (/obj/item/weapon/implant/uplink)
call stack:
Hidden Uplink. (/obj/item/device/uplink/hidden): initialize()
Objects (/datum/subsystem/obj): Initialize(197296)
Master (/datum/controller/master): Setup()
world: New()`

First runtime encountered during init.  All runtimes occurred one after another on the live server, at the same init.

**Comment by gbasood** [comment] 2017-02-15 20:54
This happens because *SOMEONE* MAPPED IN SHIT IN CENTCOMM AND DIDNT CHECK RUNTIMES AND IT GOT MERGED ANYWAYS

Stuff that shouldn't exist before the gamemode is set does and it runtimes because it doesn't know what to do with itself

Also, duplicate of an issue I made

**Comment by Intigracy** [comment] 2017-02-15 20:58
Needs to use Initialize()

**Closed as completed** 2017-02-15 20:58 UTC
Labels: Runtime Log

**Comment by gbasood** [comment] 2017-02-15 23:57
it does
that's the problem
