### ISSUE TITLE
(WEB REPORT BY: kitfox88 REMOTE: 198.245.63.50:7777) Solar Panel Autotracking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3468] opened 2015-03-18 23:21 UTC
&gt;Revision 110a86ae707512152f09ea15632c2914f5c62929

&gt;Solar panels do not seem to auto-track the sun at times.

&gt;Tracking

&gt;Not tracking

&gt;Wire the solars and fiddle with the control panel for them I guess?

**Comment by BestName** [comment] 2015-03-19 10:16
Duplicate of #3398

**Comment by ComicIronic** [comment] 2015-03-19 17:27
Check the issue base.

**Closed by ComicIronic** 2015-03-19 17:27 UTC
