### ISSUE TITLE
Burger duplication

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10249] opened 2016-05-28 08:37 UTC
(WEB REPORT BY: landshark4444 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Deep frying spaghetti with burgers creates an addtional burger
> 
> What you expected to happen
> when putting spaghetti and burger together in the deep fryer it should spit out deep fried burger spaghetti
> 
> What actually happened
> deep fryer spat out deep fried bruger spaghetti and an additional un fried burger
> 
> Steps to reproduce if possible
> - make boiled spaghetti
> - add a burger to it
> - deep fry it

**Comment by Killette2** [comment] 2016-05-28 11:01
Pretty sure this was posted, but with pizzas.

**Comment by FudgePucker** [comment] 2016-05-28 14:27
USA USA USA

**Comment by ComicIronic** [comment] 2016-05-28 15:34
Duplicate of #10062

**Closed as completed by ComicIronic** 2016-05-28 15:34 UTC
