### ISSUE TITLE
I DIE BUT I CAN REJOIN

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34424] opened 2023-06-20 19:15 UTC
(WEB REPORT BY: loveender REMOTE: 206.221.180.138:7777)
# Revision
684c5eb98f4006c575b52cd61003e0c32bce99ed

# Description
I died, I obsed for a bit then I lagged out the game, reloaded and can now rejoin the game
# Steps to Reproduce
I was dunked into a polyacid tube, then a doctor sawed my head off.
I obsed for a few minutes. Then there was this red crystal that had something to do with science. Apparently it was printing more clones of this guy, so I clicked it. My game lagged out while in obs.
I closed the client and came back in and now I can rejoin
# What you Expected
Frens to hug me and tell me I matter
# What Actually Happened
Everyone hates me

**Comment by nervere** [comment] 2023-06-20 20:12
closing as duplicate of #34425

**Closed as completed by nervere** 2023-06-20 20:12 UTC
