### ISSUE TITLE
Magic Missle is shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9953] opened 2016-05-07 05:46 UTC
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I am reporting this as a bug because that's what I consider it, it's not even a feature, magic missle has been nerfed so hard it's literally shit now.

Fuck return it to normal you faggots.

**Comment by Exxion** [comment] 2016-05-07 05:51
> Magic Missile is shit
> It's a stun that, with enough upgrades, is also a one-hit kill

**Comment by SangriaMonkey** [comment] 2016-05-07 06:28
> not 5x guns every round

nerd

**Comment by Kurfursten** [comment] 2016-05-07 06:44
Duplicate of #4416, this is safe to close

**Comment by clusterfack** [comment] 2016-05-07 11:52
Nerfed how? Nobody has nerfed it except to take away the AOE damage from it.

**Comment by Konater** [comment] 2016-05-07 13:06
It's unreliable as fuck when it comes to stunning people, needs more testing
there's a reason no one takes it any more it's buggy like mind swap and blink

**Comment by CptWad** [comment] 2016-05-08 18:22
Shit dude just include more stun spells
how about one that throws everyone on the ground, like a supermagboots spell
anyone with magboots all the way up will break their feet
only effects 5 tiles away from you and you cant move a second after casting it

**Comment by Konater** [comment] 2016-05-27 16:02
I believe the problem with magic missile is that it's making people sleep instead of stunning them. Before magic missile used to be great at stunning groups of people instantly but sleep has a delay. This is bad for two reasons, one being that the guy hit has time to shoot or attack a few times before they go down in a game where one shot can end you. The second being that the delay means that when using it against groups the person closest that is hit ends up eating all of the projectiles because they do not go down instantly. There's amt_stunned and amt_paralyse in the magic missile both set to three, removing amt_paralyse just makes magic missile do nothing so amt_stunned is busted.

Magic missile.dm
`amt_stunned = 3`

Targeted.dm
`/spell/targeted/proc/apply_spell_damage(mob/living/target)`
`target.Stun(amt_stunned)`

**Comment by Iamgoofball** [comment] 2016-05-27 17:11
oh

okay so Stun() doesn't make you fall down, you're just stuck in place

Weaken() makes you fall down

swap it for Weaken()

**Comment by ComicIronic** [comment] 2016-05-27 17:14
Yeah, amt_stunned isn't busted.

**Comment by Konater** [comment] 2016-05-27 17:15
why is stun not a stun reeeeeeeeee

**Comment by clusterfack** [comment] 2016-05-27 17:17
I don't understand did this change at some point or what?

**Comment by Konater** [comment] 2016-05-27 17:23
no idea when but it must have because I remember it stunning people

**Comment by clusterfack** [comment] 2016-05-27 17:33
Looks like it still does to me

**Comment by ComicIronic** [comment] 2016-05-27 17:40
Stun IS a stun, you cuck. What you call a stun is actually a Weaken.

**Comment by Iamgoofball** [comment] 2016-05-27 17:42
what comic said

we really need to unify this shit we have 3 procs that all do the same thing

**Comment by Exxion** [comment] 2016-05-27 20:09
Notably, while `Stun()` doesn't make you fall down, it DOES prevent you from getting up if you fall down for another reason

**Comment by gbasood** [comment] 2017-02-04 15:39
oooold
p sure magic missile has changed since then too

**Closed as completed by gbasood** 2017-02-04 15:39 UTC
Labels: Balance
