### ISSUE TITLE
Swiss Army Knife wrench can't unwrench tables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35773] opened 2024-01-14 05:08 UTC
(WEB REPORT BY: eneocho REMOTE: 209.222.101.3:7777)
# Revision
e5fc481e43d04e0367cf7aa3a9700fd373c990ce

# Description
Title
# Steps to Reproduce
Get SAK
deploy wrench
try to unwrench wooden table
fail
get regular wrench
it works!
# What you Expected
trusty swiss army knife
# What Actually Happened
it was a chinese army knife

**Comment by jwhitak** [comment] 2024-01-14 05:11
Duplicate of #35690. Fixed in #35772.

**Closed as completed** 2024-01-14 08:38 UTC
