### ISSUE TITLE
cuffing a briefcase to yourself(and removing it) makes the cuffs permanently glued

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34221] opened 2023-04-14 22:19 UTC
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
9106c7e23d9d71f5e453fba894e4a1bb85521a5a

That's some handcuffs. They are small
It's stuck to your hands!

**Comment by kacurasuo** [comment] 2023-04-15 00:28
duplicate of #33442

**Closed as not planned** 2023-04-15 02:29 UTC
