### ISSUE TITLE
facemask items being deleted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26980] opened 2020-06-29 16:16 UTC
(WEB REPORT BY: westbend REMOTE: 206.221.180.138:7777)
# Revision
cbfe7e4e47fcbc5ba777dfdd7d0bc1d94ddeb64a

# Description
Facemask item worn being deleted when I use a hotkey to equip a new facemask item.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment] 2020-06-29 16:40
if it's lost from a cig or a mask of change you can get the mask back by minimizing your gear window and clicking the oddly floating mask item.

**Comment by SonixApache** [comment] 2020-06-29 22:33
another dupe of #26768

**Closed as completed** 2020-06-30 01:20 UTC
