### ISSUE TITLE
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11382] opened 2016-08-10 23:39 UTC
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

**Comment by Intigracy** [comment] 2016-08-10 23:40
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

**Comment by Exxion** [comment] 2016-08-10 23:41
It's supposed to drop the controller, but doesn't always

**Comment by Intigracy** [comment] 2016-08-10 23:42
you mean always doesn't

**Comment by Exxion** [comment] 2016-08-10 23:42
I do not, because it sometimes does

**Comment by Intigracy** [comment] 2016-08-10 23:44
Is there any pattern to it?

all access
access required
ROUNDSTART versions of the above
BUILT MIDROUND versions of the above

**Comment by Exxion** [comment] 2016-08-10 23:46
I assume so, but I don't know exactly
I'll test it a bit

Also, this reminded me of a separate bug: Constructed windoors entirely ignore the access settings on the controller

**Comment by Exxion** [comment] 2016-08-10 23:53
This is odd.
I've definitely seen windoors drop electronics and there was at least one PR to make them do so, but I can't get it to actually happen

**Comment by Intigracy** [comment] 2016-08-10 23:55
#7960 was supposed to fix it but @clusterfack is a big phony

dupe of #9965 btw (which appeared after the above PR)

**Comment by Megamaw** [comment] 2016-08-12 20:10
this is unreasonably hard for me to clean up and reconstruct as it is, as a janitor, for something so easily broken by shitcurity/antags/etc.

fix it ASAP.

**Comment by clusterfack** [comment] 2016-09-06 06:34
Dupe

**Closed as completed by clusterfack** 2016-09-06 06:34 UTC
Labels: Bug / Fix
