### ISSUE TITLE
Map editor is completely screwed up

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#11297] opened 2016-08-05 10:48 UTC
@DrCelt 

![](http://puu.sh/qqCkM/4bacf098cc.png)
# **_PLANE ISSUES**_
- Tables and doors are drawn under turfs
- **Areas are drawn under turfs!!!**

:airplane: :office: :office: :fire:
# **_64x64/BYOND ISSUES**_
- When editing maps, updating icon files of any object on the map and hitting the update button ( http://puu.sh/qqDZa/4f25a3831c.png ) causes all objects with the updated icons to become invisible
- After loading big maps (like tgstation.dmm), half of the icons are simply invisible

![](http://puu.sh/qqEFN/1800c8f85a.png)

**Comment by Exxion** [comment] 2016-08-05 11:03
Well I guess it's also BYOND's fault for not using planes properly in the map editor

**Comment by Exxion** [comment] 2016-08-05 11:04
Wait hold on
Only doors and tables?
That might not actually be a planes thing
But the areas being drawn under turfs probably is

Are the doors and tables drawn under the turfs, or just not drawn at all?

**Comment by unid15** [comment] 2016-08-05 11:40
They're drawn underneath the turfs

map editor is ~~barely~~ NOT usable in its current state

**Comment by Faptastic** [comment] 2016-08-05 13:31
I thought that was just me, nice to know I wasn't going crazy.
Mine was mostly airlocks and stuff, work fine in game but can't see them in the editor, invisible. Screwing with the visible layers worked for a while.

**Comment by unid15** [comment] 2016-08-05 13:32
Are large maps like tgstation.dmm screwed up for you too?

**Comment by Faptastic** [comment] 2016-08-05 13:35
The entire codebase is, every single map it happens on.  I checked other codebases I had on file and they're fine.
I pulled ~25 new merges I was missing down yesterday and it was borked after, this includes my custom away missions. A recent change has done it since I haven't updated my byond software in ages, latest version anyway.

**Comment by Intigracy** [comment] 2016-08-05 16:20
As if people didn't have enough issues with the map editor already.

**Comment by unid15** [comment] 2016-08-05 16:20
At least it worked before the 64x64 stuff

**Comment by Intigracy** [comment] 2016-08-05 16:28
This is a 64x64 caused issue.

t. guy who checked out to the commit right before 64x64 was merged (which was after planes)

**Comment by Intigracy** [comment] 2016-08-05 16:58
caused by #11183

commit hunting sucks

**Comment by unid15** [comment] 2016-08-05 17:00
The doors / tables layering issues were caused by #11183 

And the other issues (like the map editor not displaying half of the icons on big maps) were caused by https://github.com/d3athrow/vgstation13/commit/6edf0208ac8e4bea5b596de53e674e0f84eaef6e (the 64x64 sprites commit)

**Comment by ghost** [comment] 2016-08-07 05:01
thanks byond

**Closed as completed** 2016-08-09 12:53 UTC
Labels: T-Thanks BYOND
