### ISSUE TITLE
If you die in the holodeck you die in the real world

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19166] opened 2018-08-07 20:32 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5e4172d0f2bc43e30b54388a61e34609202ae441

# Description

Getting bludgeoned to death with holographic Energy Swords actually kills you.
# Steps to Reproduce

Start sword fight with holopeople, lose.
# What you Expected

To not die 
# What Actually Happened

Died.

Please do not patch this to make you actually die IRL.

**Comment by Pathid** [comment] 2018-08-07 20:36
Not a bug if the holodeck was emagged.

**Comment by Kurfursten** [comment] 2018-08-07 20:39
This was not caused by the holodeck eswords, it was from the other holoman (punching...?)

**Comment by SGuivenne** [comment] 2018-08-07 20:49
Ah, it may have just been conventional holo murder.  Huh.

**Comment by brndd** [comment] 2018-08-10 16:40
In all likelihood not a bug, at least not a Roidstation one. The holodeck issues on Roid should all be fixed now.

**Closed as completed** 2018-08-10 22:55 UTC

**Comment by Exxion** [comment] 2018-08-10 22:56
The holodeck is loaded from a separate mapfile (I think), so the only way this could happen (placing real eswords instead of holo ones) wouldn't be confined to a specific map.
Also, Kurf said what was going on here.
