### ISSUE TITLE
All Mini-Map-Based Computer UI's are Fucked

### ISSUE THREAD

**Issue by Joltron** [d3athrow/vgstation13#8177] opened 2016-02-09 04:23 UTC
There's some kind of drift in the mini-maps.  Mousing over icons still yields correct coordinates, but the background is in the wrong position.  This is true for crew monitors and Advanced Security Cameras.

http://i.imgur.com/K78ZpDT.png

BYOND version 509.1318

**Comment by Exxion** [comment] 2016-02-09 04:33
That hyperlink is broken somehow

And this is a duplicate issue of something
It's because we made Box way bigger but forgot to fuck with the minimaps

**Comment by Joltron** [comment] 2016-02-09 04:36
So other than making it way easier to run out of air now floating through vastly empty space and breaking systems extremely helpful for security and medbay, did making Box's z-levels bigger actually achieve anything?

**Comment by 9600bauds** [comment] 2016-02-09 04:37
Dupe of #8157 I guess

**Comment by clusterfack** [comment] 2016-02-09 04:38
What a silly attitude you have

**Closed as completed by 9600bauds** 2016-02-09 04:38 UTC

**Comment by Exxion** [comment] 2016-02-09 05:02
Yes. It made it actually possible to add more shit. The map was basically full.
Also running out of air from a proper oxygen tank is nigh impossible under any circumstances
