### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) SME room fucked.(Map issue Box and Meta)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3806] opened 2015-04-07 04:37 UTC
>Revision (Should be above if you're viewing this from ingame!)
1344bc1

>General description of the issue
SME chamber "leaks"
In other words
FIRE OH GOD FIRE IT BURNS.

>What you expected to happen
A working sme

>What actually happened
Fire.

>Steps to reproduce if possible
Set up the SME on box or meta.
Fire.

Have we started the fire?
Damage Control: It rises.

**Comment by clusterfack** [comment] 2015-04-07 04:46
Duplicate of #3243

**Closed by clusterfack** 2015-04-07 04:46 UTC
