### ISSUE TITLE
Unable to get up.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8671] opened 2016-03-06 04:12 UTC
(WEB REPORT BY: boosterrooster REMOTE: 158.69.55.2:7777)
After being attacked by a slime, you are sometimes unable to get up but still move and interact. Holding any item causes you to lose them. 

To be able to get up after you are attacked by slimes. Babys if it means anything.

Get hurt and jumped on by a baby slime while it is hungry and you can go into this state.

**Comment by 9600bauds** [comment] 2016-03-06 04:27
I just don't know.

**Comment by Exxion** [comment] 2016-03-06 04:39
Clone damage to the legs. I do not believe this is a bug.

**Comment by 9600bauds** [comment] 2016-03-06 04:44
Did you still have clone damage at the point where you couldn't get up?

**Comment by Exxion** [comment] 2016-03-06 04:46
I believe this is the same guy complaining about it in the thread, and he did not mention anything about getting it fixed

**Comment by clusterfack** [comment] 2016-03-06 04:48
>but still move and interact

That's the problem, it's something with clone damage that does it (traumatic shock)

**Comment by Exxion** [comment] 2016-03-06 04:50
We really do not need to make slimes even more deadly right now by making them immobilize you too

**Comment by clusterfack** [comment] 2016-03-06 04:58
I'd like to reproduce this bug someday but I've never been able to do it by myself, pretty frustrating.

**Comment by AutismSpider** [comment] 2016-03-06 04:58
its the clone damage slime's do if they hit or try to eat you by hit they go for the legs and do clone damage to it.

**Comment by 9600bauds** [comment] 2016-03-06 04:59
> its the clone damage 

Yeah we've already heard this a hundred times but nobody has been able to reproduce it yet

**Comment by Exxion** [comment] 2016-03-06 04:59
It happens all the time

**Comment by 9600bauds** [comment] 2016-03-06 04:59
Couldn't reproduce =/= Doesn't happen

**Comment by clusterfack** [comment] 2016-03-06 05:05
Under a test scenario, we can't intentionally cause this to happen and view variables to see what is wrong.

If we could this would have been fixed a hundred times over already.

**Comment by 9600bauds** [comment] 2016-03-06 05:06
After doing some varediting I'm 95% sure this is caused by clonedamage deformed legs still letting you walk

**Comment by clusterfack** [comment] 2016-03-06 05:06
One of the mysteries is that people saying hurting themselves fixes it, which has always made me personally believe its a bug with weakened, but once again, couldn't reproduce to test it.

**Comment by clusterfack** [comment] 2016-03-06 05:13
However bauds is correct it could also be external organ damage since this code from canmove
```
	else if(isUnconscious() || weakened || paralysis || resting)
		stop_pulling()
		lying = 1
		canmove = 0
	else if(stunned)
//		lying = 0
		canmove = 0
	else if(captured)
		anchored = 1
		canmove = 0
		lying = 0
	else
		lying = !can_stand
		canmove = has_limbs
```

The icons are only regenerated if lying changes, however canmove can be set to 1. Therefore if a person is weakened, (thus lying is set to 1), then they cease to be weakened (thus lying is set to can stand which could also be 1 if it there was a problem with their organs) and canmove was reset to 1 from 
```
	can_stand = (canstand_l && canstand_r)
	has_limbs = hasleg_l || hasleg_r || hasarm_l || hasarm_r
```
Then it could be that canmove is set to 1 (they can move), lying is set to 1 (they appear lying down) and icons stay in the lying format.

**Comment by clusterfack** [comment] 2016-03-06 05:15
Which would theoretically be fixed by checking can_stand in the earliest bracket and setting lying to 0 in the else.

**Comment by mrpain666** [comment] 2016-03-06 05:15
If it helps any I tried to rejuvenate him and he still wouldnt get up

**Comment by clusterfack** [comment] 2016-03-06 05:15
But, again, no way to test to see if it works.

**Comment by clusterfack** [comment] 2016-03-06 05:15
No mrpain666, what would help would be if you checked his variables, organs, lying, canmove, weakened.

**Comment by 9600bauds** [comment] 2016-03-06 05:19
Wouldn't this also be the case for someone with a missing leg, for example?

**Comment by clusterfack** [comment] 2016-03-06 05:23
I believe, if my assumptions are correct that what I have described as a theoretical cause could only happen in the following scenario:

1. A person triggers this check in update_canmove
```
isUnconscious() || weakened || paralysis || resting
```
2. Afterwards their can_stand is set to 0
3. A person ceases triggering this check
```
isUnconscious() || weakened || paralysis || resting
```
4. Update_canmove is called again with can_stand set to 0
5. This triggers this else portion of the code
```
    else
        lying = !can_stand
        canmove = has_limbs
```
Which sets lying = 1, canmove = 1, and doesn't update icons because lying_prev = lying.

**Comment by clusterfack** [comment] 2016-03-06 05:24
Wow github way to FUCK up the numbering

**Comment by mrpain666** [comment] 2016-03-06 05:25
Ill check that next time I see this happen, I didnt know this was an old bug we had problems identifying.

**Comment by clusterfack** [comment] 2016-03-06 05:30
Can anyone think of a reason that a person with can_stand = 0 should be able to move? If not we could simply move the can_stand check into 
```
isUnconscious() || weakened || paralysis || resting || !can_stand
```

**Comment by 9600bauds** [comment] 2016-03-06 05:37
I guess if you're missing both legs you could crawl?

**Comment by clusterfack** [comment] 2016-03-06 05:38
Having done that bit of research thanks to you @9600bauds, I would have to estimate looking for the earliest issue related to this, along with the commits made in that time in relevant code
https://github.com/d3athrow/vgstation13/commit/742d3485075b3241e99997b63eff90d42c28b0d1#diff-5d4b1bd11a3ea50a097e83cf174bf730R203
That this change is what caused the bugs we currently have

**Comment by 9600bauds** [comment] 2016-03-06 05:39
Ah yes, the good ol' "layered stacks of bugs where something not working at all covered up the fact that it was bugged anyways"

**Comment by clusterfack** [comment] 2016-03-06 05:40
With this being the first issue I could find related to the topic, just a few days later 
https://github.com/d3athrow/vgstation13/issues/6029

**Comment by clusterfack** [comment] 2016-03-06 05:44
Anyway all this connected evidence makes me pretty sure that these connections are the cause of the bug, so I'll make a PR to patch it out.

**Closed as completed** 2016-03-06 06:33 UTC
