### ISSUE TITLE
Cannot Wear Any Gloves When You Have One Arm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16776] opened 2017-12-14 04:15 UTC
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)
# Revision
5ccc46034e0b2da362b0865fb4a4d10d9df6f732

# Description
Okay I know this probably isn't so much a bug as a """"feature"""", but let's be real: losing one arm and magically having your other glove fall off, or not being able to use one of the two gloves that you have, is absurd.
# Steps to Reproduce
1. Have one arm.
2. Try to wear gloves. You can't. Any gloves.

# What you Expected
Able to wear gloves.

# What Actually Happened
Can't wear gloves.

**Comment by MadmanMartian** [comment] 2017-12-14 04:35
all this is telling me is that we need two glove slots

**Comment by MadmanMartian** [comment] 2017-12-14 04:35
Maybe we should have two glove slots?

**Comment by Cyadox** [comment] 2017-12-14 04:51
@MadmanMartian You would think thats a good idea, but where do you stop? Not only that, but we would have to add code to determine which hand is active when calculating shock damage, materials left for evidence, etc.

We should just change the equip check to look for at least one arm.

**Comment by Killette2** [comment] 2017-12-14 05:46
what about putting gloves on top of other gloves while we're at it?

**Comment by TheFriggenSawbones** [comment] 2017-12-14 08:07
they're PAIRS of GLOVES

**Comment by DamianX** [comment] 2017-12-14 08:38
golly gee, I have two gloves but only one hand
guess I'm not wearing gloves today

**Comment by Killette2** [comment] 2017-12-14 08:42
You only get the outfit bonus from wearing both

**Comment by Hugh-G-Rection** [comment] 2017-12-22 15:35
Just wanted to mention we already have code that determines active hand in shock damage. Arm borer with shock immunity only gives you shock immunity in that particular hand, not the other one.

**Comment by ShiftyRail** [comment] 2019-06-19 19:19
Dupe of #13312

**Closed as completed by ShiftyRail** 2019-06-19 19:19 UTC
Labels: Feature Request, IT'S A FEAAAATUUUUREEEEEEEEE
