### ISSUE TITLE
Detective Noir Vision never goes away by itself

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#19569] opened 2018-09-02 18:23 UTC
I've had players report to me that after drinking some Detective Coffee (premade, or as Coffee and Whiskey) the Noir Vision matrix would never go away.

Is that intended?

**Comment by Kammerjunk** [comment] 2018-09-02 18:27
It doesn't even go away if you're dead
I'd shoot for 'no'

**Comment by DeityLink** [comment] 2018-09-02 18:28
You can "cure" players affected by the bug by resetting their client's color var.

**Comment by kilozombie** [comment] 2018-09-02 18:38
Same thing happens for grue vision. Death doesn't fix it, nor does being put into another body.

**Comment by Caboozles** [comment] 2018-09-02 19:53
I got Noir as a genetic defect a few days ago from being cloned, and nothing fixed it, not copious amounts of rye or death and being cloned

Seems like it might be problem with the code itself.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment] 2018-09-02 20:27
Dupe of https://github.com/vgstation-coders/vgstation13/issues/19569 and https://github.com/vgstation-coders/vgstation13/issues/12080#issuecomment-412379122 and https://github.com/vgstation-coders/vgstation13/issues/18491 and related to https://github.com/vgstation-coders/vgstation13/issues/19280#issuecomment-412379104
is fixed by relogging and caused by animate() not playing nice anymore for some reason

**Comment by Kurfursten** [comment] 2019-01-01 14:45
@Exxion This was fixed in #20252

**Closed as completed** 2019-01-01 19:31 UTC
Labels: Bug / Fix
