### ISSUE TITLE
Feat Requests: Beckon Emote, Trade Window discounts affect all traders in round

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30814] opened 2021-09-20 05:22 UTC
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
make it happen!

**Comment by Kurfursten** [comment] 2021-09-20 05:25
duplicate of #30793

**Closed as completed by Kurfursten** 2021-09-20 05:25 UTC
