### ISSUE TITLE
Hivehand Cuases ED bots to arrest

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8370] opened 2016-02-19 05:56 UTC
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)
Not sure if this is intended but, considering you cant put away a hivehand it seems like it may not be.

**Comment by Shadowmech88** [comment] 2016-02-19 06:02
This is somewhat of a predicament.
On one hand, the Hivehand is a weapon, and a dangerous one at that. An ED would be justified in arresting for it. On the other hand, it can't be concealed.

I'm inclined to say that this is [Not a Bug] and that if you've got a Hivehand and there are EDs about, you'd better either get a weapons permit on your ID, or make a good effort to avoid the EDs.

**Comment by Exxion** [comment] 2016-02-19 06:23
Yeah, I'm with you
You turn your hand into a gun, you face the consequences

**Comment by AutismSpider** [comment] 2016-02-19 07:15
its a gun get weapon permit or chop claw off

**Comment by ghost** [comment] 2016-02-19 07:17
Not a bug

**Comment by Imagebard** [comment] 2016-02-19 14:36
>Needs Final Decision

Who sends the final decision? Player Majority?
I'm on the "not a bug" side of this, by the way.

**Comment by PJB3005** [comment] 2016-02-19 14:38
Pomf / headmins

**Comment by Probe1** [comment] 2016-02-19 20:10
Considering Golfer is alleged to have murdered several people as a non antag in medbay last night with a hivehand I'm pretty sure you can close this now.

**Comment by Exxion** [comment] 2016-02-19 20:11
And every third round someone attacks Pun Pun with it and won't stop when I ask

**Closed as completed** 2016-02-19 20:20 UTC
Labels: IT'S A FEAAAATUUUUREEEEEEEEE
