### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Injecting a nymph with SE makes them invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4954] opened 2015-06-13 16:04 UTC
>Revision (Should be above if you're viewing this from ingame!)
0bb8b9f45d34c5a76ee6a8c6486b799550365f7b

>General description of the issue
Guy injected me with a Clean? SE, it blacks out my screen and i have to rejoin, once im back I see that I am invisible and cannot move. I am apprently still a diona nymph.

>What you expected to happen
Make me a grown diona or a human.

>What actually happened
Made the game unplayable as I cannot move or see myself.

>Steps to reproduce if possible
1. grab diona nymph
2. inject with Clean SE
3. Watch as their round is fucked.

**Comment by clusterfack** [comment] 2015-11-22 03:53
I tried to reproduce this but it did not occur, closing due to web report conventions

**Closed by clusterfack** 2015-11-22 03:53 UTC
Labels: Bug, Unable To Reproduce
