### ISSUE TITLE
(WEB REPORT BY: qbertnorf REMOTE: 198.245.63.50:7777) Condiment Bottle Injection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3726] opened 2015-04-03 14:25 UTC
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

Condiment Bottles treat mobs like normal contains as well as mobs, so you end up with situations like

"Keziah Christopher attempts to feed you Pepper Mill
You transfer 50 units of the condiment to Axe Effect."

(Also the message is wrong, as I was feeding him the pepper)

This means salt/pepper mills are 50 unit autoinjectors at present.

**Comment by dylanstrategie** [comment] 2015-04-03 17:45
Fix to drinks need to be transfered to condiment bottles, and that's odd because the normal transfer_rate for pepper mills and salt shakers is 1

Also that message will need a bit of snowflake coding since condiments are supposed to be drinkable

**Comment by NigglyWiggly** [comment] 2015-04-03 17:47
You can drink them
You just have to click on yourself and transfer the reagent into yourself, with the same silly wording

**Comment by MusgardTiger** [comment] 2015-04-17 14:15
This needs fixing.

**Comment by Scottzar** [comment] 2015-04-20 11:19
Reporter here:
Update: this is indeed instant on monkeys and people in rigsuits, although a delay was seen when I was testing this tiger, and has no range checks of any kind; I can transfer reagents to people across the room in rigsuits instantly with any reagent I want.

Again, as far as I can tell, the problem is that while the check for mobs works fine, the check to see if you can transfer reagents to containers checks neither distance nor what type the container is.

If this still isn't fixed in a week I'll probably try to fix it, but it should be pretty easy to fix (since it is literally just a missing check) and it is extremely gamebreaking.

**Closed** 2015-04-22 03:48 UTC
Labels: Bug
