### ISSUE TITLE
Foam fire extinguisher is broken as hell

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#2489] opened 2015-01-10 01:39 UTC
The foam fire extinguisher no longer puts out fires and doesn't cool rooms. Also, no matter what you put into the extinguisher, only the default foam comes out.
This is not a good thing

**Comment by d3athrow** [comment] 2015-01-10 01:43
i bet dylan did this.

**Comment by NigglyWiggly** [comment] 2015-01-10 01:46
I'll probably blame it on him regardless

**Comment by d3athrow** [comment] 2015-01-10 01:48
when was the last time you remember it working properly

**Comment by NigglyWiggly** [comment] 2015-01-10 01:50
I haven't used one in a while, but I first started seeing people complaining about them pretty recently, probably within two weeks or so

**Comment by d3athrow** [comment] 2015-01-10 02:43
Closing this as its a duplicate of #2459

**Closed by d3athrow** 2015-01-10 02:43 UTC
Labels: Bug
