### ISSUE TITLE
Diona plants never grow and always die

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3182] opened 2015-02-22 19:26 UTC
Diona plants now never grow up and will disappear before maturation. Not sure if related to bees.

**Comment by d3athrow** [comment] 2015-02-22 20:12
Double what

**Comment by CptWad** [comment] 2015-02-22 21:18
Usually lumens is the culprit. Check the tray lumens if its under or over 8 lumens

**Comment by 9600bauds** [comment] 2015-02-22 23:27
Disappear as in poof it's gone, or die before maturation?

**Comment by TermedClepe** [comment] 2015-02-23 03:47
They just reverted to empty trays without any indication that they were unhealthy. I'm pretty sure they were lit properly, I suspect it happened the moment bees improved them.

**Comment by clusterfack** [comment] 2015-04-25 17:08
Duplicate of the reference above, (its also explained better there)

**Closed by clusterfack** 2015-04-25 17:08 UTC
Labels: Needs Moar Testing
