### ISSUE TITLE
Snaxi - ZAS Hell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28387] opened 2020-12-15 03:19 UTC
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
25c56a9142ea36c09f8e8a1e0b9bcda5f169a7f1

# Description
Warm rooms or cabins that open directly to the cold surface cause massive pressure differentials which suck everything out of the room whenever you open a door. If I turn the heat on in my house, my liquor collection doesn't fall off the table.

# Steps to Reproduce
1. Build and heat the ghetto bar.
2. Open a door.
3. Suffer as everything not bolted down flies out the door.

# What you Expected
The room to cool down slightly.

# What Actually Happened
The room cooled down and every drink on my bar was flown outside.

**Comment by Exxion** [comment] 2020-12-15 03:35
So leave a door open while the room is heating up
This is just how pressure works
Could be a problem if the heater can't keep up with the heat loss from an open door though

**Comment by Kurfursten** [comment] 2020-12-15 03:36
I wasn't able to get much out of this in reproducing on live and I bwoinked west to try and ask him about conditions but he wasn't responsive. I was able to get some papers to move 1 tile by overheating a room to 50C and then opening it directly into the heavy storm.

I don't think this is a major concern - add a mud room to your cabin build. Opening your door to a snowstorm does in fact cause things to move a tiny bit.

**Comment by Exxion** [comment] 2020-12-15 03:39
You can also add a passive vent inside -> passive gate -> passive vent outside if you can get the parts

**Comment by Kurfursten** [comment] 2020-12-15 03:44
He messaged me on Discord and said that you can get ZAS'd while building because of putting down new decks. We should do more to inherit the pre-existing atmosphere with turfs if possible. This would be a good QOL change.

**Comment by Exxion** [comment] 2020-12-15 03:55
Yeah, that's been requested for years but for some reason nobody's done it yet. Atmosphere is transferred over if the old turf is simulated, but not if it's unsimulated. I might be missing something but can't think of a particular technical reason it would be harder to implement for unsim turfs.

**Closed as completed** 2020-12-22 11:03 UTC
