### ISSUE TITLE
Cryo therapy is bad for Borers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19646] opened 2018-09-10 00:47 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
62c2da231743709d56deff02086f1c47f79c1dec

# Description

Cryoing yourself as a borer generally breaks everything, makes you deaf, and generally break everything by convincing the game you are comatose 
# Steps to Reproduce

Be borer, enter active cryo.
# What you Expected

Memes
# What Actually Happened

Different shittier memes

**Comment by SGuivenne** [comment] 2018-09-10 01:05
Apparently this fucks it so bad admin rejuvinate doesn't actually fix it.

**Comment by Dacendeth** [comment] 2018-09-10 01:33
if an admin injected you with that special admin chem it might have fixed it, rejuv doesnt work well on humans coming out of cryo either.

**Comment by Kurfursten** [comment] 2018-09-10 01:52
This is a duplicate of #18953

Explanation of what's happening can be read there

**Closed as completed** 2018-09-10 09:00 UTC
Labels: Oversight
