### ISSUE TITLE
Service Borg Zippo Lighter Module Does not work (in non space, normal oxygenated environments)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15945] opened 2017-09-11 01:32 UTC
(WEB REPORT BY: anglosphere REMOTE: 172.93.109.202:7777)
# Revision
ea66db2662d0c39bd30bc835a7af603470016d3e

# Description
The Zippo Lighter Module does not work. It will not produce a flame under expected (normal atmosphere) conditions.
# Steps to Reproduce
Become Service Borg
Select Zippo lighter
Attempt to activate it

# What you Expected
The lighter to produce a flame that can be used to ignite cigs/cigars/paper/etc
# What Actually Happened
"You try to light Zippo lighter, but no flame appears"

**Comment by jknpj** [comment] 2017-09-11 01:43
isn't the zippo supposed to be already lit tho?

**Comment by Anglosphere** [comment] 2017-09-11 03:07
Weird, I got it to work. I'm not sure, what caused, it. I'll see if I can get more info.

**Comment by Exxion** [comment] 2017-09-11 03:39
Can borg zippos run out of fuel?

**Comment by Anglosphere** [comment] 2017-09-11 05:39
I messed around on the test serb trying to replicate it. I was unable to replicate it. I'd say go ahead and close this issue for the time being.

**Comment by Pathid** [comment] 2017-09-11 05:46
They do indeed use fuel. You can refill them at a welder tank. However the issue is probably that they start lit and use fuel unless the borg takes care to close the lighter at the start.

**Comment by Shadowmech88** [comment] 2017-09-14 22:39
Closing at the request of the issue creator.

**Closed as completed by Shadowmech88** 2017-09-14 22:39 UTC
Labels: Bug / Fix
