### ISSUE TITLE
Reset blob to random chance again

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#2546] opened 2015-01-17 17:01 UTC
We had a poll for players started by Velard that wanted blob reset to a random chance instead of its own game mode. And since velard is being lazy about it, I'm asking you based coders.

I just want it back to random chance because the blob usually loses instantly, and the second you get a Biohazard alert within a few minutes of the round everyone knows it's blob as well as the new law the AI gets.

**Comment by LisandraBrave** [comment] 2015-01-17 18:25
Fund it. Blob could be a lot of fun if it wasn't it's own round type.

**Comment by Probe1** [comment] 2015-01-17 18:32
Blob is definitely a weak game mode.  Enough players have figured it out and when a biohazard warning shows up at round start, everyone knows theres a blob and what actions to take before it reaches a tipping point.  

Another issue with blob as a game mode is its all the round is about.  There's no point in doing research past guns because the only point is to kill the blob, then the round ends.  There's no point in being a bartender, chaplain, librarian, et cetera, just kill dat fukken blob.  

Making it a random event (a **rare** random event) and admin event would be a good choice.  If the biohazard warning doesn't come at the start of the round then people will not be able to confidently guess it's blob.  Delaying it well past round start means players have more time to enjoy their job and have a normal round before attacking the blob becomes the priority.  

I agree with moving it to random event/admin action and away from game mode.

**Comment by VelardAmakar** [comment] 2015-01-17 19:17
currently working on it

as it is, blob has a chance to happen randomly
but it's nothing short of a miracle if it does

it has the lowest weight when the RNG tries to choose events, and there must be at least one engineer active

i can raise the weight, but pomf will need to set the configs himself to prevent blob from being a selected gamemode
i don't want to remove blob gamemode altogether for several reasons, and i shouldn't and won't.

the question is: should blob have a higher chance of happening, and should i remove meteors from the pool altogether

the answer is yes
after 30 minutes, blob will be just as likely a random viral outbreak(which is already fairly rare)
the way it is now, randomblob is pretty fucking close impossible to happening, like, you need to sacrifice a goat and three goonecodes to make it happen

**Comment by ComicIronic** [comment] 2015-01-17 19:24
Increase the chance, but add the requirement of at least 1 Sec officer as well.

**Comment by ConkerDev** [comment] 2015-01-17 19:28
Dont make it rare, so what Comic suggested. It is an interesting gamemode, and one of the few that has the crew actually working together, like aliums. Also, and I think this is a really important thing for both aliens and blobs to work correctly: Declare quarantine (aka shuttle not callable) on the station if a high-level biohazard is detected (Aliens, virus, blob, etc.) This will solve the problem of everyone just calling the shuttle the nanosecond a biohazard is detected.

**Comment by Probe1** [comment] 2015-01-17 19:28
I don't think anyone gives a shit about random meteors Velard.  I'm pretty sure all the hate is about the round type, also known as sit in the AI core for 60 minutes until the shuttle arrives.  

Random meteor events are fine.  It gives engineering something to do after the initial 30 minutes.

**Comment by Probe1** [comment] 2015-01-17 19:30
Conker that already exists.  The shuttle won't come during bleb.  The issue is the crew always shits on the blob when it's a gamemode because anybody that has been through a blob round will know it's a blob round as soon as a biohazard warning comes up at round start.  Then the crew finds the blob way before it can really do anything and curbstomps it.

**Comment by ConkerDev** [comment] 2015-01-17 19:33
Probe1, Im ok with it being a random event rather than a gamemode. I meant that, in my whole ss13 experience, I have witnessed 4 blob rounds, and never been one. It is too rare. Up it to the old alien weight, and it will be ok

**Comment by VelardAmakar** [comment] 2015-01-17 20:51
there's a difference between random meteor waves and random meteor storms

i will leave waves on
storms, no
fuck storms

and yes i won't make it mega rare
the quarantine will trigger and then deactivate a random amount of time after the last xeno/blob is removed

**Comment by SarahJohnson489** [comment] 2015-01-18 01:01
I think the blob needs its own separate antag toggle instead of being lumped in with alien so all the dudes wanting xenomorph one day end up as the blab with no idea how to blag with less than 5 minutes to get dat fukken pop zone before they become blerguka.

With a couple month of blob bans for dudes who turned it on without reading the wiki first it'll get whittled down to people who aren't morons. And with it back in rotation both sides will get more experience to be less shit at it which'll result in a higher quality round rather than blab pops and dies in a brig cell or all of 2 guys go to fight the blob and one retard welderbombs it.

NPC blob event could be good fun as a >1/1.5/2 hour round to have a chance. Maybe even check for blob ghosts and cram it in as sort of a ghetto tensioner so that longer rounds will get more PvE than shoot carps and ignore meteor waves once all the antags got dunked.

**Comment by clusterfack** [comment] 2015-01-18 06:02
I haven't seen a random blob event once in quite a few months, are you sure its even enabled? Besides the fact is a shit gamemode points to a lack of balance rather than a reason for its outright removal.

**Comment by Probe1** [comment] 2015-01-18 13:10
@SarahJohnson489 I'm pretty sure it is its own antag toggle unless I misunderstand you completely.  
![ss 2015-01-18 at 08 06 29](https://cloud.githubusercontent.com/assets/8550416/5792504/1f715ba0-9ee9-11e4-9677-9f254dc05acb.png)


@clusterfack I haven't seen a "random event" blob but I have seen it bussed late round twice in the last month, and it worked well.  Admins bussed xenos which got dunked within five minutes and then blob directly after which was a challenging but fun fight.

**Comment by clusterfack** [comment] 2015-04-29 00:39
Random event blob is a thing, it's just bugged. I'll try to get it working

**Comment by Iamgoofball** [comment] 2015-04-29 01:44
seriously

"X is underpowered, let's make it not a gamemode and a random event"

why not just fucking buff blobs you dinguses

**Comment by ConkerDev** [comment] 2015-10-27 09:35
Not a bug, or needs admin decision.

**Comment by clusterfack** [comment] 2015-10-27 09:47
Except it is, blob is in random event rotation.

**Comment by Iamgoofball** [comment] 2015-10-28 04:52
i repeat again:

# if blob is too underpowered and the crew can kill it instantly why not buff it

**Comment by Ephx1** [comment] 2015-10-28 13:16
My problem with blob is more that it functions better as a random chance than a roundtype.
If you do get it as a random chance, it actually can work well, people may think it's a virus, not everyone will immediately jump on it, and it can grow reasonably well.
If it's a roundtype, I hear the fucking announcement, drop everything because it's blob and anything you do is meaningless other than fighting the blob. I don't know about you, but getting a round that solely focuses on fighting something and you might as well not actually do your job to go fight the thing is a pain in itself. It's like if nuke ops ended when they all died, or like Wizard when they all die, but at least with Wizard the level of fuckery changes.

**Comment by ConkerDev** [comment] 2015-10-29 02:14
My point is that this issue has deformed into blob discussion. Please remove the bug label, because I dont see how this could be

**Comment by clusterfack** [comment] 2015-10-29 02:25
"Reset blob to random chance"

Blob is random chance, random chance blob is bugged. Thus it has the bugged label. Also who gives a fuck about tags.

**Comment by FudgePucker** [comment] 2015-11-16 17:02
This can't be fixed because it would be a feature while we are in a feature freeze.
We can't get out of feature freeze because of bugs like these.

This is months old, just comment out blob chance from random events, close this issue, and we can bring up a feature request to add in blob random events.

**Comment by Ephx1** [comment] 2015-11-16 17:08
I don't understand how that would be a "feature" if it's specifically broken.
That's like if energy guns had a third setting added before feature freeze, and then it turns out it was broken.
Fixing that wouldn't be adding anything, it's already there, just broken.

**Comment by FudgePucker** [comment] 2015-11-16 17:15
The diffrence is that this isn't a major bug.

If energy guns had a third setting added before feature freeze and it was broken, then it would be obvious every round, people would switch from leathal to stun and have it bug out, or even worse have a runtime.

This doesn't effect anybody, no one would notice the bug unless they digged into the code.

I have had this argument before, something out of place being fixed is still a feature, even if it is arguable that it is a bug. Silicate doesn't electrolyze, fixing it would be a feature not a bug fix.

Blobs doesn't have a random event, fixing it would be a feature, not a bug fix.

**Comment by Ephx1** [comment] 2015-11-16 17:18
Okay so bug fixing = feature addition.
Cool, that's literally the only reasoning behind this, you've already stated it's a bug, but not really because it isn't major.
If it isn't major then why close it and make an exact copy? Bug tags only need to go below 100, why not fix the actually needed bugs now and then leave this one for later?

**Comment by FudgePucker** [comment] 2015-11-16 17:26
Fixing this would also require a lot of discussion of ballance on if we want blobs to be random chance again, this discussion would need to go on before anyone even bothers to start work on it. This discussion isn't going to happen on page 27, only reason that people had a recent discussion on this is because of the feature freeze and then it died quickly because only five people chimed in on what would be a massive balance and gameplay change.

**Comment by Ephx1** [comment] 2015-11-16 17:27
That's what linking to the page is for. And polls. And the recently updated button. And the discussion tag.
We already have tons of similar xeno discussion issues, we don't need more in the same vein.

**Comment by sonime** [comment] 2015-12-26 10:38
Unless it was removed, blob is actually one of the random events that can happen, and it does nothing currently.

My idea on how to fix it is to have another blob antag come up after the first one does until x amount of blobs have spawned, a la Ragin' Mages.

Blob rounds are really bad right now like @Probe1 said, because they're super weak at the beginning and get a 10 minute round, or of they survive the initial assault, it drags on into an hour-long round of the blob slowly expanding because of not making nodes to expand with.

I've seen a round Duny bussed in where he spawned multiple cores and kept spawning more as they got defeated. It got to the point where an ERT was called and they eventually fought off the blobs.

I think it set a good precedent as to how to make the round type not shit.

**Comment by FudgePucker** [comment] 2015-12-26 15:52
Maybe give blobs more preblob time for sabatoge.

Might make it more interesting if he can set up a radio transmitter and hideaway all of the welder fuel tanks and space the emitters.

**Comment by ihadtoregisterforthis** [comment] 2015-12-26 18:47
Last night we had random blob from an asteroid unless Celt was bullshiting. It didn't survive long since it landed on the box chapel and some combat mechs were armed.

**Comment by clusterfack** [comment] 2015-12-26 18:51
As far as I know random event blobs have been bugged for 1 full year now

**Comment by ghost** [comment] 2016-01-21 10:24
How would you handle the blob random event?

A player suddenly becoming bloated, or a blob core riding in on its own meteor storm?

**Comment by Ephx1** [comment] 2016-01-21 14:53
Blob event in a random chance was simply spawning one in a few pre-determined spots, usually maintenance.
It had the generic biohazard warning, so not everyone dropped everything to immediately go kill it.

**Comment by gbasood** [comment] 2016-01-21 17:34
Blob random event should spawn blobs in a similar fashion as a blob gamemode, for the sake of consistency.

**Comment by ghost** [comment] 2016-01-29 12:41
I don't like the idea of it spawning in a few pre-determined spots, would make it too easy to remember said spots and meta the heck out of it, but random infection would also be a problem if it has no good reason to do so, unless you do a check to see if somebody can potentially be infected through some means (No internals on, no protective measures on (Minimum 60 bio protection?))

**Comment by FudgePucker** [comment] 2016-01-29 17:14
Also is there a check to see if someone isn't afk? It would be shitty if the random blob was just sitting around doing nothing

**Comment by gbasood** [comment] 2016-01-29 23:47
The role recruiter does checks for if the person is logged in, but AFK I don't think so

**Comment by Imagebard** [comment] 2016-05-16 16:02
There's a new event which drops blob meteors. This probably fulfills it.

**Closed** 2016-05-16 16:46 UTC
Labels: Bug / Fix, Discussion
