### ISSUE TITLE
minds don't get transferred to space hobos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29891] opened 2021-06-24 00:48 UTC
(WEB REPORT BY: nottoomykins REMOTE: 206.221.180.138:7777)
# Revision
82f1e8b517ee0c17865791ec83ee5c220dc44859

# Description
\>get slain, gibbed
\>brain on ground
\>Become-Space-Hobo
\>ghost settings reset, don't become hobo
\>Become-Space-Hobo
\>You must have had presence on this plane to become this.
\>admins find a catatonic space hobo in space

**Comment by DeityLink** [comment] 2021-06-25 14:48
The problem is that minds DO get transferred, they shouldn't, at all. The player's key should be transferred instead. We don't want antags getting a free respawn.

Remember, as a rule of thumb: if it's a different person entirely, it gets a new mind.

**Closed as completed** 2021-06-26 16:53 UTC
