### ISSUE TITLE
(WEB REPORT BY: talvan REMOTE: 198.245.63.50:7777) Upgraded Cyborg Hypospray

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5567] opened 2015-07-27 15:26 UTC
Revision 202e56832a55d3dfa98135f48e743ad6ffd7b3a9

I can't select it through the module HUD but I can select it through the module popup.

**Comment by BestName** [comment] 2015-07-27 15:49
Duplicate of #4926

**Closed** 2015-07-27 22:14 UTC
