### ISSUE TITLE
Showers do not put borgs on fire out

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25472] opened 2019-12-21 15:12 UTC
(WEB REPORT BY: miniaturebigfoot REMOTE: 206.221.180.138:7777)
# Revision
ebb10a2fbfbfbfb2dd7285ab480c52949692e27e

# Description
Showers cannot put borgs if they are lit on fire. Is this a feature?  
# Steps to Reproduce
Get lit on fire as a borg,I stumbled into a fire created by my RSF and tried to put it out with showers. It did not work. 
# What you Expected
To not be on fire
# What Actually Happened
I was on fire

**Comment by jknpj** [comment] 2019-12-21 15:54
Unless someone changed how ExtinguishMob() works, i don't know how this can happen.

**Comment by jknpj** [comment] 2019-12-21 16:13
A quick test shows that ExtinguishMob() works so i'll check what is happening later.

**Comment by Kurfursten** [comment] 2019-12-21 16:27
sometimes regenerate icons doesn't get called (cosmetic only)

**Comment by jknpj** [comment] 2019-12-21 21:03
It's not working for humans too

**Comment by jknpj** [comment] 2019-12-21 22:12
Seems related to atmos fires

**Comment by west3436** [comment] 2024-03-20 13:18
Duplicate of the ancient bug #13393

**Closed as not planned by west3436** 2024-03-20 13:18 UTC
Labels: Bug / Fix
