### ISSUE TITLE
Hydroponics hallway door is linked to kitchen, not hydroponics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21698] opened 2019-02-14 21:20 UTC
(WEB REPORT BY: qbone REMOTE: 206.221.180.138:7777)
# Revision
92b133c95d85ff7010d5e4f8201365949e292928

# Description
The door to hydroponics on Box's is tied to Kitchen access, I believe. At least it's not tied to hydroponics.

# Steps to Reproduce
Walk into a door with only Hydroponics access, see door flashing red, feel dumb.

# What you Expected
Door to open

# What Actually Happened
BEEP BEEP

**Comment by Exxion** [comment] 2019-02-14 21:57
Kitchen and hydroponics have the same access
IIRC it requires maint access as well as service because ???
Though I thought it was only an issue on local due to config stuff

**Comment by Aryuananime** [comment] 2019-02-14 22:26
Yeah, I only bothered because as HoP, I gave Grug Hydroponics access only so I could make him a berry picker, and he couldn't open the hallway door.

**Comment by Kurfursten** [comment] 2019-02-15 17:51
Dupe of 
https://github.com/vgstation-coders/vgstation13/issues/11998
https://github.com/vgstation-coders/vgstation13/issues/4654

**Closed as completed** 2019-10-02 18:52 UTC
Labels: Mapping (Box :baby:)
