### ISSUE TITLE
Tape recorder playback doesn't work if you're holding the tape recorder

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10864] opened 2016-07-01 06:14 UTC
only if it's on the ground or such which can get pretty confusing

**Comment by clusterfack** [comment] 2016-07-01 06:21
That's surprising, it should have a virtualhearer to hear for it instead

**Comment by 9600bauds** [comment] 2016-07-01 06:26
I mean the playback, not the listening

**Comment by Kurfursten** [comment] 2016-07-01 09:54
Partial duplicate of #7025

**Closed as completed** 2016-07-02 13:30 UTC
Labels: Bug / Fix
