### ISSUE TITLE
Issues with removing items from players who are on medical beds

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#3913] opened 2015-04-15 00:48 UTC
Ran into an issue with this a day or so ago. For whatever reason being able to remove backpacks or putting masks on players while they're on the medical table doesnt work. This makes surgery a bit of a hit or miss some times. Nothing too major but could be a problem when the ride is in full swing.

**Comment by ComicIronic** [comment] 2015-04-15 19:20
Duplicate of #3828

**Closed** 2015-04-15 19:21 UTC
