### ISSUE TITLE
APC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7941] opened 2016-01-29 17:07 UTC
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> apc cargo solar array seems to not work
> 
> What you expected to happen
> took out battery and expected lights and equipment to go off
> 
> What actually happened
> nothing lights all stayed on as did the computer
> 
> Steps to reproduce if possible
> open apc take out battery

**Comment by PJB3005** [comment] 2016-01-29 18:14
Assuming this is a dupe of #7942 as it's from the same author but simply has less info.

**Closed as completed by PJB3005** 2016-01-29 18:14 UTC
