### ISSUE TITLE
Noir mutation removal with ryetalin pills

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26007] opened 2020-03-19 07:11 UTC
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
be0273017311d5b539fd746e8c28e7887107af0b

# Description
Noir mutation can't be fixed by taking ryetalin pill
# Steps to Reproduce
Be gumshoe or private eye. Take ryetalin pill. "You feel soft boiled", mutation is gone. 
# What you Expected
To see colors
# What Actually Happened
Everything (even blood) is black and white.
Side note: noticed that getting cloned fixes it. Might be the magic heal tubes and cryomix.

**Comment by DeityLink** [comment] 2021-04-28 00:26
Looks like Gumshoe spawn with a duplicate of each of their mutations, which means that only one gets removed by the ryetalyn while the other remains forever (since the active_gene however is only added once, and thus only removed once).

![image](https://user-images.githubusercontent.com/7573912/116328374-28d14300-a7c9-11eb-84de-db5fed7e8d28.png)

**Closed as completed** 2021-04-30 17:23 UTC
Labels: Bug / Fix
