### ISSUE TITLE
Fire Alarms do not properly display Rainbow Alert Level

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22374] opened 2019-04-08 19:55 UTC
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
a5eb8957f668635454de3240bbb5f614e769e5ed

# Description

They just show "The Alert Level is: "
# Steps to Reproduce

Declare Code Rainbow like an idiot
# What you Expected

Rainbow code on fire alarms
# What Actually Happened

lol nothing

**Comment by Kurfursten** [comment] 2019-04-08 23:24
duplicate of #22042

**Comment by MadmanMartian** [comment] 2019-04-08 23:24
that link links back to itself

**Closed as completed by Kurfursten** 2019-04-08 23:24 UTC
