### ISSUE TITLE
Radio transmitter still acts like it's being turned on when it's not wrenched down

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7761] opened 2016-01-19 00:24 UTC
Originally #7741 

> Also to note, it still gives the turning on and whirr messages while being pulsed, it just doesn't do anything.

**Comment by ghost** [comment] 2016-01-31 14:53
May just be me having no idea what to do to reproduce this, but I couldn't.

**Comment by gbasood** [comment] 2016-01-31 21:47
To reproduce don't wrench it down and try to turn it on I guess
If it doesn't reproduce that way then it's closable

**Comment by BarneyGumball** [comment] 2016-10-09 22:25
Could not reproduce.  Tried leaving the multitool menu open, unwrenching it and then trying to turn it on but it did nothing.

**Comment by Zth--** [comment] 2017-02-03 08:00
Need moar testing? Close it? Honk?

**Closed as completed** 2017-02-03 22:46 UTC
Labels: Bug / Fix, Easy Fix
