### ISSUE TITLE
(WEB REPORT BY: dragonbro REMOTE: 198.245.63.50:7777) Canister release pressure showing up as 'undefined kPa'

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5419] opened 2015-07-18 18:00 UTC
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
All canisters across the map, when interacted, the release pressure shows up as 'undefined kPa' and can't be modified. Have confirmed that it is not an isolated incident (Checked EVA, engineering secure storage, and Toxins storage across multiple people.)

See picture: http://i.imgur.com/ViL4xoi.png

>What you expected to happen
Being able to modify the release pressure on the canisters.

>What actually happened
Was unable to modify the release pressure on the canisters.

>Steps to reproduce if possible
Go up to your friendly neighbourhood canister, click on it to open up the UI, proceed to panic when you can only use 101.325 kPa

**Comment by PJB3005** [comment] 2015-07-18 18:06
dupe of #5411

**Closed** 2015-07-18 19:44 UTC
