### ISSUE TITLE
(WEB REPORT BY: Rodocks REMOTE: ) Bar firelocks are facing left instead of down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4931] opened 2015-06-11 22:47 UTC
it faces left instead of down

**Comment by Exxion** [comment] 2015-06-11 23:31
Exact duplicate of #4930 except this one actually has the name of the submitter for some reason

**Comment by ComicIronic** [comment] 2015-06-12 06:59
Duplicate.

**Closed** 2015-06-12 06:59 UTC
