### ISSUE TITLE
DJ Station Sleeper has a console

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4796] opened 2015-06-01 05:42 UTC
It's supposed to be a non-functional sleeper, after the medcondecon update it now has a console that is inside the window it's against.
Happened in Taxi, untested in others

**Comment by clusterfack** [comment] 2015-06-01 05:47
Panic

**Comment by 9600bauds** [comment] 2015-06-01 05:48
Picnic

**Comment by FudgePucker** [comment] 2015-06-01 16:15
Whats wrong with having a working sleeper all the way out there in space?
You are in the middle of space, it would be a little help if you could have a buddy heal you up.

**Comment by 9600bauds** [comment] 2015-06-01 16:39
I think it's supposed to be like a cryostasis type of deal, purely for flavor. Regardless it's clearly supposed to not have a console since it's right up against the window

**Comment by FudgePucker** [comment] 2015-06-01 17:23
Can't you just flip it?
Kinda hard to have it be cryostasis with no sleeptox.

**Comment by 9600bauds** [comment] 2015-06-04 02:53
[map issue (Taxi)]

**Comment by Exxion** [comment] 2015-06-05 03:00
Is it really just Taxi? I'd expect all of the maps to have this issue, given that the medcondecon update you're referring to made sleepers automatically create their consoles.

**Comment by 9600bauds** [comment] 2015-06-05 04:32
Most likely, I didn't check tho

**Comment by Probe1** [comment] 2015-11-14 11:50
is this really a bug?

**Comment by PJB3005** [comment] 2015-11-14 18:13
All maps have this.

**Comment by gbasood** [comment] 2016-01-16 17:37
This issue could be resolved by adding a boolean to individual sleepers to prevent auto-generation for intentionally broken sleepers.

**Comment by Imagebard** [comment] 2016-01-25 12:24
It seems like people would love to have a sleeper in space, so consider if you really want to remove it.

**Comment by Exxion** [comment] 2016-01-25 13:39
There are sleepers in space
Abandoned medical ship
It even has cryo

**Comment by ghost** [comment] 2016-01-31 15:07
@gbasood Not a bug

**Comment by gbasood** [comment] 2016-01-31 19:00
No, it is a bug.

The sleeper console literally spawns **INSIDE WINDOWS AND A GRILLE**

**Comment by 9600bauds** [comment] 2016-02-05 23:16
![dreamseeker_2016-02-05_20-15-54](https://cloud.githubusercontent.com/assets/6526157/12861883/593389be-cc45-11e5-9439-6f9dd7dd7918.png)
Verily it be a bug

**Closed** 2016-04-15 23:39 UTC
Labels: Bug / Fix, Easy Fix, Map Issue (General), Oversight
