### ISSUE TITLE
Setting objectives via rolepanel is broken.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#30543] opened 2021-09-06 19:14 UTC
[bugfix]
Role objectives have many issues when you attempt to change or set new ones via Role Panel.

Assassination objectives (most, if not all) will give you a random target that you did not select even if you choose a specific player.
Time Agent's "locate objects" objective is completely non-functional.
The "kidnap crew from X department" vox raiders will turn into "Kidnap personnel from the ADMIN CHARACTERNAME department.

**Comment by DeityLink** [comment] 2021-09-07 03:52
Duplicate of #26322

**Closed as completed by DeityLink** 2021-09-07 03:52 UTC
Labels: Bug / Fix
