### ISSUE TITLE
Cyborg destruction bug on contact with singularity

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18795] opened 2018-07-10 22:24 UTC
(WEB REPORT BY: goldsteel REMOTE: 172.93.109.202:7777)
# Revision
cf65224c00e9010ff5990fc7aed2bb64dbe0c7f9

# Description
Got EMPed and sucked into the singularity and it gibbed me, but I was left as an invisible mob that could talk on binary and normally without being able to move. The singularity just clipped me slightly and went away a second later.

# Steps to Reproduce
Shove a borg into a singularity. I was EMP'ed and also my radio speaker wasn't working due to a previous EMP.

# What you Expected
Ded

# What Actually Happened
Not ded

**Comment by Pathid** [comment] 2018-07-10 23:12
Duplicate of #18334

**Closed as completed** 2018-07-10 23:14 UTC
