### ISSUE TITLE
glass floors are cursed and seem to always be on the top layer even above the ui

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30903] opened 2021-09-25 23:31 UTC
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
e69b2cecf42fbc56fa8e0374bbfa7c963745c8de

# Description
what
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by kernikov** [comment] 2021-09-26 01:27
@DeityLink duplicate of #30888

**Closed as completed** 2021-09-28 23:53 UTC
