### ISSUE TITLE
two fucking dwarf fortress themes playing at the same time in slightly different tempo when mining at the asteroid

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4927] opened 2015-06-11 14:57 UTC
STOP

**Comment by ririchiyo** [comment] 2015-06-13 01:20
I believe this is a duplicate of #2392

**Comment by 9600bauds** [comment] 2015-06-13 02:05
wisdom worth repeating

**Closed** 2015-06-13 10:00 UTC
Labels: Bug, Honk
