### ISSUE TITLE
Quick equip quirky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24702] opened 2019-11-01 17:41 UTC
(WEB REPORT BY: fluffyhive REMOTE: 206.221.180.138:7777)
# Revision
de55f3e248eb792412a720de8606af4810609eb1

# Description

Some items that don't fit on particular belt replace it with quick equip button (E), and cannot be equiped back, needs to be readjusted manually with mouse. Was not the case 3-4 days ago

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Zth--** [comment] 2019-12-09 02:14
Duplicate of #24974. That one has more info

**Closed as completed by Zth--** 2019-12-09 02:14 UTC
Labels: Oversight
