### ISSUE TITLE
blood soaked mops clean instead of spread

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20843] opened 2018-11-28 02:40 UTC
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
1d45da69591f630f53c860dab4ed501db80bdd06

# Description
blood appears to act as a cleaner when used with a mop, yet it spreads when put into a spray bottle.

# Steps to Reproduce
fill up a container of some kind with blood to soak a mop in, bucket, cart, whatever. apply to floor, watch as it doesn't spread blood, but also cleans.

# What you Expected
blood spreading everywhere

# What Actually Happened
Khorne cleaning.

**Comment by ShiftyRail** [comment] 2019-06-19 19:18
Dupe of #13913

**Closed as completed by ShiftyRail** 2019-06-19 19:18 UTC
