### ISSUE TITLE
cold drinks cool you too hard, hot drinks heat you too hard

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35878] opened 2024-01-31 01:11 UTC
(WEB REPORT BY: eneocho REMOTE: 172.93.101.77:7777)
# Revision
46ed236038a88475a77941e82033654d703b4078

# Description
drink lukewarm cola
get frostbite

drink lukewarm coffee
get burnt 
# Steps to Reproduce
drink cola 
drink coffee
# What you Expected
to warm up or cool down like before
# What Actually Happened
clown started burning up when he drank a mug of lukewarm coffee

**Comment by jwhitak** [comment] 2024-01-31 01:20
To note the little heat and cold indicators currently show up at safe but slightly severe levels of temperature. Did you/the clown take damage?

**Comment by DeityLink** [comment] 2024-01-31 01:37
I'm gonna request some testing on that with precise values. how lukewarm exactly? which coffee? 

I tested drinking a whole can of Space Cola at room temperature and while I got the "slight breeze" icon shown below (as intended), I didn't get any hypothermia message or slowdown.
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/2bf2c464-61ad-46b8-a1fe-21a43491a6e6)

Also was your character fat? I've observed some weird shit going on with the body temperature of fat humans.

**Comment by Eneocho** [comment] 2024-01-31 16:27
generic coffee and generic cola both at the temperature spawned by the chem synth, which I assume is 25°C
clown was not fat

**Comment by Eneocho** [comment] 2024-01-31 16:28
on health analyzing, a single coffee dose made him get close to 60°C

**Comment by DeityLink** [comment] 2024-01-31 16:47
60°C is safe by spess standards. Unlike hypothermia which begins when your bodytemp is like 2°C below room temperature, you don't take heat damage until like 90°C.

Also what chem synth are you talking about? the bar dispensers?

You can use thermometers to check the temperature of beverages.

**Comment by Eneocho** [comment] 2024-01-31 17:34
It was the pAI one. The clown got celebratory coffee and complained of burning up, I checked, he was at 60°C.

**Comment by DeityLink** [comment] 2024-01-31 21:42
yeah but that's working as intended. Like I said 60°C is cozy in space. Coffee raises your temperature by 20°C per tick when you drink it, and it'll do so as long as your body temperature is below 50°C, which means you can get as high as 70°C. But that don't matter because the temperature you take damage from is still higher. The clown's HUD shouldn't have displayed anything above that 
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/e61a41a1-5121-463b-8faf-7f338dd5f351)

**Comment by DeityLink** [comment] 2024-01-31 21:45
because while we have hypothermia, we don't have temperature-based fevers. And given how much people hate hypothermia, and how easy it is for body temperature to rise in general, I think fever is the last game mechanic we need.

Regarding cola, it only lowers your body temperature by 1-2, which leaves you slightly above hypothermia. 
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/729f83e6-dbc8-4ead-acea-a96b0c6509ce)

**Comment by Eneocho** [comment] 2024-01-31 22:48
guess I'll close it

**Closed as not planned by Eneocho** 2024-01-31 22:48 UTC
Labels: Needs Moar Testing, Balance
