### ISSUE TITLE
Diona nodes can't be injected with blood anymore

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#5735] opened 2015-09-19 14:18 UTC
Steps to reproduce the issue:
1. Get some diona nodes
2. Get a syringe
3. Get some blood
4. Try to inject blood into the diona nodes
5. Cry in frustration as nothing happens

**Comment by PJB3005** [comment] 2015-09-19 23:01
@DeityLink

**Comment by Intigracy** [comment] 2015-09-19 23:09
Inject the seed.

**Comment by BestName** [comment] 2015-09-19 23:11
I would if I could

**Comment by Intigracy** [comment] 2015-09-19 23:17
I thought you meant you were injecting the plant.

**Comment by PJB3005** [comment] 2015-09-19 23:18
Diona nodes are the seeds, the pod is the plant.

**Comment by DeityLink** [comment] 2015-09-20 06:47
Hasn't it be the case for over a year? The way it works right now, when a diona nymph is spawned from a pod, every ghost is prompted to take control of it, the first to press "yes" becomes the diona.

**Comment by AutismSpider** [comment] 2015-09-20 07:09
could diona clone people with blood  it would force the dead players ghost into that nymph when it was ready.

**Comment by BestName** [comment] 2015-09-20 07:30
In 2014-09-26 I injected some seeds with my own blood just to see if the feature existed so no, this hasn't been the case for over a year.

**Comment by AutismSpider** [comment] 2015-09-21 01:39
Some one took it out diona cloning people.

**Comment by BestName** [comment] 2015-09-22 12:09
Well the code still exists. I'm guessing it doesn't work because the path was changed from obj/item/seeds/replicapod to /obj/item/seeds/dionanode
```dm
/obj/item/seeds/replicapod/attackby(obj/item/weapon/W as obj, mob/user as mob)

	if(istype(W,/obj/item/weapon/reagent_containers))

		user << "You inject the contents of the syringe into the seeds."

		var/datum/reagent/blood/B

		//Find a blood sample to inject.
		for(var/datum/reagent/R in W:reagents.reagent_list)
			if(istype(R,/datum/reagent/blood))
				B = R
				break
		if(B)
			source = B.data["donor"]
			user << "The strange, sluglike seeds quiver gently and swell with blood."
			if(!source.client && source.mind)
				for(var/mob/dead/observer/O in player_list)
					if(O.mind == source.mind && config.revival_pod_plants)
						O << "<span class='interface'><b><font size = 3>Your blood has been placed into a replica pod seed. Return to your body if you want to be returned to life as a pod person!</b> \
							(Verbs -> Ghost -> Re-enter corpse, or <a href='?src=\ref[O];reentercorpse=1'>click here!</a>)</font></span>"
						break
		else
			user << "Nothing happens."
			return

		if (!istype(source))
			return

		if(source.ckey)
			realName = source.real_name
			ckey = source.ckey

		W:reagents.clear_reagents()
		return

	return ..()
```

Or not, I don't know, I can't understand code.

**Comment by BestName** [comment] 2015-09-22 12:24
Actually I don't think the file containing the above snippet of code has been in any kind of use since #1654 so I guess we should really be blaming @d3athrow or Bay instead of Deity.

**Comment by DeityLink** [comment] 2015-09-22 13:11
That snippet of code was completely unused for over a year, dionas had already been reworked back then.+

**Comment by BestName** [comment] 2015-09-22 13:14
But the file was still included in the .dme

**Comment by DeityLink** [comment] 2015-09-22 13:26
So are tons of files that we're not using, such as old hydroponics, old genetics, etc

**Comment by Zuhayr** [comment] 2015-09-22 13:44
That should have been removed, I probably overlooked it at the time.

**Comment by BestName** [comment] 2015-09-22 13:51
Well then did the code at some point exist outside of podmen.dm?
As I said before I was able to inject diona nodes with blood in 2014-09-26 (which is definitely not over a year ago) and received the exact messages that are in that snippet.

**Comment by PJB3005** [comment] 2015-10-27 21:16
@BestName did it actually do anything though, because I assume the injection code existed and worked, but the code didn't care about the vars that were set.

**Comment by BestName** [comment] 2015-10-29 13:45
I wouldn't know

**Comment by Intigracy** [comment] 2016-03-14 05:51
someone assign me

**Comment by clusterfack** [comment] 2016-03-14 07:07
Cant fam, need collaborator to be assigned shit. It's dumb

**Comment by Intigracy** [comment] 2016-03-14 13:56
someone assign me collaborator :^)

**Comment by 9600bauds** [comment] 2016-03-14 14:23
i assigned myself as a stand-in for you

**Comment by Intigracy** [comment] 2016-03-14 14:41
cool I'll just mention you for now on.

mostly I want someone assigned to them all so I can filter the issues list without having to go to too much work to find the ones I commented on, since there's no filter for "issues I've commented on"

**Comment by 9600bauds** [comment] 2016-03-14 14:43
https://github.com/d3athrow/vgstation13/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-commenter%3AIntigracy

**Comment by BestName** [comment] 2016-03-14 14:44
Quit spamming my inbox you mini-hitlers.

**Comment by Intigracy** [comment] 2016-03-14 14:53
wow wtf didn't know about that thx fam

**Comment by JMWTurner** [comment] 2016-10-29 23:20
Working as intended as far as I know. This issue doesn't make much sense anymore.

**Comment by BestName** [comment] 2016-10-30 11:06
Consider it a feature request then.

**Comment by JMWTurner** [comment] 2016-10-30 11:07
What's the request precisely then?

**Comment by Intigracy** [comment] 2016-10-30 11:47
Cloning through botany.

It used to be the behavior, you'd take someone's blood sample and inject a packet of diona seeds with it, and when it grew up that specific person would pop out, with a chance of being a diona person instead of a human.

**Comment by BestName** [comment] 2016-10-30 12:38
That.

**Comment by JMWTurner** [comment] 2016-10-30 16:45
That's what potato people and replicapods were. Not a fan of it.

**Comment by BestName** [comment] 2016-10-30 16:46
And that's also how Dionae used to work.

**Comment by JMWTurner** [comment] 2016-10-30 16:47
There was never a chance to come out as a human from a dionae pod.

**Comment by BestName** [comment] 2016-10-30 16:49
No I meant the other stuff. The whole getting cloned thing.

**Closed** 2017-01-07 15:16 UTC
Labels: Feature Loss, Feature Request, Unfulfilled Feature Requests
