### ISSUE TITLE
Holo-Impersonation is DONE FOR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24510] opened 2019-10-20 18:58 UTC
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
7b1a7a920c1f361459c0bc5a9b39274e7846c1a9

# Description
AI changing hologram to crew member displays featureless nude model.

Gee, AI sure is bugged lately, huh? Better keep an eye out for blue APCs.

**Comment by Killette2** [comment] 2019-10-20 19:19
Are you expecting holoclothes?

**Comment by SonixApache** [comment] 2019-10-20 19:54
dupe of #21492

**Comment by Blithering** [comment] 2019-10-21 09:21
It used to have the appearance of their hairstyle and  their job's starting gear

**Closed as completed** 2019-10-21 14:40 UTC
