### ISSUE TITLE
Xenobotany gene disk leaks onto other players

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3167] opened 2015-02-21 16:59 UTC
After doing xenobotany gene splicing, if another player starts using the same disks as me, I can see them in my hand as if I was holding them in my interface.

**Comment by ComicIronic** [comment] 2015-02-21 17:19
Wat.

**Comment by d3athrow** [comment] 2015-02-21 21:50
I'm confused by the report and the title.

**Comment by TermedClepe** [comment] 2015-02-21 21:54
When you use xenobotany disks to splice genes, for example you load a plant gene onto a disk, use it in biobalistic machine and then wipe the disk, the disk will somehow become glitched and you will see it in your hand as if you were holding it when someone else is holding it.

**Comment by ComicIronic** [comment] 2015-02-21 22:03
Perhaps caused by not using drop_item.

**Comment by Probe1** [comment] 2015-02-21 23:55
Oh good I was going to make this issue last night but never got around to it.  This is something that's been around a fair while but is pretty bad for botanists.

Here's a closeup of my hand after inserting a seed packet into the lysis isolation centrifuge machine 
![image](https://cloud.githubusercontent.com/assets/8550416/6316603/78870920-b9fa-11e4-81a1-867ab97f3293.png)


See how there's a faint imprint of the seed packet?  Here it is again with floral disks.  

![ss 2015-02-20 at 10 59 05](https://cloud.githubusercontent.com/assets/8550416/6316605/a441260e-b9fa-11e4-8b46-89612ae0b68f.png)

It's a pretty prolific bug and all you have to do to reproduce it is play botany on the live server.

I'm going to lump the other issue I was going to make in here since its another botany problem.  When loading plant bag items into machines and you have the plant bag view open, you've got a good chance of getting this.  Icons for the plants you loaded into the grinder or biogenerator stuck on your screen until you restart the client or get new ones stuck on the screen.  

![ss 2015-02-20 at 11 59 18](https://cloud.githubusercontent.com/assets/8550416/6316608/ce1697ca-b9fa-11e4-8d89-4fb61fae8c7a.png)

It's super fucking annoying when you have eggplant icons on top of your backpack icons and everything is an eyesore to see.

**Comment by Zuhayr** [comment] 2015-02-22 05:53
You should be able to just clear the screen loc of the items being dumped out of the bag to fix that. It sounds like it might be a matter of whatever code is moving them around not calling the right procs.

**Comment by clusterfack** [comment] 2015-04-19 12:56
Didn't we have something like this occur when you spam clicked fire extinguisher cabinets and you'd get an afterimage of fire extinguishers in your hands? This reminds me of that

**Comment by ComicIronic** [comment] 2015-04-22 17:46
Is this still happening?

**Comment by Probe1** [comment] 2015-04-22 19:14
I'll test it later today and let you know.  I suspect it is still happening.

**Comment by Kurfursten** [comment] 2015-10-15 21:28
@clusterfack This doesn't happen anymore. Close it.

**Comment by Probe1** [comment] 2015-10-16 00:37
Haven't seen it in months.

**Closed** 2015-10-16 00:49 UTC
Labels: Bug, Needs Moar Testing
