### ISSUE TITLE
Vampire Thermal Vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19216] opened 2018-08-09 01:33 UTC
(WEB REPORT BY: drneocortex REMOTE: 172.93.109.202:7777)
# Revision
4c339ee9c3013b16efc399fcc4692c1f5b1687d4

# Description
Vampire thermal vision and mesons don't mix. Useing both at the same time causes the mensons to show darkness around the user instead of being all lit up.
# Steps to Reproduce
Be a vampire, get thermal vision, put on mensons.
# What you Expected
Mensons to co-encide with thermal vision
# What Actually Happened

**Comment by DamianX** [comment] 2018-08-10 09:59
duplicate of #18939

**Closed as completed by DamianX** 2018-08-10 09:59 UTC
