### ISSUE TITLE
There should be a ttv crate available from cargo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10067] opened 2016-05-15 18:50 UTC
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
perhaps it would require cap or RD access to open.
I realize that the ammount of ttvs is limited to 6 for a reason, but it would be nice to be able to jump through a few hoops to get more.

**Comment by PJB3005** [comment] 2016-05-15 18:59
:|

There already is.

**Comment by Imagebard** [comment] 2016-05-15 19:09
TTV?

**Comment by PJB3005** [comment] 2016-05-15 19:11
Tank transfer valve

**Comment by Shadowmech88** [comment] 2016-05-15 19:13
A cargo crate is hardly what I'd call "a few hoops."

**Comment by FudgePucker** [comment] 2016-05-15 19:25
Cargo getting TTVs
There's a burn chamber below cargo.
Awesome idea

**Comment by ComicIronic** [comment] 2016-05-15 20:01
Every time you suggest a way for people to get more TTVs, the game gets slightly worse.

**Comment by Killette2** [comment] 2016-05-15 21:01
> Big complaint about cuban pete bombs recently, despite all my suggestions being perfect
> 
> LET'S ADD MORE TTS's!

**Comment by AutismSpider** [comment] 2016-05-15 21:31
>add more fucking TTVs 

>can get 8 to 9 of them on fucking deff

>yes lets add way to get more

Full Retard. NEVER GO FULL RETARD!

**Comment by 9600bauds** [comment] 2016-05-15 21:44
![js946bu](https://cloud.githubusercontent.com/assets/6526157/15276953/12eb2b5c-1acd-11e6-9e00-e21d7eb972c2.png)

**Comment by clusterfack** [comment] 2016-05-15 21:48
FUCK YOU CARL

**Comment by Orangerush** [comment] 2016-05-15 22:00
Amazing idea 6,000,000/10

**Comment by Sordine** [comment] 2016-05-15 22:01
no

**Comment by ghost** [comment] 2016-05-15 22:15
No. If you do more than 6 actual tests it's easy to write up a request form, get it stamped by a head, fax it to centcomm and have admins send it in on the next cargo shuttle. If it's deadpop nomins, you can spend time crunching numbers.

**Comment by Imagebard** [comment] 2016-05-15 23:20
>ComicIronic and 9600Bauds team up to meme tag a meme feature request

Here we go

**Comment by 9600bauds** [comment] 2016-05-15 23:20
My tags were not memes though

**Comment by Imagebard** [comment] 2016-05-15 23:21
Riddle me this, why NFD?

**Comment by 9600bauds** [comment] 2016-05-15 23:22
NFD on an issue = "this is arguably not a bug/so stupid/there is such unanimous opposition, but we can't close it or we're bullies, one of the head honchos please come and close this"

**Comment by Killette2** [comment] 2016-05-16 01:16
You closed my box babies without a NFD you fucking bullies.

**Closed as completed** 2016-05-16 19:33 UTC
Labels: Controversial, Feature Request, Balance, ✋ Do Not Merge ✋, ❤️ Quality of Life ❤️
