### ISSUE TITLE
Other ghosts are invisible when you toggle darkness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6671] opened 2015-11-20 11:51 UTC
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a42bcc700bef4fd58e11024b4a7610809b166054 
> 
> General description of the issue
> As a ghost, if you hit Toggle Darkness, you can't see other ghosts anymore. Not sure if this is a bug or feature, but it's a bitch either way.

**Comment by Ephx1** [comment] 2015-11-20 14:57
It's a feature.

**Comment by PJB3005** [comment] 2015-11-20 15:09
Issue with how BYOND handles `invisibility`:

The `invisibility` var on atoms (everything you see) determines how high the `see_invisible` of your mob needs to be.

Issue is, this is on a scale from 1-100.

Toggle darkness actually drops your `see_invisible`, so you become unable to view the overlays that create the lighting, issue is that other ghosts have a very high `invisibility`.

**Comment by Ephx1** [comment] 2015-11-20 15:19
Shhhhhh, it's a feature, as you can tell because it's been that way forever of course!

**Comment by PJB3005** [comment] 2015-11-20 15:20
@Ephx1 it's been forever, because BYOND always had a shit invisibility system.

I made a feature request on the forums about it, but the issue is that Lummox can't think of anything fast and easy (@MrStonedOne made a suggestion but it was reaaally complex).

**Comment by ihadtoregisterforthis** [comment] 2015-11-20 16:20
If you make ghosts to appear with no darkness then add a button to remove other ghosts from the scene too. Muh clear map screenshots, muh clicking someone under a ton of observers.

**Comment by Zth--** [comment] 2015-11-20 16:20
I like it this way. Maybe add another button to hide other ghosts someday

**Comment by clusterfack** [comment] 2015-11-20 18:04
I think bay fixed this *somehow* but it wasn't pretty

**Comment by MrStonedOne** [comment] 2015-11-20 18:14
We implemented a workaround at /tg/ to use client images to solve this. You can always see a client image, even if you can't see the atom its attached to.

So we gave ghosts a HUD with ghost

**Comment by PsiOmegaDelta** [comment] 2015-11-21 09:29
Bay ported /tg/'s workaround, it's pretty much the same.

**Comment by ghost** [comment] 2016-01-26 04:37
Not really a bug in that It's always been this way.

**Comment by Ephx1** [comment] 2016-01-26 05:11
You are 67 days late, celt

**Comment by SonixApache** [comment] 2016-01-27 20:54
From what I understand it's an issue with BYOND and it'd fuck over performance to implement a workaround, so you might as well file this one under "We ain't fixing it" and close it.

**Comment by gbasood** [comment] 2016-01-27 21:03
Supposedly it wouldn't actually fuck performance iunno

**Comment by clusterfack** [comment] 2016-01-28 03:51
Why do you guys just randomly think assume things will mess with performance?

**Comment by 9600bauds** [comment] 2016-01-28 04:01
Because BYOND has had honest-to-god memory leaks from the most innocuous things and consistently proves to be unworkably shit with things that have no reason to be so shit, like overlays and locate().

**Comment by clusterfack** [comment] 2016-01-28 04:04
That's the kind of superstitious attitude that kept people from optimizing the code for ages

**Comment by 9600bauds** [comment] 2016-01-28 04:04
That's why we have a Clusterfack

**Comment by Intigracy** [comment] 2016-03-15 14:15
Clusterfack you should fix this bb.

**Closed** 2017-01-07 15:19 UTC
Labels: Feature Request, T-Thanks BYOND, Unfulfilled Feature Requests
