### ISSUE TITLE
RIPLEYS cannot pick up lockers with people inside them.

### ISSUE THREAD

**Issue by utilitas-** [d3athrow/vgstation13#5351] opened 2015-07-12 09:15 UTC
1. Acquire RIPLEY with hydraulic clamp.
2. Put person in a locker.
3. Try to lift locker.
4. ???
5. NOT PROFIT

Why? They used to be able to.

**Comment by ComicIronic** [comment] 2015-07-12 12:25
Deliberate.
If they used to be able to, it was a code issue.

**Comment by utilitas-** [comment] 2015-07-12 12:27
They used to be able, but I see no reason why it should be otherwise. It didn't even delete the mobs inside when the RIPLEY exploded or anything. It's just a fun little thing you can do and I don't see why it would harm anyone. You have to put any mob in a locker first, only then load them onboard, after all.

**Comment by Exxion** [comment] 2015-07-12 16:28
Agreed
They should be able to

**Comment by clusterfack** [comment] 2015-07-12 18:36
As I remember there was no way to escape for one, and by blowing up the ripley you could delete them forever iirc.

**Comment by Exxion** [comment] 2015-07-12 19:47
Removing a feature isn't a very good way to fix issues with the feature
These ones wouldn't even be that hard to fix

**Comment by utilitas-** [comment] 2015-07-13 06:45
@clusterfack But it takes a lot of effort to get more people into a RIPLEY. They must either be willing or welded in. And as far as I remember, blowing up the RIPLEY would release the locker. That's what I remember.

**Comment by ComicIronic** [comment] 2015-07-13 08:16
You can't blow up the Ripley from the inside, however.

**Comment by ihadtoregisterforthis** [comment] 2015-07-13 17:55
Could it be related to clamps not being able to crush people either?

**Comment by Exxion** [comment] 2015-07-13 17:59
According to Comic, it's intentional
Hence the "Not a Bug" tag and his comment stating that

**Comment by PJB3005** [comment] 2015-07-15 20:30
>ihadtoregisterforthis

**Comment by 9600bauds** [comment] 2016-01-26 00:28
This is a big no-no because of the incredible amount of issues it causes, considering closing

**Comment by clusterfack** [comment] 2016-01-26 00:43
Worse than that, it doesn't check if people entered the locker when you start to pick it up so you can enter it between those times!

**Comment by gbasood** [comment] 2016-01-27 20:58
will not change

**Comment by 9600bauds** [comment] 2016-01-27 20:59
Probably should make a separate issue for the thing clusterfack said

**Closed by gbasood** 2016-01-27 20:58 UTC
Labels: Feature Request, Not A Bug
