### ISSUE TITLE
Moving items to top affects only the items above the proper items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20503] opened 2018-10-30 12:35 UTC
(WEB REPORT BY: archinist REMOTE: 172.93.109.202:7777)
# Revision
8cd61b30888cec265025068a9949886adc8ba722

# Description

I was trying to move some items above a paper in a tile but was instead moving the items above. Originally, the items were in a fire closet and a grey closet below the BoxStation metting room. When I tried to move the grey items above a piece of paper, this would shuffle the items in the fire closet instead. Moving the closts away does not seem to change this.

# Steps to Reproduce

Load up boxstation, go to maintenance room below the meeting room with shutters. Try to move items inside grey closet (with paper, to hide??) , move fire closet items instead

# What you Expected

I expected the grey closet items to be moved to hide the piece of paper

# What Actually Happened

The paper inside the grey closet was not hidden, and the fire closet items were being shuffled around

**Comment by Exxion** [comment] 2018-10-30 20:52
Duplicate of #19063
It's because we were relying on BYOND behavior we shouldn't have been relying on, and that behavior changed, and nobody's gotten around to fixing it yet

**Comment by Exxion** [comment] 2018-10-30 20:53
God damn I forgot

**Comment by Exxion** [comment] 2018-10-30 20:53
Duplicate of #19063

**Closed as completed by Exxion** 2018-10-30 20:52 UTC
