### ISSUE TITLE
(WEB REPORT BY: arachnidgrip REMOTE: 198.245.63.50:7777) Crew Monitoring Computers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5652] opened 2015-08-03 20:50 UTC
>Revision 270a4a0d6a59702390c9a944635aee1978231673 
>General description of the issue
Attempting to use the crew monitoring computers results in either a blank screen of just space ( http://gyazo.com/4d5d55f4d879d281867b78908bc6c0b1 ) or a blank screen on the text version. Attempting to change the z level to 1 closes the computer.

>What you expected to happen
To be able to monitor crew members.

>What actually happened
Broken crew monitoring computers.

>Steps to reproduce if possible
Use a crew monitoring computer and attempt to change the z level.

**Comment by PJB3005** [comment] 2015-08-04 11:51
might be related to win 10 as I noticed OP is using it, unable to reproduce myself though.

**Comment by the-socks** [comment] 2015-08-04 20:19
I also have this issue on windows 8.1 

I opened another issue before I saw this one. I've now closed the issue I opened but here's the post I made in case it offers anything of value

>Everynow and then the crew monitoring consoles will be blank and non functional.

Using one will not show you a map of the station, but just the background image of space.

Switching to textmode just displays a blank grey screen with the NT logovin the corner.

I can't reliably recreate this, it just seems to work some rounds and be broken others. Also, when it's broken for one person it's not necessarily broken for everyone, I've been unable to use it during a round while my paramedic partner has no issues.

I ahelped in search of a solution and was told the machine is just messed right now. It would be very nice to have itbfoxed because playing paramedic is near impossible without it.

**Comment by the-socks** [comment] 2015-08-04 20:21
Also when the issue arises it seems to affect all the monitoring computers, trying another does not fix the issue.

**Comment by d3athrow** [comment] 2015-08-05 17:15
should be fixed

**Comment by Zth--** [comment] 2015-11-05 02:29
This gets fixed by updating IE. Close it

**Closed** 2015-11-05 02:35 UTC
Labels: Bug
