### ISSUE TITLE
Thermals do not work with welding helmets/There are no superior welding helmets.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6327] opened 2015-10-26 13:12 UTC
I'm making this both an issue and feature request.

Issue: thermals do not work with welding helmets. When you put on a welding helmet, your vision is blurred. Thermals cannot see in this blurred area. It is up to coders to debate whether this makes sense or not but it ruined my serial killer gimmick when I wore a welding mask for fashion but the thermals didn't let me see in the darkened zone

Feature request is superior welding helmets. There are welding goggles, that are welding helmets for your eye slot that blur vision, and superior welding goggles, which have a green tint and do not blur your vision. I request a superior welding helmet for fashion reasons, which will not blur your vision rather than having to steal any space suit helmet.

**Comment by Exxion** [comment] 2015-10-26 14:12
I can't remember if we have it over here, but tg has a welding gas mask that looks like a skull and only its visor flips up, so the mask stays on even when the protection/darkening is off.

As for thermals not working through the dark of the mask, I don't think that's really fixable. I might be wrong as I have almost no experience with overlays and layering, but I don't think so. The superior welding mask would be easy, though.

**Comment by Shadowmech88** [comment] 2015-10-26 20:44
If it is fixable, it should be fixed. Thermals can see through walls, there's no reason they shouldn't be able to see through a mask.

**Comment by PJB3005** [comment] 2015-10-26 21:54
I think the issue is really hard to fix, because BYOND.

**Comment by clusterfack** [comment] 2015-11-10 18:31
It makes zero sense for welding helmets and thermals to work together.

Welding helmets block infrared radiation from frying your fucking eyeballs and heat from burning your face. Thermals rely entirely on infrared radation to work.

**Comment by Shadowmech88** [comment] 2015-11-10 19:18
Do two meter-thick solid metal walls not block infrared radiation?

**Comment by Intigracy** [comment] 2016-03-17 23:57
Two meter-thick solid metal walls you can break with just a welder and a wrench in a few seconds.

Pretty sure the metal is cheap as shit. I agree with clusterfack.

**Closed** 2016-12-20 22:28 UTC
Labels: Feature Request, IT'S A FEAAAATUUUUREEEEEEEEE, Not A Bug
