### ISSUE TITLE
Happy Mask makes everyone Unhappy

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#10581] opened 2016-06-16 10:11 UTC
#### Description of issue

Frustrates admins and players alike.
#### Difference between expected and actual behavior

Mask allows people to turn corpses with players in them into shades.
It doesn't give them antag status.
This upsets everyone
#### Steps to reproduce
1. Watch a xenoarch
2. They will find a happy mask
3. Someone will use the happy mask eventually to turn a dead player, probably one in medbay about to be cloned, into a shade
4. Nobody will be happy about this

---

Can we just toggle an objective on for people who put the mask on even if it's just 'Make people happy' or '???'  and make it unremovable even if you remove the head, so we can stop the bans, ban requests, etc etc?

**Comment by Exxion** [comment] 2016-06-16 14:11
It should be WAY rarer
I've seen someone dig up three of them in one round

**Comment by jknpj** [comment] 2016-06-16 16:31
> I've seen someone dig up three of them in one round

Once i delivered 6 to security because i wasn't sure if keeping them in the outpost would be safe. They are common RNG generates a lot of cult digsites

**Comment by Exxion** [comment] 2016-06-16 16:40
They really should be extremely rare, like once every few rounds at most
They are in the rarest class of item in the source material, after all

**Comment by jknpj** [comment] 2016-06-16 16:53
> once every few rounds at most

Miners and Xenoarchs find them every round. Literally EVERY ROUND. Even Traders find them once in a while, and that's just because they only dig digsites once in a while.

**Comment by clusterfack** [comment] 2016-06-16 16:59
Regular non large artifacts just aren't hard to find in any way

**Comment by Exxion** [comment] 2016-06-16 17:24
Yes. I said that Happiest Masks SHOULD be extremely rare, not that they ARE.

**Comment by jknpj** [comment] 2016-06-16 17:27
Can we limit the maximum amount of a certain digsite in our roid generator? If yes that should do the trick.

**Comment by Probe1** [comment] 2016-06-16 18:02
>put on mask
 >objective: ???

I like nukes idea of having it give you an objective and having it be completely unremovable.  I think the item is fine and finding multiple instances is actually pretty rare.  I once found two right next to each other.  Once.  In the thousands of hours I've played.  That sticks out to people.

I think the two things it needs are what I wrote  at the top.  Some kinda antag notification and some kinda permanence so it can't be shared.  As is, it works fine and it allows people to organically roleplay by finding a creepy item and acting creepy with it.  But once in a while it causes asspain.

So yeah, bite the bullet and make it an antag thing like a wizard survivor antag.  It'll change the dynamic and probably make happy mask wearers behave worse (and crew kill them more) but it'll save trouble about people bitching the guy wearing the evil mask did something evil.

**Comment by Shadowmech88** [comment] 2016-06-16 18:22
If it's made into an antag item, then it should also be made into a large artifact.

**Comment by ihadtoregisterforthis** [comment] 2016-06-16 18:50
Street-wise having the happiest mask means valid

**Comment by NigglyWiggly** [comment] 2016-06-16 19:46
I always figured it only meant valid if you were in medbay

**Comment by Intigracy** [comment] 2016-06-16 20:05
I think we should change it so it damages people around it slightly over time, with the shading thing being turned into an attack_self (aka the hud button in the top left) so it's INTENTIONAL

Maybe the happy objective too

**Comment by Allspice** [comment] 2016-06-16 20:29
Niggly, current mask wearers are fishing for griff regardless of their location, so they should be valid regardless of their location. And it would be "gay as fuck" if any administrative action was taken towards someone who removed a mask wearer from the round.

**Comment by AutismSpider** [comment] 2016-06-16 20:33
its why i camp the shit out of the bar/medbay when i do play greysuit to beat people to death/weld them in a locker.

Mask users are fishing for griff then cry bitch tears when killed for it.

**Comment by Killette2** [comment] 2016-06-16 22:07
I think mask wearers are valid, because we ALL know what the mask does, and you're just a huge asshole if you ever think it's a good idea to put it on.

**Comment by Allspice** [comment] 2016-06-17 01:49
Killette, like I've said before, the problem is that "valid in medbay" creates a chilling effect against collecting the valid before it niggers people over irreparably. Will the current active admins ban you or give you a pat on the back? WHO KNOWS.

**Comment by Killette2** [comment] 2016-06-17 04:17
It doesn't matter if they're in engineering. Happiest mask should mean valid because it could affect anyone at any place, and there's no reason to put it on other than to make other people shades. It doesn't heal you, it doesn't have good stats, it just shades people. It's for grief, and if you wear it it's your own ass at risk.

**Comment by nuklearcellphoneg** [comment] 2016-06-17 05:34
@Killette2

Like three years ago I thought an emagged janiborg could knock a person into a laying state, walk over their body, and then shred it to pieces.

Like three months ago I thought there were only three transfer valves in Toxins.

So not everyone knows what it does, even the person wearing the mask, or what it means.

Literally the only problem with the item right now is this:

1) You put on the mask

2) You turn people into shades

3) The people you turn into shade flip their shit because you're not a legal antagonist.

And since yes, wearing the mask kiiiind of already makes you valid, antags probably aren't going to use it anyway. Might as well turn it into an antag ticket. Knock up the rarity as a balance if you want.

**Comment by Allspice** [comment] 2016-06-17 07:04
>wearing the mask kiiiind of already makes you valid

Even the headmin is waffling on it. Yes or no, Nuke: Happy mask wearers are valid as salid, regardless of any other actions or locations.

**Comment by nuklearcellphoneg** [comment] 2016-06-17 07:08
No, I'm saying to change the mask to them an antag listed at round end, because otherwise the players are going to complain on both sides when people die or get shaded as a result.

**Comment by AutismSpider** [comment] 2016-06-17 10:11
Base on same fucking mask form risk of rain same icon and all.

Does the same thing like come on putting it on you know some thing bad going happen.

**Comment by nuklearcellphoneg** [comment] 2016-06-17 10:13
Ah right I forgot that playing through Risk of Rain was compulsory for being on this server.

I have Risk of Rain and I haven't beat it and I've never seen the mask and as far as I knew it was just some weird mask and I had no idea it was from Risk of Rain.

**Comment by Allspice** [comment] 2016-06-17 10:32
Pick up the "mysterious d20", get a sinister message. Toss it, get cluwned, you were fucked over by something you might not have had knowledge of. Such is spess.

Pick up the happy mask, get a sinister message. Wear it, get a long walk out a short airlock, you were fucked over by something you might not have had knowledge of. Such is spess.

**Comment by nuklearcellphoneg** [comment] 2016-06-17 10:43
http://ss13.moe/forum/viewtopic.php?f=20&t=2593&p=11938&hilit=happiest+mask#p11938
if everybody knows why do we have to respond to ahelps about it

**Comment by jknpj** [comment] 2016-06-17 18:02
I like to keep a mask and souls stones with me because it can turn the tables against murderbones/suicide bombing inside the shuttle and help gibbed people. It's a way to bring everyone back when there is no time to bring them back or no medbay crew left alive. It's a tool, how you use it defines if you're valid or not.

Also, don't make it a large artifact. I'm already tired of <s>wasting my luck with griff or dud artifacts</s> being lynched for bringing large artifacts(even if they are non-lethal and useful, like healers). Don't turn Xenoarch into Toxins 2.0. You can just remove it completly and make it vault-only if you want to make it another turn-into-antag item.

**Comment by ghost** [comment] 2016-06-20 06:36
Every time I play miner and spend more than 10 minutes on the roid I find at least one of these. Hell, I've found 3 in one digsite before, and find 2 regularily enough. And what you're saying about bringing people back is straight ass. Unless you are a moron it is incredibly easy to work the cloner and such to save people, there are a few doors and if you have to, smash the god damn windows. Being brought back as a shade is not the same as being brought back into the round by other means. You are bound to another persons will, fragile enough that food shot from a vendor or anything thrown at you will kill you, which results in permentant removal from the round as your character.
I made it clear how I feel about this item in the ban request I wrote. By having it actually turn people into an antag you're just giving people even more free tickets to grief. Play Miner, don't get antag? Oh I'll just ruin every digsite until I find the mask and then go back to the station and kill everyone with my 12 guns I found on the way, the spur and these 4 goliaths I lazarused. 
It would work better as a large actifact, yes, but if you're going to make it give an antag status still then it's just stupid to even have it. 
It's the sort of item which should be a tool for people who are already antags.

**Comment by nuklearcellphoneg** [comment] 2016-07-26 05:37
http://ss13.moe/forum/viewtopic.php?f=18&t=2695

**Comment by jknpj** [comment] 2016-07-26 11:51
I changed my point of view, the thing needs to fucking go and stay go. Or maybe we could make it do the same amount of damage to it's wearer of the manifest ghost rune, so people won't rush to shade people at medbay for laughs and giggles.

**Comment by Shadowmech88** [comment] 2016-07-26 19:39
Or make it a large artifact instead of a small one so miners don't stumble onto five of them during any given round.

**Comment by nuklearcellphoneg** [comment] 2016-07-27 03:32
Again, my gripe is this: It doesn't make you an antag, but it makes you basically valid, and there's no rule for this, and because it's not really a central component of the game I don't really want to address it in the rules... it's a frustrating item.

**Comment by Killette2** [comment] 2016-07-27 05:44
Well what about this. What if the ITEM was reworked instead of the rules? It would still have the same concept of risk of rain in making shades, but what if it worked differently? Such as maybe putting it on gives you a spell where you can activate that THEN puts all corpses in an AoE into bodies of shades. That makes the owner more liable for what the fuck are you doing, especially if they repeat use(read: abuse) the item.

I think this would be a great, and a QoL change to the mask all together, what do you all think?

**Comment by nuklearcellphoneg** [comment] 2016-07-27 07:22
I think a six stack of bodies at medbay would be quite unhappy.

**Comment by Killette2** [comment] 2016-07-27 09:54
It's something that can easily be logged since it's a spell, requires manual use rather than a passive effect, and if you do it more than once you know what's up. Also it should be given a name that makes it's effect obvious so you DON'T decide it would be a great idea to raise bodies in medbay.

If medbay was that backed up anyways, it would probably be merciful, but not encouraged.

**Comment by nuklearcellphoneg** [comment] 2016-07-27 10:02
> bomb
> six dead bodies

**Comment by clusterfack** [comment] 2016-07-27 12:21
What if it didn't make you uncloneable

**Comment by jknpj** [comment] 2016-07-27 13:19
@Shadowmech88
NO MORE DUD LARGE ARTIFACTS

What about a "Are you sure you want to put the mask?" confirm box explaining what the mask does when you try equip it?

**Comment by ghost** [comment] 2016-08-28 16:29
So if it's been a problem since june, why hasn't it been addressed?

**Comment by PJB3005** [comment] 2016-08-28 17:06
None of the coders cared enough.

Period.

**Comment by Killette2** [comment] 2016-08-29 10:02
Welcome to the github :smile:

**Comment by SonixApache** [comment] 2016-08-29 15:47
REMOVE MASK

MAKE IT AN ANTAG ITEM LIKE THE VIAL OF CHANGELING BLOOD / VAMPIRE MASK

**Comment by ghost** [comment] 2016-08-29 15:47
I'll get to moving it to 'artifact spawn' tier for vaults in a minute then.

**Comment by SonixApache** [comment] 2016-08-29 15:52
I was about to just remove it from all loot lists, your idea seems better.

**Comment by nuklearcellphoneg** [comment] 2016-08-31 19:58
h-h-h-hello s-s-s-s-shonny did ya say yer was gon look at my i-i-i-ishew?

**Closed as completed** 2017-02-13 01:21 UTC
Labels: Balance, Logging / Administration
