### ISSUE TITLE
[Box] Cargo / recycling conveyors are reversable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7004] opened 2015-12-13 20:19 UTC
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> fff91a99b2aac407acaf80f898f014ea0823b9ee 
> 
> General description of the issue
> The conveyor belts for Shuttle output and recycling (near the custodial closet) are reversable, which is pretty annoying.

**Comment by PJB3005** [comment] 2015-12-13 20:20
Dupe of #6923

**Closed as completed by PJB3005** 2015-12-13 20:20 UTC
