### ISSUE TITLE
Thermal goggles fuck up your vision

### ISSUE THREAD

**Issue by mikecari** [d3athrow/vgstation13#10509] opened 2016-06-11 16:24 UTC
![bug](https://cloud.githubusercontent.com/assets/10235107/15986177/5ff43f26-2fcf-11e6-9636-8623a8549ef8.png)

Why is this allowed

**Comment by ghost** [comment] 2016-06-11 16:24
byond bug

**Comment by 9600bauds** [comment] 2016-06-11 16:36
Dupe of #10479, disable parallax until fixed

**Closed as completed by 9600bauds** 2016-06-11 16:36 UTC
