### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14848] opened 2017-05-16 13:11 UTC
(WEB REPORT BY: alamier REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
4046bcd50d17ce33e0b88779edffea06fe3e93f7 

>General description of the issue
https://i.gyazo.com/22b18cad1a2f08191a8c429bc2d724da.png

>What you expected to happen
For it to work like usual

>What actually happened
It didn't work

>Steps to reproduce if possible
The only thing I did was add a name to the string detector and then closed the game after the round was over
Few hours laters I load the station again and it just never worked again

**Comment by BestName** [comment] 2017-05-16 17:26
Duplicate of #11626
For a workaraound see: https://github.com/vgstation-coders/vgstation13/issues/11626#issuecomment-248283321

**Comment by Exxion** [comment] 2017-05-17 02:49
That it is

**Closed as completed by Exxion** 2017-05-17 02:49 UTC
