### ISSUE TITLE
(WEB REPORT BY: saronsen REMOTE: 198.245.63.50:7777) Supermatter shard TOO hungry

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4237] opened 2015-05-02 07:27 UTC
>Revision 
32a7db78a474c93f6451c063fcc56a9488b5e3cc

>General description of the issue
Supermatter shard sketch as fuck when being pulled. It seems to just randomly eat cyborgs as they pull it along, or try to pull it. 

>What you expected to happen
Supermatter shard to not eat me as I'm pulling it

>What actually happened
YOU SLAM INTO SUPERMATTER SHARD AS YOUR EARS ARE FILLED WITH AN UNEARTHLY RINGING

>Steps to reproduce if possible
Drag around shard at high speeds as a borg

Take sharp turns towards other players

**Comment by PJB3005** [comment] 2015-05-02 07:45
Odd, my guess it something like atmos movement that's causing this.

**Comment by clusterfack** [comment] 2015-05-02 07:57
Or perhaps related to drag slipping

**Comment by clusterfack** [comment] 2015-05-02 21:59
I confirmed its related to drag slipping

**Comment by clusterfack** [comment] 2015-05-02 22:00
Duplicate of #3771

**Closed by clusterfack** 2015-05-02 22:00 UTC
Labels: Bug, Needs Moar Testing
