### ISSUE TITLE
cup ramen now knocks you out due to its temperature

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34975] opened 2023-09-04 21:16 UTC
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
f50f58e093be7d81c113c9e40c8908bce89088bf

# Description
see title
# Steps to Reproduce
buy a cup ramen from the vendomat
pour water so it heats
drink it
# What you Expected
a tasty cup of ramen
# What Actually Happened
paincrit, burnt head

#34842 is at fault for this

**Comment by CrazyAmphibian** [comment] 2023-09-04 21:21
just hope that #34855 gets merged so that you have to wait before stuffing your face full of noodles, the ultimate immersive experience. very realistic.

**Comment by Eneocho** [comment] 2023-09-05 17:34
Literally the same issue from the last attempt at reagent temperature fuckery.

**Comment by Hinaichigo** [comment] 2023-09-05 21:36
I'm guessing this is because chemical reactions that release heat just set adjust the temperature of the resulting mixture by a fixed amount instead of adding a definite quantity of heat, so if the reaction happens in multiple steps it ends up adding more heat than expected.
Seems like adding water triggers the calcium hydroxide reaction twice so you end up getting +47 degrees two times.
That being said one sip of the 114 C ramen will just do a little burn damage. But if you keep sipping it the pain from each sip stacks. Even if you scarf the whole thing down it's not actually enough to burn you into crit but just the hallucinated damage caused by pain that makes you faint for a bit.

I think setting `react_discretely` to false on the calcium hydroxide reaction would mask this to an extent, unless you deliberately added 1 unit with a dropper and then 1 unit again, but probably the ideal thing would be to change the fixed temperature increase to a fixed energy increase, that way the thermal mass of the ramen can "absorb" some of the heat.

**Closed as completed** 2023-10-20 22:20 UTC
