### ISSUE TITLE
revived as a monkey

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12243] opened 2016-10-17 06:11 UTC
(WEB REPORT BY: jcamleo REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> revived as a monkey and was unable to change back to human
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment] 2016-10-17 06:12
What in fuck's name is this even supposed to mean?

**Comment by Exxion** [comment] 2016-10-17 06:14
Actually, this is either a dupe of #11937 or too shit a report to be helpful.
Unless someone who knows what this guy means shows up and says it isn't the aforementioned report, bye

**Comment by TheFriggenSawbones** [comment] 2016-10-17 06:15
it's #11937 please fix it already

**Closed as completed by Exxion** 2016-10-17 06:14 UTC
