### ISSUE TITLE
Grey Pressure Helmets are invisible and hide worn head items

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#11664] opened 2016-08-29 15:40 UTC
#### Description of issue

Grey-specific pressure helmets from the crate acquired from cargo are invisible, and hide everything worn on a person's head when worn.
#### Difference between expected and actual behavior

I was supposed to be running around with a 80's style fishbowl on my head but I end up with everything on my face being hidden.
#### Steps to reproduce

Be grey
put a pressure helmet on
#### Specific information for locating

/obj/item/clothing/head/helmet/space/grey
#### Length of time in which bug has been known to occur

A month or so at least.
#### Server revision

039026b30d57f7de13dd028faf88152b571c16ec 
#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment] 2016-08-29 15:42
Seems that the conversion to and from 64x64 fucked a lot of sprites that used transparency. The grey fishbowl helmet being one of them

**Comment by clusterfack** [comment] 2016-08-29 17:18
???
64x64 was totally undone, the only things still on it are some of the lobby screens

**Comment by ghost** [comment] 2016-08-29 17:19
And the R-UST sprites and such.

They seemed to have totally disappeared around the time 64x64 came in, I'll check to see if something went wrong with another PR

**Comment by JustSumBody** [comment] 2016-08-30 10:46
The head of security cap and cult space helmet are also not appearing from what I've seen.
They're all in the general head.dmi, but not in grey/head.dmi so maybe it has species_fit for greys but no grey specific sprite?

**Comment by Exxion** [comment] 2016-08-30 12:17
I do believe the problem may be that someone forgot to use BYONDTools

**Comment by Exxion** [comment] 2016-08-30 15:25
Actually I can't read and shouldn't post when tired

**Comment by unid15** [comment] 2016-08-30 17:36
I believe 64x64 wasn't totally undone, the sprites were just resized to 32x32 using the same script that enlarged them to 64x64 in the first place

It's plausible that this was caused by the script

**Comment by Exxion** [comment] 2016-08-30 17:51
No, it was reverted properly
Well, manually, but properly
The pre-conversion files were checked out and committed

**Closed as completed** 2016-09-02 15:22 UTC
Labels: Bug / Fix
