### ISSUE TITLE
Cannot save special roles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13511] opened 2017-01-17 07:05 UTC
(WEB REPORT BY: jackrip REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

26e7b2fefc22bb29447d647add5e4f9de86bf125 

>General description of the issue
When going to settings > Special roles, after choosing roles and hitting submit, nothing happens. I have exited out of my client and restarted to no avail.

>What you expected to happen
I would be able to pick my special roles and have them save

>What actually happened
they didnt save

>Steps to reproduce if possible
see above

**Comment by Probe1** [comment] 2017-01-17 07:47
Duplicate.
We're aware.
We don't know what's wrong and can't reproduce it.

**Comment by N3X15** [comment] 2017-01-17 10:07
Duplicate of #7686

**Closed as completed by N3X15** 2017-01-17 10:07 UTC
