### ISSUE TITLE
Being Decoverted Erases Entire Memory

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18397] opened 2018-06-01 01:54 UTC
(WEB REPORT BY: otatoh REMOTE: 172.93.109.202:7777)
# Revision
db60d44def7b33f1453e06395b22485659561852

# Description
Being deconverted as a cultist erases everything in your notes tab, including your bank number and PIN.

# Steps to Reproduce
Be cultist, get waterboarded, go to the ATM.

# What you Expected
PIN and account number in memory.

# What Actually Happened
Notes tab is entirely blank. No account number/PIN.

**Comment by DamianX** [comment] 2018-06-01 01:55
duplicate of #14414

**Closed as completed by DamianX** 2018-06-01 01:55 UTC
