### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Derelict powernet is wonky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3942] opened 2015-04-16 12:25 UTC
>Revision (Should be above if you're viewing this from ingame!)
8c5577c833e51a7ee15e6ac1ef741753323eb6f6 

>General description of the issue
PSU charging without being connected to solars, research APC not charging or detected even though it was connected to the powernet

>What you expected to happen
PSU should not charge without input power, APC should charge when connected to powernet.

>What actually happened
The opposite

>Steps to reproduce if possible
I knot-wired at first then made the wires smoot, now I have a smooth cable to reseach APC and a loose end from the PSU not touching anything.

**Comment by Starnightx** [comment] 2015-04-17 13:41
Yeah that PSU thing is weird

**Comment by clusterfack** [comment] 2015-04-23 12:50
I think you fucked up the wiring buddy

**Comment by clusterfack** [comment] 2015-04-25 16:55
Didn't realize earlier but this is a duplicate of #4095

**Closed by clusterfack** 2015-04-25 16:55 UTC
Labels: Bug
