### ISSUE TITLE
'Setup Special Roles' doesn't function at all

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8675] opened 2016-03-06 09:19 UTC
(WEB REPORT BY: freakinabonk REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2edef6b3f60c28c90a610d785be130fa30d52448 
> 
> General description of the issue
> The 'Setup Special Roles' button under preferences will not save anything inputted into it when the submit button is clicked.
> 
> What you expected to happen
> I expected it to change my preference for answering 'no' to spawning as an alien/larvae to a 'yes' once I clicked the submit button.
> 
> What actually happened
> The submit button didn't work; window stayed open, when closed and reopened, my preference was still set to 'no'.
> 
> Steps to reproduce if possible
> Preferences>Setup Special Roles>Change a role from it's usual setting, press submit when finished.

**Comment by Exxion** [comment] 2016-03-06 21:40
I think this is a dupe, but I can't find the other issue

**Comment by Exxion** [comment] 2016-06-30 19:20
Oh hey I found it
#7686

**Comment by Exxion** [comment] 2018-10-02 00:46
Duplicate of #7686

**Comment by Exxion** [comment] 2018-10-02 00:47
What's the fucking point of marking something as a duplicate if it doesn't autoclose the dupes?

**Closed as completed by Exxion** 2018-10-02 00:47 UTC
Labels: Logging / Administration
