### ISSUE TITLE
deff cargo shuttle MAP PROBLEM

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16801] opened 2017-12-17 04:37 UTC
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description
second time today i got a message that cargo shuttle had no atmos, the floor under the heaters of the shuttle was gone both times

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Pathid** [comment] 2017-12-17 04:59
Duplicate of https://github.com/vgstation-coders/vgstation13/issues/16701
Fixed by https://github.com/vgstation-coders/vgstation13/pull/16741

**Closed as completed** 2017-12-17 15:13 UTC
Labels: Bug / Fix
