### ISSUE TITLE
Move to top command doesn't do anything anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19734] opened 2018-09-21 00:10 UTC
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
d10f21b723966fddc3fcf5120656277909d14ad3

# Description

On the tin
# Steps to Reproduce

Try using move to top
# What you Expected

It to work
# What Actually Happened

It no work

**Comment by Exxion** [comment] 2018-09-21 02:01
Right, since BYOND changed how it layers objects on equal plane and layer sometime in 512
To be fair we never should have relied on the old behavior

**Comment by DamianX** [comment] 2018-09-21 11:03
duplicate of #19063

**Closed as completed by DamianX** 2018-09-21 11:03 UTC
Labels: T-Thanks BYOND, Feature Loss

**Comment by Exxion** [comment] 2018-09-21 15:38
You know we can actually mark things as duplicate now
We should do that instead of just closing them
Like this:

**Comment by Exxion** [comment] 2018-09-21 15:38
Duplicate of #19603

**Comment by Exxion** [comment] 2018-09-21 15:39
God damn it I fucked up hold on

**Comment by Exxion** [comment] 2018-09-21 15:40
Duplicate of #19063

**Comment by Exxion** [comment] 2018-09-21 15:40
I hate mobile

**Comment by DamianX** [comment] 2018-09-21 15:42
it's case-sensitive for reasons that are beyond me, okay

**Comment by Exxion** [comment] 2018-09-21 15:45
It has to be *exactly* that post
This used to not be the case but I guess people complained about accidentally using the feature or something
