### ISSUE TITLE
(WEB REPORT BY: h0l3m4k3r REMOTE: 198.245.63.50:7777) RnD fucked up by destructor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4574] opened 2015-05-21 01:46 UTC
>Revision (Should be above if you're viewing this from ingame!)
>General description of the issue
Destro analyzer fuck shit up
>What you expected to happen
Item destructed, RnD got research levels
>What actually happened
Item destructed, Destructor bugs out, console freezes. Destro is busy for indefined amount of time
>Steps to reproduce if possible
Put shit in, deconstruct, done: shit fucked up
>Workaround:
Disconnect protolathe, so material transfer process wouldnt start.
Items desctructs ok this way.
Cause this bugs happens only with proto connected, i assume it's material transfer code.

**Comment by 9600bauds** [comment] 2015-05-21 01:50
You're entirely correct that it's the material transfer code, nice job
Duplicate of #4568 though

**Closed** 2015-05-21 04:52 UTC
