### ISSUE TITLE
Amputated Arms Do Not Show on Sideways Sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25145] opened 2019-11-22 18:36 UTC
(WEB REPORT BY: dtscurvy REMOTE: 206.221.180.138:7777)
# Revision
d55fd80a6841f44f28c9c70f840a03fdea1c7ae1

# Description
When a character missing an arm faces left or right, their arm will appear as if still there.

# Steps to Reproduce
Play a character with a missing arm, roundstart or otherwise, and face to the left or right. May vary depending on clothing.

# What you Expected
The arm to be displayed missing as it is when a character faces up or down.

# What Actually Happened
The sprite is default.

**Comment by Blithering** [comment] 2019-11-23 14:50
They should be properly gone, if you're thinking of the phantom hand that shows when you're wearing a jumpsuit, it's actually your buttcheek showing through a hole due to the way jumpsuits are sprited.

**Comment by DamianX** [comment] 2019-11-23 16:44
Duplicate of #22223

**Closed as completed by DamianX** 2019-11-23 16:44 UTC
