### ISSUE TITLE
(WEB REPORT BY: redun REMOTE: 198.245.63.50:7777) Double cultist

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3701] opened 2015-04-02 19:10 UTC
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
So I spawn ,round start as a cultist, two papers, two sets of the same objectives, hear cult speak and nar nar speak twice, etc.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible
No idea how it happened in the first place, antag lists might be bugged?

**Comment by clusterfack** [comment] 2015-04-08 06:58
Could he have been picked as cultist, twice? Is there sanity against that sort of thing?

**Comment by Kurfursten** [comment] 2015-11-02 22:26
@deitylink Has anyone ever been able to reproduce this as far as you've heard of?

**Comment by DeityLink** [comment] 2015-11-03 06:08
Looks like his mind got added to ticker.mode.cult twice. I need more info on what happenned that round. It's possible that there's only been 3 starting cultists and he counted for 2.

**Comment by DeityLink** [comment] 2015-11-03 09:59
Successfully reproduced on the server by manually adding the same mind to cult twice.

**Comment by xpcybic** [comment] 2016-05-12 15:53
Fixed in #9865

**Closed** 2016-05-12 16:03 UTC
Labels: Bug / Fix
