### ISSUE TITLE
[Box] The hot loop on the TEG leaks.

### ISSUE THREAD

**Issue by Rydax** [d3athrow/vgstation13#2518] opened 2015-01-14 04:19 UTC
The hot loop on the thermo-electric generator in engineering leaks.

**Comment by dylanstrategie** [comment] 2015-01-14 12:15
Can you locate the source of the leak if possible ?

**Comment by ComicIronic** [comment] 2015-01-14 22:25
Leaks into space, or just loses gas over time? This may be a maths issue.

**Comment by wild-billy** [comment] 2015-01-15 05:45
Strange, the cold loop is more prone to gas loss from rounding errors (small numbers)

**Comment by ComicIronic** [comment] 2015-01-15 18:53
Which is why I was wondering. "Leaks" would suggest that some gas is somehow escaping, but I can't think how that would happen. So I assumed it was a rounding error.

Maybe due to very small moles + very high pressure in transfer breaking Byond's float limit?

**Comment by SarahJohnson489** [comment] 2015-01-22 07:29
AFAIK, It's partly that something is chilling, so your pressure is plummeting, the hot loop when it shouldn't. While I want to think it's a vacuum floor like the old issue in toxins I don't have the problem in older versions that have vacuum floor in the burn chamber. Either way it entirely kills the TEG stone dead. It's an uphill war to get any significant power out of it.

And then there's the issue with the hot loop heat circulator. You have to wrench then rewrench it to attempt to decurse it. It's like on mapgen the pipe code rarely glitches out and the heat circ is outputting into a nonexistant pipe and destroying the gas in the process.

**Comment by Probe1** [comment] 2015-09-26 00:36
Working as intended, close this one.  The hot loop has a passive vent for it to explicitly leak and the hot loop loses temperature as it meets the cold loop and generates power.

**Closed** 2015-09-26 01:52 UTC
Labels: Map Issue (Box), Needs Moar Testing
