### ISSUE TITLE
Gumshoe: Blood no longer appearing red

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28603] opened 2021-01-16 21:49 UTC
(WEB REPORT BY: germansanta REMOTE: 206.221.180.138:7777)
# Revision
https://prnt.sc/wx779s

# Description
Same as issue
# Steps to Reproduce
Join as Gumshoe Detective. Look at blood.
# What you Expected
Red Blood
# What Actually Happened
Grey Blood

**Comment by Dacendeth** [comment] 2021-01-16 21:51
Has noir ever worked with blood here? It's been like this for years as far as im aware.

**Comment by ShiftyRail** [comment] 2021-01-16 22:03
Maybe the very first iterations of it.

**Comment by djkramer123** [comment] 2021-01-17 03:50
It used to work, years ago, good luck finding a coder that cares given how often it's bug reported.

**Comment by robintime** [comment] 2021-04-24 07:13
duplicate of #21866

**Closed as completed by robintime** 2021-04-24 07:13 UTC
