### ISSUE TITLE
Hydroponics trays are completely functional when unbolted

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17142] opened 2018-01-20 07:19 UTC
Splitting https://github.com/vgstation-coders/vgstation13/issues/13605#issuecomment-274475846

> Hydroponics trays are completely functional when unbolted, and even when stacked, leading to the current meta of just unwrenching all the trays and stacking them near the vendors and using alt-click to plant/harvest/etc them

**Comment by Kurfursten** [comment] 2018-01-20 08:42
What if we made trays dense *only when unanchored*

This means you could also push them around as you please, but you would not be able to stack them.

**Comment by DamianX** [comment] 2018-01-20 08:45
You could still deconstruct them and build machine frames on top of one another, then rebuild. I guess rather than trying to prevent stacked things I think it would be best to incentivize NOT stacking things, somehow.

**Comment by Kurfursten** [comment] 2018-01-20 08:47
It would be substantially harder though and effort matters. Take for example that you technically *can* refill a tray's water, fertilizer, and kill the weeds by deconstructing/reconstruction.

You could have it check for the presence of another machine on its tile when determining how much light it gets. Trays stacked on trays wouldn't be good for lighting.

**Comment by CptWad** [comment] 2018-01-21 00:26
I mean why bolt them on the floor in the first place
just make them not able to be put on top of eachother like crates but are otherwise movable by will

**Comment by Kurfursten** [comment] 2018-01-21 01:21
ZAS

**Comment by CptWad** [comment] 2018-01-21 09:31
oh right, dangerous space station
damn shame

**Comment by DeityLink** [comment] 2024-08-18 10:34
Duplicate of #13723

**Closed as not planned by DeityLink** 2024-08-18 10:34 UTC
Labels: Consistency Issue
