### ISSUE TITLE
Humanized Monkies always have the same hair / facial hair style

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#8899] opened 2016-03-18 01:38 UTC
Also female humanized monkies have mustaches. 
![monkey trouble](https://cloud.githubusercontent.com/assets/6353372/13866101/175019ce-ecaa-11e5-9b92-3c92dae4e9a3.png)

Steps to reproduce.
1. Acquire monkies
2. Acquire monkey to human DNA injectors
3. Turn your monkies into ugly freaks with nasty disgusting hair.

**Comment by ihadtoregisterforthis** [comment] 2016-03-18 01:43
That's the Real American 'stache you're dissing

**Comment by 9600bauds** [comment] 2016-03-18 04:44
Dupe of issue I am too lazy to find but it's there

**Closed as completed by 9600bauds** 2016-03-18 04:44 UTC
