### ISSUE TITLE
Asteroids are not smoothed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11322] opened 2016-08-06 22:15 UTC
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a96dfa85f92e6bfbb2fab9b597d2056964ea5537
> 
> General description of the issue
> http://puu.sh/qsdrJ/29a14aaa81.png
> 
> What you expected to happen
> The asteroid having smoothed edges
> 
> What actually happened
> The asteroid is sharp and square.

**Comment by Exxion** [comment] 2016-08-06 22:33
Duplicate of #10901

**Closed as completed by Exxion** 2016-08-06 22:33 UTC
