### ISSUE TITLE
(WEB REPORT BY: megamaw REMOTE: 198.245.63.50:7777) I can't print manuals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3791] opened 2015-04-06 02:27 UTC
>Revision 3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>General description of the issue
I literally can't print manuals. I've tried time after time. Something must have broken it.

>What you expected to happen
A manual to be printed.

>What actually happened
No manual.

>Steps to reproduce if possible
Click on a manual name. Watch as it doesn't print!

**Comment by NigglyWiggly** [comment] 2015-04-06 04:04
https://github.com/d3athrow/vgstation13/issues/3655
Library stuff is still a bit wonky after the big overhaul thing

**Comment by clusterfack** [comment] 2015-04-25 17:04
Duplicate of #3655

**Closed by clusterfack** 2015-04-25 17:04 UTC
Labels: Bug, Feature Loss
