### ISSUE TITLE
Softboiled color stays black and white

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19613] opened 2018-09-06 17:48 UTC
(WEB REPORT BY: vonzippenstein REMOTE: 172.93.109.202:7777)
# Revision
34f72c28e6be4f001e3c6b8bd05d1747097c7671

# Description
Vision went black and white after a genetics SE injection with the hardboiled noire detective gene. Reverted it with a clean block and my colors are still black and white.

# Steps to Reproduce
Inject yourself with the noire gene. Then inject yourself with a clean SE.

# What you Expected
Colors to return to normal and the message "You now feel softboiled."

# What Actually Happened
Just the message "You now feel softboiled" but you vision stays black and white.

**Comment by vonzippenstein** [comment] 2018-09-06 17:50
Just did a client reconnect and it fixed it.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment] 2018-09-06 18:19
Dupe of #19569 and https://github.com/vgstation-coders/vgstation13/issues/19569 and https://github.com/vgstation-coders/vgstation13/issues/12080#issuecomment-412379122 and https://github.com/vgstation-coders/vgstation13/issues/18491 and related to https://github.com/vgstation-coders/vgstation13/issues/19280#issuecomment-412379104 and #16944
is fixed by relogging and caused by animate() not playing nice anymore for some reason

**Comment by Kurfursten** [comment] 2018-09-06 20:51
I found a solution for this which is to set the player's client color to null. Tested on live with a willing subject.

Also he informed me that the NOIRBLOCK although active was not actually setting his color at roundstart and it was only after I toggled it off did it animate to black/white.

Unfortunately I believe this means no more fun 'slow transition to black/white' but it's better than being broken, no?

**Comment by BarneyGumball** [comment] 2018-10-16 20:11
I think I have a fix ready for this, but as per [this bug report](http://www.byond.com/forum/?post=2405465), resetting `client.color` is bugged in `512.1453`.  When the new version is out, I'll finalise the fix and put it up.

**Comment by Exxion** [comment] 2018-10-17 03:54
Only in 1453, which came out long after this report was made

**Comment by BarneyGumball** [comment] 2018-10-17 04:04
It wasn't a Byond bug.  The Byond bug is unrelated to this issue, it's just coincidental that resetting the client's colour matrix doesn't work properly right now (and means the fix for this can't be merged until we're on the new version).

This issue was caused by the steaming load of garbage that is `update_colour()`.  For example, it won't apply an overlay unless the current colour matrix is the default one, or it found no difference between the matrices.  So obviously, when you try to set the colour matrix back to the default, `update_colour()` says fuck you and does nothing.

**Closed as completed** 2018-12-03 10:03 UTC
Labels: Bug / Fix
