### ISSUE TITLE
Extended rolls too often.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29469] opened 2021-05-07 16:57 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
make it lower please I beg of you

**Comment by Kurfursten** [comment] 2021-05-07 18:16
Duplicate of https://github.com/vgstation-coders/vgstation13/issues/29467

**Closed as completed by Kurfursten** 2021-05-07 18:16 UTC
