### ISSUE TITLE
You can't secure Field Generator to space!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7088] opened 2015-12-17 02:53 UTC
(WEB REPORT BY: intigracy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e24
> 
> General description of the issue
> https://dl.dropboxusercontent.com/s/oppasod8sub0s4i/2015-12-16_18-52-37.png?dl=0
> 
> What you expected to happen
> Wrench
> 
> What actually happened
> https://dl.dropboxusercontent.com/s/oppasod8sub0s4i/2015-12-16_18-52-37.png?dl=0
> 
> Steps to reproduce if possible
> https://dl.dropboxusercontent.com/s/oppasod8sub0s4i/2015-12-16_18-52-37.png?dl=0

**Comment by PJB3005** [comment] 2015-12-17 02:55
Dupe of #6243

Reminder that this is @dylanstrategie's fault.

**Closed as completed by PJB3005** 2015-12-17 02:55 UTC
