### ISSUE TITLE
Paint buckets break interacting with canvases

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31797] opened 2022-01-06 01:07 UTC
(WEB REPORT BY: fargit REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
Using a paint bucket on a large canvas doesn't paint it that color, it just manages to empty the paint without taking off the lid
# Steps to Reproduce
Get a bucket of paint, click on a canvas.
# What you Expected
It to tell me the can isn't open, or the canvas to be all that color.
# What Actually Happened
Paint was splashed onto the canvas, didn't apply and the can wasn't even opened. Opened it to find it empty.

**Comment by jellyveggie2** [comment] 2022-01-06 09:03
Not the kinda present I expected to wake up to on three kings day.
Let's get things straignt, what I'm reading here is:
- [ ] Bug report: Paint cans ignore lids when used on a canvas, end up empty.
- [ ] Feature request: Paint cans should paint a canvas when used on it.

Couldn't reproduce the issue with paint ignoring lids, but I can see that using the paint cans on anything other than a floor does consume the whole can without changing the sprite to an empty can (do we even have an empty paint can sprite?). I don't know enough about reagent container code to fix that and I'll be too busy later today to figure it out, but getting it to paint a canvas should be quick and easy enough.

**Comment by west3436** [comment] 2024-03-12 13:34
Fixed via #31798

**Closed as completed by west3436** 2024-03-12 13:34 UTC
