### ISSUE TITLE
ZAS still slips you through boots sometimes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27866] opened 2020-09-21 00:11 UTC
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
9235a1c75374f52dea6a9a7da710d8b4170f9309

# Description
ZAS still stuns and slips through magboots seemingly at random

# Steps to Reproduce
walk into an airlock while wearing activated magboots 

# What you Expected
magboots to do their job

# What Actually Happened
shifty

**Comment by DamianX** [comment] 2020-09-21 11:27
Duplicate of #26988

**Closed as completed by DamianX** 2020-09-21 11:27 UTC
