### ISSUE TITLE
TRASH BAG PERMANENTLY GLUED TO SELF WHEN WORN WHILE FAT

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#26519] opened 2020-05-17 12:49 UTC
1. wear trash bag on exosuit sprite

2. become fat

3. can't remove trash bag

4. become thin

5. STILL can't remove trash bag

6. trapped as a trash man forever

**Comment by drawsstuff** [comment] 2020-05-17 13:36
you are what you eat

**Comment by RealestEstate** [comment] 2020-05-17 19:39
I believe this has been reported before

**Comment by DamianX** [comment] 2020-12-01 03:55
Duplicate of #20842

**Closed as completed by DamianX** 2020-12-01 03:55 UTC
