### ISSUE TITLE
Wizards summoned Crystal Butterflies from the new knife don't self-destruct as they are supposed to.

### ISSUE THREAD

**Issue by Fruktlimpa** [d3athrow/vgstation13#17734] opened 2018-03-04 19:49 UTC
Be Wizard
Summon your crystal butterfly
Wait 20 seconds
It is still there
Summon another one and flood the station with your snowflake vicerators.

Damian asked me to check its Autodie var and it was set to 0.

#17275

**Comment by WhiteHusky** [comment] 2018-03-04 19:53
Duplicate of #17733

**Closed as completed** 2018-03-04 20:40 UTC
