### ISSUE TITLE
Goonlights Don't Work on Escape Shuttle

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10394] opened 2016-06-04 23:26 UTC
Other shuttles are fine.
Escape shuttle's pitch black

**Comment by AutismSpider** [comment] 2016-06-05 00:55
Happens with the cargo shuttle to.

**Comment by kol1th** [comment] 2016-06-05 00:56
Don't forget the trader shuttle.

**Comment by Shadowmech88** [comment] 2016-06-05 01:57
Well, it doesn't happen with the Research shuttle. Weird.

**Comment by jknpj** [comment] 2016-06-05 02:35
It does happen with the research shuttle, but only after it arrives in the research outpost, oddly.

**Comment by kol1th** [comment] 2016-06-05 02:55
Seems like it happens when any shuttle moves from its original position.

**Comment by Exxion** [comment] 2016-06-05 04:07
Surprise surprise, those are all the shuttles that don't have lights and instead rely on area luminosity or something

**Comment by kol1th** [comment] 2016-06-05 04:12
I mean, they have light tubes installed.

**Comment by Exxion** [comment] 2016-06-05 04:19
Wait
Which ones?
I'm certain at least some of them don't
Or I'm just crazy

**Comment by Exxion** [comment] 2016-06-05 04:49
Alright, the problem is that the space area doesn't have dynamic lighting, and shuttles START in special shuttle areas that DO have dynamic lighting but most of their destinations just put them in the space area.
I'm not acquainted with lighting code well enough to say why this used to work.

**Comment by unid15** [comment] 2016-06-05 09:04
It probably happens because references to turfs aren't updated (which also causes lasers to become stuck in the air when a shuttle moves)

**Comment by PJB3005** [comment] 2016-06-05 14:56
Nope, the issue is that the new lighting corners in the place the shuttle moves to somehow point to the shuttle's origin as their master turfs.

**Comment by unid15** [comment] 2016-06-05 15:13
That's pretty much what I meant

When a shuttle moves, none of the turfs actually move - instead, their copies are created at the new location and the originals are replaced with space. Variables that reference the original turfs aren't updated, which is what causes this issue

**Comment by PJB3005** [comment] 2016-06-05 15:29
No, actually. Due to performance reasons when a turf first gets `ChangeTurf`'d the corners for it get initialized (so space turfs don't have corners jesus the startup time). For some reason when a shuttle causes this the new corners made at the shuttle's arriving position (which had no corners previously) aren't actually new and actually the corners at the shuttle's old position (???) which fucks everything up.

**Comment by FudgePucker** [comment] 2016-06-05 18:05
Can you give the space turfs for shuttles corners?

**Comment by PJB3005** [comment] 2016-06-06 13:37
Whoops forgot to close this.

**Closed as completed by PJB3005** 2016-06-06 13:37 UTC
Labels: Bug / Fix, Feature Loss
