### ISSUE TITLE
Compressed Matter cartridge bug.

### ISSUE THREAD

**Issue by TheEarlOfPuddin** [d3athrow/vgstation13#2605] opened 2015-01-22 22:15 UTC
Spawn Compressed Matter cartridge
Attempt to implant matter after setting *grin
Once emote is preformed the backpack jumps to hand or floor if not free.
Cannot fit Backback to back slot or use Compressed Matter cartridge any further even after stripping.
Backpack sprite Still appears on main body but not in the UI.

*Unconfirmed* Following these steps causes internals set on to fail if Tank is in hardsuit storage slot.

**Comment by Kurfursten** [comment] 2015-10-15 21:19
@clusterfack Cannot reproduce, ancient, and poorly formatted. Close this.

**Closed** 2015-10-16 00:48 UTC
