### ISSUE TITLE
Incorrect Pill Messages

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3586] opened 2015-03-26 14:09 UTC
![pill crush](https://cloud.githubusercontent.com/assets/3991927/6847792/12a03422-d397-11e4-8158-b46af395a73b.PNG)
![pill dissolve](https://cloud.githubusercontent.com/assets/3991927/6847793/14bfd0f0-d397-11e4-8a86-f623be49d21b.PNG)

It looks like, when a character takes a pill, the message displayed is as though the character is a beaker, rather than a person. The pill still works, though.

**Comment by d3athrow** [comment] 2015-03-26 16:14
I can't reproduce.

**Comment by dylanstrategie** [comment] 2015-03-26 16:18
Was fixed with #3585

**Closed** 2015-03-26 16:26 UTC
