### ISSUE TITLE
Disappearing tables

### ISSUE THREAD

**Issue by CyberTropic** [d3athrow/vgstation13#12037] opened 2016-09-28 01:39 UTC
If you flip a table over, and then try to build another table on the same tile, what ends up happening is you use up the table parts, you get an upright table but the flipped over table will disappear. So basically the table parts will just vanish into the ether.

**Comment by Kurfursten** [comment] 2016-09-28 02:46
This should be pretty easily fixable by adding the one per tile quality to the table recipe, so that you simply can't make a table if the tile already has a table.

**Comment by Exxion** [comment] 2016-09-28 06:14
Duplicate of #11008

**Closed as completed by Exxion** 2016-09-28 06:14 UTC
