### ISSUE TITLE
SME Containment leaks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7044] opened 2015-12-15 12:05 UTC
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> The chamber where the shard goes leaks air and plasma magically.
> 
> What you expected to happen
> Not to leak
> 
> Steps to reproduce if possible
> Bolt open chamber airlock, then close it up again. The chamber will now leak continously

**Comment by PJB3005** [comment] 2015-12-15 12:29
# GOD

# FUCKING

# DAMNIT

**Comment by FudgePucker** [comment] 2015-12-15 14:36
'Its not leaking anymore' THEY SAID

FUCK

**Comment by FudgePucker** [comment] 2015-12-16 18:00
Wait does bolting open a door then shutting it cause it to leak or is it just for this one case?

Because if I can bolt open then close all the doors connected to mant I could cause atmospheric problems to spread to the entire station, firelocks be damned.

**Comment by CptWad** [comment] 2016-01-18 08:07
I have been setting up the SME for a while
in general, I have not seen a leak beyond someone deliberately doing it. Not even any accidentals.

**Comment by gbasood** [comment] 2016-01-18 18:55
Someone want to see if this occurs after following the described steps to reproduce?

**Comment by gbasood** [comment] 2016-01-18 21:10
#4985 and #5873 related

**Comment by ihadtoregisterforthis** [comment] 2017-07-15 02:49
Never saw this happen again

**Comment by jknpj** [comment] 2017-07-17 18:17
It happens on deff due to mapping. i don't know if bolting fixes it but you can reproduce this on deff by just spawning a miner on the chamber and watching as the entire SME room gets flooded

**Comment by Exxion** [comment] 2017-07-17 21:31
You know, I wonder if the bizarre and unreliable door leaking bugs might be caused by the zone being generated starting on the door
I have no idea if that's actually the case, but if it is, the deferred list added in the air controller rewrite might possibly fix it

**Comment by Exxion** [comment] 2017-07-18 05:50
Yeah no the deferred list checks the wrong block flag to fix that
However, I might have just figured out the cause

EDIT: Disregard everything else in this comment, because it was all wrong

**Comment by Duny-** [comment] 2017-09-06 15:01
@jknpj 
![image](https://user-images.githubusercontent.com/5224390/30119119-0965d380-9325-11e7-8f21-63adcb1ab6d9.png)
Not seeing it
What am I missing

**Comment by Exxion** [comment] 2017-09-06 15:37
Yeah I don't think it's possible to make air leak through an airlock by fucking up mapping
They have so much snowflake code with ZAS that they could probably never leak no matter WHAT you edit the starting vars to, with the exception of making them start open

**Comment by Kurfursten** [comment] 2018-09-02 11:39
@Exxion If this is still a thing I've yet to see it proven and we should have a modern issue instead of a 2017 one.

However, I have not seen it recently. Let's close it.

**Comment by Exxion** [comment] 2018-09-02 19:56
Yeah, I don't know *what* was going on here, but I haven't seen anyone mention it in months

**Closed as completed by Exxion** 2018-09-02 19:56 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Honk
