### ISSUE TITLE
Bulletproof vest is spaceproof

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8170] opened 2016-02-09 01:01 UTC
(WEB REPORT BY: ch0c0latem00se REMOTE: 158.69.55.2:7777)

> Revision 2d9b868dcfa2c9fab704634d5cd7090cdcc987a2
> 
> General description of the issue
> Completely fine in space with out proper equipment
> 
> What you expected to happen
> cold painful pressurized death
> 
> What actually happened
> space crusin
> 
> Steps to reproduce if possible
> http://i.imgur.com/ClRtu4t.png this is all I had on, taking off the vest let me go in space  without any issues

**Comment by Zth--** [comment] 2016-02-09 01:05
Dupe of #8167. Your helmet was protecting you, it's not related to what you were wearing

**Comment by ihadtoregisterforthis** [comment] 2016-02-09 01:30
The blood makes it look like a lumberjack shirt

**Closed as completed** 2016-02-09 21:36 UTC
