### ISSUE TITLE
GPS coords

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22688] opened 2019-04-29 21:02 UTC
(WEB REPORT BY: robocopreb REMOTE: 206.221.180.138:7777)
# Revision
e14898b9e2abb656075b9b9a7e9b5c55ac25861b

# Description
I used a crew monitor to teleport people, but the coordinates didnt work. 
Comparing values from Crew monitor and GPS(science) i found that number are not matching

# Steps to Reproduce

# What you Expected
GPS coordinates to match from Crew monitor and  GPS system
# What Actually Happened

**Comment by SirSkeleto** [comment] 2019-04-29 21:04
duplicate of #22681

**Closed as completed** 2019-04-29 21:05 UTC
