### ISSUE TITLE
photos + mannequins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13027] opened 2016-12-23 13:31 UTC
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

dressed mannequins show naked on photos
>What you expected to happen
photos of dressed mannequins

>What actually happened

naked mannequins
>Steps to reproduce if possible
take a photo of a dressed mannequin

**Comment by ShiftyRail** [comment] 2019-06-19 19:25
Dupe of #12626

**Closed as completed by ShiftyRail** 2019-06-19 19:25 UTC
Labels: Bug / Fix
