### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Circuit printer robotic board issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3476] opened 2015-03-19 07:06 UTC
110a86ae707512152f09ea15632c2914f5c62929 

Trying to build an exosuit fabricator like the dirty powergamer I am, I found out that the printable circuit can't link to exofab.

Cockblocking the roboticist and making everything from my autism fort

I had to actually steal the Robotic RnD board giving them a non-working one.

1. Print a robotic RnD console board
2. Build the console
3. Build an exofab
4. Enjoy has you can't link the machines

**Comment by ComicIronic** [comment] 2015-03-19 17:40
Cannot reproduce.

You need to be more detailed in your bug report, as I have a sneaking suspicion what was causing the problem.
Were you building in space?
Did you define the area in which you built the console?
Are you sure you built the correct console?
Are you sure you tried the Resync with Nearby Devices button?

**Comment by Kurfursten** [comment] 2015-10-15 21:33
@clusterfack Can't reproduce, close this

Also not even relevant anymore since we got expanded access

**Closed** 2015-10-16 00:49 UTC
Labels: Needs Moar Testing
