### ISSUE TITLE
Wrenching a gas miner turns it into a pipe fitting

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#3151] opened 2015-02-21 11:01 UTC
This was done several times in live rounds last night, cannot confirm if it is still an issue but the bug report is here in case it is.

**Comment by ComicIronic** [comment] 2015-02-21 12:08
This is a duplicate of #3123, and was fixed in #3131.

Reopen if it's still happening.

**Closed by ComicIronic** 2015-02-21 12:08 UTC

**Comment by sonime** [comment] 2015-02-21 12:45
oh thanks
