### ISSUE TITLE
Magic Missile

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3826] opened 2015-04-08 07:11 UTC
You can apparently hit yourself with your magic missile projectiles now.

Saw: A wizard using magic missile, 3 missiles were apparently spawned but none of them were spawned visibly, apparently they all hit the wizard. He was in the line at the HoP's office when it occurred.

**Comment by ComicIronic** [comment] 2015-04-08 10:43
I specifically recall coding against this, and it not happening in testing.

**Comment by clusterfack** [comment] 2015-04-08 11:03
Yeah it just gave a message of the magic missile pops with a flash and the wizard got knocked down, I didn't even see any magic missiles in the first place after he cast the spell.

**Comment by dylanstrategie** [comment] 2015-04-16 09:30
Might be caused by the magic missiles popping on the same tile as the Wizard (if he was in line at the HoP and surrounded by other players)

**Comment by ComicIronic** [comment] 2015-04-16 18:00
Cannot reproduce.

**Comment by CptWad** [comment] 2015-04-29 19:34
I think this was fixed with another MM bug or something

**Closed** 2015-04-29 19:51 UTC
Labels: Bug, Needs Moar Testing, Unable To Reproduce
