### ISSUE TITLE
Plasma sealing doesn't play well with new rigsuits

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27001] opened 2020-07-01 20:23 UTC
(WEB REPORT BY: potatomancake REMOTE: 206.221.180.138:7777)
# Revision
85ff9b697a1f3bddbf445577be6b63462a1e0464
# Description
If you install plasma sealing and retract your helmet on a suit, the "plasma seal disengaged" message continues to play indefinitely as long as you wear the suit.

Also, if you take the suit off without retracting the helmet first, the helmet stays behind, then disappears entirely and the suit becomes borderline unusable between the plasma message and the broken helmet.

# Steps to Reproduce
Install plasma sealing, then retract your helmet/take off your suit without retracting
# What you Expected
Plasma seal disengaged.
# What Actually Happened
Plasma seal disengaged.(x57) and now my helmet is gone forever

**Comment by SonixApache** [comment] 2020-07-03 04:16
dupe of #26935 but this one has more in it

**Comment by jknpj** [comment] 2021-08-29 21:38
Tried to reproduce it with no luck.

**Closed as completed** 2021-08-29 21:38 UTC
Labels: Bug / Fix, Needs Moar Testing
