### ISSUE TITLE
remove bus

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#10772] opened 2016-06-25 17:24 UTC
it keeps breaking

it needs constant admin supervision

please kill it

**Comment by Ephx1** [comment] 2016-06-25 17:54
remove you

you keep breaking

you need constant admin supervision

please kill self

**Comment by 9600bauds** [comment] 2016-06-25 18:03
For those of us who were not in the game at the time can you specify how does it break

**Comment by JustSumBody** [comment] 2016-06-25 18:30
#10504
It sometimes fails to initialize lighting
The only way I know of to see anything when this happens is to enable mesons.

**Comment by kol1th** [comment] 2016-06-25 21:12
> honk label

this is serious the map keeps shitting when it comes to lighting and people keep voting for it

**Comment by mph55** [comment] 2016-06-25 22:53
I have tracked this issue and I've seen that it is happening because vaults break the lighting when they have to increase the world maxx and the world maxy. We could move the random vault areas in Bus further away from the map borders like in Box and the other maps as a temporary fix.

**Comment by PJB3005** [comment] 2016-06-25 23:17
Good job determining the cause!

**Comment by clusterfack** [comment] 2016-06-25 23:18
Someone needs to check the maploader

**Comment by Spacedong** [comment] 2016-06-26 00:25
remove defficiency first

**Comment by PJB3005** [comment] 2016-06-26 05:09
Remove box before that.

**Comment by TheFriggenSawbones** [comment] 2016-06-26 10:13
@mph55 god bless you

**Comment by kol1th** [comment] 2016-07-01 14:20
How about remove it from rotation until it's actively being worked on/finished? It's hardly functional.

**Comment by ConkerDev** [comment] 2016-07-02 18:04
@mph55 noice

**Comment by TheFriggenSawbones** [comment] 2016-07-06 15:42
PLEASE

**Comment by PJB3005** [comment] 2016-07-09 16:44
Every time I play on this map I hate it.

Please this is so half assed and poorly done.

**Comment by Zth--** [comment] 2017-01-22 08:35
Close this?

**Closed as completed** 2017-01-22 08:42 UTC
Labels: Feature Request
