### ISSUE TITLE
General fabricators too shit

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5870] opened 2015-09-27 19:42 UTC
A magazine (12mm) costs 72,000 iron and 7,200 plastic on the general fabricator while the assault rifle itself costs 10,000 iron and 1,000 glass on the protolathe. Come on, it has NO fucking sense

**Comment by Shadowmech88** [comment] 2015-09-27 19:46
I believe the general fabricator was designed to be terrible to encourage players to use the autolathe/protolathe instead.
However, 12mm magazines are not currently printable in any other way, so it seems the best fix for this would just be to add them to the protolathe.

**Comment by Zth--** [comment] 2015-09-27 19:53
I know it has to be terrible, but come on, you can build a whole spacepod with 70k iron

**Comment by AutismSpider** [comment] 2015-09-28 09:49
Iron not that hard come by can get it cheap form cargo and crap ton of it form miners

**Comment by Kurfursten** [comment] 2015-10-12 16:34
This has less to do with the General Fab being awful and more to do with the outrageous general cost of ammo_storage items. They all have a material cost of 50,000 metal (which the general fab then inflates with its own formula).

The easy fix for this is to simply agree on a lower amount. For instance, 5,000 metal. Remember, of course, that one sheet of metal is 3,750 metal units.

**Comment by icantthinkofanameritenow** [comment] 2016-06-21 02:39
I was thinking of making an issue about this myself, but this one covers a similar enough point. In its current state, virtually everything a person might actually want to make on this is either compatible only with the traitor device analyzer, costs a metric fuckton of materials moat mechanics will never see, or both. 

Either the base Device Analyzer should be able to scan more "dangerous items" (since it scans stun batons and the like in its current state just fine,), the material costs should be less expensive- or better yet, both.

**Comment by Kurfursten** [comment] 2016-06-21 06:05
Originally it could, but then everyone realized that it was not a general fabricator so much as a gun fabricator because no one wanted to use it for anything but weapons. You seem to be thinking the same thing - "virtually everything a person might actually want to make" seems to be guns based on your statement.

But really the two most poignant problems with the general fabricator are:
1) The protolathe already has designs for seemingly everything, and since the mechanic already has a protolathe, there seems to be no reason to not just use the protolathe.
2) Randomly generating material costs is not only too expensive currently, but it also kind of sucks in general. For example here I'll use the similar generator on the flatpack fab because I use that once in a while. 9 rounds out of 10, a chem dispenser will cost just plastic. But once in a rare blue moon it will also cost uranium - for a tier 1 machine. Useless.

So we have a few general solutions to problem 1. They are:
A) Decrease the number of designs in the protolathe and document on the wiki what the general fab is good for scanning/printing. This is kind of an annoying solution because most people rail against nerfing anything. OR
B) Give the general fab to someone who doesn't have a protolathe. Just for example, you could change it so that instead of uploading a blueprint, you instead merely insert an item and the machine makes copies of it. Then, without the need for other machines or a device analyzer, you could move it to tool storage for public access, to the Vox outpost so they can copy things they trade off the station, to cargo to accompany the autolathe - whatever you feel like. OR
C) Make the general fab highly preferable to the protolathe to use. The main problem with the general fab from a mechanic's point of view is that once you have one of something from the protolathe, you can just print more of it from the protolathe because mineral costs are usually pretty low. If costs were dramatically lower for everything at the general fabricator, people might use it more. I call this the "Probe Solution".

Problem 2 is much more straightforward. Strip out randomization where possible and where it must remain, make the formula much lower.

**Comment by icantthinkofanameritenow** [comment] 2016-06-21 23:24
@Kurfursten

That's not entirely true. Other things like the advanced toolbelt, hypospray, and even some forms of armor/hardsuits would give it a greater amount of use than it currently sees as well. 

We just need to think of it this way: what are the items items that the protolathe can't make which aren't "dangerous", and which ones would be most beneficial for the station to have extras of? The aforementioned advanced toolbelt comes to mind, if nothing else.

**Closed** 2017-01-07 15:40 UTC
Labels: Balance
