### ISSUE TITLE
(WEB REPORT BY: fozzington REMOTE: 198.245.63.50:7777) Vampire Sight Interfering with Eyewear Functions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4382] opened 2015-05-10 10:57 UTC
http://i.imgur.com/JCZnYtZ.jpg

Hopefully the above screenshot shows enough of my claim to be understood and dealt with

**Comment by ComicIronic** [comment] 2015-05-10 11:05
Mobs really need a sight controller, rather than trying to set things manually.

**Comment by FudgePucker** [comment] 2015-05-10 17:40
The weird thing is that normal xray from genetics works with mesons and NVGs.

**Comment by gbasood** [comment] 2016-01-18 20:03
Can't reproduce with antag madness'd vampire

Possible didn't have vampire sight either through bug or misunderstanding

Given that I know antag genetics are super fucking buggy, going to go with genetic bugs

**Comment by CptWad** [comment] 2016-02-04 21:46
I think this was fixed with later updates, I made an issue about xray not working at all which was fixed. I also never have issues as vamp with vision any more since.

**Comment by gbasood** [comment] 2016-02-06 07:49
Closing until it pops up again then

**Closed by gbasood** 2016-02-06 07:49 UTC
Labels: Bug / Fix, Needs Moar Testing
