### ISSUE TITLE
Game Glitch Wrapped Crate Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11765] opened 2016-09-05 18:03 UTC
(WEB REPORT BY: ranizyehu REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> This was a few rounds back and I wanted to confirm it was a glitch.
> 
> General description of the issue
> A player is able to pick up wrapped crates but by doing so it removes the item entirely from the server.
> 
> What you expected to happen
> This item is not possible to be picked up in the first place.
> 
> What actually happened
> The crate dissapears with all of its contents.
> 
> Steps to reproduce if possible
> Get a crate or locker.
> Open it and put whatever item inside.
> Close the locker or crate then close it.
> Wrap it in the gift wrapping paper found near the assistant area or whatever area you may find it.
> For some reason you can pick up the crate, the crate dissapears entirely without leaving a sprite or its contents.

I tested it again by using myself as a guinea pig.
I put myself in the locker.
I had a fellow graysuit wrap up the locker and then pick me up.
The entire screen turns black and oxygen drops to 0.
When I ghost and try and locate my body the game says I do not exist on this server.

Not sure if this means anything but if the locker has food in it the player seems to become obese very quickly if he or she were to pick it up.

**Comment by Exxion** [comment] 2016-09-05 18:14
Duplicate of #11674 
You're not picking up the crate, it's getting nullspaced for some reason

**Closed as completed by Exxion** 2016-09-05 18:14 UTC
