### ISSUE TITLE
The thing that should have been fixed long ago: Not being able to move shit sideways that you should

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#8787] opened 2016-03-12 23:23 UTC
![image](https://cloud.githubusercontent.com/assets/6540760/13725926/728aaf5e-e87f-11e5-9bc4-bdfabf35148a.png)

**Comment by ghost** [comment] 2016-03-12 23:27
Things that never should be fixed:
1. this

**Comment by Imagebard** [comment] 2016-03-12 23:28
You can probably move a welder tank to the side, its just that the computer screen and the reinforced wall are blocking movement.

**Comment by 9600bauds** [comment] 2016-03-12 23:28
This is not actually a bug, this is a feature called "dynamic difficulty adjustment for Diona players"

**Comment by Exxion** [comment] 2016-03-13 00:06
You know, this can be fixed with a change of exactly one line of code, but I'm afraid to do that because it may have consequences we don't want

(Two lines of code to fix both this and #4042)

**Comment by PJB3005** [comment] 2016-03-13 00:27
Yes, this is technically 100% intended AFAIK. 

It would be nice to be able to though.

**Comment by nuklearcellphoneg** [comment] 2016-03-13 11:55
Welder tank looks to have wheels... dunno why I can't slide it.

**Comment by PJB3005** [comment] 2016-03-13 11:56
They can slide, that's not the cause of the issue. 

The issue here is that the code doesn't see you as adjacent to the tile you're trying to move the welding rank to, because both the welding tank and the wall are blocking you (or the domputer).

**Comment by Exxion** [comment] 2016-03-13 18:02
Even though solid full-tile objects do NOT stop you from pulling/pushing windows that are on the same tile through them for the exact opposite reason this happens (as explained in #4042; in short, the non-diagonal case of `Adjacent()` only checks for border blockages while the diagonal case checks for border OR full-tile blockages)

**Comment by SonixApache** [comment] 2023-05-27 14:07
this is actually fixed now, you can just ctrl-click slide the welding tank into one of the two horizontally adjacent objects to push it into the diagonal space

**Comment by Exxion** [comment] 2023-05-27 14:50
I think that might have worked even back when this report was made but nobody tried it

**Comment by nervere** [comment] 2023-07-06 01:45
Works now. Testing done by @Inorien - thanks!

**Closed as completed by nervere** 2023-07-06 01:45 UTC
Labels: Balance
