### ISSUE TITLE
Closed false walls doesn't block atmos breaches

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22643] opened 2019-04-27 14:41 UTC
(WEB REPORT BY: romanzc REMOTE: 206.221.180.138:7777)
# Revision
1f131da8bd4dfb55546a640abc52a4859cb79461

# Description

Making a false wall to block a atmos breach doesn't work.
# Steps to Reproduce

1- Make false wall
2- Cause a atmos breach behind the false wall
3- Close the false wall
4- Enjoy dying to plasma anyways

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment] 2019-04-27 14:57
Yeah, that's intentional
If you want to have something that opens and is airtight, use an airlock

**Comment by SGuivenne** [comment] 2019-04-27 17:08
Nanotrasen would like to remind you that Nanotrasen Grade Walls are capable of preventing a fire burnthrough for 60 minutes of concentrated flames.  Nanotrasen is not responsible for illegal modifications or damage caused by crew to said wall and categorically will deny insurance claims caused by such illegal modifications.

**Comment by Intigracy** [comment] 2019-04-27 20:24
Or just close it and screwdriver it into a regular wall.

**Comment by ShiftyRail** [comment] 2019-04-29 09:42
Has always been intentional as far as I'm aware.

**Closed as completed by ShiftyRail** 2019-04-29 09:42 UTC
