### ISSUE TITLE
General fabricator too slow

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7722] opened 2016-01-15 20:08 UTC
A fully upgraded gen fab takes ages to produce a single matter cartridge.

**Comment by Shadowmech88** [comment] 2016-01-15 20:11
It was intentionally changed so that production time is based on material cost.
This was done specifically to prevent gen fabs from becoming matter cartridge factories and invalidating miners.

**Comment by ghost** [comment] 2016-01-15 20:17
Science invalidates every other department, this was never a reason for nerfing it to the point of uselessness.

Balance is good, but not selective balance where one thing is nerfed to the ground while there's a myriad of other more overpowered game mechanics.

**Comment by ihadtoregisterforthis** [comment] 2016-01-15 20:33
![oh-boy-here-we-go-again](https://cloud.githubusercontent.com/assets/13305885/12364536/eafff57e-bbad-11e5-987a-625e72d2c6bd.jpg)

**Comment by 9600bauds** [comment] 2016-01-15 23:55
Making it not shit was in my todo list.
Also just how are you planning to make a matter cartridge factory WITHOUT miners, ever since the material dupe bug was fixed, matter cartridges are obscenely expensive for synthetizing rare materials (plus the small detail that you need someone to bring you the rare material to scan it in the first place).

**Comment by Shadowmech88** [comment] 2016-01-16 00:02
What material dupe bug?

Back when matter cartridge factories were common practice, they were possible just because a single matter cartridge was capable of producing more materials than the gen fab required to produce them, meaning a stack of plastic and metal was able to be turned into more stacks of plastic and metal given time, which made the cost of rare materials irrelevant.

Or by "material dupe bug" are you referring to the fact that matter cartridges could produce more matter than they required to build?

**Comment by ghost** [comment] 2016-01-16 00:57
Previously you could repeatedly scan objects until you got a low cost blueprint for your cartridge in gen fab. 

Since this was fixed, someone ignorant of the matter at hand decided it would be a good idea to also make the crafting speed extremely long for no reason.

**Comment by 9600bauds** [comment] 2016-01-16 02:35
There were two material dupe bugs in the serbian, after those were fixed people resorted to the "practically free matter cartridge" business. If you actually make matter cartridges from an Autolathe though, they're extremely expensive, and now the genfab uses the Autolathe price.

@TermedClepe that was ONLY fixed for stuff that can also be printed at an Autolathe, Protolathe or Mechfab, lol

**Comment by Kurfursten** [comment] 2016-01-16 06:08
The only thing that takes a long time in the general fab are things that have a really high mineral cost, like compressed matter cartridges and ammo.

Someone really should just fix the material cost of ammo

**Comment by gbasood** [comment] 2016-01-17 11:01
Duplicate of #5626 (aside from ammo cost concerns, which would be a duplicate of #5870)

**Comment by 9600bauds** [comment] 2016-01-21 05:38
It'll wait till after the freeze

**Closed as completed** 2018-04-07 08:14 UTC
Labels: Balance, Discussion
