### ISSUE TITLE
Galactic Common is no longer a thing.

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#7670] opened 2016-01-12 05:22 UTC
It used to be that Humans had Sol Common as their species language that they could insult the filthy xenos with, and that Galactic Common was what everyone spoke.

Now everyone across the galaxy ever speaks the Sol language, and humans cannot cry out GAS THE VOX SLAY THE AYY BURN THE TREES CRACK THE ACK in their own language ever.

**Comment by Imagebard** [comment] 2016-01-12 05:38
I'd like to know what the FUCK happened with Galactic Common and why everyone speaks it Sol Common + Their Racial Language(Which, for humans, is Sol Common) instead of the old Galactic Common + Their Racial Language.

**Comment by clusterfack** [comment] 2016-01-12 06:06
Some nerds thought that ever race speaks sol common because they don't get what sol means

**Comment by 9600bauds** [comment] 2016-01-12 06:22
Well I mean, most countries speak English even though the name comes from England...

**Comment by Exxion** [comment] 2016-01-12 06:28
SS13 is a human vessel, so it makes sense all employees would be expected to know the human language
That said, I have no problem with it not being that way. I just have no problem either way.

**Comment by CptWad** [comment] 2016-01-12 06:47
Just keep it as is. Tradeband or gutter is what I use to talk shit about xenos

**Comment by uazuaz** [comment] 2016-01-12 09:43
@CptWad 

> Tradeband or gutter

what are those?

**Comment by ihadtoregisterforthis** [comment] 2016-01-12 13:03
Other races can still talk gutter or tradeband if they set it, so there's a chance they'll understand you.

**Comment by CptWad** [comment] 2016-01-12 16:43
Yes and?

**Comment by ihadtoregisterforthis** [comment] 2016-01-12 18:00
If the problem is muh hooman sekrit languash they could be made human only. At least one of them.

**Comment by Exxion** [comment] 2016-01-12 18:02
Not those two. That would make no sense given that they are both specifically meant to be universal trading languages.

**Comment by Imagebard** [comment] 2016-01-12 19:27
>SS13 is a human vessel, so it makes sense all employees would be expected to know the human language

SS13 is a space vessel so it makes sense all employees would be expected to know Galactic Common.
Seriously, Sol Common is the human racial language.

**Comment by CptWad** [comment] 2016-01-12 21:36
This seems a bit heated for a bit of fluff code. Will vox raiders know galactic common?  What we have at the moment is good. A common human language for a human ship. Baylore galactic common would be cool but who the hell would code it?
Hell we might as well add a wizard language. Or tacticool nuke op language thats all in code so that if someone hijacks comms the ops can still be un-faltered.

**Comment by d3athrow** [comment] 2016-01-12 22:03
I don't remember us ever having galactic common, it was always sol common

**Comment by CptWad** [comment] 2016-01-12 22:14
It might be a bay thing, I don't remember it when we transferred over to new saycode either.

**Comment by Imagebard** [comment] 2016-01-12 22:17
>I don't remember us ever having galactic common

It was sometime by 2014, I could swear.

>A common human language for a human ship

You mean space ship
Nobody in the space ship knows *Galactic Common*(That you're supposed to use if you're talking with other races), but somehow knows *Sol Common*(*That you're supposed to use if you're talking with other humans*)

**Comment by sonime** [comment] 2016-01-12 22:26
I totally remember having a HUMANITY FUCK YEAH language though.

Don't tell me it's a Berenstein thing.

**Comment by CptWad** [comment] 2016-01-12 22:32
I looked at bays saycode real quick and I think when it was rewritten it was just replaced with sol common.

**Comment by ihadtoregisterforthis** [comment] 2016-01-28 03:35
Why is this in the feature freeze? Who watches the watchmen?

**Comment by gbasood** [comment] 2016-01-29 23:41
this issue doesnt even describe a problem that matters to almost anyone, nor does it ask for there to be a snowflake human language

**Comment by sonime** [comment] 2016-01-30 05:06
@gbasood the issue is that we used to have a human snowflake language but ever since Riri updated saycode, it's been missing.

**Comment by gbasood** [comment] 2016-01-31 00:17
Sol Common is listed as `/datum/language/human`.
Also funnily enough, monkey language is `datum/language/human/monkey`

**Comment by sonime** [comment] 2016-01-31 00:20
Should be /datum/language/common that everyone speaks and /datum/language/human that only humans have

**Comment by gbasood** [comment] 2016-01-31 00:21
Here's the thing: Sol Common IS the human language. Let's say it's English. Or maybe it's Esperanto if you're so inclined.

What would be the human snowflake language? French? Spanish?

**Comment by sonime** [comment] 2016-01-31 00:24
Sol Common can stay as Chinese for all I care. I'd say have Latin for Galactic but it's already Tradeband. Maybe just go with Esperanto for giggles or something.

I was always under the impression that Galactic wasn't actually the human language, that Sol Common, their snowflake language, was.

**Comment by Exxion** [comment] 2016-01-31 00:32
Gutter and Tradeband are both identical _placeholder_ syllables
Specifically lorem ipsum

**Comment by sonime** [comment] 2016-01-31 00:35
Ok. Point is that Humans don't have a snowflake language like every other race has, and we used to and don't anymore.

**Comment by Exxion** [comment] 2016-01-31 00:36
Yeah, I don't have a problem with giving humans their own language as long as the default remains the one everyone speaks.

**Closed as completed** 2016-02-02 08:36 UTC
Labels: Feature Loss
