### ISSUE TITLE
mosin in hand is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28497] opened 2021-01-03 23:16 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
3b55f6b77e3eea51096d6d80817b21bc6034093c

# Description
its broken it doesnt appear

**Comment by SonixApache** [comment] 2021-01-05 02:15
dupe of #28292

**Closed as completed** 2021-01-12 14:31 UTC
