### ISSUE TITLE
Turrets are unable to shoot lasers

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3071] opened 2015-02-17 23:30 UTC
Tasers are fine but not lasers

![untitled](https://cloud.githubusercontent.com/assets/7538670/6239632/85453b3c-b6fd-11e4-954a-f5b4b779606c.png)

Pictured is Bob and Chen having a nice chat together while the turrets spaz out with nothing coming out of them

**Comment by CptWad** [comment] 2015-02-18 00:07
Confirming that they never work. :star:

**Comment by Konater** [comment] 2015-02-18 19:55
Upload turrets apparently work, they're possibly unable to fire through windows I'll check next time I'm AI

**Comment by clusterfack** [comment] 2015-02-27 20:02
Almost certainly caused by https://github.com/d3athrow/vgstation13/commit/0f12242a85a1f2f2267518115049f5f5dc5a201d

**Comment by YakumoChen** [comment] 2015-03-05 03:15
They don't really work, at best they fire once and never again, regardless of positioning or stuff in the way or who or what it is.

**Comment by ComicIronic** [comment] 2015-03-15 22:45
Not happening on local.
Is this still an issue on the server?

For the record, the reason the turrets in the image aren't firing is because the person is lying down.

**Comment by clusterfack** [comment] 2015-03-16 07:39
Nah this (and possibly all projectile issues) were fixed by a suggestion I made to d3athrow, https://github.com/d3athrow/vgstation13/commit/7b71cce700b2b1fea9ed089ca499af1918a68486

**Comment by ComicIronic** [comment] 2015-03-16 16:38
Reopen if still an issue.

**Closed by ComicIronic** 2015-03-16 16:38 UTC
Labels: Bug, Feature Loss, Needs Moar Testing
