### ISSUE TITLE
Ninja sword isn't cutting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27231] opened 2020-07-23 20:07 UTC
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
16d9bd953207bbc8b3f85b458463abe7b98ba746

# Description
Joined in as ninja to wait in solars for ten minutes because the sword won't cut through doors
# Steps to Reproduce
cut a door as ninja
# What you Expected
door open
# What Actually Happened
stuck in solars as round ended

**Comment by Kurfursten** [comment] 2020-07-23 21:00
use harm intent

I told people this is a mistake, what else could you possibly be trying to do when you sword a door but cut it open??

note that due to lazy coding there IS a bug where you can't sword open a door that is unpowered

unable to reproduce bug on live

**Comment by Kurfursten** [comment] 2020-07-23 21:15
talked to mastercasual, he did harm intent but it was unpowered, dupe of  #24891

**Closed as completed by Kurfursten** 2020-07-23 21:15 UTC
Labels: Bug / Fix
