### ISSUE TITLE
Long range plant watering

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#3196] opened 2015-02-23 23:00 UTC
I noticed that, as chef when I was holding a milk carton, I misclicked on a plant tray in botany and somehow poured milk into it, despite being in the kitchen and it being behind windows. I tried this with other containers, and noticed that for certain containers you can pour into plant trays from any range.

I noticed that a milk carton, flour sack, and glass (of water in my case) can water a tray from any range. However, buckets and bottles of nutrients work properly, and you must be next to the tray. I didn't have time to try it with other containers, but I'd assume others have this issue as well.

**Comment by Midaychi** [comment] 2015-02-24 00:59
Wonder if you can do this through a camera? Remotely mutate plants.

**Comment by ComicIronic** [comment] 2015-02-24 17:05
>all this repeated afterattack code

Sickening.
Caused by a preposterous amount of copied and snowflake.

**Comment by Kurfursten** [comment] 2015-04-22 10:51
Unable to reproduce.
* Was not able to reproduce Space Milk Jug interacting with hydroponics tray at all
* Was not able to reproduce long-distance interaction with Space Milk Jug OR Bucket of Water
* Was able to reproduce 1-range interaction with Bucket of Water only

Tested at 50/100 water level.

**Comment by clusterfack** [comment] 2015-04-25 06:59
If another person confirms its unreproduceable or there are no other comments by the end of the freeze I'll close this.

**Closed** 2015-04-28 20:15 UTC
Labels: Bug, Unable To Reproduce
