### ISSUE TITLE
Stormtrooper Helmet Lacks Image

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7102] opened 2015-12-17 08:47 UTC
(WEB REPORT BY: rhimrifer REMOTE: 158.69.55.2:7777)
Revision: db7bb2614063c55865595853c3a42ea8d568e249

Stormtrooper helmet obtained from stormtrooper conversion kit on a security hardsuit helmet has no image so it results in a bald head.

To get a stormtrooper helmet with an image

I got a stormtrooper helmet without graphics

Use stormtrooper upgrade kit on security hardsuit helmet.

**Comment by PJB3005** [comment] 2015-12-17 10:06
Dupe of #7077?

**Comment by ghost** [comment] 2015-12-17 21:21
yes

**Closed as completed** 2015-12-17 21:25 UTC
