### ISSUE TITLE
PDA issue with AI's

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#9326] opened 2016-04-08 04:42 UTC
We've been having some issues with AI's not being alerted when they get PDA messages, this has caused some pretty rough stuff for us and even caused a wrongful bannu.

**Comment by Intigracy** [comment] 2016-04-08 07:54
#9230 related

@PJB3005

**Comment by Probe1** [comment] 2016-04-08 17:26
I had an AI ignore me recently until I yelled at it over comms.  That would explain why it didn't respond to my PDA messages.  

The AI in question was an admin so I was at maximum eye roll about getting ignored.

**Comment by Intigracy** [comment] 2016-06-14 19:00
This is a dupe of #9367 which has more specifics, please close.

**Closed as completed** 2016-06-14 19:46 UTC
Labels: Bug / Fix
