### ISSUE TITLE
Hulk can go through reinforced walls

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6274] opened 2015-10-23 00:47 UTC
Yeah, maybe not. Hulk is already annoying enough as it is, it doesn't need to be the absolute all-access card while we're at it

**Comment by Shadowmech88** [comment] 2015-10-23 00:50
It's been this way for as long as I can remember, and is one of the reasons why hulks are valid if they're doing something that would warrant an arrest, since the only reasonable way to pacify a hulk is to kill it.

**Comment by AutismSpider** [comment] 2015-10-23 05:32
Been like this for long time.

This why its ok to laser or shotgun on a hulk into or try get Rye into the hulk never works.

**Comment by Rei1226** [comment] 2015-10-23 07:14
They faint after a while.

If you see this happening, wait until they faint, then cuff them, shoot them in the head, whatever.

**Comment by Cyadox** [comment] 2015-10-25 07:32
If it's working as intended then we shouldn't really keep this issue open?

**Comment by AutismSpider** [comment] 2015-10-25 18:11
Real issue is people need to know its ok to crit a hulk if they act like massive jack ass with the hulk powers

**Comment by PJB3005** [comment] 2015-10-27 17:58
@Rei1226 they wake up from fainting basically instantly, and are already able to hulk out again, and whilst hulked cuffs are useless.

**Comment by Cyadox** [comment] 2015-10-27 20:16
@PJB3005 So should we be maybe thinking of a more reliable way to stop or disable hulks? As it is they're difficult to stop without special or lethal weaponry, you'd be borderlining on metagaming to keep them handy 'just in case'.

**Comment by PJB3005** [comment] 2015-10-27 20:17
I think we should fix the cooldown on hulk out, the issue is that when you hulk out, you become hulk, but the cooldown already starts to tick down, even before you faint.

**Comment by Cyadox** [comment] 2015-10-27 20:20
So extending the hulk cooldown should fix that - should we make the faint last longer as well?

**Comment by PJB3005** [comment] 2015-10-27 20:24
Yes, both are needed, really.

IIRC the faint lasts like what, 5 seconds?

**Comment by ghost** [comment] 2016-02-13 14:21
Bumping for hulk issue awareness, just in case

**Comment by ghost** [comment] 2016-07-03 18:31
Closing for now, although Genetics can always use balance passes

**Closed by ghost** 2016-07-03 18:31 UTC
Labels: Balance, Controversial
