### ISSUE TITLE
IEDs can't open crates now.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32290] opened 2022-03-26 00:07 UTC
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
727ed38d13c29ad049b0f8988c3bd39ada2e36ac

# Description
It used to work fine a while ago, now all attemps completely destroy all crate items.
I tried testing with 5 crates, all 5 erased.
# Steps to Reproduce
IED a locked crate.
# What you Expected
Open crates.
# What Actually Happened
5 damaged circuits and no loot, at all.

**Comment by Eneocho** [comment] 2022-03-26 14:04
To clarify, I've done it a lot lately and all the IEDs have nuked the crate with only the crate circuitry surviving.

**Comment by djkramer123** [comment] 2022-03-26 16:49
skill issue

**Comment by Eneocho** [comment] 2022-03-26 17:31
Literally not. I tried again on localhost with like 30 emitter crates, all shrecked with no survivors. Something's fucked, man.

**Comment by WindowsErrors** [comment] 2022-03-26 19:37
you finally understand the situation

**Comment by Eneocho** [comment] 2022-03-26 22:10
I think the Breakable objects frame broke the IEDs. This one: #32007

**Comment by Exxion** [comment] 2022-03-26 22:46
Bro that was reverted

**Comment by Eneocho** [comment] 2022-03-27 02:07
The PR that added all the bugs and features (breaking beakers and shit) was reverted, the base frame is still in.

**Comment by Exxion** [comment] 2022-03-27 02:28
Ah, yeah, the items one wasn't reverted. Only the objects one. Thought it was both.

**Comment by Eneocho** [comment] 2022-03-27 02:31
I'm testing the pre-framework IEDs to see if they are broken, as soon as my net stops shitting itself and downloads the thing.

**Comment by Exxion** [comment] 2022-03-27 02:37
I mean it would presumably be a change either to the crate or to the items inside rather than to the IED

**Comment by Eneocho** [comment] 2022-03-27 06:00
Tested it. Crates still get completely nuked before the breakable frame.

**Comment by DamianX** [comment] 2022-03-28 01:45
@Hinaichigo

**Comment by Exxion** [comment] 2022-03-28 01:47
Didn't he just confirm that it *wasn't* that?

**Comment by Eneocho** [comment] 2022-03-28 02:03
Did he? I didn't notice.

**Comment by DamianX** [comment] 2022-03-28 02:32
You're right. I have a fix for this.

**Comment by Hinaichigo** [comment] 2022-03-28 02:34
So to confirm, this bug was still present pre #32007?

**Comment by DamianX** [comment] 2022-03-28 02:38
It was caused by #31978

**Closed as completed** 2022-03-28 05:01 UTC
