### ISSUE TITLE
Nanopaste in the Destructive Analyser doesn't get destroyed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24363] opened 2019-10-05 11:20 UTC
(WEB REPORT BY: subs455 REMOTE: 206.221.180.138:7777)
# Revision
b0ea2dc8b5347f5f96a34d7f60aab8f30c0ac5be

# Description
When you put nanopaste in RnD's destructive analyser and try to destroy it, It doesn't get destroyed, but gives all the materials and research levels you get from it.
# Steps to Reproduce
- Insert Nanopaste into the Destructive Analyser
- Destroy it
- Destroy it again cause its still there
- Keep destroying it. Getting a little bit of glass every time.
# What you Expected
The nanopaste was supposed to get destroyed
# What Actually Happened
infinite glass boys lets goooo

**Comment by MadmanMartian** [comment] 2019-10-05 12:16
>infinite glass

Odd, that shouldn't be the case

**Comment by MadmanMartian** [comment] 2019-10-05 12:17
Also this is happening because I changed the stack/sheet check to just stack, and the nanopaste is an 8 stack item

**Comment by MadmanMartian** [comment] 2019-10-05 12:26
Okay, it doesn't give infinite glass, the materials are subtracted and transferred properly.

**Comment by SonixApache** [comment] 2019-10-05 18:24
nanopaste is a stack, much like bandages
not a bug.

**Closed as completed** 2019-10-05 18:34 UTC
