### ISSUE TITLE
Pathogen scanner googles let you see while blind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24327] opened 2019-10-01 17:00 UTC
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
0d0e6f7f6e2c87612744451239c9cb785a9c1149

# Description
They let you see clouds when you shouldn't see anything, like be unconscious and stuff.
# Steps to Reproduce
Have science googles on, have an outbreak, pass out or go to sleep. You can see the clouds.
# What you Expected
Nothing
# What Actually Happened
I see everything
https://i.imgur.com/wQtCbck.png

**Comment by DeityLink** [comment] 2021-09-06 04:47
Duplicate of #29319

**Closed as completed by DeityLink** 2021-09-06 04:47 UTC
