### ISSUE TITLE
(WEB REPORT BY: teaiofj REMOTE: 198.245.63.50:7777) Taxi Tcomms SMES

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4715] opened 2015-05-27 14:48 UTC
The SMES in Telecomms on Taxi Station has no terminal and is also not connected to any wiring.

**Comment by ComicIronic** [comment] 2015-05-27 14:55
Duplicate of #4714.

**Closed by ComicIronic** 2015-05-27 14:55 UTC
Labels: Map Issue (Taxi)
