### ISSUE TITLE
you can still see objects through the walls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10802] opened 2016-06-27 16:50 UTC
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9709e5d58d69e0e097496e3af7870ca97eb44066
> 
> General description of the issue
> https://u.pomf.is/haynrm.png
> 
> Steps to reproduce if possible
> Take a walk on the station

**Comment by Exxion** [comment] 2016-06-27 18:30
Duplicate and still a BYOND issue

**Comment by MrsTonedOne** [comment] 2016-06-27 18:43
http://www.byond.com/forum/?post=2054167

there is a fix, just needs to be applied the code base.

`TILE_BOUND`

**Comment by Exxion** [comment] 2016-06-27 18:58
We already did that
`SEE_PIXELS` overrides `TILE_BOUND`

**Comment by clusterfack** [comment] 2016-06-28 18:25
http://www.byond.com/forum/?post=2107616

**Comment by PJB3005** [comment] 2016-06-28 18:35
@MrStonedOne #10402

**Comment by 9600bauds** [comment] 2016-06-29 04:41
so how do we fix it

**Comment by Exxion** [comment] 2016-06-29 05:00
By complaining at Lummox
Judging by that forum post, this isn't intended behavior, so that will probably work

EDIT: Hi! I'm a blind idiot.
Fuck
Guess we don't, then.

**Comment by clusterfack** [comment] 2016-06-29 05:15
We go back to the old non SEE_PIXELS

**Comment by 9600bauds** [comment] 2016-06-29 05:22
What's SEE_PIXELS for anyways?

**Comment by clusterfack** [comment] 2016-06-29 05:27
SEE_PIXELS is useful because it draws a barrier at plane 0, hiding everything below plane 0 on tiles you can't see with Byond style darkness. We can't create byond style darkness ourselves as we can't prevent click behavior we can only emulate it.

I used it while optimizing parallax so I wouldn't need another plane master for space to blend multiply away nonvisible turfs or some shit. But looks like we'll end up using that system since SEE_PIXELs is just unworkable.

**Comment by clusterfack** [comment] 2016-06-29 05:34
I thought SEE_PIXELS would be workable initially because the way it was originally let you click darkness (which turned out to be a bug that allowed other things, and was eventually fixed removing that functionality), and because I considered it overriding TILE_BOUND to be a bug. 

But both of those issues will be intractable with the current design decisions in the Byond engine so we wont be using SEE_PIXELs anymore, the old system will remove those bugs.

**Comment by Shadowmech88** [comment] 2016-06-29 16:00
Does Lummox not want to fix SEE_PIXELS?

**Comment by ComicIronic** [comment] 2016-06-29 16:30
There's no "fix" involved- it's considered correct behaviour.

**Closed as completed** 2016-07-09 04:32 UTC
Labels: Bug / Fix, T-Thanks BYOND
