### ISSUE TITLE
modified atmos hardsuit has no fleshlight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8775] opened 2016-03-12 13:53 UTC
(WEB REPORT BY: oberoth REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7e8c26348d714af0eeb5492306da2966308284f6 
> 
> General description of the issue
> As title
> 
> What you expected to happen
> Flashlight on modified suit
> 
> What actually happened
> no flashlight on modified suit
> 
> Steps to reproduce if possible
> modify atmos hardsuit with gold kit

**Comment by Imagebard** [comment] 2016-03-12 14:49
HERE WE GO AGAIN
[Not A Bug]

**Comment by ihadtoregisterforthis** [comment] 2016-03-12 14:58
Watch closer, the other one was about the lack of a flashlight. This one demands a fleshlight.

**Comment by ghost** [comment] 2016-03-12 19:08
It's a feeeattuuuure

**Comment by Intigracy** [comment] 2016-03-14 05:44
someone assign me

**Comment by 9600bauds** [comment] 2016-03-14 05:51
i cannot

**Comment by Intigracy** [comment] 2016-03-15 01:34
well since I got downvoted for wanting to fix this, nah.

**Comment by Imagebard** [comment] 2016-05-17 23:31
A admin said it was intentional and there's code in the golden atmos hardsuit there specifically to make the flashlight go away
Can you close this cap'n Bauds

**Comment by ComicIronic** [comment] 2016-05-17 23:38
ERP masturbation server when

**Closed as completed by ComicIronic** 2016-05-17 23:38 UTC
Labels: Honk, Grammar / Formatting
