### ISSUE TITLE
Asteroid seems to spawn mineral deposites into the vox outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9877] opened 2016-05-03 19:32 UTC
(WEB REPORT BY: boptser REMOTE: 172.93.109.202:7777)
the vox outpost on boxstation has partially been replaced with rocks, meaning its inaccessible from one of the sides and has had a lot of its items deleted

**Comment by 9600bauds** [comment] 2016-05-03 20:06
Third dupe of #4776

**Closed as completed by 9600bauds** 2016-05-03 20:06 UTC
Labels: Bug / Fix
