### ISSUE TITLE
Credits Song No Longer Plays

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35987] opened 2024-02-14 21:54 UTC
(WEB REPORT BY: gimmick1 REMOTE: 172.93.101.77:7777)
# Revision
320d688bd636ec9ace1b6a41c838df9843c334e8

# Description
Title of the Issue.
# Steps to Reproduce
Let the round end and watch the credits roll.
# What you Expected
Directed by Robert D. Werde
*trumpets*
# What Actually Happened
Directed by Robert D. Werde
*silence*

**Comment by jwhitak** [comment] 2024-02-15 00:25
Duplicate of #35954

**Closed as not planned by jwhitak** 2024-02-15 00:25 UTC
