### ISSUE TITLE
[Box outpost] Two all-in one grinders on the same spot

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#29221] opened 2021-04-12 22:44 UTC
#### Description of issue

See image

![image](https://user-images.githubusercontent.com/31417754/114471705-5925b880-9bf1-11eb-944c-c50ae7f56142.png)

**Comment by Eneocho** [comment] 2021-04-13 01:01
Very Hihg Speed Grinding

**Comment by help-maint** [comment] 2021-04-13 02:37
One for each hand

**Comment by kernikov** [comment] 2021-09-23 08:54
@DeityLink No longer an issue since Box Sci Outpost was remapped.

**Comment by DeityLink** [comment] 2021-09-23 09:06
Duplicate of #29472

**Comment by DeityLink** [comment] 2021-09-23 09:06
Fixed by #29911

**Closed as completed by DeityLink** 2021-09-23 09:06 UTC
Labels: Mapping (Box :baby:)
