### ISSUE TITLE
Double bladed toy sword had no inhands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30872] opened 2021-09-24 04:51 UTC
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
bea1b408876f3a63a4badea318d57ddb62cc371d

# Description
Made a double edged toy sword, purple blades on both sides, didnt have an inhands while activated.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment] 2021-09-24 14:05
Duplicate of #30712

**Closed as completed by DeityLink** 2021-09-24 14:05 UTC
Labels: Bug / Fix
