### ISSUE TITLE
Coffins give metal when deconstructed rather than wood.

### ISSUE THREAD

**Issue by toomykins** [d3athrow/vgstation13#18393] opened 2018-05-31 18:22 UTC
#### Description of issue

when using a welder on an open coffin, it gives 2 metal, despite requiring 5 wood to create

#### Difference between expected and actual behavior

expected to get wood, got metal.

#### Steps to reproduce 

build coffin out of 5 wooden planks
open it
use welder
get 2 metal.

#### Length of time in which bug has been known to occur

since coffins exist probably

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Pathid** [comment] 2018-05-31 19:19
Duplicate of #12571

**Closed as completed** 2018-05-31 19:35 UTC
