### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 198.245.63.50:7777) Solars not rotating when set to auto despite being wired.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3922] opened 2015-04-15 12:46 UTC
>Revision 
d2b95c949a53c4194728882075579ce1d2984f39 

Wired all 4 solars to grid, set tracking to automatic, array orientation never changed from the default 0 degrees even a half hour later. Had to manually rotate all the solars just to get power

>What you expected to happen
Auto to rotate the damn panels so it gets power

>What actually happened
It sat at array orientation 0 degrees

>Steps to reproduce if possible
wire solars and wire them to grid
Set tracking to auto
Watch it not rotate even when the star is nearby in orientation

**Comment by ComicIronic** [comment] 2015-04-15 19:13
Duplicate of #3398

**Closed by ComicIronic** 2015-04-15 19:13 UTC
