### ISSUE TITLE
at last we have discovered infinite food

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#26895] opened 2020-06-18 21:04 UTC
>put food in a bowl
>take food out of bowl with a knife
>food is still bound to bowl so if you eat whats in the bowl the food dissapears
>BUT
>put food in ANOTHER bowl
>first bowl is now safe to eat
>knife second bowl
>continue infinitely for infinite bowls of whateverthefuck

told it also works with pizza
sounds like something's missing a check

**Comment by anunknownentity03** [comment] 2020-06-18 21:05
feature, food fabrication

**Comment by ShiftyRail** [comment] 2020-06-18 21:09
David Hilbert's feed and seed

![image](https://user-images.githubusercontent.com/31417754/85072070-c2e35a80-b1b8-11ea-8589-f9b45be71817.png)

**Comment by DeityLink** [comment] 2021-08-31 14:59
Duplicate of #26654

**Closed as completed by DeityLink** 2021-08-31 14:59 UTC
Labels: Bug / Fix, Exploitable, Muh Immulsions, Sanity / Ghosthands
