### ISSUE TITLE
Detective's Medical Laptop "Search Records" Functionality is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35399] opened 2023-11-18 19:26 UTC
(WEB REPORT BY: gimmick1 REMOTE: 206.221.180.138:7777)
# Revision
fe539d65f43db559f03d28d7c9bdd1f2be5616a4

# Description
Detective's Medical Laptop "Search Records" Functionality is not working.
# Steps to Reproduce
Scan something with a crewmember's DNA on it, copy that DNA string and paste it into Search Records pop-up window.
# What you Expected
It to say the DNA belongs to the Iroquos Henry, the Captain.
# What Actually Happened
"Could not locate record 9837039f8dd880d808816dd7551ebf27." By manually finding Cap on the list of records, you can see the DNA string is actually his.

**Comment by pedr69** [comment] 2023-11-20 07:35
security records can search for fingerprints and support partial searching
medical records(and laptops) can search for DNA hash and do NOT support partial searching

**Comment by nervere** [comment] 2023-11-26 17:22
It's because you often copy a space when copying someone's DNA string. If there's a space at the end of the DNA string, it fails to match. Noob mistake but it really should be fixed.

**Comment by jwhitak** [comment] 2024-02-01 07:26
Can't reproduce.

**Closed as completed by jwhitak** 2024-02-01 07:26 UTC
