### ISSUE TITLE
Welder fuel doesn't ignite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6411] opened 2015-11-02 14:09 UTC
(WEB REPORT BY: ricklaus REMOTE: 158.69.55.2:7777)
Welder fuel does not ignite with sparks, a lit welder dropped on it, a flare, or any other items i've tried using.

**Comment by Zth--** [comment] 2015-11-02 15:16
Duplicate of #6116

**Closed** 2015-11-02 15:19 UTC
Labels: Bug, Feature Loss
