### ISSUE TITLE
Janicart is faster than a bullet

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7156] opened 2015-12-19 23:39 UTC
Shooting assault rifle while moving in same direction on a janicart makes you shoot yourself.

**Comment by 9600bauds** [comment] 2015-12-20 01:06
ahhhahahahahaha

**Comment by CptWad** [comment] 2015-12-20 01:07
![nobody](https://cloud.githubusercontent.com/assets/3959840/11915956/09e44404-a673-11e5-8c0a-2019f229a73b.jpg)

**Comment by ConkerDev** [comment] 2015-12-20 01:09
Not a bug, tbh fam.
Donut fix

**Comment by Exxion** [comment] 2015-12-20 01:12
_Faster than a speeding bullet. More powerful than a clown. Able to clean large messes in a single second._
_Look! Over in the bar! It's a borg!_
_It's a zamboni!_
_It's super-janitor!_

**Comment by Intigracy** [comment] 2016-03-19 22:58
ahahahahahahaha

**Comment by ConkerDev** [comment] 2016-04-18 21:38
Not a bug you shitters its a SCIENTIFIC FACT that movility scooters run at mach 3 get a brain you MORANS. #notabug #pleaseunderstand

**Comment by Kurfursten** [comment] 2018-09-24 16:59
@Exxion No longer a bug, likely fixed by atom locking

**Comment by Exxion** [comment] 2018-09-24 17:54
No longer a bug in that the bullets are now faster, or in that they just don't hit you?
Not that it really matters

**Closed as completed by Exxion** 2018-09-24 17:54 UTC
Labels: Bug / Fix, Honk

**Comment by Kurfursten** [comment] 2018-09-24 18:59
The bullets appear to be faster than the cart and do not hit you upon firing, tested with three different bullet guns
