### ISSUE TITLE
Pop-up / NanoUI issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23563] opened 2019-07-16 10:04 UTC
(WEB REPORT BY: thatredpyro REMOTE: 206.221.180.138:7777)
# Revision
217aa33a41e891e144ceec710fbe1877df747adb

# Description
Nanoui randomly freezes and/or just opens up as a blank white page,UI that has done that wont open back properly and not even guaranteed to get fixed after a restart of game, resending resources, reconnecting or pressing that fix nanoui button.This even includes the ''new player options'' popup when you start.Has been a thing for a week or so.
I have also changed my Byond version from the latest to xx69 and xx64, doesnt fix anything despite working ok when they were the current patches.
# Steps to Reproduce
Just trying a bunch of machines or UI options that result in any popup, some are bound to happen
# What you Expected
This damn thing to work
# What Actually Happened
Popup UI either freezes if it manages to show the screen properly, or just turns up as a blank screen no matter how many times you close and re open it or wait.

**Comment by PJB3005** [comment] 2019-07-16 10:06
Seems like a BYOND issue. If Nano doesn't even get past a blank screen then there is nothing we can do.

**Comment by ThatRedPyro** [comment] 2019-07-17 11:12
Just tried a complete uninstall+reinstall, UI still gets fucked after like 2 interactions with it

**Comment by DeityLink** [comment] 2021-11-23 10:47
Duplicate of #26957

**Closed as completed by DeityLink** 2021-11-23 10:47 UTC
Labels: Needs Moar Testing, UI
