### ISSUE TITLE
Light Replacer Interface is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26956] opened 2020-06-25 02:16 UTC
(WEB REPORT BY: buchse REMOTE: 206.221.180.138:7777)
# Revision
92a6267090ade0f8764d65fc43012ee3524cfc17

# Description
The interface screen for light replacers is completely blank

# Steps to Reproduce
use replacer in-hand or click it or something

# What you Expected
to make more lights

# What Actually Happened
blank screen of death

**Comment by Kurfursten** [comment] 2020-06-25 03:34
it's just the nanoui bug

**Comment by DeityLink** [comment] 2021-08-29 21:27
Duplicate of #26957

**Closed as completed by DeityLink** 2021-08-29 21:27 UTC
Labels: UI
