### ISSUE TITLE
Suicides taint the body, even after being beheaded

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25729] opened 2020-01-22 23:57 UTC
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
386474467ea5d5fc0a04040c7ce57cfd39dd9a7c

# Description
Bodies should inherent appearances and suicided status from their heads/brains.
# Steps to Reproduce
Get a viable head.
Grab the body of a suicide.
Remove it's head, attach the viable head.
Try to clone, fail because it says suicide.
try to defib, see it says nerve trauma.
Toss it in a morgue tray, stare at the red light while the guy sits in his body and cries because his round is now over.

# What you Expected
To be revived as normal, with my appearance and identity as my head was attached to a headless body.
# What Actually Happened
I was taken out of the round because I am now a suicided person who can't even make the morgue tray light green.

**Comment by SGuivenne** [comment] 2020-01-25 01:17
Duplicate of #21458

**Comment by SGuivenne** [comment] 2020-01-25 01:18
Both names are almost identical too.

**Closed as completed** 2020-01-29 14:41 UTC
