### ISSUE TITLE
NanoUI Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22791] opened 2019-05-05 17:45 UTC
(WEB REPORT BY: thatredpyro REMOTE: 206.221.180.138:7777)
# Revision
b172cfaba5ed24ccc75f8d8530a269aa52d44669

# Description
Some nanoUI's tend to not since this or the last week, they used to work without any problems beforehand.Trying to use the fix the NanoUI command, reconnecting, starting the game&byond alltogether or trying to resend resources do not work.I have also tried reverting to an older byond client as well after an admin suggested so (512.1464), no solutions.
# Steps to Reproduce
Sadly have no idea, but the ones that have this problem the most often - nearly always- are the antimatter control one and the GPS UI.Had this with chem dispensers too albeit it's not constant.
# What you Expected
Just the regular UI to appear
# What Actually Happened
Popup with nothing on it appears, no name, no text etc.

**Comment by SonixApache** [comment] 2019-05-06 09:17
There's been a LOT of nano complaints this last month.

**Comment by DeityLink** [comment] 2020-05-24 13:28
Add me to the list of players unable to do their job because of this bug. Can't use any autolathes.

**Comment by DeityLink** [comment] 2020-05-24 13:33
Oh hell, if you place your PDA inside a PDA Terminal it's gone forever as well.

**Comment by SonixApache** [comment] 2020-05-24 15:16
you can just kick the terminal to get the PDA out(?) but it's still shit

**Comment by DeityLink** [comment] 2021-11-23 10:47
Duplicate of #26957

**Closed as completed by DeityLink** 2021-11-23 10:47 UTC
Labels: UI
