### ISSUE TITLE
An AI can right click static to see what's underneath it.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10507] opened 2016-06-11 12:07 UTC
An AI can right click static to see what's underneath it.

**Comment by kol1th** [comment] 2016-06-11 12:36
I thought AIs couldn't right click things?

**Comment by Allspice** [comment] 2016-06-11 17:32
AI can right-click shit that is within ~7 tiles radius of its core, examine what boards a person is holding if they're high enough up in the upload.

**Comment by ShiftyRail** [comment] 2019-06-19 19:21
Dupe of #20772

**Closed as completed** 2021-04-12 05:33 UTC
Labels: Exploitable
