### ISSUE TITLE
Windows construction bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34303] opened 2023-05-26 02:49 UTC
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
69e1a8f231d881be7061e1efed754e08b114634e

Couple of window construction steps are working incorrectly:
some examples:
-make a full window, proceed to fasten it, it transforms into an unfastened single pane window, proceed to fasten the new single pane, turns into an unfastened full window, process repeats.
-attempting to go through the motions of unsecuring a mapped tinted window will proceed reach a point where when you use a crowbar you will pull plastic sheets off the window, infinitely, without prying the window out of its frame.

**Comment by pedr69** [comment] 2023-05-26 21:32
the window is actually fine, it blocks air on the whole tile
just that non-reinforced windows look like they're directional downfacing
probably related to the thing where all windows are also directional downfacing on photos

RCD building also doesn't smooth windows properly

**Comment by Eneocho** [comment] 2023-05-27 17:10
RCD building a _| window makes the windows but the icons are all fucked.

**Comment by DeityLink** [comment] 2023-05-28 09:08
I'm gonna assume that this was also caused by #34287, and will be fixed by #34310

**Comment by pedr69** [comment] 2023-05-28 12:33
this is still a thing
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/b8043edc-9ca1-4e33-942d-26f3b85270b7)

as i said, non-reinforced glass windows don't smooth right(they still block air and movement on the full tile)
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/b1d7201b-b748-48e1-b8dc-0cbd5bb3b2ad)

**Comment by DeityLink** [comment] 2023-05-28 12:52
seems like that other one was there ever since #33574 as full non-reinforced windows didn't have the correct base_state.

**Comment by adacovsk** [comment] 2023-05-28 16:42
Diety keeps breaking things... 🤔

**Comment by DeityLink** [comment] 2023-05-28 17:13
> Diety keeps breaking things... 🤔

That one is a kanef bug caused by his rework (#33574) that's been in the game since last October but ok.

**Closed as completed** 2023-05-28 21:09 UTC
