### ISSUE TITLE
Robot Parts Get You Shocked When Walking Into Electrified Grilles (Glass-Covered)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11440] opened 2016-08-16 02:24 UTC
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)

> Revision: 8bec0b1c70207c03e37d4dc11e14e23f0a1606b5 
> 
> General description of the issue
> Shocked by walking into glass when having robot parts (I know the last part is a factor as I attempt to reproduce this bug after I was cloned, and was unsuccessful).
> 
> What you expected to happen
> Not to be shocked when I walked into a glassed-over shocked grille. 
> 
> What actually happened
> ZAP, MOTHAFUCKA
> 
> Steps to reproduce if possible
> 1. Have robotic parts on your character.
> 2. Walk into an electrified grille that's covered with glass.
> 3. DANGER, DANGER, HIGH VOLTAGE!

**Comment by Exxion** [comment] 2016-08-16 04:34
I'm 95% sure that the robot parts had nothing to do with it and the reason it didn't work when tested after cloning was that it was attempted on a different window that was constructed in a different order, which would make this a duplicate
But that still leaves 5%, so I won't close this just yet

**Comment by nervere** [comment] 2022-08-14 18:59
Not able to reproduce this. Exxion's post is the most likely explanation.

**Closed as completed by nervere** 2022-08-14 18:59 UTC
Labels: Needs Moar Testing

**Comment by Exxion** [comment] 2022-08-14 19:41
Pretty sure some movecode changes at some point after this fixed it regardless of contents order anyway
