### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Eat (Power)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3706] opened 2015-04-02 21:05 UTC
So with the Eat Power you are capable of eating the station intercom ,basically

**Comment by PJB3005** [comment] 2015-04-02 21:55
Who coded intercomms to be /obj/item again? /obj/machinery makes way more sense

**Comment by clusterfack** [comment] 2015-04-08 07:00
They needed to be that way to inherit from radio code, which overall is much larger than machinery code's inheritance.

**Comment by Kurfursten** [comment] 2015-10-15 21:44
@clusterfack Not a bug, close this. Seriously, it's a power that lets you eat wirecutters, shards, arms, and plasma sheets, radios, and we're worried about eating intercoms?

**Closed** 2015-10-16 00:50 UTC
Labels: Oversight
