### ISSUE TITLE
Captain Armor- Suit Storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22377] opened 2019-04-09 06:51 UTC
(WEB REPORT BY: djkramer REMOTE: 206.221.180.138:7777)
# Revision
a5eb8957f668635454de3240bbb5f614e769e5ed

# Description
The captain's armor can't be returned to it's storage
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment] 2019-05-22 16:22
Duplicate of #22294. That is because the cap armour isn't actually a spacesuit.

**Closed as completed by ShiftyRail** 2019-05-22 16:22 UTC
