### ISSUE TITLE
Disintegrate ("Ei Nath")

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#5355] opened 2015-07-12 16:02 UTC
This spell has been a contentious one for a long time. It would probably be worthwhile to have a discussion to see if people like how it currently works, or whether it could be retooled/removed to make wizard shifts more interesting.

This discussion is prompted by requests following a shift I didn't play in -- I'm neutral toward the issue, so I'm posting this Issue for discussion with no agenda as to where it should go. Please post your personal thoughts on the spell and its role within the game.

**Comment by utilitas-** [comment] 2015-07-12 16:10
Completely replace it. Replace it with an area of effect spell that affects the wizard's entire screen and deals 30~ damage to every mob. Long cooldown.

**Comment by Probe1** [comment] 2015-07-12 16:13
Ei Nath sucks but 
I complained about firebirding through walls and being unstoppable.  
I complained about staff of cluwning which is every bit as bad as disintegrate but ranged
I have complained about Ei Nath but I don't have it in my heart to strip away the last vestige of overpowered bullshit away from the antag role.  

Previously if you lost as a wizard it was because you chose not to use these spells.  Or you were new and not very good.  Now there is somewhat more challenge related to wizard and I feel like it's in a good place.  Disintegrate still feels terrible from both sides for me but so does changelings sting and other silence + stun + 1 click you lose buttons.  

I don't feel it's right to take away this last thing from wizards.  They need something.  If you were to remove disintegrate I would like it but I would like more to see it replaced with something that is as dynamic as disintegrate and clutch but isn't as (lack of a better word) cheap.

**Comment by Exxion** [comment] 2015-07-12 16:22
I think it should stay, but maybe have an even longer cooldown/cost more spell points

**Comment by Probe1** [comment] 2015-07-12 16:23
What @Exxion said is a viable solution.

**Comment by utilitas-** [comment] 2015-07-12 16:24
If it's going to stay, it should take the wizard's health as well.

**Comment by AutismSpider** [comment] 2015-07-12 16:33
Give it a cast time.Or make it so the wizard has to get full grab on some one then they can cast it as of right now Ei Nath is the oh shit spell and the i want be lazy fuck and i want kill people in a lazy way.

**Comment by utilitas-** [comment] 2015-07-12 16:38
@AutismSpider Grabbing solves nothing in the MM + Ei Nath combination. They'll be stunned anyway. Cast time would be good. Maybe make it work only on dead or critical mobs?

**Comment by Probe1** [comment] 2015-07-12 16:40
It might not solve anything but it does significantly increase the opportunity cost.  You'd have to cast MM.  Then they'd have to get hit by it.  And you'd have to hit everyone in the room or else they'll swarm your ass.  Then grab them which takes a second and you're stationary.  THEN Ei Nath.

**Comment by kylefiredemons** [comment] 2015-07-12 16:45
The problem isn't rather the spells themselves, it's when MM and Ei Nath gets combined is there a problem, just mainly because of the combo mm+Ei Nath is devastatingly powerful. I think that some armors should actually cancel out MM stun effect or at the very least reduce it, preventing it from being a single 'i win' button. Ei Nath is certainly overpowered, but that's the make the crew keep their distance from the wizard, rather then all of them bumrushing at the same time for valids.

**Comment by Kurfursten** [comment] 2015-07-12 16:51
Also it is worth noting that you can't grab someone while on the ground/stunned/cuffed. Part of apprehending a wizard is realizing that you have to lethal them because they can Ei Nath while tased or cuffed.

**Comment by ComicIronic** [comment] 2015-07-12 16:54
The issue with rebalancing MM is that its criticism applies to most stunning weaponry.

**Comment by Probe1** [comment] 2015-07-12 16:54
You could always chloral them.

**Comment by Kurfursten** [comment] 2015-07-12 16:59
True, but not really the point I was making. Once they're chloraled they're done. Stunned, they can still blink, jaunt, teleport, etc.

**Comment by AutismSpider** [comment] 2015-07-12 16:59
Game combat is base on ebin stun to win shit.

unless some one wants to port over the Stamina stuff?

**Comment by Probe1** [comment] 2015-07-12 17:00
It's a fair point.  

@AutismSpider if that's the scope of the discussion I'm telling you right now it won't happen.  Might as well hash out something that could *possibly* happen.

**Comment by AutismSpider** [comment] 2015-07-12 17:01
Only thing that could possibly happen is Ei Nath getting longer cool down form 60 to 120 or some thing or cast time.

**Comment by Tehsapper** [comment] 2015-07-12 18:22
remove wizard as a gamemode, bam, all problems fixed.

otherwise make it so it requires a consumable item, such as a soulstone, to function

**Comment by FudgePucker** [comment] 2015-07-12 18:29
Ei Nath fucking sucks.
It just fucking sucks.
It doesn't make everybody go 'oh no I better steer clear of the wizard'.
It makes everyone rush for chloral so that they don't get taken out of the round for 2 hours and they can end the shitty game mode as soon as possible.
Steering clear of the wizard doesn't work, he can teleport and go though walls, so if the wizard decides to kill everyone in your department, well too bad, you should have steered clear of the wizard :^), or you should have git gud :^).
Its a fucking spell that can remove anything and everything from the round, that cyborg over there? Fucking gone. The HoS in full combat gear? Fucking gone. Wizard wants you dead you are dead. You can't just leave the wizard alone, he will fucking kill you for shits and giggles, you just cleaning up as a janiborg, dead, you fixing something as a MoMMI, dead, it doesn't matter, he has the ultimate murderboner spell. Its fucking stupid.

Shit why don't we just fucking remove wizard rounds anyways?
Not like anybody really even likes them.

**Comment by utilitas-** [comment] 2015-07-12 18:35
@kylefiredemons 50% of all Ei Nath is when the wizard is laying down, someone comes up to robust him and he Ei Naths him. It doesn't really solve much.

**Comment by Exxion** [comment] 2015-07-12 19:50
Honestly, my only problem with Ei Nath is that the Gem-Encrusted Hardsuit doesn't look distinct enough if you aren't used to seeing it, so you can be disintegrated by someone you hadn't even noticed was a wizard
That said, it combines way too well with anything that stuns, so maybe it should be made to be incompatible with certain spells

**Comment by SangriaMonkey** [comment] 2015-07-12 20:49
Maybe you should come up with better spells so your offensive capability isn't limited to blowing the floor up or an AoE nuke. Honest to god the only reason it gets picked is because it's one of two usable offensive spells. Everything else is a gimmick or an item.

**Comment by Intigracy** [comment] 2015-07-12 23:03
I think it should break every bone in the person's body, not kill them.

**Comment by FudgePucker** [comment] 2015-07-12 23:08
That's even worse.
At least they can kill then clone instead of transplanting the brain.

Or you could just make wizard rounds bus only, that way wizard rounds are a fun treat of sillyness instead of 'oh fucking great another wizard round let me get the chl- EI NATH EI NATH EI NATH EI NATH'

**Comment by AutismSpider** [comment] 2015-07-12 23:14
Add back in the summon carp spell (make it summon three and not one) add some way for wizman to call Experiment 35b to aid him in combat or to summon demons in some goofy way.

When you look at combat spells its el nath or fire ball need fire ball people like 4 to 5 times to crit them and bit more to gib the body or mental focus ends up like fire ball takes 2 to 4 shots crit some one and bit more to blow limbs off.

**Comment by FudgePucker** [comment] 2015-07-12 23:20
@AutismSpider
I think having more silly offincive spells would be nice.
Still,
Wizard rounds would be fixed by making them bus only.
People would enjoy the wizard shinanagans instead of out metagaming the instagibbing murderboner. Admins would be able to choose who would be the wizard, so we might get someone who can roleplay instead of faggots like termed who just murderboner and get dat green text.

**Comment by SangriaMonkey** [comment] 2015-07-12 23:29
>bus only
>roleplay

Neither are going to happen. Players are going to get pissed off about admins spawning shit and the wizard is still going to get syringegunned or shotgunned immediately no matter how much monologuing he can squeeze in. I like wizard rounds because they're one of a small handful where people aren't afraid to *actually antagonize the crew*. It needs more content added to it so it's not limited to murder, cluwning, or having the crew jack you off in the bar for trading cards. Removing things isn't the answer.

**Comment by FudgePucker** [comment] 2015-07-12 23:39
@SangriaMonkey 
>Wizards being the only ones who can antagonize the crew
What are vampires that aren't metagaming fucks who drink from monkey people then just get green text and do nothing
What are lings that aren't metagaming fucks who eat monkey people then just get green text and do nothing
What are traitors who aren't metagaming fucks who just do their easy objective of steal an RCD by printing one and then do nothing

Any antagonist can antagonize, they just have to not be gay homosexuals and try harder.
Only problem with wizard rounds is that the antagonize part comes from being a metagaming fuck and just EI NATH'ing people, to the point of where it is the meta to just take them down on sight because they have taken EI NATH three times, and all the other wizards have to do it because the crew will kill on sight with chloral and shotguns unless you EI NATH them.

Aliums rounds were removed because it became too meta gamey and was the same round over and over and over again.

Wizard rounds are good on paper, but because it is becoming the same round over and over and over and over and over again, it might be best to make it bus only so that the wizard has a chance to survive because the crew didn't go for chloral at round start 'just to be safe if its a wizard round.'

**Comment by Intigracy** [comment] 2015-07-13 00:17
People take them out on sight because of ei nath, yeah, so we don't have to completely get rid of wizard, just find a way to make ei nath less of a shitty headache that it's required to get or else you lose.

I think making it not gib people would help, or even making it deal brute damage to the wizard on use.

**Comment by SangriaMonkey** [comment] 2015-07-13 00:23
If you have a spell that grants some deal of mobility, even blink, you can just horsemask or mime or butt people easily. I do this every time. It pisses them off but doesn't remove them from the round. It's just that not everyone is content with doing that. Some people play this game to kill everyone and gloat about their luck. You can't change people.

Give it a fixed 200 second cooldown and make it on-touch or something.
Add more spells that give the wizard some actual offensive ability. They shouldn't have to scroll into the armory at round start just to function without mm or ei nath.
Don't throw it out entirely just because you don't like it.

**Comment by Probe1** [comment] 2015-07-13 02:49
>Add more spells that give the wizard some actual offensive ability.

Doctor Disintegrate, or How I Learned to Stop Worrying and Fix Fireball.

**Comment by AutismSpider** [comment] 2015-07-13 06:32
Make fire ball work like this.

IED level boom or higher and if the ball hits a mob it sets them on fire.

some thing to make the mental focus suckless and more combat spells or spells so the wizard can summon mobs and stuff.

**Comment by Probe1** [comment] 2015-07-13 06:38
The problem with fireball is it loves to explode on any little thing and take you with it.  I made a poll in the thread the other day after a 3 minute wizard round - the majority of respondents answered Yes to the question "Have you ever killed yourself on accident with fireball?".  The second most voted choice was "I am not an idiot so never use fireball"

This is more general than the topic at hand (disintegrate) but it's part of the issue with wizards going for ei nath.  It works.  It works really well.  Fireball is the opposite.

**Comment by SangriaMonkey** [comment] 2015-07-13 07:39
It'd be nice to have something that hurts but doesn't blow people up or blow holes in the floor every time.

**Comment by Intigracy** [comment] 2015-07-13 07:56
Like mental focus?

**Comment by AutismSpider** [comment] 2015-07-13 07:59
Help if the mental focus was not a staff and suck-less.

**Comment by SangriaMonkey** [comment] 2015-07-13 07:59
No something that can't be disarm spammed away by Johnny Dickfuck the assistant

**Comment by SonixApache** [comment] 2015-07-13 08:01
make it turn people into slightly injured skeletons

make the staff of necromancy enslave skeletons

**Comment by Probe1** [comment] 2015-07-13 10:21
That would be fucking awesome.

![1346949433076](https://cloud.githubusercontent.com/assets/8550416/8647597/5ace732c-2927-11e5-9be8-7d8b43b3e04c.png)

**Comment by Arthurdentist** [comment] 2015-07-14 01:27
In my opinion the best way to balance it would to make it risky. You want to make it a weapon of last resort instead of the go to weapon of every bloody wizard who can't be arsed to think before he picks his spells. The solution I would propose is this then, every time you cast Disintergrate, you take 10 to 20 Brain Damage. You can use it to get out of a sticky situation, but use it too much and it will turn you into a drooling window licker. You'll want to use it when you absolutely have to, as opposed to using it whenever anyone has the audacity to stand adjacent to you. 

You'll get a good few uses out of it before it really starts to hurt, but if you spam it then you'll be falling over, smashing your face into buttons and too dumb to use any machines. Brain damage is also a kind of damage that isn't easy to fix, which is why its ideal. You can't just zip off and grab a medkit to fix your brain problems, you gotta get that alkysine and if you use it too much you'll be a sitting target whilst you stare at the chem dispensers wondering where it all went wrong.

**Comment by Imyourtarget** [comment] 2015-07-14 01:51
I like that idea.  One of the main problems I have with disintegrate as it is is that it COMPLETELY removes you from the round, barring adminbus or a nice botanist or roboticist making a diona or pAI.  

Maybe a Death spell could be added that just kills the target and leaves the body behind?  That spell could have a 60-second cooldown with less ill effects on the caster, while Disintegrate gets a 90-120 second cooldown along with minor brain damage.  Each spell could add a 30-second cooldown to the other spell if the other spell is ready/almost ready to prevent the wizard from spamming both spells into a group of people.

**Comment by FudgePucker** [comment] 2015-07-14 01:54
@Arthurdentist 
Problems with that being:
A) Brain damage doesn't kill you.
You don't need to have 0 brain damage to get 'DAT GREEN TEXT', so there is no real downside to just using EI NATH. You don't need to use computers when you can just gib anybody in your way. At least make it toxin damage, where if you use it more than once with out getting meds, your liver shuts down, and no one is going to perform surgery on that one fucking faggot who picked EI NATH.
To fix faggots just looting medbay storage and taking 20 antitox pills for the entire round, make it so that casting the spell removes antitox from the bloodstream.

B) You can't make cyborgs in wizard rounds. BECAUSE WIZARD ROUNDS ARE GOD FUCKING AW-
You can't make cyborgs because the wizard can just phaze into the walls of AI upload and one human the AI and all the cyborgs. Its fucking bullshit and wizard rounds should be removed holy shit why are they still fucking in?

C)No really, this isn't goon where brain damage is the cause of death in the end, you really think not using computers is really going to matter when he can just fucking EI NATH every single fucking thing on the station?

**Comment by Exxion** [comment] 2015-07-14 01:56
Make brain damage have a chance of causing you to fail at casting a spell, increasing with more brain damage

**Comment by Arthurdentist** [comment] 2015-07-14 03:03
@FudgePucker I do think toxin damage would be a bad idea because of how trivial it is to fix. There is one other type of damage that can kill you and is very hard to fix and that is clone damage, not sure about that, maybe it would be better to use instead of brain damage.

**Comment by FudgePucker** [comment] 2015-07-14 04:07
@Arthurdentist 
You forgot about organ damage.
Make it kill their internal organs if they use it twice within a short period.

**Comment by Intigracy** [comment] 2015-09-17 23:15
Ei nath has been removed, please close.

**Closed** 2015-09-18 00:05 UTC
Labels: Balance, Discussion
