### ISSUE TITLE
MoMMI stuck in vent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15229] opened 2017-06-16 01:41 UTC
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Ventcrawling while buckled into a chair makes you unable to move in the vent, unable to come out of the vent so basically you are trapped forever unless somebody unbuckles you from the chair you got stuck to.

>What you expected to happen
Able to move after ventcrawl.

>What actually happened
Stuck, needed admin intervention.

>Steps to reproduce if possible
Be mommi, buckle to chair near vent, ventcrawl.

**Comment by Exxion** [comment] 2017-06-16 03:57
The real problem is that you can ventcrawl while buckled to a chair

**Comment by Shadowmech88** [comment] 2017-06-16 09:18
Someone made a PR to fix that but the collabs didn't like it.
Also this is essentially a duplicate of #14015.

**Comment by Exxion** [comment] 2017-06-16 17:02
That it is

**Closed as completed by Exxion** 2017-06-16 17:02 UTC
