### ISSUE TITLE
Cyborg missing sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6452] opened 2015-11-06 18:38 UTC
(WEB REPORT BY: gamblorez REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by PJB3005** [comment] 2015-11-06 18:51
Closing because this is definetly caused by #6453.

**Closed by PJB3005** 2015-11-06 18:51 UTC
