### ISSUE TITLE
Light replacer bug

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#4988] opened 2015-06-16 14:58 UTC
The light replacer converts any High Efficiency lights into normal lights when you put them in it.

**Comment by Exxion** [comment] 2015-06-16 16:05
Duplicate of #4972 and fixed in #4800 whenever I finish that

Also, it currently converts all lights to the type of light for the fixture it's used on, so it will turn regular bulbs into HE if used on a fixture that had an HE light manually inserted

**Closed** 2015-06-16 17:36 UTC
