### ISSUE TITLE
Pumping gas at 1.#INF temperature into the TEG causes the server to die from lag.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#16423] opened 2017-11-02 16:52 UTC
Pretty self explanatory really.

But hey at least I'm now the best engineer ever.

**Comment by N3X15** [comment] 2017-11-02 16:53
Gas should never reach this temperature.  It should trigger an assert or something.

/hot opinions

**Comment by FudgePucker** [comment] 2017-11-02 17:10
Why not just have it delete the TEG and spawn a trophy that is named 'you won engineering' description being 'congrats, you broke the laws of physics. I hope you are proud of yourself' and also an infinate power cell.

**Comment by Exxion** [comment] 2017-11-02 17:16
Fun Fact: Judging by falsewall and firelock code, pressure was intended (or at least expected) to be limited to 16777216 (2^24) (the limit of integer precision for a single-precision float)

**Comment by PJB3005** [comment] 2017-11-02 18:22
I think it's caused by an infinite loop in `format_watts`:
https://github.com/vgstation-coders/vgstation13/blob/aacd0c447ddeb4f65ccb3df134cbf77365530633/code/__HELPERS/text.dm#L396-L407

If the number is `1.#INF` that's gonna go on forever and kill the server in the mean time.

**Comment by Shadowmech88** [comment] 2017-11-02 18:30
Don't infinite loops freeze the server completely, not just severely slow it?

**Comment by PJB3005** [comment] 2017-11-02 18:40
@Shadowmech88 BYOND is weird about it.

**Comment by Exxion** [comment] 2017-11-02 19:50
No. BYOND doesn't let a loop execute more than a couple dozen thousand times in a row without pausing to let other things happen unless you explicitly tell it to not check for infinite loops.
This is pretty much pointless because <1 FPS is pretty much exactly as bad as 0

**Comment by gbasood** [comment] 2017-11-03 03:39
While this error did cause an infinite loop warning, it might not have been the thing that killed the server.
Now that the fix PR is merged someone should test if it's still gonna kill serb

**Comment by SonixApache** [comment] 2017-11-03 09:00
superheat cascades when

**Closed as completed** 2018-01-24 21:53 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️
