### ISSUE TITLE
Make infinite glass with an autolathe

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30549] opened 2021-09-06 20:19 UTC
#### Description of issue
You can use the autolathe to make more glass out of glass by making boxes of ornaments and then recycling their contents individually along with the box.

#### Difference between expected and actual behavior
I expect the object produced require equal or less to the materials to produce it, not more.

#### Steps to reproduce

1. place 1 sheet of glass into lathe, you now have 3750 units glass to work with
2. print 1 box of christmas ornaments, costing 2500 units
3. throw ornaments to the floor, they have a chance to break into shards worth 3750 units each recycled
4. repeat until all ornaments are destroyed and recycled
5. recycle the ornament box itself for an additional 2500 units

#### Server revision

69bdef3a6a8981793aac786e7aabc4e2d06a242c

**Comment by Eneocho** [comment] 2021-09-06 20:23
duplicate of #20438

**Comment by Armadingus** [comment] 2021-09-06 20:25
That issue is more related to recycling furnaces and you will still have the issue of ornaments breaking into glass shards.

**Closed as completed** 2021-09-07 04:59 UTC
Labels: Exploitable
