### ISSUE TITLE
When you revive as a zombie, you lose any spells that you would've had when you were alive.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25097] opened 2019-11-19 21:35 UTC
(WEB REPORT BY: memerino REMOTE: 206.221.180.138:7777)
# Revision
a7ab877f80e501efc4e4d07471cdd98625ef80ca

# Description
When you die as a zombie, you lose all your spells.
# Steps to Reproduce
1. Get No Clothes and Pain Mirror (like I did)
2. Suicide, choke to death, and get revived as a zombie (like I did)
3. Run into a crowd of Security and die as a zombie.
4. Revive, and notice that all your spells, including No Clothes, are gone.
# What you Expected
I would revive, then proceed rip and tear.
# What Actually Happened
I woke up and lost a kidney, my wallet, and all my spells.

**Comment by DeityLink** [comment] 2021-09-05 02:15
Duplicate of #30360

**Closed as completed by DeityLink** 2021-09-05 02:15 UTC
