### ISSUE TITLE
PDA light toggle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35626] opened 2023-12-17 16:05 UTC
(WEB REPORT BY: luminaar REMOTE: 209.222.101.3:7777)
# Revision
fb4e0e35de01cb0e64f937426a0d75dfcc0669ea

# Description
The PDA light toggle at the top left of the screen does not turn on the PDA flaslight.
# Steps to Reproduce
Equip PDA on your ID slot, and click on the "Toggle Light" with PDA icon that appears at the toggles.
# What you Expected
The PDA flashlight, however weak, to function.
# What Actually Happened
Nothing.

**Comment by ShiftyRail** [comment] 2023-12-17 16:14
Dupe issue. You can enable the PDA lights from your pda menu like before. Since it's not critical and I dont want to have to revert too many PRs on the 29th I will leave this one as a fix if we keep the eurolights.

**Comment by DeityLink** [comment] 2023-12-22 03:02
Duplicate of #35650

**Closed as completed by DeityLink** 2023-12-22 03:02 UTC
