### ISSUE TITLE
Braindead people getting autoborged

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#4044] opened 2015-04-22 01:37 UTC
Braindeads can be borged using an autoborger, not exactly a bug, but it tends to waste a lot of time given the cooldown for the machine

**Comment by PJB3005** [comment] 2015-04-22 10:47
...then don't put  braindead people on the autoborger?

**Comment by ComicIronic** [comment] 2015-04-22 13:23
Why would you put a braindead in the autoborger?
Not a bug.

**Comment by AutismSpider** [comment] 2015-04-22 19:40
Eh if people ghost when toss in the autoborger just give them temp ban etc.

**Comment by Intigracy** [comment] 2016-03-19 17:55
close it up fam

**Closed** 2016-03-19 18:09 UTC
Labels: Not A Bug
