### ISSUE TITLE
Turrets can't hit you if you're ontop of something, apparently.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2324] opened 2014-12-22 21:36 UTC
http://s7.postimg.org/51atf9orf/000_Fuck_Off.png

**Comment by Kurfursten** [comment] 2015-04-22 11:36
Solved more than a month ago according to Comic in #2371 

Close this

**Comment by clusterfack** [comment] 2015-04-22 11:59
Different issue is different

**Comment by Kurfursten** [comment] 2015-04-22 12:17
Please describe the difference, photocopier is used in the OP image

**Comment by clusterfack** [comment] 2015-04-22 12:26
Ririchiyo made the same mistake, that issue was about the enter proc not being called for the area, as such the mob was not being considered a valid target to shoot at.

**Comment by ComicIronic** [comment] 2015-04-22 13:16
Can confirm this issue is unrelated to #2371 except that they both involve photocopiers.

This could be fixed by making the photocopier's CanPass return 1 if the atom can go over tables.
Otherwise, density works as expected.

**Closed** 2015-04-22 16:32 UTC
Labels: Bug

**Comment by clusterfack** [comment] 2015-04-23 12:14
I mean thanks for that pomf, but I think the issue was supposed to be that lasers dont hit mobs on top of ANY dense object?

**Comment by ComicIronic** [comment] 2015-04-23 18:15
That's intended behaviour.
A mob in a dense turf is embedded inside the turf. Mobs aren't otherwise meant to be able to reach those positions.
