### ISSUE TITLE
The Templar Knight Helmet

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#8357] opened 2016-02-18 19:43 UTC
The north facing sprite is one pixel to the right when it shouldn't be.

My autism.

![](http://puu.sh/ncLMR/2d2d7fa993.png)

**Comment by ghost** [comment] 2016-02-18 19:45
I'm certain this is a duplicate of some form as I've seen this bug reported before. It's worth nothing there are two PRs open right now which edit head.dmi so may be wise not to fix this immediately.

**Comment by 9600bauds** [comment] 2016-02-18 19:47
I think the other issue was inexplicably closed for no reason

**Comment by Imagebard** [comment] 2016-02-18 19:47
The last Issue was closed. They just keep getting closed.

**Comment by NigglyWiggly** [comment] 2016-02-18 19:48
It's a conspiracy

**Comment by ghost** [comment] 2016-02-18 19:48
SHUT IT DOWN

**Comment by 9600bauds** [comment] 2016-02-18 19:49
whoops wrong button ;)

**Comment by Imagebard** [comment] 2016-02-18 19:50
Okay found it
#8205 
Can we close 8205 instead of this one? Its better formatted.

**Comment by NigglyWiggly** [comment] 2016-02-18 19:50
# **:^)**

**Closed as completed** 2017-04-04 19:13 UTC
Labels: Sprites
