### ISSUE TITLE
Two issues about blood

### ISSUE THREAD

**Issue by Manaony** [d3athrow/vgstation13#4241] opened 2015-05-02 10:02 UTC
Issue one: Transforming a monkey mob to human resplenish all it's blood. Allowing medbay to get infinite blood from a single O- SE

Issue two: While this one might be a feature ingesting blood pill instantly regenerate the blood which make no sense. Someone should also test if it bypass blood type rejection.

**Comment by Shadowmech88** [comment] 2015-05-02 10:39
>Someone should also test if it bypass blood type rejection
It doesn't, I've had issues where people make antibody pills containing their blood and I take toxin damage because it doesn't match mine. Presumably, if the toxin damage happens, then you also don't get it added to your blood level.

**Comment by clusterfack** [comment] 2015-05-02 17:23
Consuming blood as a pill doesn't even make sense, if someone forgot to take ingestion methods of activating the reagent they fucked up. It should be injection.

**Comment by Shadowmech88** [comment] 2015-05-02 17:35
It can't be a feature? I mean, making blood pills is pretty handy for Medbay, and paramedics especially, since they can't carry an IV around with them. It's a lot faster and more reliable than using iron to fix blood loss patients.

**Comment by clusterfack** [comment] 2015-05-02 17:37
But in this case it is a literal oversight on the part of the guy who added it, and it should make literally zero sense to a new player because swallowing blood DOES NOT WORK LIKE THAT.

**Comment by ComicIronic** [comment] 2015-05-02 17:37
The issue is that it supplants IVs, which it shouldn't do.

You also don't get anything from drinking blood in real life except vomiting.

**Comment by Shadowmech88** [comment] 2015-05-02 17:40
It wouldn't always supplant IVs given that it's a lot more initial work to acquire the blood, drain it, and put it in pill form. You'd only use the pill method if you have a lot of time to kill as a chemist/doctor and want to make Medbay more prepared, IVs are still the superior immediate solution.
Also you can make and eat antibody pills and get the virus immunity, which should be the same deal given that viral antibodies are blood-based. And I know people won't like having to give an injection to each crewmember when they can't churn out 1u antibody pills.

**Comment by clusterfack** [comment] 2015-05-02 17:56
Actually you are kinda right about that, antibodies should be injection only as well if we want to be consistent.

**Comment by Shadowmech88** [comment] 2015-05-02 17:58
Good luck getting literally everyone who uses Virology to accept that.

**Comment by ComicIronic** [comment] 2015-05-02 18:02
We got them to accept wrapping paper, didn't we?

**Comment by Shadowmech88** [comment] 2015-05-02 18:07
That wasn't as well known, and wasn't a crucial part of a job.

**Comment by Iamgoofball** [comment] 2015-05-02 18:52
Muh reels!

**Comment by 9600bauds** [comment] 2015-05-03 00:13
I'm fairly sure this is new, I've tried multiple times to make blood pills in the past and they never actually added to the person's blood count.
That said: Blood is a little finicky because you can't put it IN an IV bag except by taking it out of someone. Which makes stuff like blood tomatoes useless since the only way of giving someone blood tomato blood would be 5u at a time, in a syringe.

**Comment by Probe1** [comment] 2015-05-03 20:14
Just hook them up to 4 IVs with beakers of blood problem solved.  

Forward thinking bauds.  
No but seriously hook people up to multiple IVs.

@Shadowmech88 an IV is 1 or 2 sheets of metal right?  I don't play paramedic and can't speak to the strategies but you can carry all the IVs you want if you just wrench up the chairs in medbay lobby with that wrench next to cryo or from any youtool™.

**Comment by 9600bauds** [comment] 2015-05-03 21:35
You need to set up four different IV's just because for whatever reason you can't inject blood back into the IV bag? That's a little backwards

**Comment by MercuryDoll** [comment] 2015-05-03 21:35
the problem isn't creating IV "drips", the problem is having enough IV bags to put blood in.
Another problem with using IVs is secure space, because you'll ALWAYS have dumbfucks running either the guy or the drip over, ripping it out. Doesn't help that detaching them is unintuitive. Which is why i always asked for patient examination rooms to be closer to the desk so you can drag them from the scanner right into the exam room to get them fixed without someone else tripping over you.

**Comment by clusterfack** [comment] 2015-05-03 21:41
I'm still not sure I know how to take an IV drip out of myself. Maybe I'll make it so clicking the IV while it is attached detaches it, that would make sense.

**Comment by 9600bauds** [comment] 2015-05-03 21:41
Clicking the IV ejects the container, to detach it you have to click and drag it to the person again.

**Comment by clusterfack** [comment] 2015-05-03 21:43
That's just... just terrible

**Comment by 9600bauds** [comment] 2015-05-03 21:46
Also, to toggle between taking blood and injecting it you have to rightclick it and use the "Toggle mode" verb. There's no indicator on which mode it's on until you toggle it.

**Comment by clusterfack** [comment] 2015-05-03 21:48
Examine text could clear that up pretty easily

**Comment by Probe1** [comment] 2015-05-03 23:09
@MercuryDoll I put people on stretchers when I need them immobilized.  That's what they're for.

**Comment by MercuryDoll** [comment] 2015-05-04 15:34
it's not the people that are IV'd, it's the other dumbfucks clogging medbay, running through people so they can see all the action and find a situation to be hero. Especially the greyshirts in search of selfmedication like to run over IVs and patients.

**Comment by Probe1** [comment] 2015-05-04 15:36
Can't run over a stretcher with someone on it.  You can push it but as long as you didn't do something crazy like leave it in the middle of the medbay halls where it becomes an obstacle, that shouldn't be a problem.  Try it out.

**Comment by MercuryDoll** [comment] 2015-05-05 03:38
that's the problem though. where in medbay are you supposed to store a patient on a roller with an IV drip next to it without some fucktard running it over.
The problem is that the patient rooms' doors need medbay access, so you can't just leave them there while trying to fix another patient.
Would help if we had actual treatment cabins (glasswalled 2x2 rooms without doors) where the sleeper and cryos are. I know we could technically build them ourselves but eh.

**Closed** 2017-01-07 15:22 UTC
Labels: Bug / Fix, Discussion, Oversight
