### ISSUE TITLE
Losing limbs doesn't hurt you

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#14199] opened 2017-02-26 00:10 UTC
You can slice off every limb on a person and they'll stay at 100% health. They don't even bleed. I think it even technically heals them if it takes multiple hits to delimb since they'll go 100%->85%->100%. I appreciate that you can lose limbs in combat now without being killed or put in crit, but this isn't how it should work unless the limb is a prosthetic. 

![untitled](https://cloud.githubusercontent.com/assets/25004372/23335895/2d5df880-fb95-11e6-91ea-6eb81bd81c27.png)

**Comment by Riekland** [comment] 2017-02-26 00:15
>he can't survive quadruple amputation

I didn't know our server health settings were at "casual"

**Comment by jknpj** [comment] 2017-02-26 00:17
if you have 80 burn damage in your arm and ir gets sliced off, those 80 brute damage don't apply to you anymore.

**Comment by Riekland** [comment] 2017-02-26 00:20
Wait, that's how they fixed it? I thought it was a percentage of the damage to the limb is transferred to the chest or something like that?

**Comment by Zth--** [comment] 2017-02-26 00:21
The only problem I see here is you should bleed if someone cuts your arm. So then you should be able to apply a tourniquet or something like that.

**Comment by Kurfursten** [comment] 2017-02-26 00:27
I discuss my thoughts at length on this subject at the end of #12804

**Comment by SkowronX** [comment] 2017-02-26 01:43
Health, damage, and dismemberment is a highly broken system that really hasn't been touched much.

**Comment by NigglyWiggly** [comment] 2017-02-26 15:14
I'm pretty sure this was intentional.
The HF blade is supposed to be able to slice you to bits perfectly

**Comment by Lokiamis** [comment] 2017-02-26 15:40
@NigglyWiggly 

![untitled](https://cloud.githubusercontent.com/assets/25004372/23341123/2b875bb8-fc18-11e6-8fee-b23dd5906d26.png)

**Comment by NigglyWiggly** [comment] 2017-02-26 16:08
Well yeah, the damage system is broken as hell. I just mean the HF blade was intended to slice off limbs cleanly. It used to just do insta-kill tier damage

**Comment by Shadowmech88** [comment] 2017-02-26 16:13
It actually still does do instakill damage.
But severing code is run before damage application, so the HF sword's perfect sharpness results in limbs being severed without fail when hit, meaning there's never a chance to apply damage to them.

Hitting someone in the chest with it will still deal instakill damage, though.

**Closed as completed** 2019-03-19 18:29 UTC
Labels: Discussion
