### ISSUE TITLE
give exotic seeds biomolecules

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34226] opened 2023-04-18 23:16 UTC
(WEB REPORT BY: jesture REMOTE: 206.221.180.138:7777)
exotic sneeds

**Comment by Eneocho** [comment] 2023-04-22 21:16
Duplicate of #34120

**Comment by nervere** [comment] 2023-06-12 18:39
content is reverted

**Closed as completed by nervere** 2023-06-12 18:39 UTC
