### ISSUE TITLE
(WEB REPORT BY: somhuan REMOTE: 198.245.63.50:7777) Borg modules are locked when empty

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4256] opened 2015-05-03 02:38 UTC
>Revision (Should be above if you're viewing this from ingame!)
92fb48c0462e9eea7ebd055067f4e488601d3a37

>General description of the issue
Engineer borgs lose access to modules if they use up all of a material
>What you expected to happen
When I use up a material, the module naturally retracts so I can use another module. Or, at least, I could select store to put it away and swap out.

>What actually happened
When I used all of a material, in this case floor tiles, the module they were in became locked and could not be stored or changed, because you "can't store something you're not holding". Even if I synthesize more materials, the lockout remains and I am still registered as not holding the item.

>Steps to reproduce if possible
Empty a stack of materials entirely, whether through placing floor tiles down or loading metal into a machine.

**Comment by Exxion** [comment] 2015-05-03 05:27
Duplicate of #4010 and (sort of) #4163

**Closed** 2015-05-03 10:51 UTC
