### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Taxi station Viro

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5071] opened 2015-06-20 18:28 UTC
There be a table in taxi's viro room that can't be reached because of it being blocked by the machines. It has supplies that viro can use but can't.

**Comment by PJB3005** [comment] 2015-06-20 18:53
Dupe of #4696

**Closed** 2015-06-20 19:32 UTC
