### ISSUE TITLE
Needs Glasses disability bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34168] opened 2023-03-18 13:13 UTC
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

# Description
If your character needs prescription glasses and you slide mesons over them, you will lose the effect of the glasses and suffer the nearsightedness penalty (3 dithered tile radius at the end of vision range) until the mesons are taken off

**Comment by pedr69** [comment] 2023-03-18 19:32
duplicate of #34119

**Comment by Exxion** [comment] 2023-03-19 01:27
I can't wait to accidentally close another issue as not planned since changing that changes the default

**Closed as not planned** 2023-03-19 01:26 UTC
