### ISSUE TITLE
it keeps happening

### ISSUE THREAD

**Issue by PrimeDSS13** [d3athrow/vgstation13#28357] opened 2020-12-12 03:10 UTC
the supermatter shard doesn't kill people if ZAS shoves it into people, only if they walk into it
![image](https://user-images.githubusercontent.com/57536342/101971206-aa9b4800-3bfd-11eb-869c-77bd098a1eea.png)

**Comment by Exxion** [comment] 2020-12-12 03:14
Duplicate of #22176 and probably others

**Closed as completed by Exxion** 2020-12-12 03:14 UTC
