### ISSUE TITLE
[Feature Request] Refactor the way that borg component damage is calculated

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#21900] opened 2019-02-28 16:12 UTC
[featurerequest]

At the risk of being booed...

Damage should be dealt exclusively to your armor plating until it breaks, then begin evenly damaging your components. Bonus points if higher tier cyborg components (or at least armor plating) are added to the exofab via research, similar to stock parts, with higher HP values.

I've complained about this for years, but borgs have become increasingly fragile over time. They are now susceptible to stuns, (still) instakilled by EMPs, melted by atmos, and yet nothing has been done to make it easier to bring one back into the round, or to prevent them from losing their vision, tools, or even their damn power cell when they eat a stray laser or a toolbox and get unlucky.

Do I really need to justify this further? What is even the point of having overall health or an "armor plating" component when damage seems to destroy anything inside of you at leisure, regardless of the status of the armor plating, which is just as good as instant death?

Cyborgs also don't enjoy the luxury of the magic heal tube or cloner, where they can be back in the round in two minutes if someone shoves them in one, then the other. They need someone to care enough about borgs to do something in the first place, to somehow get science/robotics access to operate the exofab, to have materials available, and to have the knowledge to do any of the repairs, or even to pry their MMI out and free them from cybernetic hell.

**Comment by jknpj** [comment] 2019-02-28 16:15
You're not supposed to take damage before your armor breaks

**Comment by Hoshi-chan** [comment] 2019-02-28 16:16
It happens all the time. Try to flash an assistant and eat a toolbox, or catch a stray hit from a blob, and kiss your camera, cell, or actuator goodbye, rendering you effectively dead.

EDIT: You're right though, armor plating seems to be broken every time this happens to me, but the damage that it's receiving seems disproportionate to what it should be.

EDIT: Take me to the thunderdome and beat me with toolboxes, since the test serb is gone, and I'll show you.

**Comment by SonixApache** [comment] 2019-02-28 16:21
IMO: Borgs should have targetting-based damage, like carbons. And I think there should be two actuators; one for the modules and one for the legs.

**Comment by Hoshi-chan** [comment] 2019-02-28 16:22
I don't really care how it's refactored so long as you no longer lose the ability to fight back LONG before your health is actually depleted. It's like if humans could randomly lose limbs and organs from minor injuries.

Maybe a scaling loss of functionality rather than the binary you have it or you don't that is currently in place.

**Comment by SonixApache** [comment] 2019-02-28 16:45
>so long as you no longer lose the ability to fight back LONG before your health is actually depleted. 
>It's like if humans could randomly lose limbs and organs from minor injuries.

>It's like if humans could randomly lose limbs and organs from minor injuries.

So what you're saying is, code borg blood? 😂

**Comment by SGuivenne** [comment] 2019-02-28 18:22
You know, while you're at it you could throw several borg armor flavors down, like an ablative armor that ups heat damage resistance and reduces effect of lasers but is less effective at blocking conventionals, or have some super expensive ferro-fibrous armor for the nerds here to be able to consider flavortext.  Maybe even some stupid borg mythril armor.

**Comment by Kurfursten** [comment] 2019-02-28 18:31
Uhh the technical term is borg *oil*

**Comment by Sooose** [comment] 2019-02-28 19:12
>humans could randomly lose limbs

Sounds a lot like breaking your hand with 30 or so brute. I down thumbed for the idea that borgs should have all their modules take damage evenly after armor wearing off, nothing would ever get disabled at that point. If borgs are taking module damage before their armor is removed that is a bug that should be fixed.

**Comment by SGuivenne** [comment] 2019-02-28 19:15
You know what would actually be nice?  If borgs got some kind of "internal damage detected" notifications when their armor breaks and they start taking module damage, up until the diagnostic system itself gets broken.   Would increase survivability without power creep.

**Comment by SonixApache** [comment] 2019-02-28 19:30
@SGuivenne they have that, I'm not sure if you're trolling or not.

**Comment by spoonylove** [comment] 2019-02-28 19:36
How come nanobots dont work for borgs? 🤔

**Comment by SGuivenne** [comment] 2019-02-28 21:40
> @SGuivenne they have that, I'm not sure if you're trolling or not.

They have a system that tells you when its destroyed, not when its just damaged.

**Comment by Dacendeth** [comment] 2019-02-28 21:51
I did some tests as and borg armor seems to always break first as intended (having 60 health) before any of your components get hit, after which it's randomly picked between remaining functional components. So if you are very unlucky you can only take 4 laser shots (120 damage) before your actuator or cell breaks or take as much as 9 shots (270 damage) and still retain your ability move, talk locally, see, and use all modules if you got lucky.

**Comment by DrSnips** [comment] 2019-02-28 23:39
We currently do have upgraded borg parts but some small oversights/issues came up now that time has passed with them. 1) They are kind of expensive for the protection they offer partly due to the next issue. 2) The cell doesn't have any resist so it ends up getting killed first which means upgrades outside of armor don't increase your life at all. Its a chain is only as strong as it's weakest link thing. 3) The upgraded parts don't see much use maybe due to them being kind of hidden behind research.

**Closed as completed** 2021-04-24 06:54 UTC
Labels: Unfulfilled Feature Requests
