### ISSUE TITLE
Infinitely drinkable/pourable glass of blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6261] opened 2015-10-22 06:26 UTC
(WEB REPORT BY: sandvichman REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

http://github.com/d3athrow/vgstation13 ?
>General description of the issue
Apparently I was able to make a glass of blood infinitely usable

>What you expected to happen
I would drink it and it would go away

>What actually happened
I drank it and drank it and drank it and drank it and it didn't go away

>Steps to reproduce if possible
Hook a chef drink up to the IV and set it to take blood. Then remove it and enjoy.

I seriously hope this wasn't a one time thing.

**Comment by clusterfack** [comment] 2015-10-22 06:34
Ha, hahahaha. I think I remember someone (d3athrow?) causing blood to fail being transferred to/from some mobs. 

If I had to bet that would be the cause of this.

**Comment by clusterfack** [comment] 2015-10-22 06:40
Or related to this runtime

runtime error: undefined variable /obj/item/weapon/reagent_containers/blood/empty/var/my_atom
11:11:34 Runtime detected
undefined variable /obj/item/weapon/reagent_containers/blood/empty/var/my_atom at Chemistry-Reagents.dm:220

**Comment by PJB3005** [comment] 2015-10-27 18:02
With how blood works, wouldn't this allow you to BASICALLY make bleeding a joke?

**Comment by ihadtoregisterforthis** [comment] 2015-10-31 21:32
Blood doesn't appear to be consumed on a reaction either.

Tested in the test server an exgrenade with smoke and blood and there wasn't even smoke.
Tried again a small grenade of foam and blood, no foam appeared and the grenade was intact, with only blood inside.

**Comment by clusterfack** [comment] 2015-10-31 22:58
It's a runtime caused because blood uses special code to make sure you cant draw blood from skellingtons, but it trys to read unreadable vars from different containers to check that

**Comment by FudgePucker** [comment] 2015-11-05 04:44
@clusterfack 
Remove skellingtons.
PROBLEM
SOLVED

Also what caused this to happen?
I remember that plantbros also can't have their blood drawn.
Did this bug recently pop up, or was it here the entire time and we just didn't notice it?

**Comment by clusterfack** [comment] 2015-11-08 03:35
Caused by shitty IV code for drawing blood apparently, more of an indirect result than anything of that. The skellington blood code only revealed the problem because nothing had been really properly used by IV's up until now.

**Closed** 2015-11-09 12:56 UTC
Labels: Bug, Exploitable
