### ISSUE TITLE
C-20R uses weird 12mm ammo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28712] opened 2021-01-29 09:27 UTC
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
129c0dcfb1e694cea583118e774bacdfa556a00d

# Description
C-20R mags can't be reloaded with 12mm ammo.
# Steps to Reproduce
Hack autolathe, print c-20R mag. Print 12mm ammo box. Try to load the mag. It's not fitting in.
Print normal 12mm mag, try to load it - it loads fine.
# What you Expected
c-20r takes 12mm, so gets loaded with 12mm ammo
# What Actually Happened
C-20R takes 12mm but doesn't want 12mm from ammolathe.

the ammo found in C-20R, spawned in pre-loaded:
/obj/item/ammo_casing/a12mm
The ammo in 12mm ammo box:
/obj/item/ammo_casing/a12mm/assault

**Comment by SonixApache** [comment] 2021-01-29 16:49
dupe of  #28675

**Comment by DeityLink** [comment] 2021-08-17 15:05
Duplicate of #28675

**Closed as completed by DeityLink** 2021-08-17 15:05 UTC
