### ISSUE TITLE
(TWO AI) Malf AI still rolls with normal AI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31786] opened 2022-01-04 02:50 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
this leads to a normal AI in the main core and a second malf AI in the right/left AI holder
also it alerts everyone its malf because this is the only scenario where this could occur

**Comment by robintime** [comment] 2022-01-04 03:38
duplicate of #31439 and #31346. please do not make duplicate issues. thank you!

**Closed as completed by robintime** 2022-01-04 03:38 UTC
