### ISSUE TITLE
invisible grills

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9540] opened 2016-04-20 19:00 UTC
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I think I am making invisible grills. when I use the rods, there is no words that come up saying,"assembling grill", but if I wait for a sec, move away, and try to move back, I can't. I tried alt clicking on the square, and nothing came up
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible
> assemble grill. I used the pagedown shortcut, if that even makes a difference

**Comment by Intigracy** [comment] 2016-04-20 19:44
dupe of #8976

**Comment by Exxion** [comment] 2016-04-20 20:01
Wait hold on
Nothing came up when you Alt+clicked on the tile?
...Maybe something did come up but it had neither an icon nor a name so you couldn't see it

**Closed as completed** 2016-04-20 20:06 UTC
