### ISSUE TITLE
Pod construction bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25873] opened 2020-02-19 06:31 UTC
(WEB REPORT BY: cabik REMOTE: 206.221.180.138:7777)
# Revision
a3c046ba069068b80a47bc2a48a923328166f391

# Description
when bulding a pod using a welder at a certain point will skip steps
# Steps to Reproduce
after board is screwed in I used a welder "You cut The spacepod frame's bulkhead panelling loose" which set the pod to one that had the core and bulkhead installed
# What you Expected

# What Actually Happened

**Comment by west3436** [comment] 2024-03-21 13:10
Unable to reproduce; likely fixed in #27519.

**Closed as not planned by west3436** 2024-03-21 13:10 UTC
Labels: Bug / Fix
