### ISSUE TITLE
Diona stuck in vent.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14016] opened 2017-02-14 20:33 UTC
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
>Revision (3887dd072566a1606ca7903249c8cbf301de2847)

>General description of the issue
Stuck in a pipe on Box station in Xenobio maint whilst ventcrawling as a diona nymph.

>What you expected to happen
To be able to traverse the pipes.

>What actually happened
I got stuck in the pipes. (None of the four cardinals would move me)

>Steps to reproduce if possible
Go inside the xenobio pipes as a Nymph, and keep traversing the maint from start to end.

**Comment by Exxion** [comment] 2017-02-14 20:35
This is not at all enough information

**Comment by Exxion** [comment] 2017-02-14 21:01
After checking it out on the server, I'm pretty sure something was just stunning the nymph. Every time I revived the body and moved around, it would happen again after a few seconds. It's not clear exactly what caused the stun, though. The pipes were cold and at low pressure, but it would always happen before the cold warning even showed up.

It was probably the cold, but you should really at least have SOME warning before getting stunfucked directly to death.

**Comment by Zth--** [comment] 2017-02-14 21:03
Celt said this was intended, I say it's bullshit

**Comment by Exxion** [comment] 2017-02-14 21:04
>Getting stunned permanently until you die with no warning or way to know it will happen without an atmos analyzer is a feature

Thanks, Celt

**Comment by PJB3005** [comment] 2017-02-14 21:10
You literally get a warning before entering potentially lethal vents though.

**Comment by Exxion** [comment] 2017-02-14 21:11
Oh yeah
I forgot about that

You should still get a warning before ACTUALLY DROPPING though
We have the cold warning
It just happens after you're already fucked, making it worthless (in this circumstance)

**Comment by Shadowmech88** [comment] 2017-02-14 22:27
Since very few ventcrawling mobs are capable of resisting cold, I think it's dumb to allow the high volume of gas inside pipes to make any mob that ventcrawls cold to the point of hypothermia.

What's the point of monkeys and nymphs being able to ventcrawl if they always pass out inside the pipes? They're not even capable of bringing cold resistant gear with them.

**Comment by Exxion** [comment] 2017-02-14 23:02
The pipes in the case of this report weren't even at high pressure
They were at low pressure
I think, at least

**Comment by JustSumBody** [comment] 2017-02-14 23:07
I'm PRETTY SURE this is the related ahelp(made 3 hours ago)
```MoMMibot: Help: Avadanatinde/(Noodles): I BUCKLED MYSELF INTO A CHAIR BEFORE VENTCRAWLING AND NOW IM STUCK IN THE VENT - 4 Active admins, 0 AFK admins.```
This is likely just a duplicate of #14015

**Comment by PJB3005** [comment] 2017-02-14 23:10
The steps to reproduce of this bug report seem to imply he got stuck while moving, not from the get go.

**Comment by Exxion** [comment] 2017-02-14 23:21
Yeah
I asked him
He got stuck once that way, and twice in a different way (the way in this report)

Also, nice job reading the comments

**Comment by FudgePucker** [comment] 2017-02-16 04:21
@Shadowmech88 
And how exactly does your plan of reducing volume in pipes work?
You could destroy several engines, forcing us to use nothing but Singuloth and AME.

**Comment by Shadowmech88** [comment] 2017-02-16 05:21
I don't think we should reduce the volume in pipes.
I think hypothermia in pipes should function differently than regular hypothermia so mobs don't pass out when they try to ventcrawl.

**Comment by Aurx** [comment] 2017-02-16 22:35
Hypothermia for non-humans that have valid reasons to be naked just needs to be reworked in general.  

Actually, hypothermia in general needs adjustment.

**Closed as completed** 2017-08-16 16:43 UTC
Labels: IT'S A FEAAAATUUUUREEEEEEEEE
