### ISSUE TITLE
WIZARD: pitbulls attack arcane golems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29339] opened 2021-04-25 02:39 UTC
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
summon pitbull, summon arcane golem, pitbulls ravage golem to death.

**Comment by DeityLink** [comment] 2021-08-11 12:41
Duplicate of #26736

**Closed as completed by DeityLink** 2021-08-11 12:41 UTC
