### ISSUE TITLE
Toxins Test Area Atmos Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34899] opened 2023-08-12 23:54 UTC
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
9e32cd263de90541cf23651273be707f8492d280

# Description
In all Toxins Test Ranges that use a mass driver with a timed door at the test site to launch a TTV for testing, unless you put a trash chute leading to the driver, the room where the driver is will repressurize as you enter it to place another bomb. Not only is the ZAS a pain in the ass every time you open the windoor, but your bomb is also highly likely to just get sucked out as soon as the blast door opens before the mass driver can even fire it. This affects numerous maps except for maybe roid?

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment] 2024-04-04 13:49
Duplicate of #14354.

**Closed as not planned by west3436** 2024-04-04 13:49 UTC
