### ISSUE TITLE
Wizards still have their flavor text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22875] opened 2019-05-10 20:55 UTC
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
9ac014065248be774c1b5c3143416a605cf38379

# Description

See title.

**Comment by Zth--** [comment] 2019-11-19 11:23
Duplicate of #20903
Closing because that one has more info

**Closed as completed by Zth--** 2019-11-19 11:23 UTC
