### ISSUE TITLE
Missing or Orphaned Sprites

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#8215] opened 2016-02-11 04:07 UTC
I've got two sprite issues needing to be looked at, one more important than the other.
Firstly, Bullet Shrapnel. It counts as an object you can pick up when removed and cuts like glass if stepped on, which is bad for freshly stripped patients, but also means without alt clicking you cant pick it up. Could be really dangerous for any naked crew members being worked on as being placed there could cut them up if not cleaned.

Secondly, Plasterer's jacket, the yellow and green one from the Costume Autodrobe hides your uniform while its equipped, showing you in your skivvies and a jacket, probably not as intended but could be used to hide objectives if found out.

**Comment by ghost** [comment] 2016-02-11 08:05
First part is a duplicate of #8066 but the second part I can fix.

**Closed as completed** 2017-03-13 08:26 UTC
Labels: Sprites
