### ISSUE TITLE
Blind as MMI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15275] opened 2017-06-23 00:19 UTC
(WEB REPORT BY: saronsen REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!) d2b45f9c028a58ad5879a8939ba61ed2a8cc4229 

>General description of the issue
You are blind as an MMI when you are debrained then added to the MMI, or removed from the MMI then put back on. Functions normally if removed from cyborg body or body is destroyed.

>What you expected to happen
To be able to see when your brain is placed in the MMI

>What actually happened
Blind while in the MMI

>Steps to reproduce if possible
Have brain removed, be put in MMI. Be removed from MMI, then put back on.

**Comment by Dacendeth** [comment] 2017-06-23 07:29
I've had this happen to me as well when I was debrained after a suicide with a duck.

**Comment by SonixApache** [comment] 2017-06-23 19:29
same

**Comment by Exxion** [comment] 2017-06-24 00:10
I had to fix this for three people in one round once
Not sure if it breaks for a round at a time or depends on how you do the debraining though

**Comment by SonixApache** [comment] 2017-06-24 00:32
I think it tries to apply blindness from being dead (or being a brain?), but then doesn't unfuck it after you get put in the MMI.

**Comment by Shadowmech88** [comment] 2017-09-16 05:22
Duplicate of #14690.

**Closed as completed by Shadowmech88** 2017-09-16 05:22 UTC
Labels: Bug / Fix
