### ISSUE TITLE
Pitbulls and Arcane Golems fight each other

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27508] opened 2020-08-11 00:16 UTC
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
3bb9b5316d9d8d35158c9cb1d3167886c2570bd7
# What you Expected
Six thousand pitbulls
# What Actually Happened
Captain's Quarters turned into a dogfighting ring.

**Comment by kernikov** [comment] 2020-08-11 00:17
Duplicate of #26736

**Comment by DeityLink** [comment] 2021-08-11 12:41
Duplicate of #26736

**Closed as completed by DeityLink** 2021-08-11 12:41 UTC
