### ISSUE TITLE
You can be radded through a full radsuit.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8099] opened 2016-02-05 02:01 UTC
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision 9cb2cff81bce122c4596573433b45605e3d5e52e 

Radsuit and rad hood, stand next to DJ station transmitter, instantly collapse.

**Comment by ihadtoregisterforthis** [comment] 2016-02-05 02:05
This is getting out of hand

**Comment by 9600bauds** [comment] 2016-02-05 02:15
hmmm

**Comment by ghost** [comment] 2016-02-05 02:46
This was reported the round before the bugfix for what I presume will fix it was merged.

**Comment by CptWad** [comment] 2016-02-05 07:56
doesn't need more testing its broken confirmed last round when I myself was radded 4noraisin after celts _bugfix_

**Comment by ghost** [comment] 2016-02-05 08:02
Feck.

**Comment by 9600bauds** [comment] 2016-02-05 08:03
I'm gonna be fair and tag this as oversight

**Comment by AutismSpider** [comment] 2016-02-05 08:35
going be more then over sight my man he needs redo all code for the suits now some one test the bio suits etc next make sure they stop viros and big stings.

**Comment by 9600bauds** [comment] 2016-02-05 08:38
> he needs redo all code for the suits now 

uhhh

**Comment by ghost** [comment] 2016-02-05 11:34
See if your PRs were atomic you'd be able to revert just the one causing trouble.

**Comment by CptWad** [comment] 2016-02-05 17:46
Careful termed niggly bullied celt for a good few hours over atomic

**Comment by 9600bauds** [comment] 2016-02-05 20:13
Atomic is a buzzword

**Comment by ghost** [comment] 2016-02-05 20:21
Alright, I know what the reason behind this is, and it's awful.
The radiation suit doesn't cover the whole body, it exposes the hands and feet. TECHNICALLY SPEAKING, this is actually desired behaviour.

**Comment by ghost** [comment] 2016-02-05 20:21
I'll get a fix soon

**Comment by ihadtoregisterforthis** [comment] 2016-02-05 20:41
Either radpoof gloves and boots or a larger suit. The sprite itself doesn't cover hands or feet.

**Comment by ghost** [comment] 2016-02-05 20:46
Yeah, that's what I'm doing, @ihadtoregisterforthis

**Comment by ghost** [comment] 2016-02-05 21:41
Well, this is awful - turns out rad code checks ONLY whether or not the armour is exposed, it doesn't give a fuck about boots or gloves.

`altered = max((((effect - (effect*(getarmor(null, "rad")/100))))/(blocked+1)),0)//Rads auto check armor
            radiation += altered
`

**Comment by ghost** [comment] 2016-02-05 21:45
`
    var/list/body_parts = list(head, wear_mask, wear_suit, w_uniform)`

thanks oldcoders

**Closed as completed** 2016-02-07 01:15 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Oversight
