### ISSUE TITLE
Grey's can't use Project Mind on round start

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6828] opened 2015-12-02 01:50 UTC
(WEB REPORT BY: densane REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: cd32136cb983ffc498e7fe7a0a45f93c64ed6ee3 
> 
> General description of the issue
> Cannont use Project Mind as Grey
> 
> What you expected to happen
> To be able to use Project Mind.
> 
> What actually happened
> Get a flag in the chat box in red saying "You shouldn't have this spell! Something's Wrong." even though you get the annoucenment in chat upon spawning into the game saying "You feel your voice can penetrate other minds."
> 
> Steps to reproduce if possible
> Be Grey
> Click the UI button to project mind
> Be sad when you get an error message

**Comment by Kurfursten** [comment] 2015-12-02 01:53
Duplicate of #6818

**Closed as completed** 2015-12-02 02:55 UTC
