### ISSUE TITLE
HUD is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11351] opened 2016-08-09 04:20 UTC
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)

> Revision 
> 978a440d2fa85b07884ed99bc821346ed8519b74 
> 
> General description of the issue
> Button placement on HUD is fucked, run/walk toggle is partly offscreen and damage zone selector is completely absent
> 
> What you expected to happen
> Normal HUD
> 
> What actually happened
> see above
> 
> Steps to reproduce if possible
> Play the game

**Comment by icantthinkofanameritenow** [comment] 2016-08-09 04:21
And here is the screenshot of the issue.
![scrnshot1](https://cloud.githubusercontent.com/assets/16140902/17504485/36cc0f86-5dc7-11e6-9d88-fcb844501065.png)

**Comment by Exxion** [comment] 2016-08-09 04:25
Duplicate of #11352
Technically this one came first but that one's better

**Closed as completed by Exxion** 2016-08-09 04:25 UTC
