### ISSUE TITLE
Allow the copying of the station blueprints.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8758] opened 2016-03-11 01:37 UTC
It's no surprise that people like to hog their one of a kind items, here are some examples. Ask to borrow the captains laser, or his or the HoS's telebaton? Fat chance. Want a hand tele? Unless you're the clown you won't have much luck with that. Want the CMO's hypospray? Once you pry it off of his dead body. The RD's superior welding goggles? Just kidding you can make those in RnD now. But the station blueprints. This has to be one of the most harmless out of all the unique items, so why not let it be reproduced for building purposes?

Also on a side note, traitors can currently just take a picture of the station blueprints and succeed that objective anyways, leaving the original blueprints untouched. It's just a hastle to ask the CE to loan you the blueprints 50% of the time because they think you just want to steal them.

**Comment by 9600bauds** [comment] 2016-03-11 01:42
What is this reaction shit
We facepunch now

**Comment by ihadtoregisterforthis** [comment] 2016-03-11 01:50
I can't encourage that reaction, have a downvote

**Comment by gbasood** [comment] 2016-03-11 02:45
Might be useful for gathering opinions on discussion issues though, neato

**Comment by Shadowmech88** [comment] 2016-03-11 02:48
Won't be fantastic until Github adds a total tally for :+1: / :-1: like Gitlab has.

**Comment by Blithering** [comment] 2016-03-11 02:59
I am reminded of that one comic where some MoMMI renamed every room on the station to benis.

**Comment by CptWad** [comment] 2016-03-11 03:27
Its not much trouble for the objective if you know how to take pictures of the blueprints
otherwise, yeah, maybe we could add a file cabinet with like five copies of the blueprints in the CE's office and presto issue gone

**Comment by gbasood** [comment] 2016-03-11 05:18
@Shadowmech88 It tallies the :+1: :-1: for reactions on the main issue so that's basically the same

**Comment by clusterfack** [comment] 2016-03-11 07:21
The station blueprints are too stronk.

Well it may be okay if you can only make copies of the original and not copies of copies.

**Comment by CptWad** [comment] 2016-03-11 07:24
Like using nanopaper on it can copy it and allow its functions, and counts as an objective too?
But if you copy the copies it just tells you that its shitty and too inaccurate to properly do shit with?
Maybe copies are a lot like mommi prints and can only designate new rooms and not rename them

**Comment by ghost** [comment] 2016-03-11 10:11
Not seen the horror that is 'The clown got the blueprints'?

> Atmospheric alarm detected in the captains butt

Some stripped-function blueprints orderable via cargo or reproducable via nanoprint, that act like the MoMMI ones would be good, as they are already limited to only defining new rooms, so wouldn't be too hard to code in

**Comment by Imagebard** [comment] 2016-03-11 15:48
In space, nobody cares about your ~~upvotes~~ post reactions.
Unless you're gauging if a PR is controversial that is.

>But the station blueprints. This has to be one of the most harmless out of all the unique items, so why not let it be reproduced for building purposes?

If traitors are interested in it, then its a high security item. Please understand.

**Comment by PJB3005** [comment] 2016-03-11 16:18
@Imagebard it's high security because muh immersions.

**Comment by Blithering** [comment] 2016-03-11 16:45
Perhaps have a mechanic printable nanopaper item on the lines of 'station design addendum'. Single use, designates a new room for people's projects.

**Comment by Killette2** [comment] 2016-03-11 20:49
Well to sum up most people's opinions, the blueprints are obviously useful and having only one in existence sucks ass. A mini blueprint or one use blueprint for new areas seems like a good idea.

**Comment by Imagebard** [comment] 2016-03-11 20:54
>A mini blueprint or one use blueprint for new areas

*That don't count as a tater tot objective

**Comment by Killette2** [comment] 2016-03-12 00:12
Despite the ability for mechanics to replicate hand teles with the regular device analyzer as non-antags, but hey! That's another issue

**Comment by AutismSpider** [comment] 2016-03-12 00:17
Do people really want all the station rooms rename to dumb shit making it hard to use the cams or the Ai to jump to shit?

@Killette2 rpd and rcd are fucking tot objectives all you got do is hack one thing to make them

**Comment by ihadtoregisterforthis** [comment] 2016-03-12 00:18
Make them some sort of MoMMI blueprint.

**Comment by AutismSpider** [comment] 2016-03-12 00:19
MoMMI prints are just for making new rooms and to rename ones you build

**Comment by Killette2** [comment] 2016-03-12 00:19
@AutismSpider 

Shit I forgot about those, those are easier to get than the voidsuits too. Should RPD or RCD even BE objectives?

Edit: They're even easier than magboots, which were also old objectives before being defined as too easy and turned into the CE magboot objective

**Comment by Imagebard** [comment] 2016-03-12 00:20
Hey, as long as Security officers can arrest you for having them...

**Comment by AutismSpider** [comment] 2016-03-12 00:20
You forgot the jetpack you can grab off the vox outpost or pay 2000$ for one or ask the Ai shit one out for you etc

**Comment by ihadtoregisterforthis** [comment] 2016-03-12 00:23
What can you need the blueprints for other than rooms in space and rename grief?

**Comment by Imagebard** [comment] 2016-03-12 00:24
@ihadtoregisterforthis You can break the space law with them.

**Comment by Intigracy** [comment] 2016-03-13 23:25
I'm assuming the reactions on OP were a meme since it was the first issue people noticed the reactions on.

**Comment by Killette2** [comment] 2016-03-14 00:16
But how do you copy them?

Nothing in the changelog yet

**Comment by Intigracy** [comment] 2016-03-14 00:36
The PR isn't merged yet

**Comment by Intigracy** [comment] 2016-03-20 04:44
You can close this since the general consensus is a resounding whiny no.

Muh greentext.

**Comment by Intigracy** [comment] 2016-04-04 22:06
clooooooooooooooooooooooooooooooooooooooooose

**Comment by Shadowmech88** [comment] 2016-04-04 22:13
Why does it bother you to have open issues?

**Comment by Intigracy** [comment] 2016-04-04 22:17
- Because there's 0 reason to keep something open if it's never going to get fulfilled.
- Because the issue tracker is bloated.
- Because we have more feature requests than we do bug reports.
- Because the consensus on this specific feature request when I made a PR was no.
- Because I dislike idea guys who just spam feature requests yet don't code.

**Comment by Killette2** [comment] 2016-04-04 23:00
The only problem people had with this was calling it a high access item, however that's incredibly annoying considering its vital for building a new powered room. Why don't we have a way to do things like that without muh potential greentext?

**Comment by Intigracy** [comment] 2016-04-04 23:11
Why don't you code it?

**Comment by 9600bauds** [comment] 2016-04-04 23:40
because muh greentexts :-1: please close

**Comment by Killette2** [comment] 2016-04-05 00:26
Is greentext really more important than being able to build space forts? You can already take pictures of blueprints with a camera and that still counts as greentext without stealing the actual useful item, not only that but you've always been able to print off other "high risk items" such as RPD and RCD, and if you use mechanics, the hand tele. As a miner you can just buy the jetpack you're supposed to steal, a lot of the high risk items are stupid.

**Closed as completed** 2017-03-22 11:55 UTC
Labels: Feature Request, Discussion, Unfulfilled Feature Requests
