### ISSUE TITLE
Certain objects (shaker, bike horn, deck of cards) have fuckhuge 'hitboxes'

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11976] opened 2016-09-22 05:39 UTC
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5e01bf34bdfef989ba31f27eed62029ec59e28c3
> 
> General description of the issue
> Certain objects, like a deck of cards, the shaker and the bike horn have fuckhuge hitboxes that usually take up an entire table. It's annoying as fuck.
> 
> What you expected to happen
> Pick up my drink off a table with a drink and a deck of cards on a corner.
> 
> What actually happened
> Drew a card.
> 
> Steps to reproduce if possible
> Place a shaker, bike horn, or deck of cards on a table.

Has been like this for a month or so at the very least.

**Comment by Exxion** [comment] 2016-09-22 05:43
Yeah no that's not an issue with certain items, that's an issue with items not getting removed from storage properly.
I guess whatever is causing it this time is something that happens most often to those items.
@SonixApache How did you put said items on the table?

**Comment by SonixApache** [comment] 2016-09-22 08:41
Spawned the deck of cards with a rapid service dispenser, picked up the deck and moved it into my pack. Later moved it out of my pack and onto a glass table.

**Comment by Exxion** [comment] 2016-09-22 13:07
I can't reproduce with the shaker or bike horn, but the deck of cards (and, for that matter, anything else that has to be clickdragged to be removed from storage other than other storage items) consistently gets fucked up and sticks with `mouse_opacity` 2 if put into a storage item and removed.

I'm already working on something that'll fix this, as it happens

**Comment by clusterfack** [comment] 2016-09-22 21:11
How did you move it out of your pack

**Comment by SonixApache** [comment] 2016-09-22 22:00
Click-and-drag from table to pack, then again click-and-drag from pack to table.

**Comment by Intigracy** [comment] 2016-10-17 22:09
@Exxion did you ever get a fix for this?

**Comment by Exxion** [comment] 2016-10-17 23:43
Yes this is fixed by my refactor, but that'll be a while. Maybe band-aid it in the mean time.

**Comment by Shadowmech88** [comment] 2018-10-13 10:13
Can confirm this still happens.

**Comment by Kurfursten** [comment] 2021-06-04 19:45
Exxion says this still happens

**Closed as completed** 2021-06-18 17:31 UTC
Labels: Bug / Fix
