### ISSUE TITLE
Gourmonger rads too fucking strong.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29035] opened 2021-03-18 05:19 UTC
With a steady-ish supply of food, they released 20-25 rads per tick, killing unprotected people via rad poisoning in less than 20 seconds or so.

**Comment by GreatBigFailure** [comment] 2021-03-18 05:21
They most certainly are. It's 1am so I can't fix it now but I'll just change the "This I guess" number into a "That I estimate" number in the morning.

**Comment by Killette3** [comment] 2021-03-19 05:23
The problem is how easy they are to mass. Perhaps they should be coded as expected to be mass farmed?

**Comment by robintime** [comment] 2021-04-09 23:25
pr #29037 fixes the radiation issue, as well as makes gours split slower. closing now!

**Closed as completed by robintime** 2021-04-09 23:25 UTC
