### ISSUE TITLE
Shower/Sink Should wash off plasma.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4152] opened 2015-04-26 18:53 UTC
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) 

>Revision (Should be above if you're viewing this from ingame!)
9f10dc411b9f5b9436f76adb8f9f7f4288c75837 

>General description of the issue
Shower and washing in the sink do not properly remove plasma from gloves, shoes, or suit

**Comment by PJB3005** [comment] 2015-04-26 19:07
They're not supposed to, not a bug I would say

**Comment by MercuryDoll** [comment] 2015-04-26 19:21
Aren't washing machines supposed to do that?

**Comment by PJB3005** [comment] 2015-04-26 19:27
yes, and suit storage units.

@kurfurst

**Comment by ComicIronic** [comment] 2015-04-26 19:29
How would you even wash plasma off something in the sink?

**Comment by Kurfursten** [comment] 2015-04-26 21:28
Weirdly, the shower cleaned off my exosuit, so I assumed it was supposed to clean other things too. The bug might be that it's cleaning exosuits.

**Comment by ComicIronic** [comment] 2015-04-26 21:53
What exosuit were you wearing that the shower cleaned off?
In local testing, the shower doesn't remove contamination from anything.

**Comment by Kurfursten** [comment] 2015-04-26 22:01
The orange construction suit that spawns in engineering and cargo but is worn by no-one.

**Comment by ComicIronic** [comment] 2015-04-26 22:06
If you're talking about the hazard vest, it doesn't clean in the shower either.

You may have missed that the suit doesn't contaminate at all (unless held in the hand or dropped, for whatever reason) and assumed it cleaned off. But contamination doesn't come off in the shower.

**Comment by Kurfursten** [comment] 2015-04-27 01:00
That must be it. Then the real bug is that the hazard vest is immune to plasma.

**Comment by ComicIronic** [comment] 2015-04-27 05:44
The real bug is that any suit worn doesn't contaminate, it's not just the hazard vest.

The contamination proc seems to only go for jumpsuit, gloves, shoes, etc.

**Comment by Zth--** [comment] 2015-11-02 22:43
Close it? Or at least change the label. No final decision lasts for 6 months

**Comment by Kurfursten** [comment] 2015-11-02 23:15
Yeah, close it

**Comment by PJB3005** [comment] 2015-11-02 23:16
And such is why you don't use web reports.

**Closed** 2015-11-02 23:15 UTC
Labels: Feature Request, Needs Final Decision
