### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Can't add beakers to alien dart gun once removed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5350] opened 2015-07-12 06:43 UTC
>Revision (Should be above if you're viewing this from ingame!)
8068683f81778067e22ed536f91e4905a4f6b72d

>General description of the issue
Cannot replace beakers once taken out of dart gun, unless it's done some way other then taking beaker > clicking dart gun

>What you expected to happen
Be able to reload my gun

>What actually happened
Fail.

>Steps to reproduce if possible
You're a smart guy, figure it out.

**Comment by PJB3005** [comment] 2015-07-12 07:09
dupe of #4847

**Closed** 2015-07-12 12:28 UTC
