### ISSUE TITLE
Silver slime carbon reaction bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16936] opened 2017-12-30 00:25 UTC
-get a multi use silver slime core/use a bunch while standing in the same tile
-intended behavior is that it spawns 2 random bars with a quality of 5
-bug behavior that instead of the new bars stacking with the old bars, they overwrite them
-no matter how many extracts you use if you don't move you will only have a max of 5 of everything and the excess bars will be deleted

**Comment by jknpj** [comment] 2017-12-30 12:21
duplicate of #16454

**Closed as completed** 2017-12-30 12:21 UTC
Labels: Bug / Fix
