### ISSUE TITLE
New ZAS makes body retrieval from space impossible

### ISSUE THREAD

**Issue by aceedex** [d3athrow/vgstation13#12146] opened 2016-10-10 07:20 UTC
#### Description of issue
Attempting to bring a body inside the station results in them getting pushed by the airflow and lost to the void

#### Difference between expected and actual behavior
Bring the body inside
not have a dead guy be ZASed into oblivion

#### Steps to reproduce 
Be paramedic
try to bring a dead guy inside
dead guy goes flying off and is permanently removed from the round
cry

but really, can items be anchored while being dragged or something? or should I just make a PR putting a hookshot in the paramedic office

**Comment by Kurfursten** [comment] 2016-10-10 07:23
This isn't really ideal but here's a tip from a longtime engineering player.

* Move next to airlock and click your tile to move their body directly under you
* Use glass sheets to make a window
* Open airlock, no ZAS

**Comment by Exxion** [comment] 2016-10-10 08:17
Duplicate of #11879

**Closed by Exxion** 2016-10-10 08:17 UTC
