### ISSUE TITLE
Cannot anchor moveable machinery over reinforced tables.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12453] opened 2016-11-02 16:33 UTC
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
An attempt to wrench them down gives you the message that the table is already anchored in this location, so you cannot move machines like microwaves or the fancy cafe machines ontop of the tables and wrench them down.

**Comment by Kurfursten** [comment] 2016-11-02 22:24
Workaround: flip the table, wrench, then put table back

Caused by objs.dm line 313
`if(other.anchored == 1 && other.density == 1 && density && !anchored && !(other.flags & ON_BORDER))`

Flipping the table confers the ON_BORDER flag necessary to anchor

**Comment by Exxion** [comment] 2016-11-02 22:45
Can't flip reinforced tables, as far as I know

**Comment by Exxion** [comment] 2016-11-02 22:45
Can't flip reinforced tables, as far as I know

**Comment by Kurfursten** [comment] 2016-11-03 00:54
You can, but you have to weaken it with a welding torch first

**Comment by FudgePucker** [comment] 2016-11-06 19:07
Can't you make the machine first, then put down the table while still on the same turf as the machine?

**Comment by Kurfursten** [comment] 2016-11-06 19:35
Instead of brainstorming more workarounds, I think the most productive thing to do would be to brainstorm if there's anything OTHER than a table that immediately springs to mind that you might want to be able to anchor machines on top of.

That way if someone wants to set up a flag for this sort of thing, they'll know what to give it to.

**Comment by FudgePucker** [comment] 2016-11-06 19:45
A separate machine frame for small appliances that can be picked up in both hands and set on tables

**Comment by DamianX** [comment] 2018-10-17 09:39
fixed by #20181

**Closed as completed by DamianX** 2018-10-17 09:39 UTC
Labels: Bug / Fix
