### ISSUE TITLE
Space Pod Construction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25078] opened 2019-11-18 04:47 UTC
(WEB REPORT BY: buttnick REMOTE: 206.221.180.138:7777)
# Revision
5f8636e9dd71c0e00fc74f6d9555dd769fd0b644

# Description
While following the instructions for constructing a space pod I was unable to complete step 7, "wire pod frame"

# Steps to Reproduce
*go to ss13.moe/wiki/index.php/Space_Pod
*follow instructions up to step 6.
*attempt to wire space pod by left clicking with a hand holding a cable coil
*wonder where you went wrong

# What you Expected
Space pod would be successfully wired and you would be able to continue in the process of construction

# What Actually Happened
construction was unable to continue, felt really sad. :(

**Comment by brndd** [comment] 2019-11-18 04:50
I've successfully built pods in the past, but I do remember there being something strange about the construction steps and having to read the code to see what the fuck I'm supposed to do next.

**Comment by Zth--** [comment] 2019-11-19 12:40
I think this one is caused by #24978

Will fix tonight

**Comment by Zth--** [comment] 2019-11-19 12:45
Also duplicate of #25021

**Closed as completed** 2019-11-19 19:53 UTC
Labels: Bug / Fix, Update WIKI
