### ISSUE TITLE
Ghosts can step on broken glass

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#4270] opened 2015-05-04 02:06 UTC
2SPOOKY

**Comment by Probe1** [comment] 2015-05-04 03:31
so add "you hear a faint crunching sound" to living players within 1 tile of the glass when ghosts walk over it.

**Comment by clusterfack** [comment] 2015-05-04 07:06
forcemove why

**Comment by CptWad** [comment] 2015-05-04 07:24
oh god it lags so much please fix

**Comment by clusterfack** [comment] 2015-05-04 07:27
lags?

**Comment by ComicIronic** [comment] 2015-05-04 08:10
Caused by no isliving() check in the code.

**Comment by Exxion** [comment] 2015-05-18 13:47
Wasn't this fixed weeks ago?
I remember trying to do it and failing quite a while ago

**Comment by clusterfack** [comment] 2015-05-18 13:49
Forgot to close the issue with my PR I guess

**Closed by clusterfack** 2015-05-18 13:49 UTC
Labels: Oversight
