### ISSUE TITLE
Can't build firelocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15801] opened 2017-08-23 00:32 UTC
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
# Revision
a562f556644694e3e03636bb1483e37fb1141d3f

# Description
As a mommi I was unable to build a firelock with the firedoor frame, maybe its mommi specific since an admin was able to build one in the thunderdome.
# Steps to Reproduce
Try making a firelock with a frame
# What you Expected
Make a firelock
# What Actually Happened
Literally nothing

**Comment by Shadowmech88** [comment] 2017-09-15 22:23
Duplicate of #15392.

**Closed as completed by Shadowmech88** 2017-09-15 22:23 UTC
Labels: Bug / Fix, Needs Moar Testing, Consistency Issue
