### ISSUE TITLE
Beepsky, heem sleepy

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3818] opened 2015-04-07 18:31 UTC
Beepsky is sleeping and is too lazy to do his job. He sits where he spawns and does nothing. I think its time for an intervention.

**Comment by ComicIronic** [comment] 2015-04-07 18:56
He's drinking too much.

**Comment by clusterfack** [comment] 2015-04-08 06:14
Beepsky has to stop coming into work smashed

**Comment by clusterfack** [comment] 2015-04-08 06:26
This issue was a high priority for me to fix as I modified beepsky's astar 5 days ago.

This is clearly visible and happening on the main server, but I cannot reproduce it by compiling bleeding edge on my test server. Can someone else ttry this out for me as well?

**Comment by clusterfack** [comment] 2015-04-12 03:22
It's fixed now at least, was a watchdog error I believe.

**Closed by clusterfack** 2015-04-12 03:22 UTC
Labels: Bug, Feature Loss
