### ISSUE TITLE
Spider Queen Delimbing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15670] opened 2017-08-10 01:12 UTC
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
so if you decide to use the advanced butchering options and remove a leg from the spider queen, the sprite for the spider queen dissappears, likely trying to become a sprite that does not exist, making it invisible.

**Comment by SonixApache** [comment] 2017-08-10 01:51
dupe of #14998

**Closed as completed** 2017-08-10 01:52 UTC
