### ISSUE TITLE
Light replacer places regular lights rather than high efficiency lights when loaded with high efficiency lights.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6807] opened 2015-11-30 21:20 UTC
(WEB REPORT BY: pedonymous REMOTE: 87.106.26.203:2244)

> Revision (Should be above if you're viewing this from ingame!)
> 7d1fcbb93c3e53c47ef34fc838580dcac7b48034 
> 
> General description of the issue
> The light replacer fills a socket with a standard light rather than a high-efficiency light, despite high-efficiency lights being loaded into the replacer.
> 
> What you expected to happen
> A high-efficiency light to fill the socket
> 
> What actually happened
> A standard light filled the socket, the high-efficiency lights are gone
> 
> Steps to reproduce if possible
> Take an empty light replacer, fill it with high-efficiency lights, click a light socket and see that it placed a normal light.

**Comment by Kurfursten** [comment] 2015-12-01 00:17
@exxion This is YOUR fault.
Duplicate of #4988 and #4972
May some day be fixed by #4800

**Comment by Exxion** [comment] 2015-12-01 03:12
Yes I'm sorry I will do that someday
It's still almost done

I could actually probably have it finished within the next couple hours if using browser datums rather than the standard interface isn't too big a deal

Wait. I apparently already ported the menus to browser datums and forgot I did.
Neat!

**Comment by Exxion** [comment] 2015-12-01 07:53
OK that didn't happen because I spent like two hours trying to get around a BYOND issue
But I just have to add one feature and write a changelog and it's done unless I'm forgetting something

**Comment by PJB3005** [comment] 2015-12-01 21:13
@Exxion which BYOND bug, if you haven't asked in IRC yet, we might be able to help.

**Comment by Exxion** [comment] 2015-12-01 21:57
Nah, I got around it. Thanks, though. The way I got around it isn't exactly elegant, but it works.
It's actually done except for the changelog and testing, unless I'm forgetting something

**Comment by Exxion** [comment] 2015-12-04 16:19
Not that it matters at this point, but it's not feature loss because it never worked

**Closed as completed** 2015-12-08 07:53 UTC
Labels: Bug / Fix, Feature Loss
