### ISSUE TITLE
Activating the Pirate energy cutlass doesn't update your sprite

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2308] opened 2014-12-21 12:53 UTC
You have to drop/equip something with a in-hand sprite for it to show.

**Comment by clusterfack** [comment] 2015-01-19 22:39
I can't reproduce this, they seem to work perfectly fine at the moment. We have made more recent changes to updating player icons than this.

**Comment by ComicIronic** [comment] 2015-01-19 22:41
I'll give everyone a chance to reply, but if it can't be reproduced then I'll close this.

**Comment by clusterfack** [comment] 2015-02-06 09:00
Closeable I guess

**Closed** 2015-02-06 17:45 UTC
Labels: Needs Moar Testing
