### ISSUE TITLE
getting zas'd into supermatter doesnt kill you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28336] opened 2020-12-08 02:34 UTC
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
9adf6be7302d5955dae2d71daa69288a6dd7b006

Larry Burns slams into a Supermatter Shard!

**Comment by Zth--** [comment] 2020-12-08 03:50
#27642

**Comment by DamianX** [comment] 2020-12-09 22:38
Duplicate of #27642

**Closed as completed by DamianX** 2020-12-09 22:38 UTC
