### ISSUE TITLE
Ghosts will stop haunting if the haunted guy goes through a portal

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#30854] opened 2021-09-23 03:19 UTC
@DeityLink #29978 maybe?

**Comment by DeityLink** [comment] 2021-09-23 08:05
Now that you mention it is completely because of that, since haunting ghosts are anchored. I had already assigned the issue to myself a while ago but now I know how to fix it, I'll handle it tonight.

**Comment by DeityLink** [comment] 2021-09-23 08:05
Duplicate of #30352

**Comment by DeityLink** [comment] 2021-09-24 01:45
Wait actually no, it's something else

**Closed as completed** 2021-09-24 20:58 UTC
Labels: Bug / Fix
