### ISSUE TITLE
mobs cant wake up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31793] opened 2022-01-05 22:05 UTC
(WEB REPORT BY: fargit REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
Mobs can't wake up once they go to sleep
# Steps to Reproduce
become a zombie, get cryo'd
# What you Expected
to not fall asleep, or to at least "wake up"
# What Actually Happened
Permenantly paralyzed

**Comment by boy2mantwicethefam** [comment] 2022-01-05 22:15
WAKE ME UP

**Comment by Kurfursten** [comment] 2022-01-05 22:59
Dupe of https://github.com/vgstation-coders/vgstation13/issues/28179

**Comment by SonixApache** [comment] 2022-01-05 23:49
\>issue for over a goddamn year
i think the dupe is warranted

**Closed as completed** 2022-05-08 15:32 UTC
