### ISSUE TITLE
Sticking Akimbo guns into your mouth doesn't kill you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21801] opened 2019-02-21 18:10 UTC
(WEB REPORT BY: qbone REMOTE: 206.221.180.138:7777)
# Revision
734405997d86b46a36367e25c23df165091f3c48

# Description
Sticking Akimbo guns into your mouth doesn't kill you
# Steps to Reproduce
Target mouth while dual wielding firearms. Click you'reself.
# What you Expected
The sweet release of death but like, twice.
# What Actually Happened
Reality still is terrible.

**Comment by SonixApache** [comment] 2019-02-22 07:06
dupe of #18497

**Comment by Aryuananime** [comment] 2019-02-22 17:29
Sorry I was told to smash that mothereffin' bug report button by an admin and didn't check, I will from now on

**Comment by SonixApache** [comment] 2019-02-22 17:39
better to have two reports than zero tbh
collabs can close the dupes

**Closed as completed** 2019-05-22 16:16 UTC
