### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Lighting on Janicart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4922] opened 2015-06-10 23:39 UTC
>General description of the issue
Lighting doesn't follow the player while on the janicart. It activates when you turn on a light source but the light stays still on the activated tile as the player moves.

>What you expected to happen
Drive through dark maint and see where I'm going.

>What actually happened
Shit was dark. Had to keep turning my flashlight on and off to see where I was going.

>Steps to reproduce if possible
Get on Janicart and ride into the dark.

**Comment by Exxion** [comment] 2015-06-11 00:08
Duplicate of #4904

**Closed** 2015-06-11 02:15 UTC
