### ISSUE TITLE
Hyperspectral Imager and Fourier Transform Spectroscope Problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30985] opened 2021-10-03 13:35 UTC
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
3668def331c952f4bac6738a4cea657d3f08700e

# Description
When opening their menus, they are completely blank. reloading nano ui and restarting my client AND updating to the latest byond version did nothing to fix it (version is 514.1566 for reference)
# Steps to Reproduce
click on the machine
# What you Expected
to be able to use it
# What Actually Happened
i was unable to use it

**Comment by SonixApache** [comment] 2021-10-03 14:54
nano strikes again

**Comment by DeityLink** [comment] 2021-11-23 10:48
Duplicate of #26957

**Closed as completed by DeityLink** 2021-11-23 10:48 UTC
Labels: UI
