### ISSUE TITLE
Can't hear yourself on the radio when wearing headphone radios.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21862] opened 2019-02-25 16:40 UTC
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
5584b927501f25a797be66b2db5362bfd5127a04

# Description
what it says on the tin

**Comment by robintime** [comment] 2021-04-24 07:00
duplicate of #21092

**Closed as completed by robintime** 2021-04-24 07:00 UTC
