### ISSUE TITLE
timer-timer assembly bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21920] opened 2019-03-02 14:47 UTC
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
fd2459528f0aac4e9209e6ad1554018738a509bb

# Placing timer timer assembly on fueltank repeatedly, moves the sprite to the right, to the point it is not visible anymore

# place assembly on tank, take it off, rince and repeat

# expected sprite to stay in place

# It actually moved and disappeared

**Comment by Tokanova** [comment] 2019-03-02 15:24
hilarious

**Comment by SonixApache** [comment] 2019-03-02 16:26
dupe of #21301

**Closed as completed** 2019-03-02 17:22 UTC
