### ISSUE TITLE
Fat ninjas don't have a sword

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27730] opened 2020-09-03 20:44 UTC
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
54878f74855bb6cb9f1edea374a743466d567939
Shifty...

**Comment by Kurfursten** [comment] 2020-09-03 22:40
Duplicate of  #27550

**Closed as completed by Kurfursten** 2020-09-03 22:40 UTC
