### ISSUE TITLE
Escape pods do not escape

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7018] opened 2015-12-14 04:58 UTC
(WEB REPORT BY: xpcicyn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 12d460e9b02ac56f7ad662c14967cdb10db48873
> 
> General description of the issue
> During evacuation, the escape shuttle leaves but none of the pods seem to. I've seen it happen twice - to the ones at Arrivals, and to the one in Engineering.
> 
> What you expected to happen
> The pods take off when the shuttle does.
> 
> What actually happened
> The pods stay at the station until round end.
> 
> Steps to reproduce if possible
> 1. Call shuttle
> 2. Go to pods
> 3. Wait
> 4. _toot_

**Comment by Exxion** [comment] 2015-12-14 04:59
Duplicate of #7010

**Closed as completed** 2015-12-14 08:04 UTC
