### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) (Map Issue - Taxi) Brig Bell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5240] opened 2015-07-04 15:42 UTC
You can't ring the Taxi brig bell because of the window which is not public access

**Comment by ComicIronic** [comment] 2015-07-04 16:09
Duplicate of #4690.

**Closed by ComicIronic** 2015-07-04 16:09 UTC
