### ISSUE TITLE
Glass Tiles Show People As Standing Under Them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30942] opened 2021-09-28 21:35 UTC
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
it looks like you're under the tiles despite being above them

**Comment by kernikov** [comment] 2021-09-28 22:32
@DeityLink duplicate of #30888

**Closed as completed** 2021-09-28 23:53 UTC
