### ISSUE TITLE
Testserver lighting doesn't work

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9123] opened 2016-03-29 01:59 UTC
So all the lighting on the test server is on but it doesn't actually show any light. The lighting is using up power, the lights are turned on, it shows the right sprite but it's just dark.

**Comment by uazuaz** [comment] 2016-03-29 07:55
a workaround for this is to put the lights off for a couple of seconds then on again;
you can do it using the zone light switch or unlocking the zone APC with an authorized ID (captain's spare is fine), putting the main breaker off then on:
after this, the zone will be lighted properly.

**Comment by PJB3005** [comment] 2016-03-29 15:26
I have no idea why this happens, it appears to be due to the server running for a really long time but that's the best I got.

**Comment by ihadtoregisterforthis** [comment] 2016-03-29 16:02
Even at roundstart the lights are dark. If I had to make an uneducated non-coder guess I'd say the lights aren't updating from the state of no-lighting during the lobby time.

**Comment by PJB3005** [comment] 2016-03-29 16:11
Then I've got no explanation.

**Comment by uazuaz** [comment] 2016-03-29 17:31
if i remember right, this is what actually happens:
on the test server, if you enter at round start, the lights work as intended;
on the other hand, if the server starts when NOONE readied up, then you join the server, this issue happens. the important thing is that this issue happens only when the server starts empty.

additionally, on the regular (not the testing) server, i noticed that if you start to observe before the round starts, you can see the lights as ON but the zones are not actually lighted, just like this issue; then, when the round starts with people on, the zones are lighted; maybe it's related someway.

**Comment by PJB3005** [comment] 2016-03-29 17:33
@uazuaz the issue with the main server not being lit if you observe before it starts is because the process to handle lighting hasn't started yet.

**Comment by uazuaz** [comment] 2016-03-29 17:35
yes, i mean that that's what happens on the test server: when it starts empty, that process doesn't start at all, even if someone joins later.

then, if you put the light off and on, it will be reset someway.

**Comment by gbasood** [comment] 2016-03-30 05:08
Will be fixed with the 510 PR whenever we actually get to that point
It used to be that btime.dll was missing from the test server and that caused this

**Comment by Brolaire** [comment] 2016-05-13 10:08
Has this been fixed now?

**Comment by gbasood** [comment] 2016-06-30 17:38
Test it and find out

**Comment by clusterfack** [comment] 2016-09-06 07:50
It's fine I think

**Closed as completed by clusterfack** 2016-09-06 07:50 UTC
Labels: Bug / Fix
