### ISSUE TITLE
Gloves are invisible: It's loose edition

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35220] opened 2023-10-21 11:09 UTC
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
facc939ef083e9734de9cffb26eae828b4e69eea

# Description
ALL gloves sprites are invisible on Vox and Insectoids (also tested on an insectoid with mechanical arms+hands, gloves were still invisible)
This includes !!!STUN GLOVES!!!, you have literally NO way of telling if a Vox or Insectoid is wearing them since examining will not show the scrubgloves sprite either.

**Comment by Hinaichigo** [comment] 2023-10-21 12:27
Duplicate of #35157

**Comment by toomykins** [comment] 2023-10-21 22:03
@Hinaichigo will you fix this? it's because of your one-handed gloves PR
update_icons.dm line 670 onward.

**Comment by Hinaichigo** [comment] 2023-10-21 22:19
I'm not sure that it is, because I also encountered this issue when making the one-handed gloves PR and tried numerous gloves on vox and was able to get some to show up (for example the supermatter-touchable gloves show up). But I'll check once I'm free in a bit.

**Comment by toomykins** [comment] 2023-10-21 22:22
> I'm not sure that it is, because I also encountered this issue when making the one-handed gloves PR and tried numerous gloves on vox and was able to get some to show up (for example the supermatter-touchable gloves show up). But I'll check once I'm free in a bit.

icon_status is null on vox. I changed the var/image/standing in that piece of code back to the original before your PR. it worked again. It's your code.

**Comment by Hinaichigo** [comment] 2023-10-21 22:25
I'll try to fix it. Thanks for finding it. I'm going to be busy irl for the next few days but after that I can.

**Closed as completed** 2023-11-18 23:19 UTC
