### ISSUE TITLE
State Laws broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26259] opened 2020-04-21 03:41 UTC
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
4cf1d4f0c579e649564ba69cc24559183b822830

# Description

No clue what did it, I was subverted, locked down, un locked down, and went power critical at one point, something in this or none of it broke the state laws button.
# Steps to Reproduce

No clue
# What you Expected

A functional state laws and nanoUI
# What Actually Happened

shit nanoUI

**Comment by DeityLink** [comment] 2021-09-03 00:27
Duplicate of #26957

**Closed as completed by DeityLink** 2021-09-03 00:27 UTC
Labels: UI
