### ISSUE TITLE
(WEB REPORT BY: kismywaifu REMOTE: 198.245.63.50:7777) DEPARTMENT CHAT

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3634] opened 2015-03-29 20:02 UTC
DEPARTMENT CHAT IS BROKEN.
NOT SHOWING UP AS AN OPTION TO ENABLE ON HEADSETS

ANY TIME YOU TRY TO TALK INTO A DEPARTMENT IT ANNOUNCES IT OVER COMMON

DON'T KNOW ABOUT SYNDIE OR BINARY

PS. FUCK YOU DYLAN

**Comment by ComicIronic** [comment] 2015-03-29 21:13
Duplicate of #3632

**Closed by ComicIronic** 2015-03-29 21:13 UTC
