### ISSUE TITLE
Roidstation issues/thoughts list

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#19168] opened 2018-08-07 20:40 UTC
Really happy with this map, but broken in a lot of ways.

> Table in front of chemistry pill storage makes you unable to store stuff in it from Chemistry
> 
> No plasma or plasma-lined beaker (really important)
> 
> DNA modifiers aren't connected to scanners (can't make monkeymen or... do any genetics really)
> 
> Every single monitor in the entire station displays the cargo shuttle status (i think?)
> 
> Medical doctors don't have access to Corpse Disposal
> 
> Morgue tray in front of Corpse Disposal can't open because of the windoor
> 
> Morgue tray two tiles below Corpse Disposal opens downwards despite being horizontal
> 
> Cryopod area is a bit of a clusterfuck with 3 tiles of entrance, could be fixed by lowering the top scanner and sleeper to be flush with the lower scanner and sleeper
> 
> The science/cargo lobby with the glass floor is so fucking cool that it should be in a more important place, honestly
> 
> Tons of places where areas are messed up, like in Cryo where there's a tiny area one tile wide on the right which is separate
> 
> Space around Escape can be seemingly walked around on before the escape shuttle actually gets there

**Comment by Kammerjunk** [comment] 2018-08-07 20:55
If there are 2 chemist slots, you should have 2 chemist spawn points or they'd just spawn on top of each other. Don't listen to Irradiation, he has brain damage

**Comment by kilozombie** [comment] 2018-08-07 21:03
It seems sort of clear that the mapping team didn't test Medbay much at all, even after people gave feedback Medbay-wise.

It's not the biggest deal if this stuff is fixed but a map shouldn't be pushed out in a broken state. That's terrible form.

**Comment by Kurfursten** [comment] 2018-08-07 22:08
1 & 2 closed in day0 patch

**Comment by brndd** [comment] 2018-08-08 01:55
>Cryopod area is a bit of a clusterfuck with 3 tiles of entrance, could be fixed by lowering the top scanner and sleeper to be flush with the lower scanner and sleeper

I've done this now, should be in the next update. I still don't like the area personally, but restructuring it will have to come at a later date after it has been given more playtime and opinions.

>Tons of places where areas are messed up, like in Cryo where there's a tiny area one tile wide on the right which is separate

Can't reproduce. The areas around the medbay cryo cells seem all right to me.

>Space around Escape can be seemingly walked around on before the escape shuttle actually gets there

Not sure what you mean by this? Sounds like server lag or something.

The rest of the issues will be fixed in the next update.

**Comment by kilozombie** [comment] 2018-08-08 02:29
@brndd 

Doing great work. Would have liked a few of them to be in the original commit but I understand mapmaking is a monumental task and you can't ever be perfect. Thanks for being quick to the fixes.

**Closed as completed** 2021-11-25 16:57 UTC
Labels: Mapping (Roidstation :pick:)
