### ISSUE TITLE
Isolation Centrifuge shows a blank screen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32529] opened 2022-05-04 02:34 UTC
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
58bf87d4d3a91b3d1588d4247f9306c721eda266

# Description
Not sure what's happening, since it worked before.
# Steps to Reproduce
Try to use the centrifuge, it doesn't work.
# What you Expected
It to work
# What Actually Happened
Screenshot incoming.

**Comment by jwhitak** [comment] 2022-05-04 02:34
![image](https://user-images.githubusercontent.com/69739118/166616150-ea604ba9-0d1f-4b3f-b1a7-b6d32a6bacc8.png)

**Comment by pedr69** [comment] 2022-05-04 02:45
you tried the resend resources and fix nanoui buttons?

**Comment by jwhitak** [comment] 2022-05-04 02:56
I'll try resend resources. I've already tried the fix nanoUI and a complete restart of the executable.

**Comment by Eneocho** [comment] 2022-05-04 03:09
God I hate nanoUI, it breaks like half the time. At least shitty and ugly html screens work reliably in comparison.

**Comment by jwhitak** [comment] 2022-05-04 03:18
Resend does nothing as well. New round, the problem persists... what the heck. I'm on 514.1566. To clarify, this machine worked before.

**Comment by Eneocho** [comment] 2022-05-04 03:21
Try to delete BYOND's cache then restart your PC.
For the cache's location its at: "C:\Users\NAMEHERE\Documents\BYOND"

**Comment by jwhitak** [comment] 2022-05-04 03:22
Same error on a local hosted server, but I get this as well:
![image](https://user-images.githubusercontent.com/69739118/166619154-78c86ff5-8ea0-4510-bf51-2a7cdc316d59.png)

**Comment by jwhitak** [comment] 2022-05-04 03:58
A restart, cache removal, and reinstall of Byond did not fix this. What the hell. It is also only happening to me. I must be missing some secret cache somewhere?

**Comment by Kurfursten** [comment] 2022-05-04 04:27
Working fine for me, it's your nanoui

**Comment by Eneocho** [comment] 2022-05-04 04:40
Shit's fucky, nothing you can do really. It seems to fix itself (for me) whenever the serb updates.

**Comment by jwhitak** [comment] 2022-05-06 19:39
Spontaneously started working again. Note that this brokenness persisted through a full uninstall+reinstall of byond, multiple restarts, clearing of any cache/byond I could find. After two days, it suddenly works again. I have no idea of the solution here. If you read this issue, I pray for you like those who have prayed for me.

Someone close this issue for me please, I cannot. Nobody else had this issue and I can't seem to replicate either the cause or the cure.

**Comment by Eneocho** [comment] 2022-05-06 19:58
Did it fix today? Because we had a serb update today. That issue fixes itself for me whenever the serb updates.

**Comment by jwhitak** [comment] 2022-05-06 21:48
Local version without the new updates. The mystery remains.

**Comment by adacovsk** [comment] 2022-05-09 17:31
Probably because you were doing stuff to UIs on your own server

**Closed as completed** 2022-08-08 04:08 UTC
