### ISSUE TITLE
Sasha InHand sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15634] opened 2017-08-04 12:48 UTC
(WEB REPORT BY: electroblueguy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>General description of the issue
when held in hand, sasha takes the sprite of Ian

>What you expected to happen
There should be the inHand sasha sprite

>What actually happened
it seems like i'm holding Ian

>Steps to reproduce if possible
grab sasha

**Comment by jknpj** [comment] 2017-08-06 12:21
And all cats are runtime when you hold them. Not really a bug but a WYSI

**Comment by robintime** [comment] 2021-04-10 21:22
duplicate of #28727

**Closed as completed by robintime** 2021-04-10 21:22 UTC
Labels: Needs Spritework
