### ISSUE TITLE
Robust harvest is still fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32969] opened 2022-07-24 22:01 UTC
(WEB REPORT BY: poales REMOTE: 206.221.180.138:7777)
# Revision
821b34fc36cd569c7994eff8f27028478be93c1e

# Description
burns through 1 u robust harvest per tick and the potency barely increases
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment] 2022-07-25 01:30
wasn't the botany rework a month or two back? how is everything still broken

**Comment by adacovsk** [comment] 2022-07-25 01:30
@Eneocho hey, are you experiencing this? I made your change and it's broken?

**Comment by adacovsk** [comment] 2022-07-25 01:32
> wasn't the botany rework a month or two back? how is everything still broken

yes, I reverted one of my changes very recently though at @Eneocho 's request, so I don't know why it's not working as intended... I'll wait for his input

**Comment by adacovsk** [comment] 2022-07-25 01:38
Upon discussion, it may have to do with metabolism, where robustharvest would consume only 0.1 units?

**Comment by Eneocho** [comment] 2022-07-25 03:07
I haven't used diethylamine to speed up plant growth after the merged change so not really sure, I've been playing Factorio. Robust IS broken however. You gotta dump the entire vendor's supply to get anywhere near 100 potency.

**Closed as completed** 2022-08-18 03:24 UTC
