### ISSUE TITLE
Dead Organs spawnd from organ wave behave weirdly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8708] opened 2016-03-08 12:24 UTC
(WEB REPORT BY: msdd REMOTE: 158.69.55.2:7777)
Revision: 722f05bda1808592e5c7b22f7781f86fc616ad39  
The organ wave event spawns a bunch of dead organs (dead kidney, dead eye, dead heart, etcetera). These objects defy any logic: when throw they move around haphazardly; even going backwards; they can't be carried in a container as the container automatically opens (tested with closets and a pizza container), they can't be cleaned using space cleaner, the mob or soap, they can't be eaten and they don't seem to incinerate. 
Thus, they are seemingly impossible to remove from the round

Although it might be intended for the organs to be uncleanable, uneatable and unburnable, the throwing and container code is definitely non-standard. It's hard to describe and best experienced in practice.

You can easily test the above by triggering the event using admin verbs and fiddling with the organs.

**Comment by Exxion** [comment] 2016-03-08 12:59
Dupe of not one, but two separate issues, albeit with some additional information

**Comment by 9600bauds** [comment] 2016-12-12 14:44
Closing in favor of #8232

**Closed as completed by 9600bauds** 2016-12-12 14:44 UTC
Labels: Bug / Fix
