### ISSUE TITLE
Pokeymans take Damage while in Ball - Possible Playermob Only?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29778] opened 2021-06-12 20:25 UTC
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
Mobs in creature capture orbs, at least those controlled by players, take thermal and oxygen-related damage, which shouldn't be happening. My mob was a modified unknown horror that needed to be able to breathe and was captured by a player. They took me in orb to go mining and I began suffocating and freezing. Really weird.

**Comment by AutismSpider** [comment] 2021-06-12 20:45
laz balls are not space proof so if mob is not space harden/needs air it die.

**Comment by SGuivenne** [comment] 2021-06-23 21:38
Duplicate of #25689

**Closed as not planned** 2024-01-27 14:52 UTC
