### ISSUE TITLE
ID computers, comms console are broken

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#14424] opened 2017-03-25 01:40 UTC
Since I asked @PJB3005 to review #14314 **before merging it** since he seemed ot know what might break
this is his fault

**Comment by IAGFPRMF** [comment] 2017-03-25 02:18
R E D U N D A N T part two

**Comment by kilozombie** [comment] 2017-03-25 02:54
I noticed the lysis-isolation centrifuge has missing UI also

**Comment by gbasood** [comment] 2017-03-25 05:20
@PJB3005 fix the issues and make a new PR

**Comment by PJB3005** [comment] 2017-03-25 17:50
> my fault.

M8

**Comment by gbasood** [comment] 2017-03-26 04:52
@PJB3005 yeah totally not your fault
![](http://i.imgur.com/IhGMOMA.png)

**Comment by Exxion** [comment] 2017-03-26 04:58
Wait. You weren't joking, Sood?
I hope you know that someone failing to catch someone else's error does not make the error the fault of the former.

**Comment by PJB3005** [comment] 2017-03-26 12:14
Literally all I told him was that "dude nano may have some shit break".

Then his response is "do my job and go through the game and test every single nanoUI we have"

Of course then I realized that sood wasn't gonna do it so I just WE'RE DOING IT LIVE'd it, because that's literally the only sane way to test this kind of shit.

**Comment by gbasood** [comment] 2017-03-26 16:34
he merged it
I asked him to look at the problems he knew existed that I didn't find
and instead he merged it
If I *ASKED* for a merge I would take blame
But I didn't

**Comment by PJB3005** [comment] 2017-03-26 17:32
I didn't know that the problems existed, I told you they might exist, and that you should test it. 

It's your responsibility to test your shit no matter who points out where it could break. If we had to test everybody's PR before merging ourselves nothing would get merged.

**Comment by Probe1** [comment] 2017-03-26 18:24
Lets not devolve into arguing the focus is to fix the issue.  Please.

**Comment by mtpowell** [comment] 2017-03-26 20:51
Well, what's wrong it?

**Comment by Exxion** [comment] 2017-03-26 20:56
It didn't work at all
The change was reverted so it's no longer actually broken in-game

**Comment by gbasood** [comment] 2017-03-30 07:21
@PJB3005 maybe read the PR then before you merge shit because, again, a merge wasn't asked for

@Exxion it did work, but a lot of machines break with it regardless
For example APCs work fine but ID computers don't

**Comment by Exxion** [comment] 2017-03-30 08:26
By "it," I was referring to the comms console
Though looking back on it, I have absolutely no idea why that one specifically, or how I thought anyone would know what I meant

**Comment by mtpowell** [comment] 2017-03-30 15:14
I spent some time look at this and it outputs the raw json, so that tells us the new JSON procs are working as intended.

What happens is the Javascript nano_state_manager.js tosses an error in regards to the variable "initial_data" which tells us it isn't being set properly and that's as far as I got before I gave up.

If someone wishes to continue where I left off, I believe the bug resides in nanoui.dm in the functions get_send_data and get_config_data, possibly due to the use of datums in associative arrays.

**Comment by gbasood** [comment] 2017-03-31 03:51
yeah it's associative values from what PJB said
not sure what about t hem

**Comment by PJB3005** [comment] 2017-03-31 09:54
Because BYOND lists are both arrays and some map type, they are arrays UNTIL assoc values are used, then switch to maps forever.

BYOND native JSON encode is aware of this and can use the internal knowledge to know whether to write an object or an array, but the old one isn't so it has to resort to checking if any assoc values are not null for this info.

This means that if you set an assoc value then immediately null it again, the old one will see it as an array, and the new one as an object with null values.

So some things expect an array but get an object instead instead and explode.

**Comment by DamianX** [comment] 2017-05-17 19:24
this was fixed though, close it?

**Comment by Intigracy** [comment] 2017-05-17 20:01
I'll take your word for it.

**Closed as completed by Intigracy** 2017-05-17 20:01 UTC
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

**Comment by gbasood** [comment] 2017-05-17 20:11
it
was fixed by reverting the json changes
if we ever try to move to byond's JSON entirely then we're going to have the same problem again
