### ISSUE TITLE
Deathsquad problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26998] opened 2020-07-01 15:23 UTC
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
85ff9b697a1f3bddbf445577be6b63462a1e0464

# Description
My seraph had no weapons on the module, thus i could not reload or change to my missiles
# Steps to Reproduce
Get squid, be leader, hop in mech, ???, profit
# What you Expected
To fight the blob
# What Actually Happened
*click click click*

**Comment by DeityLink** [comment] 2020-07-05 15:04
>fighting a blob with a Seraph, a mecha that has no energy weapon

This was doomed to end badly either way.

**Comment by DeityLink** [comment] 2021-08-30 15:11
Duplicate of #26999

**Closed as completed by DeityLink** 2021-08-30 15:11 UTC
Labels: Needs Moar Testing
