### ISSUE TITLE
Plasma glass bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30941] opened 2021-09-28 21:34 UTC
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
The plasmaglass floor on roid goes over the UI and characters
# Steps to Reproduce
Play roid, walk over the plasmaglass floor north of arrivals

# What you Expected
Functions like a floor
# What Actually Happened
Goes over UI

**Comment by kernikov** [comment] 2021-09-28 22:33
@DeityLink duplicate of #30888

**Closed as completed** 2021-09-28 23:53 UTC
