### ISSUE TITLE
Admin ghosts are fucked up

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6337] opened 2015-10-27 08:28 UTC
A few issues I've seen

1. Sometimes when flying in the chapel, I get the "You cannot get past holy grounds while you are in this plane of existence!" message partway in, and I'm trapped, having to teleport out. This can make investigating issues really difficult.

2. I seem to be an AI eye now, where previously not. When I go to the Centcom Ferry terminal now and try to send it to the station, I'm fire walled out. Now I can var edit it to allow silicons to use it, and I can then use it normally, but I'd prefer not leaving it open for random borgs and MoMMIs. Previously this issue wasnt coming up at all, so I assume something is broken.

**Comment by Probe1** [comment] 2015-10-27 12:39
As far as the second one goes, the ferry was open to silicons previously but we hadn't noticed it come up.  Then I left the ferry at the station and a borg helped half the crew go to centcomm and loot all the energy axes and mechs their greedy fingers could carry.

So I guess @unid15 fixed it but fixed it too good

**Comment by d3athrow** [comment] 2015-10-27 14:31
ghosts are partially visible in darkness now

**Comment by dylanstrategie** [comment] 2015-10-27 16:33
The first problem is caused by your secret repo content @d3athrow, this is related to ghosts becoming visible when they wait in darkness a little bit

Either adminghosts should not be affected by this, or they should be immune to holy objects. The second way seems better, since making an object holy could screw up adminghost interaction

**Comment by Probe1** [comment] 2015-10-27 16:49
to be honest I enjoy that adminghosts are effected by it.

even though some times I have to hide on the other side of a wall so some bully doesn't see me watching him and deciding how big of a bully he is.

**Comment by FudgePucker** [comment] 2015-10-27 18:13
I think admin ghosts and observers should not show up in the dark.
>Oh man there are spooks with all their skin melted off from space and... wait whats that guy doing wearing a blue tee shirt?
Oh hey dude, I'm here on vacation, wheres the bathroom?

muh imulsions.

Although I have to say having ghosts show up sometimes is comedic gold.
'I didn't murder anyone' said the murderboner. 'ooooooohhhhhhhh get the valids ooooooooohhhhh' said the 50 ghosts hovering around him.

**Comment by d3athrow** [comment] 2015-10-27 19:14
observers having the stupid icon should be fixed

**Comment by DeityLink** [comment] 2015-10-27 21:06
@d3athrow You realize that the "stupid icon" is a way to let observers know when they're visible right?
By the way I've meant to tell you, I know it stems from really good intentions to make Halloween spooky by having partially visible ghosts in darkness but, the way it's implemented, admins cannot make ghosts permanently visible anymore, since they immediately become visible again, which sucks. We should have a button or a variable to toggle this behavior. Also imo visible ghosts should have their colour set to black. partially visible tourists hanging on the walls are nothing short of immersion breaking.

**Comment by ihadtoregisterforthis** [comment] 2015-10-27 22:52
All ghosts, as of right now, have the old ghost sprite.

![fuck lab iv 2015-10-27 194207](https://cloud.githubusercontent.com/assets/13305885/10774868/f5ee8ee6-7ce2-11e5-98aa-8bebe49d5fe0.png)

No casual inter-worlds tourists

This should change, they are in no way spooky and they have no directions.
Yes, a tourist is spookier than this.

**Comment by DeityLink** [comment] 2015-10-27 22:59
You should use the narsie-ghost sprite instead. They are spooky alright.

**Comment by mrpain666** [comment] 2015-10-27 23:16
Personally, I liked the old sprite system better. But that's not really what this issue was about.

**Comment by unid15** [comment] 2015-10-29 13:30
Hasn't this issue been fixed?

**Comment by Probe1** [comment] 2015-10-29 14:26
yup

**Closed** 2015-10-29 14:47 UTC
Labels: Bug, Feature Loss, OH GOD IT'S LOOSE
