### ISSUE TITLE
Equal ruleset weights and its consequences have been a disaster for the server

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26461] opened 2020-05-13 18:48 UTC
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)

**Comment by ShiftyRail** [comment] 2020-05-13 18:49
I would ask him to give more info but he can't

**Comment by gurfan** [comment] 2020-05-13 18:51
what's wrong with them?

**Comment by DeityLink** [comment] 2021-09-01 15:23
Duplicate of #26463

**Closed as completed** 2021-09-01 15:23 UTC
